# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : usbredir
version    : 0.15.0
release    : 9
source     :
    - https://gitlab.freedesktop.org/spice/usbredir/-/archive/usbredir-0.15.0/usbredir-usbredir-0.15.0.tar.bz2 : e3966c5d0221173867b3668a1ecc4d11506e8848ef9750a157723b8c9b7f1421
homepage   : https://www.spice-space.org/usbredir.html
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : USB redirection protocol
description: |
    usbredir is a protocol for redirection USB traffic from a single USB device, to a different (virtual) machine then the one to which the USB device is attached. See usb-redirection-protocol.txt for the description / definition of this protocol.
builddeps  :
    - pkgconfig(libusb-1.0)
optimize   :
    - speed
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING COPYING.LIB
check      : |
    %ninja_check
