# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : verilator
version    : '5.050'
release    : 56
source     :
    - https://github.com/verilator/verilator/archive/refs/tags/v5.050.tar.gz : ec6723f30c1798b1fbbbed97364f09c431fb4875577c314f37240e99b60a4a04
license    :
    - Artistic-2.0
    - LGPL-3.0-only
homepage   : https://www.veripool.org/wiki/verilator
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
builddeps  :
    - help2man
rundeps    :
    - ccache
checkdeps  :
    - python-distro
setup      : |
    autoconf
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license LICENSE LICENSES/*
check      : |
    make test
