# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libkscreen
version    : 6.6.2
release    : 134
source     :
    - https://download.kde.org/stable/plasma/6.6.2/libkscreen-6.6.2.tar.xz : 2bc247268fdbbea584af33f8a67c9fd1e891aba1e174f272c71a42a1787929d8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE's screen management software
description: |
    KDE's screen management software.
builddeps  :
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(xrandr)
    - kf6-kconfig-devel
    - plasma-wayland-protocols-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
