# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gram
version    : 3.2.0
release    : 1
source     :
    - https://codeberg.org/GramEditor/gram/archive/3.2.0.tar.gz : ff455814b3ba5909a1ae359bd5716874bd072495fdaa55fafbc025ed060f1989
homepage   : https://gram-editor.com/
license    :
    - AGPL-3.0-or-later
    - Apache-2.0
    - GPL-3.0-or-later
component  : editor
summary    : A code editor for humanoid apes and grumpy toads
description: |
    Gram is a powerful and modern source code editor. It features solid performance and is highly configurable, 
    yet comes with batteries included out of the box. Gram supports many popular programming languages and file formats, 
    and can use Zed extensions to support additional languages. Other features include built-in documentation, 
    debugger support via the DAP protocol, source control using git and more. Gram started as a fork of the Zed editor.
networking : true
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(glib-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(libdrm)
    - pkgconfig(libelf)
    - pkgconfig(libssl)
    - pkgconfig(libzstd)
    - pkgconfig(protobuf)
    - pkgconfig(sqlite3)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkbcommon-x11)
    - cmake
    - envsubst
    - jq
    - mold
    - rust
rundeps    :
    - unzip
environment: |
    export RUSTFLAGS="$RUSTFLAGS -Clink-arg=-fuse-ld=mold"

    # vars for envsubst
    export APP_CLI="gram"
    export APP_ICON="gram"
    export APP_ID="app.liten.Gram"
    export APP_NAME="Gram"
    export APP_ARGS="%U"
    export DO_STARTUP_NOTIFY="true"

    # stable branding
    export BRANDING_LIGHT="#b2d88f"
    export BRANDING_DARK="#4e4b5c"

    # disable auto-updates / bundled uninstall
    export GRAM_UPDATE_EXPLANATION="Auto-updates disabled in distribution build. Please update via your package manager"
    export GRAM_NO_BUNDLED_UNINSTALL="Use your package manager to uninstall"

    # use system libs
    export LIBSQLITE3_SYS_USE_PKG_CONFIG=1
    export LIBSSH2_SYS_USE_PKG_CONFIG=1
    export OPENSSL_NO_VENDOR=true
    export ZSTD_SYS_USE_PKG_CONFIG=1
setup      : |
    # Fill out desktop info
    envsubst < crates/gram/resources/gram.desktop.in > gram.desktop
    
    # Fill out appstream metainfo
    envsubst < crates/gram/resources/flatpak/gram.metainfo.xml.in > gram.metainfo.xml
    sed -i -e '/@release_info@/{r crates/gram/resources/flatpak/release-info/stable' -e 'd}' gram.metainfo.xml

    %cargo_fetch
build      : |
    ./script/generate-licenses
    %cargo_build -p gram -p cli
install    : |
    %install_exe target/release/cli ${installdir}/usr/bin/gram
    %install_exe target/release/gram ${installdir}/%libdir%/gram/gram-editor

    %install_file gram.desktop ${installdir}/usr/share/applications/$APP_ID.desktop
    %install_file gram.metainfo.xml ${installdir}/usr/share/metainfo/$APP_ID.metainfo.xml

    %install_file crates/gram/resources/app-icon.png ${installdir}/usr/share/icons/hicolor/512x512/apps/gram.png
    %install_file crates/gram/resources/app-icon@2x.png ${installdir}/usr/share/icons/hicolor/512x512@2/apps/gram.png
    %install_file crates/gram/resources/app.liten.Gram.svg ${installdir}/usr/share/icons/hicolor/scalable/apps/gram.svg

    %install_license LICENSE*
