# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : breeze-gtk-theme
version    : 6.7.3
release    : 146
source     :
    - https://download.kde.org/stable/plasma/6.7.3/breeze-gtk-6.7.3.tar.xz : fa93b6819dc5e4acb6e96ec0dbb3d4de7eebff2f1de480be01776a80107a087b
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt6Core)
    - breeze-devel
    - extra-cmake-modules
    - python-cairo
    - sassc
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
