# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ark
version    : 26.04.2
release    : 109
source     :
    - https://download.kde.org/stable/release-service/26.04.2/src/ark-26.04.2.tar.xz : b81c4055486c99f4f21ff228bf12485bc73e8e6b0064edee1043a11ad5d1e555
homepage   : https://kde.org/applications/utilities/org.kde.ark
license    :
    - BSD-2-Clause
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-3.0-only
    - MIT
component  : desktop.kde.core
summary    : A graphical file compression/decompression utility
description: |
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libzip)
    - 7zip
    - breeze-icons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kfilemetadata-devel
    - kf6-kiconthemes-devel
    - kf6-kparts-devel
    - kf6-kpty-devel
    - lrzip
    - unrar
rundeps    :
    - 7zip
    - lrzip
    - unrar
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*

    # remove docs
    rm -rf $installdir/usr/share/doc
