# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ksanecore
version    : 26.04.3
release    : 88
source     :
    - https://download.kde.org/stable/release-service/26.04.3/src/ksanecore-26.04.3.tar.xz : e5c96840ba21e7afa6e0635b21cc117552898b14628d9555f2a600c77884747d
homepage   : https://kde.org/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : Library providing logic to interface scanners
description: |
    KSaneCore is a library that provides a Qt interface for the SANE library for scanner hardware.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - kf6-ki18n-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
