# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-online-accounts-gtk
version    : 3.50.10
release    : 4
source     :
    - https://github.com/xapp-project/gnome-online-accounts-gtk/archive/refs/tags/3.50.10.tar.gz : 1335240713781c7f88d3d0a179cd275d309fd010cbd9d9048518560a75d774ac
homepage   : https://github.com/xapp-project/gnome-online-accounts-gtk
license    : GPL-3.0-or-later
component  : desktop.gtk
summary    : A GTK Frontend for GNOME Online Accounts
description: |
    A GTK Frontend for GNOME Online Accounts.
builddeps  :
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk4)
rundeps    :
    - gvfs-goa
    - xapp-symbolic-icons
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
