# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-responses
version    : 0.26.2
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/r/responses/responses-0.26.2.tar.gz : 9c9259b46a8349197edebf43cfa68a87e1a2802ef503ff8b2fecbabc0b45afd8
homepage   : https://github.com/getsentry/responses
license    : Apache-2.0
component  : programming.python
summary    : Utility library for mocking out the requests library
description: |
    A utility library for mocking out the requests Python library.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - python-pytest
    - python-pytest-asyncio
    - python-pytest-httpserver
    - python-requests
    - python-tomli-w
    - pyyaml
rundeps    :
    - python-requests
    - pyyaml
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
