# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : neon
version    : 0.37.1
release    : 9
source     :
    - https://notroj.github.io/neon/neon-0.37.1.tar.gz : a99b7262525a454d1065cf76dd17240fd808dfc4ef15636990ff83a5d0d9e740
license    : LGPL-3.0-or-later
component  : network.library
homepage   : https://notroj.github.io/neon/
summary    : neon is an HTTP and WebDAV client library
description: |
    neon is an HTTP and WebDAV client library, with a C interface.
setup      : |
    %configure --enable-shared --with-ssl --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license src/COPYING.LIB
