# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kanagram
version    : 26.04.1
release    : 100
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/kanagram-26.04.1.tar.xz : e39e7ebbeee0dce822334e7b6ea2f1314826299b73eaff3173ef3b5754e22065
homepage   : https://kde.org/applications/education/org.kde.kanagram
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6TextToSpeech)
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - kf6-kxmlgui-devel
    - kf6-sonnet-devel
    - libkeduvocdocument-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rfv $installdir/usr/share/doc
