# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnote
version    : '50.2'
release    : 41
source     :
    - https://download.gnome.org/sources/gnote/50/gnote-50.2.tar.xz : e1377439533d55464340e81dbaac274eba32b29ec60ed568c7026294d5b15478
homepage   : https://gitlab.gnome.org/GNOME/gnote
license    : GPL-3.0-or-later
component  : office.notes
summary    : A simple and easy to use desktop note-taking application
description: |
    Gnote is a simple note-taking application for GNOME desktop environment. It allows you to capture your ideas, link them together using WikiWiki-style links, group together in notebooks and some extra features for everyday use.
optimize   :
    - lto
builddeps  :
    - pkgconfig(glibmm-2.68)
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-4.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
