# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : privoxy
version    : 4.1.0
release    : 8
source     :
    - https://sourceforge.net/projects/ijbswa/files/Sources/4.1.0%20%28stable%29/privoxy-4.1.0-stable-src.tar.gz : 23e4686e5848c74cb680c09c2811f0357739ecfe641f9c4072ee42399092c97b
homepage   : https://www.privoxy.org/
license    : GPL-2.0-or-later
component  : network.clients
summary    : Non-caching web proxy with advanced filtering capabilities
description: |
    Privoxy is a non-caching web proxy with advanced filtering capabilities for enhancing privacy, modifying web page data and HTTP headers, controlling access, and removing ads and other obnoxious Internet junk. Privoxy has a flexible configuration and can be customized to suit individual needs and tastes. It has application for both stand-alone systems and multi-user networks.
builddeps  :
    - pkgconfig(libpcre)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %install_license LICENSE
    sed -i 's|^confdir \.|confdir /etc/privoxy|; s|^logdir \.|logdir /var/log/privoxy|' config

    %install_exe privoxy ${installdir}/usr/sbin/privoxy
    %install_file privoxy.8 ${installdir}/usr/share/man/man1/privoxy.8
    %install_dir ${installdir}/etc/privoxy/templates
    %install_file {config,*.action,*.filter,trust} ${installdir}/etc/privoxy
    %install_file templates/* ${installdir}/etc/privoxy/templates

    %install_file ${pkgfiles}/privoxy.service ${installdir}/%libdir%/systemd/system/privoxy.service
    %install_file ${pkgfiles}/privoxy.sysusers ${installdir}/%libdir%/sysusers.d/privoxy.conf
    %install_file ${pkgfiles}/privoxy.tmpfiles ${installdir}/%libdir%/tmpfiles.d/privoxy.conf

