# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dnsmasq
version    : '2.93'
release    : 19
source     :
    - https://thekelleys.org.uk/dnsmasq/dnsmasq-2.93.tar.xz : 0c00d4e5c97c8306e5fb932b348b34269c9c29a0e7df0e8e82958b407092bc19
homepage   : https://thekelleys.org.uk/dnsmasq/doc.html
license    :
    - GPL-2.0-only
    - GPL-3.0-only
component  : network.base
summary    : DNS cache and forwarder
description: |
    dnsmasq in Solus is used to forward and cache DNS queries.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(gmp)
    - pkgconfig(nettle)
setup      : |
    %apply_patches

    sed -e 's|#define CHUSER "nobody"|#define CHUSER "dnsmasq"|' \
        -e 's|#define CHGRP "dip"|#define CHGRP "dnsmasq"|' -i src/config.h

    sed -e 's|%%%%PREFIX%%%%|/usr|' -i dnsmasq.conf.example
build      : |
    %make all-i18n \
        CFLAGS="${CFLAGS}" \
        COPTS='-DHAVE_DBUS -DHAVE_DNSSEC' \
        LDFLAGS="${LDFLAGS}"
install    : |
    %make install-i18n \
        DESTDIR=${installdir} \
        PREFIX=/usr \
        BINDIR=/usr/bin
    %install_license COPYING COPYING-v3

    install -Dm00644 dnsmasq.conf.example ${installdir}/usr/share/defaults/dnsmasq/dnsmasq.conf
    install -Dm00644 trust-anchors.conf -t ${installdir}/usr/share/dnsmasq

    install -Dm00644 dbus/dnsmasq.conf ${installdir}/usr/share/dbus-1/system.d/uk.org.thekelleys.dnsmasq.conf
    install -Dm00644 $pkgfiles/dnsmasq.service -t ${installdir}/usr/lib64/systemd/system
    install -Dm00644 $pkgfiles/dnsmasq.sysusers ${installdir}/%libdir%/sysusers.d/dnsmasq.conf
