# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : asusctl
version    : 6.3.7
release    : 1
source     :
    - https://gitlab.com/asus-linux/asusctl/-/archive/6.3.7/asusctl-6.3.7.tar.gz : e971665c6bb8b81f125304574d1a0568997cd23ad67a048d595abdde6ba8d63a
homepage   : https://asus-linux.org/
license    : MPL-2.0
component  : hardware.power
summary    : Control daemon, CLI and GUI for ASUS ROG laptops
description: |
    asusctl is a control daemon, CLI tools, and Slint-based GUI for
    interacting with ASUS ROG laptops on Linux. It exposes platform
    profile, keyboard LEDs (Aura), AniMe Matrix display, battery
    charge limit, fan curves, and GPU MUX where supported.
clang      : true
networking : true
builddeps  :
    - pkgconfig(expat)
    - pkgconfig(fontconfig)
    - pkgconfig(gbm)
    - pkgconfig(libinput)
    - pkgconfig(libpcre2-8)
    - pkgconfig(libseat)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libzstd)
    - pkgconfig(xkbcommon)
    - rust
setup      : |
    %cargo_fetch
build      : |
    %make
install    : |
    %make_install prefix=/usr
    install -Dm00644 ${pkgfiles}/asusctl.tmpfiles ${installdir}/usr/lib/tmpfiles.d/asusctl.conf
    install -dm00755 ${installdir}/usr/share/licenses/${package}
    mv ${installdir}/usr/share/asusctl/LICENSE ${installdir}/usr/share/licenses/${package}/LICENSE
    rmdir ${installdir}/usr/share/asusctl
