# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : cubeb
version    : '20260123'
release    : 4
source     :
    - git|https://github.com/mozilla/cubeb : 484857522c73318c06f18ba0a3e17525fa98c608
homepage   : https://github.com/mozilla/cubeb
license    : ISC
component  : multimedia.audio
summary    : A cross-platform audio library
description: |
    A cross-platform audio library developed by Mozilla.
networking : true
clang      : true
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtest)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(sndio)
    - pkgconfig(speexdsp)
    - rust
setup      : |
    # https://github.com/mozilla/cubeb/issues/736
    sed -i '/cubeb_add_test(logging)/d' CMakeLists.txt

    # Remove Android build files
    rm -rf src/android

    %cmake \
        -DBUILD_RUST_LIBS=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_TESTS=OFF \
        -DBUNDLE_SPEEX=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_SANITIZERS=OFF
build      : |
    %cmake_build
install    : |
    %cmake_install
