# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kmod
version    : '34.2'
release    : 19
source     :
    - https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-34.2.tar.xz : 
        5a5d5073070cc7e0c7a7a3c6ec2a0e1780850c8b47b3e3892226b93ffcb9cb54
homepage   : https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git
license    :
    - LGPL-2.1-or-later # for libkmod, testsuite and helper libraries
    - GPL-2.0-or-later  # for tools
component  : system.base
summary    : Linux kernel module management utilities
description: |
    Linux kernel module management utilities
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libssl)
    - pkgconfig(libzstd)
    - pkgconfig(zlib)
    - scdoc
optimize   :
    - lto
    - size
setup      : |
    # On Solus we compress kernel modules with zstd. Users may use
    # lzma/zlib, so build support for those but use dlopen() if necessary
    %meson_configure \
        -Ddlopen=xz,zlib
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING

    # Stateless
    install -Dm 00644 ${pkgfiles}/kmod.tmpfiles ${installdir}/%libdir%/tmpfiles.d/kmod.conf
    rmdir -v \
        ${installdir}/etc/depmod.d \
        ${installdir}/etc/modprobe.d \
        ${installdir}/etc
