# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-omemo-dr
version    : 1.2.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/o/omemo-dr/omemo_dr-1.2.0.tar.gz : 18b6542b3bb7ed6dce34dd02f32b16401982ba24f0146ddae091dcb92c79a484
homepage   : https://dev.gajim.org/gajim/omemo-dr
license    : GPL-3.0-or-later
component  : programming.python
summary    : OMEMO Crypto Library
description: |
    This library handles only the crypto part of OMEMO, not the XMPP protocol part. This means you need to take care yourself of things like publishing/downloading bundles, publishing/subscribing to PEP deviceliste updates, sending and receiving messages.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - python-cryptography
    - python-protobuf
build      : |
    %pyproject_build
install    : |
    %pyproject_install
