# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : signon-kwallet-extension
version    : 26.08.2
release    : 96
source     :
    - https://download.kde.org/stable/release-service/26.08.2/src/signon-kwallet-extension-26.08.2.tar.xz : bc5cd2cc79683cee25e7f8ad5b405e00494cfebc97f543c3e1185b8caf1d88f1
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kf6-kwallet-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
