# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : signon-kwallet-extension
version    : 26.04.2
release    : 93
source     :
    - https://download.kde.org/stable/release-service/26.04.2/src/signon-kwallet-extension-26.04.2.tar.xz : a8795fa827a6996b91c100d10e8a0c302ae7f8c731c5cc540d50f5a723a2891f
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kf6-kwallet-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
