# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libde265
version    : 1.0.19
release    : 15
source     :
    - https://github.com/strukturag/libde265/releases/download/v1.0.19/libde265-1.0.19.tar.gz : bb19a0b485d2643e0eeb7e91f3ab32d1ad617e7c487dbedc91214ca3dbd8d7eb
homepage   : https://www.libde265.org/
license    : LGPL-3.0-or-later
component  : multimedia.codecs
summary    : An open h.265 video codec implementation
description: |
    libde265 is an open source implementation of the h.265 video codec. It is written from scratch and has a plain C API to enable a simple integration into other software. libde265 supports WPP and tile-based multithreading and includes SSE optimizations. The decoder includes all features of the Main profile and correctly decodes almost all conformance streams.
setup      : |
    # disable dec265 & sherlock265 examples so we don't need any build dependencies
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DENABLE_DECODER=OFF \
        -DENABLE_SHERLOCK265=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
