# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-activities-stats
version    : 6.7.3
release    : 50
source     :
    - https://download.kde.org/stable/plasma/6.7.3/plasma-activities-stats-6.7.3.tar.xz : 448b85d569f3912f8c93c1c412e36551bab7dfe8991baa0c6206c60223e98a08
homepage   : https://invent.kde.org/plasma/plasma-activities-stats
license    :
    - CC0-1.0
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : A library for accessing the usage data collected by the activities system.
description: |
    A library for accessing the usage data collected by the activities system.
builddeps  :
    - pkgconfig(Qt6Core)
    - kf6-kconfig-devel
    - plasma-activities-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
