# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : manaverse
version    : 1.9.3.23
release    : 1
source     :
    - git|https://git.themanaworld.org/mana/verse.git : 655bf6dd
homepage   : https://manaplus.germantmw.de/
license    : GPL-2.0-or-later
component  : games
summary    : Advanced game client for tmwAthena and Evol2 servers. Fork of ManaPlus.
description: |
    Advanced game client for tmwAthena and Evol2 servers. Fork of ManaPlus.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(x11)
setup      : |
    %reconfigure --with-sdl2
build      : |
    %make
install    : |
    %make_install
    ln -srv $installdir/usr/bin/manaplus $installdir/usr/bin/manaverse

    %install_license COPYING
replaces   :
    - manaplus
