# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dua-cli
version    : 2.42.0
release    : 11
source     :
    - https://github.com/Byron/dua-cli/archive/refs/tags/v2.42.0.tar.gz : 1be17656a08653ed75f9187a8909c2fbed0f03da0a5d1a11ab648ab2ee08e332
homepage   : https://github.com/Byron/dua-cli
license    : MIT
component  : system.utils
summary    : A tool to conveniently learn about the disk usage of directories
description: |
    dua (Disk Usage Analyzer) is a tool to conveniently learn about the disk usage of directories, fast! It offers a terminal user interface for interactive exploration and supports parallel directory traversal for improved performance.
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install dua
    %install_license LICENSE

    # Shell completions
    %install_dir ${installdir}/usr/share/{bash-completion/completions,fish/vendor_completions.d,zsh/site-functions}
    ./target/release/dua completions bash > ${installdir}/usr/share/bash-completion/completions/dua
    ./target/release/dua completions zsh  > ${installdir}/usr/share/zsh/site-functions/_dua
    ./target/release/dua completions fish > ${installdir}/usr/share/fish/vendor_completions.d/dua.fish
check      : |
    %cargo_test -- --skip interactive
