# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libiconv
version    : '1.19'
release    : 9
source     :
    - https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.19.tar.gz : 88dd96a8c0464eca144fc791ae60cd31cd8ee78321e67397e25fc095c4a19aa6
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
homepage   : https://www.gnu.org/software/libiconv/
summary    : GNU LIBICONV - character set conversion library
description: This library provides an iconv() implementation, for use on systems which don't have one, or whose implementation cannot convert from/to Unicode.
setup      : |
    %configure
build      : |
    # #Ignore a warning in stdio.in.h
    # sed -i -e '697d' srclib/stdio.in.h
    %make
install    : |
    %make_install
    %install_license COPYING
    # conflicts with glibc iconv
    rm %installroot%/usr/bin/iconv
    rm %installroot%/usr/include/iconv.h

    rmdir -v $installdir/usr/bin
