# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kdav
version    : 6.24.0
release    : 30
source     :
    - https://download.kde.org/stable/frameworks/6.24/kdav-6.24.0.tar.xz : acc5698655403a0d2fbeadf2405218662a42d2201c41edb33651083615642913
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : DAV protocol implementation with KJobs
description: |
    DAV protocol implementation with KJobs
builddeps  :
    - kf6-kio-devel
rundeps    :
    - devel :
        - kf6-kcoreaddons-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
