# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kdav
version    : 6.29.0
release    : 35
source     :
    - https://download.kde.org/stable/frameworks/6.29/kdav-6.29.0.tar.xz : 0a4d5c21bace495004571b626a14ae864362a069caea153d8a149a911524cd08
homepage   : https://community.kde.org/Frameworks
license    :
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : DAV protocol implementation with KJobs
description: |
    DAV protocol implementation with KJobs
builddeps  :
    - kf6-kio-devel
rundeps    :
    - devel :
        - kf6-kcoreaddons-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
