# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kdecoration
version    : 6.7.1
release    : 138
source     :
    - https://download.kde.org/stable/plasma/6.7.1/kdecoration-6.7.1.tar.xz : 3a5d8f57bab452eabd1aadc45088b95a669a951626c7e601f6a0ef36030684bf
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - CC0-1.0
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
