# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-findpython
version    : 0.8.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/f/findpython/findpython-0.8.0.tar.gz : 53b32264874dfa5990bd09d717819386d8db3149d89fe20f88fe1078de286bae
homepage   : https://github.com/frostming/findpython
license    : MIT
component  : programming.python
summary    : A utility to find python versions on your system
description: |
    This library is a rewrite of pythonfinder project by @techalchemy. It simplifies the whole code structure while preserving most of the original features.
builddeps  :
    - python-build
    - python-installer
    - python-pdm-backend
    - python-wheel
checkdeps  :
    - python-platformdirs
    - python-pytest
rundeps    :
    - python-packaging
    - python-platformdirs
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    # Deselected test fails because tests are run as root
    %pytest -v --deselect tests/test_posix.py::test_find_python_exclude_unreadable
