# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kpmcore
version    : 26.04.3
release    : 69
source     :
    - https://download.kde.org/stable/release-service/26.04.3/src/kpmcore-26.04.3.tar.xz : 08018d9465fccaf9f56ee8178f2aa3419d6bcfef667308bb558e387516216e6d
homepage   : https://invent.kde.org/system/kpmcore
license    :
    - CC-BY-4.0
    - CC0-1.0
    - GPL-3.0-or-later
    - MIT
component  : programming.library
summary    : Library for managing partitions
description: |
    Common code for KDE Partition Manager and other projects. Library for managing partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(polkit-qt6-1)
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - kf6-kwidgetsaddons-devel
rundeps    :
    - devel :
        - qt6-base-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    # we need this for calamares
    # https://github.com/calamares/calamares/issues/2367
    # https://invent.kde.org/system/kpmcore/-/merge_requests/52
    %patch -p1 -R -i $pkgfiles/52.diff
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
