# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kpmcore
version    : 26.04.1
release    : 67
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/kpmcore-26.04.1.tar.xz : d14b349f16bdbbc26086e5eeea71e2fe7d657157fa0721ef3952ea439ee96f9b
homepage   : https://invent.kde.org/system/kpmcore
license    : GPL-3.0-or-later
component  : programming.library
summary    : Library for managing partitions
description: |
    Common code for KDE Partition Manager and other projects. Library for managing partitions.
builddeps  :
    - pkgconfig(blkid)
    - pkgconfig(polkit-qt6-1)
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - kf6-kwidgetsaddons-devel
rundeps    :
    - devel :
        - qt6-base-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    # we need this for calamares
    # https://github.com/calamares/calamares/issues/2367
    # https://invent.kde.org/system/kpmcore/-/merge_requests/52
    %patch -p1 -R -i $pkgfiles/52.diff
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
