# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : conmon
version    : 2.2.1
release    : 29
source     :
    - https://github.com/containers/conmon/archive/refs/tags/v2.2.1.tar.gz : 814fb5979a3a4b8576b1f901e606b482bebb41cb7e57926e6d5765ee786b96d3
license    : Apache-2.0
homepage   : https://github.com/containers/conmon
component  : virt
summary    : An OCI container runtime monitor
description: |
    Conmon is a monitoring program and communication tool between a container manager (podman) and an OCI runtime (runc) for a single container.
networking : true
builddeps  :
    - pkgconfig(libseccomp)
    - git
    - go-md2man
    - golang
rundeps    :
    - runc
environment: |
    export PREFIX=%PREFIX%
build      : |
    set -e
    GIT_COMMIT=$(git ls-remote https://github.com/containers/conmon refs/tags/v$version | awk '{print $1}')
    %make GIT_COMMIT="$GIT_COMMIT"
install    : |
    %make_install
    %install_license LICENSE
