# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : snapd-glib
version    : '1.72'
release    : 18
source     :
    - https://github.com/canonical/snapd-glib/archive/refs/tags/1.72.tar.gz : b7367792b58047da5e8f81d5c3a694a5c141b40f29b5ac2037340c24d9c12e52
homepage   : https://snapcraft.io/
license    : LGPL-3.0-or-later
component  : programming.library
summary    : glib library for communicating with snapd
description: |
    glib library for communicating with snapd
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(Qt6Core)	
    - pkgconfig(Qt6Network)
    - pkgconfig(Qt6Qml)
    - pkgconfig(vapigen)
    - gobject-introspection-devel
    - vala
setup      : |
    %meson_configure -Ddocs=false
build      : |
    %meson_build
install    : |
    %meson_install
patterns   :
    - ^snapd-qt :
        - /usr/lib64/libsnapd-qt-*.so.*
        - /usr/lib64/qt6/qml/Snapd*/*
    - ^snapd-qt-devel :
        - /usr/include/snapd-qt-*/*
        - /usr/lib64/libsnapd-qt-*.so
        - /usr/lib64/pkgconfig/snapd-qt-*.pc
        - /usr/lib64/cmake/Snapd*/*
