# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : cpptrace
version    : 1.0.4
release    : 1
source     :
    - https://github.com/jeremy-rifkin/cpptrace/archive/refs/tags/v1.0.4.tar.gz : 5c9f5b301e903714a4d01f1057b9543fa540f7bfcc5e3f8bd1748e652e24f9ea
homepage   : https://github.com/jeremy-rifkin/cpptrace
license    : MIT
component  : programming.library
summary    : Simple, portable, and self-contained stacktrace library for C++11 and newer
description: |
    Cpptrace is a simple and portable C++ stacktrace library supporting C++11 and greater on Linux, macOS, and Windows including MinGW and Cygwin environments. The goal: Make stack traces simple for once.
builddeps  :
    - pkgconfig(libdwarf)
    - pkgconfig(libunwind)
    - pkgconfig(libzstd)
setup      : |
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DCPPTRACE_FIND_LIBDWARF_WITH_PKGCONFIG=ON \
        -DCPPTRACE_UNWIND_WITH_LIBUNWIND=ON \
        -DCPPTRACE_USE_EXTERNAL_LIBDWARF=ON \
        -DCPPTRACE_USE_EXTERNAL_ZSTD=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
