# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gramps
version    : 6.0.8
release    : 32
source     :
    - https://github.com/gramps-project/gramps/archive/refs/tags/v6.0.8.tar.gz : f36069c71449b92636883f69addae38e76fa07ec37d9b3fcb5cac0b38390e314
homepage   : https://gramps-project.org
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Gramps genealogical research software
description: |
    Gramps is a free software project and community. We strive to produce a genealogy program that is both intuitive for hobbyists and feature-complete for professional genealogists. It is a community project, created, developed and governed by genealogists.
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - gexiv2-0.14
    - goocanvas
    - graphviz
    - osm-gps-map
    - pyicu
    - python-bsddb3
    - python-gobject
    - python-orjson
    - python-pillow
    - pyxdg
build      : |
    %pyproject_build
install    : |
    %pyproject_install
