# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-console
version    : '51.0'
release    : 10
source     :
    - https://download.gnome.org/sources/gnome-console/51/gnome-console-51.0.tar.xz : f40d13903b1f067f0c02e0812f78df8ec25d8cd129794e7e46bd56ca0c156f2f
homepage   : https://apps.gnome.org/Console/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Terminal Emulator
description: |
    A simple user-friendly terminal emulator for the GNOME desktop
optimize   :
    - lto
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(vte-2.91-gtk4)
    - appstream
    - desktop-file-utils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
