# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : rocm-clr
version    : 7.2.0
release    : 11
source     :
    - https://github.com/ROCm/rocm-systems/archive/refs/tags/rocm-7.2.0.tar.gz : 728ea7e9bf16e6ed217a0fd1a8c9afaba2dae2e7908fa4e27201e67c803c5638
    - https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-7.2.0.tar.gz#HIPCC-7.2.0.tar.gz : e86138d2a63fbcbdf64668d55573b26ae944d0f0ae5a3f5bb59bf7bdb3124d3f
homepage   : https://github.com/ROCm/clr
license    : MIT
component  : programming.library
summary    : AMD Common Language Runtime for HIP and OpenCL
description: |
    AMD Common Language Runtime contains source code for AMD's HIP and OpenCL compute languages runtimes.
builddeps  :
    - pkgconfig(OpenCL)
    # - pkgconfig(d3d)
    - pkgconfig(gl)
    - pkgconfig(numa)
    - pkgconfig(x11-xcb)
    - python-cppheaderparser
    - rocm-cmake
    - rocm-compilersupport-devel
    - rocm-device-libs-devel
    - rocm-llvm
    - rocm-runtime-devel
    - rocprofiler-register-devel
rundeps    :
    - ^rocm-hip:
      - rocm-clr
      - rocm-device-libs-devel
      - rocm-compilersupport-devel
      - rocm-info
      - rocm-runtime-devel
      - rocm-smi-devel
    - ^rocm-opencl:
      - rocm-clr
patterns   :
    - ^rocm-hip:
      - /usr/bin/hip*
      - /usr/bin/roc-*
      - /usr/include/hip*
      - /usr/lib64/cmake/hip*
      - /usr/lib64/libamdhip64.so
      - /usr/lib64/libhiprtc.so
      - /usr/lib64/libhiprtc-builtins.so
    - ^rocm-opencl:
      - /usr/include/rocm-opencl
      - /usr/lib64/libamdocl64.so
      - /usr/lib64/libcltrace.so
replaces   :
    - ^rocm-hip:
      - rocm-hip-devel
    - ^rocm-opencl:
      - rocm-opencl-devel
environment: |
    export ROCM_PATH=/usr
    export CMAKE_PREFIX_PATH=/usr/lib64/llvm-rocm
    export HIP_DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
    export HIP_CLANG_PATH=/usr/lib64/llvm-rocm/bin
    export HIP_PLATFORM=amd

    export HIP_DIR=$workdir/projects/hip
    export ROCTRACER_DIR=$workdir/projects/roctracer
    export HIPCC_DIR=$workdir/HIPCC

    export GCC_IGNORE_WERROR=1
setup      : |
    pushd $sources
        mkdir -p $HIPCC_DIR
        tar --strip-components=3 -C $HIPCC_DIR -xf $sources/HIPCC-%version%.tar.gz llvm-project-rocm-%version%/amd/hipcc
    popd

    pushd $HIPCC_DIR
        %patch -p3 -i $pkgfiles/0014-Add-HIP_CLANG_LAUNCHER-for-launching-Clang-through-a.patch
        %cmake_ninja -DHIPCC_BACKWARD_COMPATIBILITY=OFF
        %ninja_build
    popd

    pushd projects/clr/opencl
        # Add soname to amdocl and cltrace:
        # Upstream doesn't want this because they don't guarentee ABI.
        # Just use the package version. SOVERSION can be major.minor as patch releases
        # are unlikely to break anything.
        echo "set_target_properties(amdocl PROPERTIES VERSION %version% SOVERSION $(v=%version%;echo ${v%%.*}))" \
            >> amdocl/CMakeLists.txt
        echo "libamdocl64.so.%{rocm_release}" > config/amdocl64.icd
        echo "set_target_properties(cltrace PROPERTIES VERSION %version% SOVERSION $(v=%version%;echo ${v%%.*}))" \
            >> tools/cltrace/CMakeLists.txt
    popd

    %apply_patches

    %cmake_ninja -S projects/clr -L \
      -DROCM_PATH=$ROCM_PATH \
      -DHIP_COMMON_DIR=$HIP_DIR \
      -DHIPCC_BIN_DIR=$HIPCC_DIR/solusBuildDir \
      -DCLR_BUILD_HIP=ON \
      -DCLR_BUILD_OCL=ON \
      -DBUILD_ICD=OFF \
      -DPROF_API_HEADER_PATH=$ROCTRACER_DIR/inc/ext \
      -DHIP_ENABLE_ROCPROFILER_REGISTER=ON \
      -DBUILD_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -dm00644 $installdir/usr/share/OpenCL/vendors
    echo "libamdocl64.so.7" >> $installdir/usr/share/OpenCL/vendors/amdocl64.icd

    # Avoid file conflicts with opencl-headers package:
    install -dm00644 $installdir/usr/include/rocm-opencl
    mv $installdir/usr/include/CL $installdir/usr/include/rocm-opencl/CL

    # Avoid file conflicts with clinfo package:
    mv $installdir/usr/bin/clinfo $installdir/usr/bin/rocm-clinfo
