# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : vapoursynth
version    : '75'
release    : 51
source     :
    - https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R75.tar.gz : a1f71019de7f5c252c309e134f245bf49d64038b1f4e1df7f4dfb1e1ed290526
homepage   : https://www.vapoursynth.com/
license    :
    - LGPL-2.1-or-later
    - OFL-1.1
component  : multimedia.library
summary    : A video processing framework with simplicity in mind
description: |
    A video processing framework with simplicity in mind.
libsplit   : false
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(zimg)
    - cython
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING*
    install -Dm00644 ${pkgfiles}/vapoursynth.xml -t ${installdir}/usr/share/mime/packages/

    # Upstream installs development files in the python module directory.
    # Provide compatibility symlinks in standard system locations.
    install -dm00755 ${installdir}/usr/include/vapoursynth
    ln -sv ../lib/python%python3_version%/site-packages/vapoursynth/include/VSConstants4.h ${installdir}/usr/include/vapoursynth/VSConstants4.h
    ln -sv ../lib/python%python3_version%/site-packages/vapoursynth/include/VSHelper4.h ${installdir}/usr/include/vapoursynth/VSHelper4.h
    ln -sv ../lib/python%python3_version%/site-packages/vapoursynth/include/VSScript4.h ${installdir}/usr/include/vapoursynth/VSScript4.h
    ln -sv ../lib/python%python3_version%/site-packages/vapoursynth/include/VapourSynth4.h ${installdir}/usr/include/vapoursynth/VapourSynth4.h

    ln -sv python%python3_version%/site-packages/vapoursynth/libvapoursynth.so ${installdir}/usr/lib/libvapoursynth.so
    ln -sv python%python3_version%/site-packages/vapoursynth/libvapoursynth.so.4 ${installdir}/usr/lib/libvapoursynth.so.4
    ln -sv python%python3_version%/site-packages/vapoursynth/libvsscript.so ${installdir}/usr/lib/libvsscript.so

    install -dm00755 ${installdir}/usr/lib/pkgconfig
    ln -sv ../python%python3_version%/site-packages/vapoursynth/pkgconfig/vapoursynth.pc ${installdir}/usr/lib/pkgconfig/vapoursynth.pc
