# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lightdm
version    : 1.33.0
release    : 52
source     :
    - https://github.com/canonical/lightdm/archive/refs/tags/1.33.0.tar.gz : e699ac06f44fcbbbda9a81433588e2a916c9a222e942b023e339919a57ae5e8e
homepage   : https://github.com/Canonical/lightdm
license    :
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  :
    - gobject : desktop.gtk
    - gobject-devel : programming.devel
    - qt6 : desktop.qt
    - qt6-devel : programming.devel
    - desktop
summary    :
    - gobject : LightDM GObject client library
    - gobject-devel : Development files for lightdm-gobject
    - qt6 : LightDM Qt6 client library
    - qt6-devel : Development files for lightdm-qt6
    - Lightweight and attractive Display Manager
description:
    - gobject : This package contains a GObject based library for LightDM clients to use to interface with LightDM.
    - qt6 : This package contains a Qt6-based library for LightDM clients to use to interface with LightDM.
    - Lightweight and attractive Display Manager
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6DBus)
    - pkgconfig(Qt6Gui)
    - pkgconfig(libgcrypt)
    - pkgconfig(libxklavier)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xdmcp)
    - pkgconfig(yelp-xsl)
    - gettext-devel
    - gtk-doc
    - itstool
    - vala
    - yelp-devel
    - yelp-tools
rundeps    :
    - gobject :
        - lightdm
    - gobject-devel :
        - lightdm-gobject
    - qt6 :
        - lightdm
    - qt6-devel :
        - lightdm-qt6
    - linux-driver-management-lightdm-integration
    - setxkbmap
    - xauth
    - xhost
    - xkbcomp
    - xkeyboard-config
setup      : |
    sed -i -e 's:getgroups:lightdm_&:' tests/src/libsystem.c

    %patch -p1 -i ${pkgfiles}/0004-common-Support-a-stateless-configuration-for-etc-lig.patch

    %autogen \
        --disable-static \
        --disable-tests \
        --enable-gtk-doc \
        --enable-liblightdm-qt6 \
        --enable-introspection \
        --with-greeter-user=lightdm \
        --with-greeter-session=lightdm-gtk-greeter
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING.LGPL2 COPYING.LGPL3

    # Enable by default
    %install_file -t ${installdir}/%libdir%/systemd/system ${pkgfiles}/lightdm.service
    ln -sv lightdm.service ${installdir}/%libdir%/systemd/system/display-manager.service

    # Stateless configuration
    rm -rfv ${installdir}/etc/lightdm

    # We don't use apparmor
    rm -rfv ${installdir}/etc/init
    rm -rfv ${installdir}/etc/apparmor.d

    # Install our lightdm wrapper
    %install_bin ${pkgfiles}/lightdm-wrapper

    # Install lightdm configuration
    %install_file ${pkgfiles}/lightdm.conf ${installdir}/usr/share/lightdm/lightdm.conf.d/10_solus_default.conf
    %install_file -t ${installdir}/usr/share/lightdm ${pkgfiles}/users.conf

    # Sysusers and tmpfiles
    %install_file ${pkgfiles}/lightdm.tmpfiles ${installdir}/%libdir%/tmpfiles.d/lightdm.conf
    %install_file ${pkgfiles}/lightdm.sysusers ${installdir}/%libdir%/sysusers.d/lightdm.conf

    # Install polkit rules
    %install_file -t ${installdir}/usr/share/polkit-1/rules.d ${pkgfiles}/lightdm.rules

    # Allow us to forward xorg logs to the journal
    %install_exe -t ${installdir}/%libdir%/${package} ${pkgfiles}/xserver-wrapper

    # PAM configs
    %install_dir ${installdir}/usr/share/defaults/etc/pam.d
    mv ${installdir}/etc/pam.d/* ${installdir}/usr/share/defaults/etc/pam.d/
    rmdir -v ${installdir}/etc/pam.d \
             ${installdir}/etc
conflicts  :
    - gdm
    - greetd
    - sddm
patterns   :
    - gobject :
        - /usr/lib64/liblightdm-gobject-*.so.*
    - gobject-devel :
        - /usr/include/lightdm-gobject-*
        - /usr/lib64/liblightdm-gobject-*.so
        - /usr/lib64/pkgconfig/liblightdm-gobject-*.pc
        - /usr/share/gir-1.0/LightDM-*.gir
        - /usr/share/vala/vapi/liblightdm-gobject-*.*
    - qt6 :
        - /usr/lib64/liblightdm-qt6-*.so.*
    - qt6-devel :
        - /usr/include/lightdm-qt6-*
        - /usr/lib64/liblightdm-qt6-*.so
        - /usr/lib64/pkgconfig/liblightdm-qt6-*.pc
