# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : naev
version    : 0.13.4
release    : 27
source     :
    - https://codeberg.org/naev/naev/releases/download/v0.13.4/naev-0.13.4-source.tar.xz : e3a9335cc9bf0fcf35e5e5b66ff8ed4575fefa125f709c20de270052830ceebb
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : games.action
homepage   : https://naev.org/
summary    : Naev is a 2D space trading and combat game, in a similar vein to Escape Velocity
description: |
    NAEV is played from a top-down perspective, featuring fast-paced combat, many ships, a large variety of equipment and a large galaxy to explore. The game is highly open-ended, letting you proceed at your own pace.
libsplit   : false
networking : true
builddeps  :
    - pkgconfig(dav1d)
    - pkgconfig(freetype2)
    - pkgconfig(lapack)
    - pkgconfig(libcmark)
    - pkgconfig(libenet)
    - pkgconfig(libunibreak)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(openblas)
    - pkgconfig(opus)
    - pkgconfig(physfs)
    - pkgconfig(sdl3)
    - pkgconfig(vorbis)
    - appstream
    - glpk-devel
    - mutagen
    - rust
    - rust-bindgen
    - suitesparse-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
