name       : extension-manager
version    : 0.6.5
release    : 2
source     :
    - https://github.com/mjakeman/extension-manager/archive/refs/tags/v0.6.5.tar.gz : 5a43c7b9570775948a35f402b1c1d5f0f0401e339ab2144d466f75eae26ef9de
homepage   : https://mattjakeman.com/apps/extension-manager
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Browse, install, and manage GNOME Extensions with ease.
description: |
    A native tool for browsing, installing, and managing GNOME Shell Extensions in one app.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsoup-3.0)
    - blueprint-compiler
    - desktop-file-utils
setup      : |
    %meson_configure -Dbacktrace=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
