# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kicad-templates
version    : 10.0.5
release    : 23
source     :
    - https://gitlab.com/kicad/libraries/kicad-templates/-/archive/10.0.5/kicad-templates-10.0.5.tar.gz : bb42390db45f8a6b1539c6f83850ad2091506b6a63598049b4bc805900491145
homepage   : https://www.kicad.org/
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : KiCad project templates
description: |
    KiCad project templates
setup      : |
    %cmake
install    : |
    %make_install
    %install_license LICENSE.md
