# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : rssguard
version    : 5.1.0
release    : 21
source     :
    - https://github.com/martinrotter/rssguard/releases/download/5.1.0/rssguard-5.1.0-src.tar.gz : eb36e6bda7996901c3492c293461037067c45a6bae31efad29ff9e4ba55471fd
license    : GPL-3.0-or-later
homepage   : https://github.com/martinrotter/rssguard
component  : network.news
summary    : Simple (yet powerful) Qt feed reader
description: |
    Simple (yet powerful) Qt feed reader
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6WebEngineWidgets)
    - pkgconfig(mpv)
    - golang
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/0001-default-settings.patch
    %cmake_ninja -DNO_UPDATE_CHECK=ON \
                 -DREVISION_FROM_GIT=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - /usr/lib64/librssguard.so
