# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : fooyin
version    : 0.10.5
release    : 22
source     :
    - https://github.com/fooyin/fooyin/archive/refs/tags/v0.10.5.tar.gz : cd0fe77028fc5d181faf1da517e1e2a74166331bbd1f07a62c4bcc139e189af2
homepage   : https://www.fooyin.org/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : fooyin is a music player built around customisation.
description: |
    fooyin is a music player built around customisation.
clang      : true
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6Platform)
    - pkgconfig(Qt6SvgWidgets)
    - pkgconfig(alsa)
    - pkgconfig(icu-i18n)
    - pkgconfig(libavfilter)
    - pkgconfig(libspa-0.2)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(taglib)
    - kdsingleapplication-devel
    - qcoro-qt6-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
