# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : caddy
version    : 2.11.3
release    : 26
source     :
    - https://github.com/caddyserver/caddy/archive/refs/tags/v2.11.3.tar.gz : de751e6b7ca769f0dc1f9b0a1949c7b149c115efde3aaf53182da2bf6a94c825
    - git|https://github.com/caddyserver/dist.git : 836ff569ed513837874a3aa5441f6719622bb08c
homepage   : https://caddyserver.com
license    : Apache-2.0
component  : programming
summary    : Fast, multi-platform web server with automatic HTTPS
description: |
    Caddy is a powerful, open source web server with automatic HTTPS written in Go
networking : true
builddeps  :
    - golang
setup      : |
    %patch -p1 -i ${pkgfiles}/0001-Disable-commands-that-can-alter-the-binary.patch
    cp -r ${sources}/dist* dist
    %patch -p1 -i ${pkgfiles}/0001-Tweak-welcome-site-for-Solus.patch

    GOFLAGS="-mod=readonly" go mod vendor -v
build      : |
    export CGO_LDFLAGS=${LDFLAGS}
    export CGO_CPPFLAGS=${CPPFLAGS}
    export CGO_CFLAGS=${CFLAGS}
    export CGO_CXXFLAGS=${CXXFLAGS}
    export GOFLAGS="-buildmode=pie -mod=vendor -modcacherw -buildvcs=false"
    export GOPATH="${workdir}"

    ld_flags=" \
        -X github.com/caddyserver/caddy/v2.CustomVersion=v${version} \
        -compressdwarf=false \
        -linkmode=external \
    "

    go build -v -ldflags "${ld_flags}" -o bin/caddy ./cmd/caddy

    # Generate completions
    mkdir completions
    for i in bash zsh fish; do
        ./bin/caddy completion ${i} > ${package}.${i}
    done
install    : |
    install -Dm00755 bin/caddy ${installdir}/usr/bin/caddy
    %install_license LICENSE

    install -Dm00644 ${pkgfiles}/${package}.sysusers ${installdir}/%libdir%/sysusers.d/${package}.conf
    install -Dm00644 ${pkgfiles}/${package}.tmpfiles ${installdir}/%libdir%/tmpfiles.d/${package}.conf

    # Install systemd services and default config
    install -Dm00644 dist/init/caddy.service dist/init/caddy-api.service -t ${installdir}/%libdir%/systemd/system
    install -Dm00644 ${pkgfiles}/${package}.preset ${installdir}/%libdir%/systemd/system-preset/60-${package}.preset
    install -Dm00644 dist/config/Caddyfile ${installdir}/usr/share/caddy/Caddyfile

    # Install default welcome page
    install -Dm00644 dist/welcome/index.html ${installdir}/usr/share/caddy/index.html

    # Install manpages
    ./bin/caddy manpage --directory ${installdir}/usr/share/man/man8

    # Install completions
    install -vDm00644 ${package}.bash "${installdir}/usr/share/bash-completion/completions/${package}"
    install -vDm00644 ${package}.zsh "${installdir}/usr/share/zsh/site-functions/_${package}"
    install -vDm00644 ${package}.fish "${installdir}/usr/share/fish/vendor_completions.d/${package}.fish"
check      : |
    # ensure that the version was embedded correctly
    [[ "$(./bin/caddy version)" == "v${version}" ]] || exit 1

    go test --short ./...
