# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-google-auth
version    : 2.56.3
release    : 11
source     :
    - https://github.com/googleapis/google-cloud-python/archive/refs/tags/google-auth-v2.56.3.tar.gz : 
        0d96ed9deef233e168ef5b52b6d74cad5c6d2c461fef110d9f8469b1ff0a335f
homepage   : https://pypi.org/project/google-auth/
license    : Apache-2.0
component  : programming.python
summary    : Google Auth Python Library
description: |
    This library simplifies using Google's various server-to-server authentication mechanisms to access Google APIs.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
# checkdeps  :
#     - flask
#     - python-aiohttp
#     - python-asn1-modules
#     - python-cryptography
#     - python-freezegun
#     - python-pytest
#     - python-pytest-asyncio
rundeps    :
    - python-asn1-modules
    - python-cryptography
build      : |
    pushd packages/google-auth
    %pyproject_build
install    : |
    pushd packages/google-auth
    %pyproject_install
# check      : |
#     pushd packages/google-auth
#     %pytest -v
