# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-sonnet
version    : 6.26.0
release    : 36
source     :
    - https://download.kde.org/stable/frameworks/6.26/sonnet-6.26.0.tar.xz : 3ac4e165c0b3c79eda416b754bb837292f354188a1220f2065f57f686489af25
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.tools
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - extra-cmake-modules
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-base-devel
clang      : true
optimize   : thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
