# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-module-runtime
version    : '0.018'
release    : 12
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Module-Runtime-0.018.tar.gz : 0bf77ef68e53721914ff554eada20973596310b4e2cf1401fc958601807de577
homepage   : https://metacpan.org/pod/Module::Runtime
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Module::Runtime - runtime module handling
description: |
    The functions exported by this module deal with runtime handling of Perl modules, which are normally handled at compile time
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
check      : |
    %perl_build test
patterns   : /*
