# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : breeze-icons
version    : 6.27.0
release    : 112
source     :
    - https://download.kde.org/stable/frameworks/6.27/breeze-icons-6.27.0.tar.xz : bc8c2337802837ff1809269a8e4c4311b93e7e90c78ab4fe2a86cf5300ffd414
homepage   : https://community.kde.org/Frameworks
license    :
    - CC-BY-SA-4.0
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
    - python-lxml
    - qt6-base-private-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING-ICONS COPYING.LIB

    # Re-use icon for Doflicky
    ln -srv $installdir/usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -srv $installdir/usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg

    # Required for Solus-SC
    ln -s update-none-symbolic.svg $installdir/usr/share/icons/breeze/status/22/software-update-available.svg
    ln -s update-none-symbolic.svg $installdir/usr/share/icons/breeze-dark/status/22/software-update-available.svg
