# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : breeze-icons
version    : 6.26.0
release    : 111
source     :
    - https://download.kde.org/stable/frameworks/6.26/breeze-icons-6.26.0.tar.xz : 4e123fac511dfab2b7c505857849a5cecfac2ce6194e3230c51ceec31676b06e
homepage   : https://community.kde.org/Frameworks
license    :
    - CC-BY-SA-4.0
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.theme
summary    : Breeze icon theme
description: |
    Breeze-icons is a freedesktop.org compatible icon theme.
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
    - python-lxml
    - qt6-base-private-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING-ICONS COPYING.LIB

    # Re-use icon for Doflicky
    ln -srv $installdir/usr/share/icons/breeze/devices/64/cpu.svg $installdir/usr/share/icons/breeze/apps/48/jockey.svg
    ln -srv $installdir/usr/share/icons/breeze-dark/devices/64/cpu.svg $installdir/usr/share/icons/breeze-dark/apps/48/jockey.svg

    # Required for Solus-SC
    ln -s update-none-symbolic.svg $installdir/usr/share/icons/breeze/status/22/software-update-available.svg
    ln -s update-none-symbolic.svg $installdir/usr/share/icons/breeze-dark/status/22/software-update-available.svg
