# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : adwaita-icon-theme
version    : '51.0'
release    : 34
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/51/adwaita-icon-theme-51.0.tar.xz : ba561cf3c96305a47179fa5605856ad695c9238ea07f7093aebd9ba80c4e323b
homepage   : https://gitlab.gnome.org/GNOME/adwaita-icon-theme
license    :
    - CC-BY-SA-3.0
    - LGPL-3.0-or-later
summary    : The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(librsvg-2.0)
    - inkscape
rundeps    :
    - adwaita-icon-theme-legacy
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 -i $pkgfiles/remove-unused-icon-theme-caches.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
