# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : bspwm
version    : 0.9.12
release    : 11
source     :
    - https://github.com/baskerville/bspwm/archive/0.9.12.tar.gz : ca3be808e3d0c785955f1613e6e860fc51b5db086b821b48707466da1a06392c
homepage   : https://github.com/baskerville/bspwm
license    : BSD-2-Clause
component  : desktop
summary    : A tiling window manager based on binary space partitioning
description: |
    A tiling window manager based on binary space partitioning
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xinerama)
    - sxhkd
rundeps    :
    - sxhkd
build      : |
    %make PREFIX=/usr
install    : |
    %install_license LICENSE
    %make_install PREFIX=/usr
    rm -rf $installdir/usr/share/doc/bspwm/*.md
