# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-modemmanager-qt
version    : 6.27.0
release    : 34
source     :
    - https://download.kde.org/stable/frameworks/6.27/modemmanager-qt-6.27.0.tar.xz : a893a169dd40c430c51d39326b1af0aab2a9d6c20adc34f2b8e6332c152f6234
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-only
    - GPL-3.0-only
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(Qt6Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - modem-manager-devel
        - qt6-base-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
