name       : polkit-kde-agent
version    : 6.2.1
release    : 108
source     :
    - https://download.kde.org/stable/plasma/6.2.1/polkit-kde-agent-1-6.2.1.tar.xz : 9703e93fdb69bbda953418d748dedbf25a16afd116fc5099e8a6a1b7e41012c7
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
builddeps  :
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(polkit-qt6-1)
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
