# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-filelock
version    : 3.32.2
release    : 21
source     :
    - https://pypi.io/packages/source/f/filelock/filelock-3.32.2.tar.gz : c33351e1f49cae33414acbc6d56784e6ecee82514ec90795da1161fc4836b5b8
homepage   : https://github.com/tox-dev/py-filelock/
license    : MIT
component  : programming.python
summary    : A platform independent file lock for Python
description: |
    This package contains a single module, which implements a platform independent file lock in Python, which provides a simple way of inter-process communication.
builddeps  :
    - python-build
    - python-hatch-vcs
    - python-installer
    - python-wheel
checkdeps  :
    - python-pytest
    - python-pytest-asyncio
    - python-pytest-mock
    - python-pytest-timeout
    - virtualenv
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    # Operation probably succeeds because tests are run as root
    %pytest -v --deselect tests/test_strict_soft.py::test_strict_soft_unreadable_claim_fails_closed
