# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : numix-icon-theme-circle
version    : 26.02.21
release    : 57
source     :
    - https://github.com/numixproject/numix-icon-theme-circle/archive/refs/tags/26.02.21.tar.gz : 0a64821bc9ce005be4d2d2786bcbbfb0e908932e1c3c4cf65859da2cccd598ba
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Circle Icon Theme
description: |
    Numix Circle is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Circle,Numix-Circle-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
    %install_license LICENSE
