# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-colorlog
version    : 6.12.0
release    : 17
source     :
    - https://github.com/borntyping/python-colorlog/archive/refs/tags/v6.12.0.tar.gz : e2af839288367ac5785e819fc288a7fcf9b63a48883dcd5c677e4c627cd3f4f7
homepage   : https://github.com/borntyping/python-colorlog
license    : MIT
component  : programming.python
summary    : A colored formatter for the python logging module
description: |
    colorlog.ColoredFormatter is a formatter for use with Python's logging module that outputs records using terminal colors.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-pytest
setup      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
