# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : accountsservice
version    : 26.27.3
release    : 39
source     :
    - https://gitlab.freedesktop.org/accountsservice/accountsservice/-/archive/26.27.3/accountsservice-26.27.3.tar.gz : 
        11de07bcd499c2277f78a6fc830d1437654f3397cc7bbed19c28b3818435ba38
homepage   : https://www.freedesktop.org/wiki/Software/AccountsService
license    : GPL-3.0-or-later
component  : desktop.core
summary    : D-Bus service for accessing user accounts and information
description: |
    AccountsService is a D-Bus service for accessing the list of user accounts and information attached to those accounts.
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(json-c)
    - pkgconfig(libxcrypt)
    - vala
checkdeps  :
    - python-dbusmock
    - python3-test
setup      : |
    %patch -p1 -i $pkgfiles/0001-daemon-Stateless-systemd-service-path.patch
    %patch -p1 -i $pkgfiles/0001-daemon-Add-support-for-default-user-groups.patch
    %patch -p1 -i $pkgfiles/0001-tests-Drop-check-format-test.patch

    %meson_configure --sysconfdir=/usr/share \
        -Dadmin_group=wheel \
        -Dextra_admin_groups="adm,lpadmin" \
        -Ddefault_user_groups="audio,video,cdrom,dialout,fuse,users,sambashares" \
        -Dgtk_doc=true \
        -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Stateless
    install -Dm00644 $pkgfiles/accountsservice.tmpfiles $installdir/usr/lib/tmpfiles.d/accountsservice.conf
    rmdir -v $installdir/var/lib/AccountsService/icons \
             $installdir/var/lib/AccountsService/users \
             $installdir/var/lib/AccountsService/ \
             $installdir/var/lib/ \
             $installdir/var/
# Tests cannot be run as root
# check      : |
#     unset LD_PRELOAD
#     %ninja_check
