# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kguiaddons
version    : 6.28.0
release    : 42
source     :
    - https://download.kde.org/stable/frameworks/6.28/kguiaddons-6.28.0.tar.xz : f46aeca80707e774fcffe8aa82e464a81056ce84f613347a5c9cc24c1c9a8432
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - CC0-1.0
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-tools-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6 -DBUILD_PYTHON_BINDINGS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
