# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kpeople
version    : 6.26.0
release    : 35
source     :
    - https://download.kde.org/stable/frameworks/6.26/kpeople-6.26.0.tar.xz : bd1092cd9900d0ee3b3d08d0971e669a82d1a11c9bec6e2322d713b59191b873
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.1-or-later
component  : programming.tools
summary    : Provides access to all contacts and aggregates them by person
description: |
    KPeople offers unified access to our contacts from different sources, grouping them by person while still exposing all the data. Furthermore, KPeople will also provide facilities to integrate the data provided in user interfaces by providing QML and Qt Widgets components.
builddeps  :
    - pkgconfig(Qt6Quick)
    - kf6-kcodecs-devel
    - kf6-kconfig-devel
    - kf6-kcontacts-devel
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - kf6-kitemviews-devel
    - kf6-kwidgetsaddons-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        - qt6-base-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
