# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-icoextract
version    : 0.3.0
release    : 3
source     :
    - https://github.com/jlu5/icoextract/archive/refs/tags/0.3.0.tar.gz : ce46a9dde2054edd13922dbe254e01eefe64a110ebbfe3c0d695fe703e9d295a
homepage   : https://projects.jlu5.com/icoextract.html
license    : MIT
component  : programming.python
summary    : Extract icons from Windows PE files (.exe/.dll)
description: |
    Icon extractor for Windows PE files (.exe/.dll) with optional thumbnailer functionality
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - imagemagick
    - mingw-w64
    - mingw-w64-32bit
    - mingw-w64-gcc
    - mingw-w64-gcc-32bit
    - python-pefile
    - python-pillow
    - python-pytest
rundeps    :
    - python-pefile
    - python-pillow
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %make \
        MINGW64="/usr/share/mingw-w64/bin/x86_64-w64-mingw32-" \
        MINGW32="/usr/share/mingw-w64/bin/i686-w64-mingw32-" \
        -C tests
    %pytest -v
