# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : rocm-device-libs
version    : 7.2.0
release    : 9
source     :
    - https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-7.2.0.tar.gz : e86138d2a63fbcbdf64668d55573b26ae944d0f0ae5a3f5bb59bf7bdb3124d3f
homepage   : https://github.com/RadeonOpenCompute/ROCm-Device-Libs
license    : NCSA
component  : xorg.driver
summary    : ROCm Device Libraries
description: |
    This package contains a set of AMD specific device-side language runtime libraries in the form of bit code. Specifically:
builddeps  :
    - rocm-cmake
    - rocm-llvm
environment: |
    export CMAKE_PREFIX_PATH=/usr/lib64/llvm-rocm
setup      : |
    %apply_patches
    %cmake_ninja -S amd/device-libs
build      : |
    %ninja_build
install    : |
    %ninja_install
