# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xkeyboard-config
version    : '2.48'
release    : 19
source     :
    - https://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.48.tar.xz : b77041324f0109f77161ee43743fe04baa485866af8460d31e476ad3f7648fd5
license    : MIT
component  : xorg.base
homepage   : https://www.x.org/
summary    : Keyboard configuration database
description: |
    The XKeyboardConfig package contains the keyboard configuration database for the X Window System.
builddeps  :
    - pkgconfig(x11)
setup      : |
    %meson_configure -Dxorg-rules-symlinks=true
build      : |
    %ninja_build
install    : |
    %ninja_install
