# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : systemd
version    : '261.2'
release    : 190
source     :
    - https://github.com/systemd/systemd/archive/refs/tags/v261.2.tar.gz : ed1059ff964f5df35b6056434cc17cc83f86dc913f10489948a0b19b6081c5ec
license    :
    - LGPL-2.1-or-later
    - GPL-2.0-or-later
component  : system.base
homepage   : https://www.github.com/systemd/systemd
summary    : System and Service Manager
description: |
    systemd is a system and service manager for Linux, compatible with SysV and LSB init scripts. systemd provides aggressive parallelization capabilities, uses socket and D-Bus activation for starting services, offers on-demand starting of daemons, keeps track of processes using Linux control groups, supports snapshotting and restoring of the system state, maintains mount and automount points and implements an elaborate transactional dependency-based service control logic. It can work as a drop-in replacement for sysvinit.
autodep    : false
clang      : true
devel      : true
emul32     : true
libsplit   : false
optimize   :
    - size
    - lto
builddeps  :
    - pkgconfig32(libcap)
    - pkgconfig32(libgcrypt)
    - pkgconfig32(libxcrypt)
    - pkgconfig32(libzstd)
    - pkgconfig32(mount)
    - pkgconfig(blkid)
    - pkgconfig(bzip2)
    - pkgconfig(dbus-1)
    - pkgconfig(fdisk)
    - pkgconfig(glib-2.0)
    - pkgconfig(gpg-error)
    - pkgconfig(libacl)
    - pkgconfig(libarchive)
    - pkgconfig(libattr)
    - pkgconfig(libbpf)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libcurl)
    - pkgconfig(libdw)
    - pkgconfig(libffi)
    - pkgconfig(libfido2)
    - pkgconfig(libidn2)
    - pkgconfig(libiptc)
    - pkgconfig(libkmod)
    - pkgconfig(liblz4)
    - pkgconfig(liblzma)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(libpcre2-8)
    - pkgconfig(libqrencode)
    - pkgconfig(libseccomp)
    - pkgconfig(openssl)
    - pkgconfig(p11-kit-1)
    - pkgconfig(pam)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(pwquality)
    - pkgconfig(tss2-esys)
    - pkgconfig(xkbcommon)
    - pkgconfig(zlib)
    - docbook-xml
    - gperf
    - libxslt
    - linux-tools-bpftool
    - python-jinja
    - python-pefile
    - python-pyelftools
    - rsync
    - sbsigntools
rundeps    :
    - 32bit :
        - libcap2-32bit
        - libgcrypt-32bit
    - 32bit-devel :
        - libcap2-32bit-devel
        - libgcrypt-32bit-devel
        - xz-32bit-devel
        - zstd-32bit-devel
    - devel :
        - libcap2-devel
        - libgcrypt-devel
        - xz-devel
        - zstd-devel
    - font-terminus-console
    - kernel-glue
    - libgcrypt
environment: |
    # TODO: Maybe one day this wont be needed
    export CFLAGS="${CFLAGS} -Wno-incompatible-pointer-types-discards-qualifiers"
setup      : |
    # Downstream patches
    %patch -p1 -i ${pkgfiles}/patches/downstream/0001-tmpfiles-Make-var-cache-ldconfig-world-readable.patch
    %patch -p1 -i ${pkgfiles}/patches/downstream/0001-tmpfiles-Allow-nsswitch-clobber-at-non-boot-interval.patch
    %patch -p1 -i ${pkgfiles}/patches/downstream/0001-gpt-auto-generate-Stop-automounting-xbootldr-and-esp.patch
    %patch -p1 -i ${pkgfiles}/patches/downstream/0001-path-lookup-Include-stateless-xdg-path-by-default.patch
    %patch -p1 -i ${pkgfiles}/patches/downstream/0001-downstream-Allow-default-font-to-be-set.patch
    %patch -p1 -i ${pkgfiles}/patches/downstream/0001-Don-t-build-32bit-EFI-stub.patch
    %patch -p1 -i ${pkgfiles}/patches/downstream/0001-Remove-etc-os-release-from-tmpfiles.patch

    # Upstream patches
    %patch -p1 -i ${pkgfiles}/patches/upstream/systemd-261-dont-discard-x11-context.patch

    # ERROR: File fuzz-unit-file/dm-back-slash.swap does not exist.
    # mv "test/fuzz/fuzz-unit-file/dm-back\x2dslash.swap" "test/fuzz/fuzz-unit-file/dm-back-slash.swap"

    _IS_64BIT_BOOL="true"
    _IS_64BIT_FEAT="enabled"

    if [[ "${EMUL32BUILD}" ]]; then
        _IS_64BIT_BOOL="false"
        _IS_64BIT_FEAT="disabled"
    fi

    %meson_configure \
        --prefix=/usr \
        --bindir=/usr/bin \
        --sbindir=/usr/sbin \
        -Dacl=${_IS_64BIT_FEAT} \
        -Dadm-group=true \
        -Danalyze=${_IS_64BIT_BOOL} \
        -Dbacklight=${_IS_64BIT_BOOL} \
        -Dbinfmt=${_IS_64BIT_BOOL} \
        -Dblkid=${_IS_64BIT_FEAT} \
        -Dbootloader=${_IS_64BIT_FEAT} \
        -Dbpf-compiler="clang" \
        -Dbpf-framework=${_IS_64BIT_FEAT} \
        -Dbzip2=${_IS_64BIT_FEAT} \
        -Dcoredump=${_IS_64BIT_BOOL} \
        -Dcreate-log-dirs=false \
        -Ddefault-compression=zstd \
        -Ddefault-dnssec=no \
        -Ddefault-llmnr=resolve \
        -Ddefault-mdns=no \
        -Ddefault-timeout-sec=30 \
        -Ddefault-user-timeout-sec=30 \
        -Ddns-over-tls=${_IS_64BIT_BOOL} \
        -Defi=${_IS_64BIT_BOOL} \
        -Delfutils=${_IS_64BIT_FEAT} \
        -Denvironment-d=${_IS_64BIT_BOOL} \
        -Dfdisk=${_IS_64BIT_FEAT} \
        -Dfirstboot=${_IS_64BIT_BOOL} \
        -Dfuzz-tests=false \
        -Dgcrypt=${_IS_64BIT_FEAT} \
        -Dgshadow=${_IS_64BIT_BOOL} \
        -Dgnutls=${_IS_64BIT_FEAT} \
        -Dhibernate=${_IS_64BIT_BOOL} \
        -Dhomed=${_IS_64BIT_FEAT} \
        -Dhostnamed=${_IS_64BIT_BOOL} \
        -Didn=${_IS_64BIT_BOOL} \
        -Dima=${_IS_64BIT_BOOL} \
        -Dinitrd=${_IS_64BIT_BOOL} \
        -Dinstall-sysconfdir=false \
        -Dinstall-tests=false \
        -Dipe=${_IS_64BIT_BOOL} \
        -Dkernel-install=false \
        -Dkmod=${_IS_64BIT_FEAT} \
        -Dldconfig=${_IS_64BIT_BOOL} \
        -Dlibarchive=${_IS_64BIT_FEAT} \
        -Dlibcryptsetup=${_IS_64BIT_FEAT} \
        -Dlibcurl=${_IS_64BIT_FEAT} \
        -Dlibfido2=${_IS_64BIT_FEAT} \
        -Dlibidn2=${_IS_64BIT_FEAT} \
        -Dlocaled=${_IS_64BIT_BOOL} \
        -Dlogind=${_IS_64BIT_BOOL} \
        -Dmachined=${_IS_64BIT_BOOL} \
        -Dman=${_IS_64BIT_FEAT} \
        -Dmicrohttpd=${_IS_64BIT_FEAT} \
        -Dmode=release \
        -Dmountfsd=${_IS_64BIT_BOOL} \
        -Dnetworkd=${_IS_64BIT_BOOL} \
        -Dnobody-group=nobody \
        -Dnobody-user=nobody \
        -Dnsresourced=${_IS_64BIT_BOOL} \
        -Dnss-systemd=true \
        -Dntp-servers='0.solus.pool.ntp.org 1.solus.pool.ntp.org 2.solus.pool.ntp.org 3.solus.pool.ntp.org' \
        -Dok-color=highlight-blue \
        -Doomd=${_IS_64BIT_BOOL} \
        -Dopenssl=${_IS_64BIT_FEAT} \
        -Dp11kit=${_IS_64BIT_FEAT} \
        -Dpam=${_IS_64BIT_FEAT} \
        -Dpamconfdir="/usr/share/defaults/etc/pam.d" \
        -Dpamlibdir="%libdir%/security" \
        -Dpcre2=${_IS_64BIT_FEAT} \
        -Dpolkit=${_IS_64BIT_FEAT} \
        -Dportabled=${_IS_64BIT_BOOL} \
        -Dpstore=${_IS_64BIT_BOOL} \
        -Dpwquality=${_IS_64BIT_FEAT} \
        -Dqrencode=${_IS_64BIT_FEAT} \
        -Dquotacheck=${_IS_64BIT_BOOL} \
        -Drandomseed=${_IS_64BIT_BOOL} \
        -Drepart=${_IS_64BIT_FEAT} \
        -Dresolve=true \
        -Drfkill=${_IS_64BIT_BOOL} \
        -Drpmmacrosdir=no \
        -Dsbat-distro="solus" \
        -Dsbat-distro-summary="Solus Project" \
        -Dsbat-distro-pkgname="systemd" \
        -Dsbat-distro-version="$version" \
        -Dsbat-distro-url="https://getsol.us/" \
        -Dseccomp=${_IS_64BIT_FEAT} \
        -Dshellprofiledir="/usr/share/defaults/etc/profile.d" \
        -Dslow-tests=false \
        -Dsmack=${_IS_64BIT_BOOL} \
        -Dsplit-bin=true \
        -Dsshconfdir="/usr/share/defaults/ssh/ssh_config.d" \
        -Dsshdconfdir="/usr/share/defaults/ssh/sshd_config.d" \
        -Dstatus-unit-format-default=combined \
        -Dstoragetm=${_IS_64BIT_BOOL} \
        -Dsysext=${_IS_64BIT_BOOL} \
        -Dsysupdate=disabled \
        -Dsysupdated=disabled \
        -Dsysusers=${_IS_64BIT_BOOL} \
        -Dsysvinit-path="" \
        -Dtests=false \
        -Dtimedated=${_IS_64BIT_BOOL} \
        -Dtimesyncd=${_IS_64BIT_BOOL} \
        -Dtmpfiles=${_IS_64BIT_BOOL} \
        -Dtpm=${_IS_64BIT_BOOL} \
        -Dtpm2=${_IS_64BIT_FEAT} \
        -Duser-path=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin \
        -Duserdb=${_IS_64BIT_BOOL}  \
        -Dusers-gid=100 \
        -Dutmp=${_IS_64BIT_BOOL} \
        -Dvconsole=${_IS_64BIT_BOOL} \
        -Dwheel-gid=30 \
        -Dwheel-group=true \
        -Dxdg-autostart=${_IS_64BIT_BOOL} \
        -Dxkbcommon=${_IS_64BIT_FEAT} \
        -Dzlib=${_IS_64BIT_FEAT}
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Solus is responsible for its own glibc + PAM configuration, *not* systemd..
    rm -rfv ${installdir}/usr/share/factory/*

    # Only need to do the rest of the stuff on 64-bit build
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exit 0
    fi

    # Move licenses
    %install_dir ${installdir}/usr/share/licenses/${package}
    mv ${installdir}/usr/share/doc/${package}/LICENSE.* \
       ${installdir}/usr/share/doc/${package}/LICENSES \
       ${installdir}/usr/share/licenses/${package}/

    # Configs
    %install_file -t ${installdir}/usr/lib/systemd/journald.conf.d ${pkgfiles}/configs/journald/00-journald.conf
    %install_file -t ${installdir}/usr/lib/systemd/system/service.d ${pkgfiles}/configs/10-timeout-abort.conf
    %install_file -t ${installdir}/usr/lib/systemd/system.conf.d ${pkgfiles}/configs/00-timeouts.conf
    %install_file -t ${installdir}/usr/lib/systemd/user.conf.d ${pkgfiles}/configs/00-timeouts.conf
    %install_file -t ${installdir}/%libdir%/sysctl.d ${pkgfiles}/configs/10-map-count.conf

    # Default to BFQ scheduler for rotational drives, and kyber for sata/nvme SSDs
    %install_file -t ${installdir}/usr/lib/udev/rules.d ${pkgfiles}/configs/60-block-scheduler.rules

    # Coredump configuration
    %install_file ${pkgfiles}/configs/coredump/limits.conf ${installdir}/usr/share/defaults/etc/security/limits.d/20-coredump-solus.conf
    %install_file ${pkgfiles}/configs/coredump/manager.conf ${installdir}/usr/lib/systemd/system.conf.d/20-coredump-solus.conf
    %install_file ${pkgfiles}/configs/coredump/manager.conf ${installdir}/usr/lib/systemd/user.conf.d/20-coredump-solus.conf

    # OOMD configuration
    %install_file -t ${installdir}/usr/lib/systemd/oomd.conf.d ${pkgfiles}/configs/oomd/10-defaults.conf
    %install_file -t ${installdir}/usr/lib/systemd/system/-.slice.d ${pkgfiles}/configs/oomd/10-oomd-root-slice-defaults.conf
    %install_file -t ${installdir}/usr/lib/systemd/system/user@.service.d ${pkgfiles}/configs/oomd/10-oomd-user-service-defaults.conf

    # Resolved configuration
    # Temporarily disabled until we figure out how we want to handle mDNS (https://github.com/AerynOS/recipes/issues/1952)
    # %install_file -t ${installdir}/usr/lib/systemd/resolved.conf.d ${pkgfiles}/configs/resolved/00-disable-mdns.conf

    # Disable networkd in favor of NetworkManager
    %install_file -t ${installdir}/usr/lib/systemd/system-preset/ ${pkgfiles}/60-systemd.preset

    # Disable services by default, unless explicitly enabled
    %install_file -t ${installdir}/usr/lib/systemd/system-preset/ ${pkgfiles}/99-default.preset
    %install_file -t ${installdir}/usr/lib/systemd/user-preset/ ${pkgfiles}/99-default.preset

    ln -sv systemd-timesyncd.service ${installdir}/usr/lib/systemd/system/dbus-org.freedesktop.timesync1.service

    # Install compat dirs
    %install_dir ${installdir}/%libdir%/udev

    # Compat for old tools
    ln -srv ${installdir}/usr/lib/systemd/systemd-udevd ${installdir}/%libdir%/udev/udevd

    # Ensure that XDG_CONFIG_DIRS is set globally
    %install_exe -t ${installdir}/usr/lib/systemd/system-environment-generators ${pkgfiles}/configs/50-xdg-{config,data}-dirs

    # Stateless xinitrc.d path
    %install_exe -t ${installdir}/usr/share/defaults/etc/X11/xinit/xinitrc.d xorg/50-systemd-user.sh

    # Required basic support
    %install_file ${pkgfiles}/solus-base-groups.sysusers ${installdir}/usr/lib/sysusers.d/solus-base-groups.conf

    # add fixed pam config
    rm -rfv ${installdir}/usr/lib/pam.d
    %install_file ${pkgfiles}/systemd-user.pam ${installdir}/usr/share/defaults/etc/pam.d/systemd-user

    # Sign systemd-boot with our MOK key if it exists
    if [[ -e ${pkgfiles}/secureboot-keys/MOK.key ]]; then
        sbsign --key ${pkgfiles}/secureboot-keys/MOK.key \
               --cert ${pkgfiles}/secureboot-keys/MOK.crt \
               --output ${installdir}/usr/lib/systemd/boot/efi/systemd-bootx64.efi \
               ${installdir}/usr/lib/systemd/boot/efi/systemd-bootx64.efi

        %install_file ${pkgfiles}/secureboot-keys/MOK.cer ${installdir}/usr/lib/systemd/boot/solus-mok.cer
    fi

    # Make sure systemd can be found
    ln -srv ${installdir}/usr/lib/systemd/systemd ${installdir}/usr/bin/systemd
