# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : yodl
version    : 4.05.01
release    : 5
source     :
    - https://gitlab.com/fbb-git/yodl/-/archive/4.05.01/yodl-4.05.01.tar.gz : 602d1d2a9ee1917adfd408c4c81e1a11e867275d59f15da171471306ca3f9baf
homepage   : https://fbb-git.gitlab.io/yodl/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Yodl implements a pre-document language and tools to process it
description: |
    Yodl is a package that implements a pre-document language and tools to process it.  The idea of Yodl is that you write up a document in a pre-language, then use the tools (e.g. yodl2html) to convert it to some final document language. Current converters are for HTML, ms, man, LaTeX, a simple txt converter and an experimental XML converter.  Main document types are "article", "book", "letter", "manpage" and  "report". The Yodl document language is designed to be easy to use and extensible.
builddeps  :
    - icmake
build      : |
    cd yodl
    ./build programs
    ./build macros
    ./build man
install    : |
    %install_license LICENSE
    cd yodl
    ./build install programs %installroot%
    ./build install macros %installroot%
    ./build install man %installroot%
