# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : bdwgc
version    : 8.2.12
release    : 21
source     :
    - https://github.com/bdwgc/bdwgc/archive/v8.2.12.tar.gz : d09001f45dabf1c29a5df3e63020a4bab5ad4aad69137bb07100c717e2ecba0b
homepage   : https://www.hboehm.info/gc/
license    :
    - GPL-2.0-only
    - MIT
component  : programming.tools
emul32     : true
summary    : Boehm-Demers-Weiser Garbage Collector
description: |
    The Boehm-Demers-Weiser conservative garbage collector can be used as a garbage colecting replacement for C malloc or C++ new. It allows you to allocate memory basically as you normally would, without explicitly deallocating memory that is no longer useful. The collector automatically recycles memory when it determines that it can no longer be otherwise accessed.
setup      : |
    %reconfigure --disable-static --enable-cplusplus
build      : |
    %make
install    : |
    %make_install
