# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : feh
version    : 3.12.2
release    : 55
source     :
    - https://feh.finalrewind.org/feh-3.12.2.tar.bz2 : 7ce358b18a7f37bcc97a09b4efd89fdadd54cd8e7032db345f61e66dd04b1c3f
homepage   : https://feh.finalrewind.org/
license    : MIT
component  : multimedia.graphics
summary    : feh is an X11 image viewer aimed mostly at console users
description: |
    feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. It is controlled via commandline arguments and configurable key/mouse actions.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(xinerama)
    - pkgconfig(xt)
build      : |
    %make PREFIX=/usr exif=1 inotify=1
install    : |
    %make_install PREFIX=/usr
    %install_license COPYING
    install -Dm00644 ${pkgfiles}/org.finalrewind.feh.feh.metainfo.xml -t ${installdir}/usr/share/metainfo
