# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dos2unix
version    : 7.5.6
release    : 11
source     :
    - https://sourceforge.net/projects/dos2unix/files/dos2unix/7.5.6/dos2unix-7.5.6.tar.gz : 63650acbd0c7fa8623429bcbf93a888e3351a1cad0f556cf41876f5673dd7d0b
homepage   : https://waterlander.net/dos2unix/
license    : BSD-2-Clause-FreeBSD
component  : system.utils
summary    : DOS/Mac to Unix and vice versa text file format converter
description: |
    DOS/Mac to Unix and vice versa text file format converter
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING.txt
    rm ${installdir}/usr/share/doc/dos2unix-${version}/COPYING.txt
check      : |
    %make test
