# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libgsystemservice
version    : 0.3.0
release    : 1
source     :
    - http://tecnocode.co.uk/downloads/libgsystemservice/libgsystemservice-0.3.0.tar.xz : b80344beeb12e8cb763f2b6b73efeb6c4916f22ab02f7f2ef56439ac3534e494
homepage   : https://gitlab.gnome.org/pwithnall/libgsystemservice
license    : LGPL-2.1-or-later
component  : desktop.gnome
summary    : Utility library providing common components needed for building system services to be exposed on the D-Bus system bus
description: |
    libgsystemservice is a utility library providing common components needed for building system services to be exposed on the D-Bus system bus
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk-doc)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
