pref("general.smoothScroll",                true);
pref("intl.locale.matchOS",                 true);
pref("toolkit.networkmanager.disable",      false);
pref("toolkit.storage.synchronous",         0);
pref("offline.autoDetect",                  true);
pref("browser.backspace_action",            0);
pref("browser.link.open_external",          3);
pref("browser.shell.checkDefaultBrowser",   false);
pref("network.manage-offline-status",       true);
pref("extensions.shownSelectionUI",         true);
pref("startup.homepage_override_url",       "");
pref("browser.startup.homepage",            "data:text/plain,browser.startup.homepage=https://solus-project.com/blog/");
pref("browser.newtabpage.pinned",           '[{"url":"https://solus-project.com/blog/","title":"Blogs | Solus Project"}]');
pref("extensions.autoDisableScopes",        0);
pref("layers.use-image-offscreen-surfaces", false);
pref("media.mediasource.enabled",           true);
pref("media.mediasource.webm.enabled",      true);
pref("app.update.auto",                     false);
pref("app.update.enabled",                  false);
pref("app.update.autoInstallEnabled",       false);
pref("layers.acceleration.force-enabled",   false);
pref("extensions.webextensions.base-content-security-policy", "script-src 'self' https://* moz-extension: blob: filesystem: 'unsafe-eval' 'unsafe-inline'; object-src 'self' https://* moz-extension: blob: filesystem:;");
pref("browser.tabs.remote.autostart",       true);
pref("geo.wifi.uri", "https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%");
