# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : bump-my-version
version    : 1.4.0
release    : 1
source     :
    - https://github.com/callowayproject/bump-my-version/releases/download/1.4.0/bump_my_version-1.4.0.tar.gz : 3eea26b3ae6c4900ab9924ad0733365c0254db58e4bbe2d9a643752495bcfecb
homepage   : https://github.com/callowayproject/bump-my-version
license    : MIT
component  : system.utils
summary    : Version-bump your software with a single command!
description: |
    A small command line tool to simplify releasing software by updating all version strings in your source code by the correct increment and optionally commit and tag the changes.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
replaces   :
    - bumpversion
