# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-wayland-protocols
version    : 1.21.0
release    : 22
source     :
    - https://download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-1.21.0.tar.xz : 698a7b28b711270314e396e248ae86087cfeaed01372009063995be6e1dc85ba
homepage   : https://kde.org/plasma-desktop
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma Specific Protocols for Wayland
description: |
    Plasma Specific Protocols for Wayland
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
