# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-jupyter-lsp
version    : 2.3.1
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyter-lsp/jupyter_lsp-2.3.1.tar.gz : fdf8a4aa7d85813976d6e29e95e6a2c8f752701f926f2715305249a3829805a6
homepage   : https://github.com/jupyter-lsp/jupyterlab-lsp
license    : BSD-3-Clause
component  : programming.python
summary    : Multi-Language Server WebSocket proxy for Jupyter Notebook/Lab server
description: |
    Multi-Language Server WebSocket proxy for Jupyter Notebook/Lab server
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - python-jupyter-server
build      : |
    %python3_setup
install    : |
    %python3_install
