# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libpeas-2
version    : 2.2.1
release    : 13
source     :
    - https://download.gnome.org/sources/libpeas/2.2/libpeas-2.2.1.tar.xz : 589eca89b437006edf3755478df037c740a2a84cfa5d202dbad6095e828e2488
homepage   : https://gnome.pages.gitlab.gnome.org/libpeas/libpeas-2/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : libpeas provides a plugin framework for GLib applications
description: |
    libpeas is a gobject-based plugins engine, and is targetted at giving every application the chance to assume its own extensibility.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - python-setuptools
    - vala
rundeps    :
    - python-gobject
setup      : |
    %meson_configure -Dlua51=false -Dvapi=true
build      : |
    %ninja_build
install    : |
    %ninja_install
