# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : moby
version    : 29.4.2
release    : 30
source     :
    - https://github.com/moby/moby/archive/refs/tags/docker-v29.4.2.tar.gz : f2d4d892f5439ac8b3b28a2ba03d29db1a377f8dd5d057ca941cdbba92f6ed7f
homepage   : https://www.docker.com
license    : Apache-2.0
component  : virt
summary    : The open-source application container engine
description: |
    The open-source application container engine. This package contains the Docker server.
strip      : false
networking : true
builddeps  :
    - pkgconfig(libnftables)
    - pkgconfig(libsystemd)
    - git
    - go-md2man
    - golang
    - linux-headers
rundeps    :
    - containerd
    - dnsmasq
    - nftables
    - tini
environment: |
    export AUTO_GOPATH=1
    export GO111MODULE=auto

    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
    export CGO_CFLAGS="${CFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"

    export VERSION="$version"
    export PLATFORM="Docker Engine - Community"
    export DOCKER_BUILDTAGS="journald"
    export DISABLE_WARN_OUTSIDE_CONTAINER=1

    export GO_MD2MAN=/usr/bin/go-md2man
build      : |
    # Git commit corresponding to the version tag
    export GITCOMMIT="$(git ls-remote https://github.com/moby/moby.git refs/tags/docker-v$version | awk '{print $1}')"
    export DOCKER_GITCOMMIT=$GITCOMMIT

    ./hack/make.sh dynbinary

    make -C man
install    : |
    # Main docker daemon
    install -Dm00755 bundles/dynbinary-daemon/dockerd ${installdir}/usr/bin/dockerd

    # Now install docker-init
    ln -s tini-static ${installdir}/usr/bin/docker-init

    # Now install proxy service
    install -Dm00755 ${workdir}/bundles/dynbinary-daemon/docker-proxy ${installdir}/usr/bin/docker-proxy

    # Now install systemd units
    install -Dm00644 ${pkgfiles}/docker.service -t ${installdir}/%libdir%/systemd/system/
    install -Dm00644 contrib/init/systemd/docker.socket -t ${installdir}/%libdir%/systemd/system/

    install -Dm644 ${pkgfiles}/docker.preset ${installdir}/%libdir%/systemd/system-preset/20-docker.preset

    # Add the docker group
    install -Dm00644 ${pkgfiles}/docker.sysusers ${installdir}/%libdir%/sysusers.d/docker.conf

    # Install manpage
    install -Dm00644 man/man8/dockerd.8 -t ${installdir}/usr/share/man/man8/

    %install_license LICENSE
