# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mpc-qt
version    : '26.07'
release    : 15
source     :
    - https://github.com/mpc-qt/mpc-qt/archive/refs/tags/v26.07.tar.gz : 03cb0b02c67cab810147e5423c6f12c20d0b00b2bad200f38d117724e2ecf8e6
homepage   : https://mpc-qt.github.io
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : Media Player Classic Qute Theater
description: |
    Media Player Classic Qute Theater (mpc-qt) aims to reproduce most of the interface and functionality of mpc-hc while using libmpv to play video instead of DirectShow.
builddeps  :
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(mpv)
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
