# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : psycopg2
version    : 2.9.13
release    : 24
source     :
    - https://github.com/psycopg/psycopg2/archive/refs/tags/2.9.13.tar.gz : 7f5a4f8be459737148bee311f6063781d7e51363591ac877aefbc71004506741
homepage   : https://www.psycopg.org/
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Psycopg is the most popular PostgreSQL adapter for the Python programming language
description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming language. At its core it fully implements the Python DB API 2.0 specifications. Several extensions allow access to many of the features offered by PostgreSQL.
builddeps  :
    - pkgconfig(libpq)
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
build      : |
    %pyproject_build
install    : |
    %pyproject_install
    %install_license LICENSE
