# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dtc
version    : 1.8.1
release    : 2
source     :
    - https://mirrors.edge.kernel.org/pub/software/utils/dtc/dtc-1.8.1.tar.gz : 454e5cce748ce957c91e7f45e66da2cff5100ddb52155d7a909c43cbeaf1bcb0
license    : GPL-2.0-or-later
component  : system.utils
homepage   : https://www.devicetree.org/
summary    : Device Tree Compiler
description: |
    Device Tree Compiler
builddeps  :
    - pkgconfig(yaml-0.1)
checkdeps  :
    - pkgconfig(python3)
    - swig
    - valgrind
clang      : true
setup      : |
    %meson_configure -Ddefault_library=shared
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license GPL
check      : |
    unset LD_PRELOAD
    %ninja_check
patterns   :
    - ^libfdt :
        - /usr/lib64/libfdt.so.1*
