# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : weechat
version    : 4.9.0
release    : 103
source     :
    - https://github.com/weechat/weechat/archive/refs/tags/v4.9.0.tar.gz : 337fc24c0a4c00aa2c47262f123014b23d55c5cf02785ecfdf204f96ccef5c65
homepage   : https://weechat.org
license    : GPL-3.0-or-later
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(enchant-2)
    - pkgconfig(gnutls)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcjson)
    - pkgconfig(libcurl)
    - pkgconfig(libgcrypt)
    - pkgconfig(libzstd)
    - pkgconfig(lua-5.4)
    - pkgconfig(python3)
    - pkgconfig(ruby-4.0)
    - pkgconfig(tcl)
    - asciidoctor
    - perl
rundeps    :
    - perl
setup      : |
    %cmake_ninja \
        -DENABLE_ENCHANT=ON \
        -DENABLE_JAVASCRIPT=OFF \
        -DENABLE_PHP=OFF \
        -DENABLE_MAN=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING LICENSES/*
