# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : weechat
version    : 4.10.1
release    : 112
source     :
    - https://github.com/weechat/weechat/archive/refs/tags/v4.10.1.tar.gz : 84207fc87f19274e2d9efb3f229b3594af6ca5d54e2ee25b10f07015e681b8d1
homepage   : https://weechat.org
license    : GPL-3.0-or-later
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(enchant-2)
    - pkgconfig(gnutls)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcjson)
    - pkgconfig(libcurl)
    - pkgconfig(libgcrypt)
    - pkgconfig(libzstd)
    - pkgconfig(lua-5.4)
    - pkgconfig(python3)
    - pkgconfig(ruby-4.0)
    - pkgconfig(tcl)
    - asciidoctor
    - perl
rundeps    :
    - perl
setup      : |
    %cmake_ninja \
        -DENABLE_ENCHANT=ON \
        -DENABLE_JAVASCRIPT=OFF \
        -DENABLE_PHP=OFF \
        -DENABLE_MAN=ON
build      : |
    %cmake_build
install    : |
    %cmake_install
    %install_license COPYING LICENSES/*
