# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : supercollider
version    : 3.14.1
release    : 20
source     :
    - https://github.com/supercollider/supercollider/releases/download/Version-3.14.1/SuperCollider-3.14.1-Source.tar.bz2 : ee640c68777ae697682066ce5c4a8b7e56c5b223e76c79c13b5be5387ee55bb2
homepage   : https://supercollider.github.io/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : An audio server, programming language, and IDE for sound synthesis and algorithmic composition
description: |
    An audio server, programming language, and IDE for sound synthesis and algorithmic composition
builddeps  :
    - pkgconfig(Qt6DBus)
    - pkgconfig(Qt6Linguist)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WebChannel)
    - pkgconfig(Qt6WebEngineWidgets)
    - pkgconfig(Qt6WebSockets)
    - pkgconfig(alsa)
    - pkgconfig(avahi-core)
    - pkgconfig(fftw3)
    - pkgconfig(jack)
    - pkgconfig(sndfile)
    - pkgconfig(xt)
    - pkgconfig(yaml-cpp)
    - libboost-devel
environment: |
    export CXXFLAGS="${CXXFLAGS} -Wno-template-body"
setup      : |
    %patch -p1 -i ${pkgfiles}/0001-SuperColliderIDE.desktop-Force-to-run-in-xcb-mode-X.patch
    %patch -p1 -i ${pkgfiles}/0002-Fix-compilation-with-Qt6.patch
    %cmake -B build \
          -DLIB_SUFFIX=64 \
          -DSC_EL=no \
          -DSYSTEM_BOOST=1 \
          -DSYSTEM_YAMLCPP=1
build      : |
    %make -C build
install    : |
    %make_install -C build
    %install_license COPYING
