# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : teamspeak
version    : 6.0.0
release    : 1
source     :
    - https://files.teamspeak-services.com/pre_releases/client/6.0.0-beta4/teamspeak-client.tar.gz : b433040815a6878409cf255dbe59105bb32abbc327e898c5897309252e3911f8
homepage   : https://teamspeak.com/en/
license    : Distributable # See files/Redistribution.eml
component  : network.im
summary    : Crystal Clear Cross-Platform Voice Communication
description: |
    VoIP software designed with security in mind, featuring crystal clear voice quality, endless customization options, and scalabilty up to thousands of simultaneous users.
strip      : false
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atspi-2)
    - pkgconfig(libnotify)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
install    : |
    install -dm00755 $installdir/usr/share/teamspeak
    find "$workdir" \
        -mindepth 1 \
        -maxdepth 1 \
        -type d,f \
        ! -name teamspeak-client.desktop \
        -exec cp -r {} "$installdir/usr/share/teamspeak" \;

    # Make sysmlink to binary
    install -dm0755 $installdir/usr/bin
    ln -s /usr/share/teamspeak/TeamSpeak $installdir/usr/bin/teamspeak
    # Install Desktop file, icon, and appstream metainfo
    install -Dm00644 $pkgfiles/teamspeak.desktop -t $installdir/usr/share/applications/
    install -Dm00644 $pkgfiles/com.teamspeak.TeamSpeak.png -t $installdir/usr/share/icons/hicolor/256x256/apps/
    install -Dm00644 $pkgfiles/com.teamspeak.TeamSpeak.metainfo.xml -t $installdir/usr/share/metainfo/
replaces   :
    - teamspeak3
