# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gcompris
version    : '26.1'
release    : 16
source     :
    - https://gcompris.net/download/qt/src/gcompris-qt-26.1.tar.xz : c389b863b29f012ccc1b3eef740982ff6c7654c13a2e343397ee466124f31339
license    : GPL-3.0-or-later
component  : games
homepage   : https://gcompris.net/
summary    : Educational software suite comprising of numerous activities for children aged 2 to 10
description: |
    GCompris is a high quality educational software suite, including a large number of activities for children aged 2 to 10.
    Some of the activities are game orientated, but nonetheless still educational.
builddeps  :
    - pkgconfig(Qt6Charts)
    - pkgconfig(Qt6Graphs)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6QuickWidgets)
    - pkgconfig(Qt6Sensors)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(Qt6WaylandClient)
    - extra-cmake-modules
    - kf6-kdoctools-devel
    - qml-box2d
rundeps    :
    - qml-box2d
    - qt6-svg
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_ninja -DQML_BOX2D_LIBRARY=/usr/lib64/qt6/qml/Box2D
build      : |
    %ninja_build
install    : |
    %ninja_install
