# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : marp-cli
version    : 4.4.0
release    : 20
homepage   : https://marp.app/
source     :
    - https://github.com/marp-team/marp-cli/archive/refs/tags/v4.4.0.tar.gz : ae85fa2a244aa6aa90feb14317a05fa7545833fc6fe0e2bc3a7a5ed49b7fdd2e
license    : MIT
component  : office
summary    : A CLI interface for Marp and Marpit based converters
description: |
    A CLI interface for Marp and any slide deck converter based on Marpit framework. It can convert Marp / Marpit Markdown files into static HTML / CSS, PDF, PowerPoint document, and image(s) easily.
networking : true
strip      : false
debug      : false
builddeps  :
    - git
    - nodejs
    - yarn
setup      : |
    yarn install
build      : |
    yarn build
    yarn run pkg . \
        --out-path ./bin \
        --targets host \
        --compress Brotli
install    : |
    install -Dm0755 bin/marp-cli $installdir/usr/bin/marp
    %install_license LICENSE
