# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ksystemlog
version    : 26.04.2
release    : 68
source     :
    - https://download.kde.org/stable/release-service/26.04.2/src/ksystemlog-26.04.2.tar.xz : 00815b5318b916ba733d6e8305b6618bfe4c9fb3736140df8ee024dac485009f
homepage   : https://kde.org/applications/system/ksystemlog/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-or-later
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - pkgconfig(audit)
    - kf6-karchive-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-ktextwidgets-devel
    - kf6-kxmlgui-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*

    # remove docs
    rm -rfv $installdir/usr/share/doc

    # Fix appstream processing
    install -Dm00644 $workdir/logo.png $installdir/usr/share/pixmaps/utilities-log-viewer.png
