# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ksystemlog
version    : 26.04.3
release    : 69
source     :
    - https://download.kde.org/stable/release-service/26.04.3/src/ksystemlog-26.04.3.tar.xz : a93b84c398be0f85ee5b4d54214f306f86f21c168f93791c7a809f6108d28c82
homepage   : https://kde.org/applications/system/ksystemlog/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-or-later
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - pkgconfig(audit)
    - kf6-karchive-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-ktextwidgets-devel
    - kf6-kxmlgui-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*

    # remove docs
    rm -rfv $installdir/usr/share/doc

    # Fix appstream processing
    install -Dm00644 $workdir/logo.png $installdir/usr/share/pixmaps/utilities-log-viewer.png
