# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dustrac
version    : 2.2.0
release    : 15
source     :
    - https://github.com/juzzlin/DustRacing2D/archive/2.2.0.tar.gz : 9a393675106d90b7c4fcf8e3280a1b80c0c35e90f03ce75742276b40d5495182
homepage   : https://juzzlin.github.io/DustRacing2D
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  : games.arcade
summary    : Dust Racing (Dustrac) is a tile-based, cross-platform 2D racing game
description: |
    Dust Racing 2D (Dustrac) is a tile-based, cross-platform 2D racing game written in Qt (C++) and OpenGL. Dust Racing 2D comes with a Qt-based level editor for easy level creation. A separate engine, MiniCore, is used for physics modeling.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6Linguist)
    - pkgconfig(Qt6Sql)
    - pkgconfig(Qt6Widgets)
    - pkgconfig(Qt6Xml)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
setup      : |
    sed -i "s|share/games/DustRacing2D|share/dustrac|" InstallLinux.cmake

    %cmake_ninja \
        -DReleaseBuild=1 \
        -DDEFAULT_DATA_PATH_BASE=share/dustrac
build      : |
    %cmake_build
install    : |
    %cmake_install
    %install_license COPYING
