# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : font-iosevka-ttf
version    : 34.5.0
release    : 91
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v34.5.0/PkgTTF-Iosevka-34.5.0.zip : bbc253ac3c00d2e4e0715677a739a0529064a2decc6f85c6739446c998cf1500
homepage   : https://typeof.net/Iosevka
license    : OFL-1.1
component  : desktop.font
summary    : Versatile typeface for code, from code.
description: |
    Iosevka is an open-source, sans-serif + slab-serif, monospace + quasi-proportional typeface family, designed for writing code, using in terminals, and preparing technical documents.
install    : |
    install -Dm00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
    install -Dm00644 $pkgfiles/iosevka.metainfo.xml $installdir/usr/share/metainfo/iosevka.metainfo.xml
