# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kbackup
version    : 26.04.1
release    : 51
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/kbackup-26.04.1.tar.xz : 584d4f80ced90697799bec8ddcf3cfb1cc225e8ec6576ce23978844d0acb3219
homepage   : https://apps.kde.org/en/kbackup
license    : GPL-2.0-or-later
component  : network.util
summary    : KBackup is an application which lets you back up your data in a simple, user friendly way
description: |
    KBackup is an application which lets you back up your data in a simple, user friendly way
builddeps  :
    - pkgconfig(KF6GuiAddons)
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(libarchive)
    - kf6-karchive-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-kxmlgui-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rfv $installdir/usr/share/doc
