# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : docker-compose
version    : 5.3.0
release    : 64
source     :
    - https://github.com/docker/compose/archive/refs/tags/v5.3.0.tar.gz : 496ee43bc6ecee6fbac28e93f6e784a7b0207baec7ae2b0ffb57cfd83bc92874
homepage   : https://docs.docker.com/compose/
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
networking : true
builddeps  :
    - git
    - golang
rundeps    :
    - docker
environment: |
    export _compose_r=github.com/docker/compose
    export GO111MODULE=auto

    export CGO_CFLAGS="${CFLAGS}"
    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_CXXFLAGS="${CXXFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
setup      : |
    go mod vendor
build      : |
    export GOFLAGS+=" -ldflags=-X=${_compose_r}/v2/internal.Version=v$version"

    # Git commit corresponding to the version tag
    export GITCOMMIT="$(git ls-remote https://github.com/docker/compose.git refs/tags/v$version | awk '{print $1}')"

    go build -tags "e2e,kube" -o docker-compose ./cmd
install    : |
    install -Ddm00755 ${installdir}/%libdir%/docker/cli-plugins
    install -m00755 ${workdir}/docker-compose ${installdir}/%libdir%/docker/cli-plugins/docker-compose

    install -dm00755 ${installdir}/usr/bin
    ln -srv ${installdir}/%libdir%/docker/cli-plugins/docker-compose ${installdir}/usr/bin/docker-compose

    %install_license LICENSE
