# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-setuptools-scm
version    : 10.2.1
release    : 27
source     :
    - https://files.pythonhosted.org/packages/source/s/setuptools-scm/setuptools_scm-10.2.1.tar.gz : 4fa7dd82cf8c800df59c9a288c90299b1657ff1ecfc3f5cc00287c5dbf5e27a9
homepage   : https://github.com/pypa/setuptools_scm/
license    : MIT
component  : programming.python
summary    : Manage your Python package versions using scm metadata
description: |
    setuptools_scm handles managing your Python package versions in scm metadata instead of declaring them as the version argument or in a scm managed file. It also handles file finders for the supported scm.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-typing-extensions
    - python-wheel
checkdeps  :
    - git
    - gnupg
    - mercurial
    - python-pytest
    - python-pytest-timeout
    - python-rich
    - python-vcs-versioning
rundeps    :
    - python-packaging
    - python-setuptools
    - python-typing-extensions
    - python-vcs-versioning
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
   %pytest -v -k 'not (test_pip_download or test_integration)'
