# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libgtkmm-3
version    : 3.24.11
release    : 24
source     :
    - https://download.gnome.org/sources/gtkmm/3.24/gtkmm-3.24.11.tar.xz : 19e383c82d5dd89db275e00b82864e90414d4c3fb3d100b2f996bcc2338a4cc7
homepage   : https://gtkmm.org
license    : GPL-2.0-only
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangomm-1.4)
patterns   :
    - devel : [/usr/lib64/g*]
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
