# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : croc
version    : 11.1.0
release    : 13
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v11.1.0.tar.gz : ae71b65f54c48fd2f4d60bb0209a0a18584bb0c744967675b0a0d4f2ffb22e8f
homepage   : https://github.com/schollz/croc
license    : MIT
component  : network.clients
summary    : Easily and securely send things from one computer to another
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders.
    It provides end-to-end encryption and enables easy cross-platform transfers.
builddeps  :
    - golang
networking : true
clang      : true
environment: |
    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"
    export GO111MODULE=auto
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
build      : |
    go build -v -o croc
install    : |
    %install_license LICENSE
    %install_bin croc
    %install_file croc.service ${installdir}/%libdir%/systemd/system/croc.service
