# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : croc
version    : 11.4.0
release    : 16
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v11.4.0.tar.gz : a5f06d9364e8ea41e60ba1ca7251f33f930fc91b3e4fdd510f8d6e99b463283e
homepage   : https://github.com/schollz/croc
license    : MIT
component  : network.clients
summary    : Easily and securely send things from one computer to another
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders.
    It provides end-to-end encryption and enables easy cross-platform transfers.
builddeps  :
    - golang
networking : true
clang      : true
environment: |
    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"
    export GO111MODULE=auto
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
build      : |
    go build -v -o croc
install    : |
    %install_license LICENSE
    %install_bin croc
    %install_file croc.service ${installdir}/%libdir%/systemd/system/croc.service
