# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : croc
version    : 10.4.1
release    : 2
source     :
    - https://github.com/schollz/croc/archive/refs/tags/v10.4.1.tar.gz : e544ff0c07166cab4e070d2a5af5105544d797a059879738075779775a19263d
homepage   : https://github.com/schollz/croc
license    : MIT
component  : network.clients
summary    : Easily and securely send things from one computer to another
description: |
    croc is a tool that allows any two computers to simply and securely transfer files and folders.
    It provides end-to-end encryption and enables easy cross-platform transfers.
builddeps  :
    - golang
networking : true
clang      : true
environment: |
    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"
    export GO111MODULE=auto
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
build      : |
    go build -v -o croc
install    : |
    %install_license LICENSE
    install -Dm00755 croc $installdir/usr/bin/croc
    install -Dm00644 croc.service $installdir/%libdir%/systemd/system/croc.service
