# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mkvtoolnix
version    : '98.0'
release    : 112
source     :
    - https://codeberg.org/mbunkus/mkvtoolnix/archive/release-98.0.tar.gz : 39d6b7a414336b1be374a723c3ccb50b66fa4b86b816b8635fc44781d34e49f4
homepage   : https://codeberg.org/mbunkus/mkvtoolnix
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : MKV Toolkit for Linux
clang      : true
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(dvdread)
    - pkgconfig(flac)
    - pkgconfig(fmt)
    - pkgconfig(gtest)
    - pkgconfig(libcmark)
    - pkgconfig(libcurl)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(ruby-4.0)
    - pkgconfig(vorbis)
    - docbook-xml
    - libboost-devel
setup      : |
    %autogen --disable-static --disable-update-check
build      : |
    rake %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
    %install_license COPYING
check      : |
    rake tests:run_unit
