# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dnspython
version    : 2.8.0
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/d/dnspython/dnspython-2.8.0.tar.gz : 181d3c6996452cb1189c4046c61599b84a5a86e099562ffde77d26984ff26d0f
homepage   : https://www.dnspython.org/
license    : ISC
component  : programming.python
summary    : DNS toolkit for Python
description: |
    DNS toolkit for Python supporting almost all record types. It can be used for queries, zone transfers, and dynamic updates.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
    - python-wheel
checkdeps  :
    - python-pytest
    - python-trio
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
