# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tokodon
version    : 26.04.2
release    : 36
source     :
    - https://download.kde.org/stable/release-service/26.04.2/src/tokodon-26.04.2.tar.xz : 7ec4a2bf6e4825e814bd3230fae620852ce81d163704dcbde2bf3d1979993d0b
homepage   : https://apps.kde.org/tokodon
license    :
    - AGPL-3.0-or-later
    - BSD-2-Clause
    - BSD-3-Clause
    - CC-BY-SA-4.0
    - CC0-1.0
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - GPL-3.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - LGPL-3.0-only
    - MIT
component  : desktop.kde
summary    : A Mastodon client for Plasma
description: |
    A modern client for Mastodon and other decentralized servers that implement its API (such as Pixelfed).
builddeps  :
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WebSockets)
    - pkgconfig(Qt6WebView)
    - kf6-kconfig-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-knotifications-devel
    - kf6-purpose-devel
    - kf6-qqc2-desktop-style-devel
    - kirigami-addons-devel
    - kunifiedpush-devel
    - mpvqt-devel
    - qcoro-qt6-devel
    - qt6-base-private-devel
    - qtkeychain-qt6-devel
rundeps    :
    - kf6-kirigami
    - kf6-kitemmodels
    - kf6-qqc2-desktop-style
    - kf6-sonnet
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
