# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-requests-ratelimiter
version    : 0.10.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/r/requests-ratelimiter/requests_ratelimiter-0.10.0.tar.gz : 9c1a78d7646caa5ccf211a6c341abd16d329be2c8c35044a418aa9da7c0e7a33
homepage   : https://github.com/JWCook/requests-ratelimiter
license    : MIT
component  : programming.python
summary    : Rate-limiting for the requests library
description: |
    Rate-limiting for the requests library using pyrate-limiter.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-pyrate-limiter
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
