# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-lwp-protocol-https
version    : '6.17'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/LWP-Protocol-https-6.17.tar.gz : 361c7c1eee8cf66812958f975f26ef2e2272a0c6221d2043477cb9c22b8d1c23
homepage   : https://metacpan.org/pod/LWP::Protocol::https
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : LWP::Protocol::https - Provide https support for LWP::UserAgent
description: |
    The LWP::Protocol::https module provides support for using https schemed URLs with LWP. This module is a plug-in to the LWP protocol handling, so you don't use it directly. Once the module is installed LWP is able to access sites using HTTP over SSL/TLS.
rundeps    :
    - perl-io-socket-ssl
    - perl-net-http
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
patterns   : /*
