# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : eventviews
version    : 25.12.3
release    : 100
source     :
    - https://download.kde.org/stable/release-service/25.12.3/src/eventviews-25.12.3.tar.xz : c2e776f55e485b346d256a9f21fd244af2b75e18c489ec811e334050cccbca6a
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library for creating events
description: |
    Library for creating events.
builddeps  :
    - pkgconfig(KF6CalendarCore)
    - pkgconfig(KF6GuiAddons)
    - akonadi-calendar-devel
    - calendarsupport-devel
    - kcalutils-devel
    - kdiagram-devel
    - kf6-kcompletion-devel
    - kf6-kcontacts-devel
    - kf6-kholidays-devel
    - kf6-kiconthemes-devel
    - kf6-kservice-devel
    - kmime-devel
    - libkdepim-devel
rundeps    :
    - devel :
        - akonadi-calendar-devel
        - akonadi-devel
        - calendarsupport-devel
        - kcalutils-devel
        - kf6-kcalendarcore-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
