# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-clocks
version    : '51.0'
release    : 26
source     :
    - https://download.gnome.org/sources/gnome-clocks/51/gnome-clocks-51.0.tar.xz : 4bdf9c0481a83037da1d0fa26d2c2c6a80cb736458fd18fde14acaf7924874c6
homepage   : https://apps.gnome.org/Clocks/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Keep track of time
description: |
    A simple and elegant clock application. It includes world clocks, alarms, a stopwatch, and timers.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gnome-desktop-4)
    - pkgconfig(gweather4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgeoclue-2.0)
    - desktop-file-utils
    - itstool
    - vala
    - vorbis-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
