# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-solid
version    : 6.28.0
release    : 38
source     :
    - https://download.kde.org/stable/frameworks/6.28/solid-6.28.0.tar.xz : 47fa84db565372584c6ecb03f71a6085f706a1c031ea4f2ffc35808f09a19b3d
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - LGPL-3.0-only
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libplist-2.0)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-tools-devel
    - media-player-info
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
