# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : girara
version    : 2026.07.18
release    : 18
source     :
    - https://pwmt.org/projects/girara/download/girara-2026.07.18.tar.xz : d7255635776a45d42d1e555aa425ab96caf23755442474cf240cbac966d8502f
homepage   : https://pwmt.org/projects/girara/
license    : Zlib
component  : programming.library
summary    : A user interface library that focuses on simplicity and minimalism
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gobject-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
