# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-soupsieve
version    : 2.9.1
release    : 21
source     :
    - https://github.com/facelessuser/soupsieve/archive/refs/tags/2.9.1.tar.gz : 0ffe1a8a48cfa18860172bdd0fdad87ba85df9c3b0bdb88759f07fd34c3b39f5
homepage   : https://facelessuser.github.io/soupsieve/
license    : MIT
component  : programming.python
summary    : A modern CSS selector implementation for BeautifulSoup
description: |
    Soup Sieve is a CSS selector library designed to be used with Beautiful Soup 4. It aims to provide selecting, matching, and filtering using modern CSS selectors. Soup Sieve currently provides selectors from the CSS level 1 specifications up through the latest CSS level 4 drafts and beyond (though some are not yet implemented).
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
checkdeps  :
    - python-beautifulsoup4 #(warning; circular)
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
