# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lact
version    : 0.9.1
release    : 17
source     :
    - git|https://github.com/ilya-zlobintsev/LACT.git : v0.9.1
homepage   : https://github.com/ilya-zlobintsev/LACT
license    : MIT
component  : system.utils
summary    : Linux GPU Configuration Tool
networking : true
clang      : true
description: |
    This application allows you to control your GPU on a Linux system.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libdisplay-info) 
    - pkgconfig(libdrm)
    - pkgconfig(ocl-icd)
    - git
    - rust
    - vulkan-tools
rundeps    :
    - ocl-icd
    - vulkan-tools
setup      : |
    %patch -p1 -i $pkgfiles/0001-Solus-Start-after-systemd-udev.patch
    %patch -p1 -i $pkgfiles/0001-Solus-Adapt-to-our-amdgpu-kernel-argument.patch
build      : |
    %make
install    : |
    %make_install PREFIX=/usr

    install -Dm00644 ${pkgfiles}/${package}.preset ${installdir}/%libdir%/systemd/system-preset/60-${package}.preset

    # Allow amdgpu users to overclock their GPUs by default
    install -Dm00644 $pkgfiles/kernel-lact.cmdline $installdir/usr/lib64/kernel/cmdline.d/50_lact.conf

    %install_license LICENSE
