# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : zanshin
version    : 26.08.1
release    : 60
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/zanshin-26.08.1.tar.xz : ebd4d528eb266d3c7fec278134be784c785cb1ce51f1fdaf43bdbbc20e53c623
homepage   : https://zanshin.kde.org/
license    :
    - CC0-1.0
    - GPL-2.0-only
    - GPL-3.0-only
    - LGPL-2.0-or-later
    - MIT
component  : office.notes
summary    : To-do management application for KDE.
description: |
    A powerful yet simple application to manage your day to day actions.
builddeps  :
    - pkgconfig(KF6CalendarCore)
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(Qt6Qml)
    - akonadi-calendar-devel
    - kf6-kparts-devel
    - kf6-krunner-devel
    - kontactinterface-devel
    - libboost-devel
rundeps    :
    - kdepim-runtime
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
