# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libktorrent
version    : 26.08.1
release    : 72
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/libktorrent-26.08.1.tar.xz : 0a55d129024f39b474ceb108bfa536caca15fea6cb0fb3aa7bb0b87acc476845
homepage   : https://invent.kde.org/network/libktorrent
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-or-later
    - MIT
component  : programming.library
summary    : BitTorrent protocol implementation
description: |
    libkTorrent is a BitTorrent protocol implementation for KDE.
builddeps  :
    - pkgconfig(libgcrypt)
    - kf6-karchive-devel
    - kf6-kcrash-devel
    - kf6-kio-devel
    - libboost-devel
    - qt6-base-private-devel
    - xfsprogs-devel
rundeps    :
    - devel :
        - kf6-karchive-devel
        - kf6-kconfig-devel
        - kf6-kio-devel
        - libboost-devel
        - libgcrypt-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
