# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-nbxmpp
version    : 7.3.0
release    : 34
source     :
    - https://files.pythonhosted.org/packages/source/n/nbxmpp/nbxmpp-7.3.0.tar.gz : 5b0f231abb438321da8a4beaae3b876b973efb1a78e39f859c84ef736b253e05
homepage   : https://python-nbxmpp.gajim.org
license    : GPL-3.0-or-later
component  : programming.python
summary    : Library to connect to Jabber/XMPP networks in a non-blocking way
description: |
    python-nbxmpp is a Python library that provides a way for Python applications to use Jabber/XMPP networks in a non-blocking way.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-setuptools
    - python-wheel
rundeps    :
    - libsoup
    - python-gobject
    - python-idna
    - python-packaging
    - python-precis_i18n
build      : |
    %python3_setup
install    : |
    %python3_install
