# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : korganizer
version    : 26.04.3
release    : 102
source     :
    - https://download.kde.org/stable/release-service/26.04.3/src/korganizer-26.04.3.tar.xz : 89a11d44aa4c46fe3e3ca64f2b38fd806cfcdb23262c63cc764c5e6ab9e04d48
homepage   : https://kde.org/applications/office/org.kde.korganizer
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-only
    - MIT
component  : office
summary    : KDE calendar and scheduling program
description: |
    KOrganizer provides management of events and tasks, alarm notification, web export, network transparent handling of data, group scheduling, import and export of calendar files and more. It is able to work together with a wide variety of groupware servers, for example Kolab, Open-Xchange, Citadel or OpenGroupware.org.
builddeps  :
    - pkgconfig(x11)
    - akonadi-calendar-devel
    - calendarsupport-devel
    - eventviews-devel
    - incidenceeditor-devel
    - kf6-kcmutils-devel
    - kf6-kcontacts-devel
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kholidays-devel
    - kf6-kiconthemes-devel
    - kf6-knewstuff-devel
    - kf6-kparts-devel
    - kf6-kuserfeedback-devel
    - kidentitymanagement-devel
    - kldap-devel
    - kmailtransport-devel
    - kontactinterface-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*

    # remove doc
    rm -rfv $installdir/usr/share/doc
