# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xdg-desktop-portal-gnome
version    : '51.0'
release    : 17
source     :
    - https://download.gnome.org/sources/xdg-desktop-portal-gnome/51/xdg-desktop-portal-gnome-51.0.tar.xz : ec228b305091b649c16c690e102aa1d66fc10e9834888d51e411913c82c1430d
homepage   : https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
description: |
    A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
builddeps  :
    - pkgconfig(gnome-desktop-4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(xdg-desktop-portal)
    - gnome-keyring
rundeps    :
    - nautilus
    - xdg-desktop-portal-gtk
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
