# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-icecream
version    : 2.2.0
release    : 7
source     :
    - https://github.com/gruns/icecream/archive/refs/tags/v2.2.0.tar.gz : 83b7921b16f0bdad9443ecb853d2acad20c206c698051fd2a667aee924a6802a
homepage   : https://github.com/gruns/icecream
license    : MIT
component  : programming.python
summary    : Never use print() to debug again
description: |
    Do you ever use print() or log() to debug your code? Of course you do. IceCream, or ic for short, makes print debugging a little sweeter.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - pygments
    - python-asttokens
    - python-colorama
    - python-executing
    - python-pytest
rundeps    :
    - pygments
    - python-asttokens
    - python-colorama
    - python-executing
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
