# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-zope.deferredimport
version    : 6.1.1
release    : 13
source     :
    - https://github.com/zopefoundation/zope.deferredimport/archive/refs/tags/6.1.1.tar.gz : 66402cb2eb250c31e0ca44d06a1cc4d77b8e4c721f39a599045ac9d7db8f71e3
homepage   : https://github.com/zopefoundation/zope.deferredimport
license    : ZPL-2.1
component  : programming.python
summary    : Defer imports until used by code
description: |
    Often, especially for package modules, you want to import names for convenience, but not actually perform the imports until necessary. The zope.deferredimport package provided facilities for defining names in modules that will be imported from somewhere else when used. You can also cause deprecation warnings to be issued when a variable is used.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
rundeps    :
    - python-zope.proxy
build      : |
    # skip dep check for setuptools 82.0, remove on update
    %python3_setup --skip-dependency-check
install    : |
    %python3_install
