# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : abiword
version    : 3.0.8
release    : 39
source     :
    - https://gitlab.gnome.org/World/AbiWord/-/archive/release-3.0.8/AbiWord-release-3.0.8.tar.gz : 7c490e46f0a6143f84d5c7e3fed246f34486ad70cd55f162c792827607cd7e9a
homepage   : https://gitlab.gnome.org/World/AbiWord
license    : GPL-2.0-or-later
component  : office
summary    : Free lightweight word processor similar to Microsoft Word
description: |
    Abiword is a free and lightweight word processor similar to Microsoft Word, allowing many of the same functions while being better on resources.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(fribidi)
    - pkgconfig(gspell-1)
    - pkgconfig(libgcrypt)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libturbojpeg)
    - pkgconfig(wv-1.0)
    - autoconf-archive
    - intltool
    - libboost-devel
    - libtool-devel
clang      : false
libsplit   : false
setup      : |
    %autogen \
        --enable-clipart \
        --enable-emacs-keybinding \
        --enable-templates \
        --enable-vi-keybinding \
        --without-evolution-data-server \
        --with-goffice
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
    mv $installdir/usr/share/applications/{abiword.desktop,com.abisource.AbiWord.desktop}

    # Don't install metainfo to obsolete path
    %install_file $installdir/usr/share/appdata/abiword.appdata.xml \
    $installdir/usr/share/metainfo/abiword.metainfo.xml
    rm -rv $installdir/usr/share/appdata
