# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : delta
version    : 0.20.1
release    : 5
source     :
    - https://github.com/dandavison/delta/archive/refs/tags/0.20.1.tar.gz : d9d502396e3595ee8fd926f1ed2e54ac9935baabd3569a3753efab36304f90fa
homepage   : https://dandavison.github.io/delta/
license    : MIT
component  : programming.tools
summary    : A syntax-highlighting pager for git, diff, and grep output
description: |
    A syntax-highlighting pager for git, diff, and grep output
networking : true
builddeps  :
    - pkgconfig(oniguruma)
    - rust
checkdeps  :
    - git
setup      : |
    %cargo_fetch
build      : |
    export RUSTONIG_DYNAMIC_LIBONIG=1
    %cargo_build --all-features

    for shell in bash fish zsh; do
        target/release/delta --generate-completion="${shell}" > "${shell}-completion"
    done
install    : |
    %cargo_install
    %install_license LICENSE

    # Completions
    %install_file bash-completion ${installdir}/usr/share/bash-completion/completions/delta
    %install_file fish-completion ${installdir}/usr/share/fish/vendor_completions.d/delta.fish
    %install_file zsh-completion ${installdir}/usr/share/zsh/site-functions/_delta
check      : |
    %cargo_test
