# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : vifm
version    : 0.14.4
release    : 13
source     :
    - https://github.com/vifm/vifm/archive/refs/tags/v0.14.4.tar.gz : eaabff68da048620e30b3131c8fbb0cdd60177591409acd28a7ad5339c166e80
homepage   : https://vifm.info/
license    : GPL-2.0-or-later
component  : system.utils
summary    : ncurses file manager with vi keybindings
description: |
    Vifm is a file manager with curses interface, which provides Vi[m]-like environment for managing objects within file systems, extended with some useful ideas from mutt. If you use vi, Vifm gives you complete keyboard control over your files without having to learn a new set of commands.
builddeps  :
    - man-db
setup      : |
    %configure \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING*
