# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : sirikali
version    : 1.8.6
release    : 6
homepage   : https://mhogomchungu.github.io/sirikali/
source     :
    - https://github.com/mhogomchungu/sirikali/archive/refs/tags/1.8.6.tar.gz : 84eb3c9df08e6b7ce4b7f1a3a4267d42e3a3be7104e595154860b8e83c0eceae
license    : GPL-2.0-or-later
component  : security.crypto
summary    : SiriKali is a frontend application for managing encrypted volumes
description: |
    SiriKali is a Qt/C++ GUI application that manages ecryptfs, cryfs, encfs, gocryptfs and securefs based encrypted folders. SiriKali can also connect to ssh servers using sshfs.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
rundeps    :
    - cracklib
    - libpwquality
setup      : |
    %cmake_ninja -DBUILD_WITH_QT6=true
build      : |
    %cmake_build
install    : |
    %cmake_install
    %install_license LICENSE
