# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-asn1
version    : 0.6.4
release    : 16
source     :
    - https://github.com/pyasn1/pyasn1/archive/refs/tags/v0.6.4.tar.gz : 8eba5d49bbdedfe58c2adcd9eed32658bd1a58e6418581a32c7f4d16eb49c70f
homepage   : https://github.com/pyasn1/pyasn1
license    : BSD-2-Clause
component  : programming.python
summary    : Generic ASN.1 library for Python
description: |
    This is a free and open source implementation of ASN.1 types and codecs as a Python package. It has been first written to support particular protocol (SNMP) but then generalized to be suitable for a wide range of protocols based on ASN.1 specification.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest
