# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : neovim
version    : 0.12.5
release    : 63
source     :
    - https://github.com/neovim/neovim/archive/refs/tags/v0.12.5.tar.gz : a810c95332317bd0017e1ca07e376a8472c79075cbed00fa3737d190a8a0a45a
homepage   : https://neovim.io
license    : Apache-2.0
component  : editor
summary    : Fork of Vim aiming to improve user experience, plugins, and GUIs
description: |
    Fork of Vim aiming to improve user experience, plugins, and GUIs
builddeps  :
    - pkgconfig(libluv)
    - pkgconfig(libutf8proc)
    - pkgconfig(libuv)
    - pkgconfig(luajit)
    - pkgconfig(termkey)
    - pkgconfig(tree-sitter)
    - pkgconfig(unibilium)
    - gperf
    - libmpack
    - lpeg
rundeps    :
    - lpeg
    - xclip
networking : true
setup      : |
    # Build the bundled tree-sitter parsers
    %cmake_ninja -S cmake.deps -B .deps \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DUSE_BUNDLED=OFF \
        -DUSE_BUNDLED_TS_PARSERS=ON

    cmake --build .deps

    %cmake_ninja \
        -DUSE_BUNDLED=OFF \
        -DUSE_BUNDLED_TS_PARSERS=ON \
        -DENABLE_TRANSLATIONS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -sv /usr/bin/nvim ${installdir}/usr/bin/neovim

    %install_license LICENSE.txt

    # Install Appstream data
    %install_file runtime/nvim.appdata.xml ${installdir}/usr/share/metainfo/io.neovim.nvim.metainfo.xml

    # Set EDITOR and VISUAL defaults should nano be removed.

    %install_file -t ${installdir}/usr/share/defaults/etc/profile.d ${pkgfiles}/80-neovim-is-default-EDITOR-and-VISUAL.{sh,fish}
