# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : flatpak
version    : 1.18.1
release    : 89
source     :
    - https://github.com/flatpak/flatpak/releases/download/1.18.1/flatpak-1.18.1.tar.xz : bc683fc916ed21c0524bb064f358c2ac18586b8ec88c76f2f7f289877521631c
homepage   : https://flatpak.org/
license    : LGPL-2.1-or-later
component  : desktop
summary    : Universal application support
description: |
    Linux application sandboxing and distribution framework
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(dconf)
    - pkgconfig(fuse3)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gpgme)
    - pkgconfig(gtk-doc)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libseccomp)
    - pkgconfig(libzstd)
    - pkgconfig(ostree-1)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-scanner)
    - pkgconfig(xau)
    - bubblewrap
    - pyparsing
    - socat
    - xdg-dbus-proxy
    - xmlto
rundeps    :
    - bubblewrap
    - xdg-dbus-proxy
setup      : |
    %patch -p1 -i $pkgfiles/0001-Solus-Tmpfiles-additions-for-statelessness.patch

    %meson_configure \
                     -Ddbus_config_dir=/usr/share/dbus-1/system.d \
                     -Dprivileged_group=wheel \
                     -Dprofile_dir=/usr/share/defaults/etc/profile.d \
                     -Dsystem_bubblewrap=bwrap \
                     -Dsystem_dbus_proxy=xdg-dbus-proxy
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING

    # Make sure that flatpak profile script is loaded after 10-xdg.sh
    mv $installdir/usr/share/defaults/etc/profile.d/flatpak.sh $installdir/usr/share/defaults/etc/profile.d/70-flatpak.sh

    # We don't have the csh shell
    rm -v $installdir/usr/share/defaults/etc/profile.d/flatpak.csh

    # Add auto-update systemd services
    %install_file -t $installdir/%libdir%/systemd/system $pkgfiles/system/flatpak-update.{service,timer}
    %install_file -t $installdir/%libdir%/systemd/user $pkgfiles/user/flatpak-update.{service,timer}

    # Enable flathub
    %install_file $pkgfiles/flathub.flatpakrepo -t $installdir/usr/share/flatpak/remotes.d/
