# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kmime
version    : 6.30.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/6.30/kmime-6.30.0.tar.xz : 2969a5ef484e98f91bf78e88c98a9d613bdd3bb86ac154ceece0557b70f373bc
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - CC-BY-SA-4.0
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles
builddeps  :
    - extra-cmake-modules
    - kf6-kcodecs-devel
rundeps    :
    - devel:
        - kf6-kcodecs-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
