# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : parallel
version    : '20260422'
release    : 12
source     :
    - https://mirrors.rit.edu/gnu/parallel/parallel-20260422.tar.bz2 : 664cf165d66ea217b2f49cd96a7865ecf90c9d0616599cc2aba8cad481d907bb
license    : GPL-3.0-or-later
component  : programming.tools
homepage   : https://www.gnu.org/software/parallel/
summary    : Execute jobs in parallel
description: |
    GNU parallel is a shell tool that allows for execution of jobs in parallel. This source file also contains a command line SQL client (sql) and a tool for nicing jobs (niceload).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license LICENSES/*
    # remove html, rst, and pdf docs
    rm -rf $installdir/usr/share/doc
