# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xdg-desktop-portal-wlr
version    : 0.8.2
release    : 4
source     :
    - https://github.com/emersion/xdg-desktop-portal-wlr/releases/download/v0.8.2/xdg-desktop-portal-wlr-0.8.2.tar.gz : 5e6840d3326a4afb440c353ee19cf68d4e4fba40a5648224904b3a06612aae87
license    : MIT
component  : desktop.util
homepage   : https://github.com/emersion/xdg-desktop-portal-wlr
summary    : xdg-desktop-portal backend for wlroots
description: |
    xdg-desktop-portal backend for wlroots
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(inih)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libsystemd)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - scdoc
rundeps    :
    - grim
    - pipewire
    - slurp
    - xdg-desktop-portal
setup      : |
    %meson_configure -Dsd-bus-provider=libsystemd
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE

    # Install our portal configuration
    install -Dm00644 $pkgfiles/wlroots-portals.conf $installdir/usr/share/xdg-desktop-portal/wlroots-portals.conf
