# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : joe
version    : '4.8'
release    : 6
source     :
    - https://github.com/joe-editor/joe/archive/refs/tags/releases/joe-4.8.tar.gz : bb51da192e9daeb234d0663e6cf398673f779e48578944c74a765041e70f15c3
homepage   : https://joe-editor.sourceforge.io/
license    : GPL-2.0-or-later
component  : editor
summary    : Small text editor that can emulate other popular text editors
description: |
    Joe is a simple but powerful text editor. In addition to its default look. It can emulate GNU Emacs, WordStar and Pico. Termcap/Terminfo support allows JOE to use any terminal or terminal emulator. It also supports ANSI terminals.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
