# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-socketio
version    : 5.16.2
release    : 11
source     :
    - https://github.com/miguelgrinberg/python-socketio/archive/refs/tags/v5.16.2.tar.gz : 24c958763657d0b3b528ec3d2c9d1b3a8d84001f5412fc1f0e65bf6da05248f5
homepage   : https://github.com/miguelgrinberg/python-socketio
license    : MIT
component  : programming.python
summary    : Socket.IO server and client for Python
description: |
    Python implementation of the Socket.IO_ realtime client and server.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - python-aiohttp
    - python-bidict
    - python-engineio
    - python-msgpack
    - python-pytest
    - python-pytest-asyncio
    - python-uvicorn
    - python-websocket-client
rundeps    :
    - python-bidict
    - python-engineio
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v \
        --ignore=tests/async/test_redis_manager.py \
        --ignore=tests/common/test_redis_manager.py
