# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : falcond
version    : 2.0.8
release    : 3
source     :
    - https://git.pika-os.com/general-packages/falcond/archive/v2.0.8.tar.gz : 0fc81d651bda5765f923a998d3ce592a948b3be21b7bd0fc3ac74d1fd6a34c17
    - git|https://github.com/PikaOS-Linux/falcond-profiles.git : 5023a846980685812334586ae265f8f6a1ded38b
homepage   : https://git.pika-os.com/general-packages/falcond
license    : MIT
component  : games
summary    : Advanced Linux Gaming Performance Daemon
description: |
    falcond is a powerful system daemon designed to automatically optimize your Linux gaming experience. It intelligently manages system resources and performance settings on a per-game basis, eliminating the need to manually configure settings for each game.
conflicts  : gamemode
networking : true
environment: |
    export ZIG_GLOBAL_CACHE_DIR=$workdir/zig-cache
    export DESTDIR=%installroot%
builddeps  :
    - zig
build      : |
    pushd falcond
        zig build %JOBS% \
            --release=fast \
            --prefix %PREFIX% \
            -Dcpu=baseline \
            -Doptimize=ReleaseFast \
            -Duser-profiles-dir=/etc/falcond/profiles/user # changed since users shouldn't edit /usr/share files
        
        sed -i '9d' debian/falcond.service
    popd
install    : |
    %install_license LICENSE
    pushd falcond
        install -Dm00644 debian/falcond.service $installdir/%libdir%/systemd/system/falcond.service
    popd

    pushd ${sources}/falcond-profiles.git
        install -Dm00644 -t $installdir/usr/share/falcond usr/share/falcond/system.conf
        install -Dm00644 -t $installdir/usr/share/falcond/profiles/ usr/share/falcond/profiles/*.conf
        install -Dm00644 -t $installdir/usr/share/falcond/profiles/htpc/ usr/share/falcond/profiles/htpc/*.conf
    popd

    install -Dm00644 -t ${installdir}/%libdir%/systemd/system-preset/ ${pkgfiles}/60-falcond.preset
