# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libkdepim
version    : 26.08.1
release    : 103
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/libkdepim-26.08.1.tar.xz : f4de990ab9a8e38b9f73870c1f9523d51c69ede75b8ccf2d62e51be48a861682
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - MIT
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kf6-kcompletion-devel
    - kf6-ki18n-devel
    - kf6-kwidgetsaddons-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
