# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libkdepim
version    : 26.04.3
release    : 102
source     :
    - https://download.kde.org/stable/release-service/26.04.3/src/libkdepim-26.04.3.tar.xz : 089f1b24839a66b234e987f9eb71aca9efe20c2e9d8dd7387f24c14cbff37bf5
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - MIT
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kf6-kcompletion-devel
    - kf6-ki18n-devel
    - kf6-kwidgetsaddons-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
