# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : safeeyes
version    : 3.5.0
release    : 22
source     :
    - https://github.com/slgobinath/safeeyes/archive/refs/tags/v3.5.0.tar.gz : 47a44e35b2c312eac7c9d76d0d24d1746818666bb9dc3986802b2fa0411bb89a
homepage   : https://slgobinath.github.io/safeeyes/
license    : GPL-3.0-or-later
component  : desktop
summary    : Safe Eyes is a tool to reduce and prevent repetitive strain injury (RSI)
description: |
    Protect your eyes from eye strain using this simple and beautiful, yet extensible break reminder.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - libgtk-4
    - libnotify
    - pipewire
    - python-babel
    - python-croniter
    - python-gobject
    - python-psutil
    - python-pywayland
    - python-xlib
    - xprintidle
build      : |
    %python3_setup
install    : |
    %python3_install
    %install_license LICENSE

    install -Dm00644 safeeyes/platform/io.github.slgobinath.SafeEyes.desktop -t ${installdir}/usr/share/applications

    install -Dm00644 safeeyes/platform/io.github.slgobinath.SafeEyes.metainfo.xml -t ${installdir}/usr/share/metainfo

    # Install icons
    for size in 16x16 24x24 32x32 48x48 64x64 128x128; do
        if [ -d safeeyes/platform/icons/hicolor/${size}/status ]; then
            install -Dm00644 safeeyes/platform/icons/hicolor/${size}/status/*.png -t ${installdir}/usr/share/icons/hicolor/${size}/status
        fi

        install -Dm00644 safeeyes/platform/icons/hicolor/${size}/apps/*.png -t ${installdir}/usr/share/icons/hicolor/${size}/apps
    done

    # Remove duplicate icons and desktop file.
    rm -rv $installdir/usr/lib/python%python3_version%/site-packages/safeeyes/platform
