# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-jupyter-server
version    : 2.18.2
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyter_server/jupyter_server-2.18.2.tar.gz : 06b4f40d8a7a00bb39d5216859c81374a0e7cfefe6d8a5a7facc5a5c37c679a7
homepage   : https://github.com/jupyter-server/jupyter_server
license    : BSD-3-Clause
component  : programming.python
summary    : The backend—i.e. core services, APIs, and REST endpoints—to Jupyter web applications
description: |
    The Jupyter Server provides the backend (i.e. the core services, APIs, and REST endpoints) for Jupyter web applications like Jupyter notebook, JupyterLab, and Voila.
builddeps  :
    - python-build
    - python-hatch-jupyter-builder
    - python-installer
rundeps    :
    - python-anyio
    - python-argon2-cffi
    - python-jupyter-events
    - python-jupyter-server-terminals
    - python-jupyter_client
    - python-nbconvert
    - python-overrides
    - python-prometheus_client
    - python-send2trash
    - python-websocket-client
build      : |
    %python3_setup
install    : |
    %python3_install
