# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : uncrustify
version    : 0.83.0
release    : 16
source     :
    - https://github.com/uncrustify/uncrustify/archive/refs/tags/uncrustify-0.83.0.tar.gz : 1d4d3ab3a991c66eb24cb0a3e690573b4882fd98bc6ec64a01c283998c20dc87
homepage   : https://uncrustify.sourceforge.net/
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Source code beautifier for C, C++, CSharp, ObjectiveC, D, Java, Pawn and Vala
description: |
    Source code beautifier for C, C++, CSharp, ObjectiveC, D, Java, Pawn and Vala.
    The goals of this project are simple: Create a highly configurable, easily modifiable source code beautifier.
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
