# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-zope.exceptions
version    : '6.0'
release    : 4
source     :
    - https://github.com/zopefoundation/zope.exceptions/archive/refs/tags/6.0.tar.gz : 00642014c4e584a5b6f518fc5b756b30bbcd0c6fac400d4af150c924355905f2
homepage   : https://zopeexceptions.readthedocs.io/
license    : ZPL-2.1
component  : programming.python
summary    : Zope exceptions and implementations which are general purpose.
description: |
    Zope exceptions and implementations which are general purpose.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
build      : |
    # skip dep check for setuptools 82.0, remove on update
    %python3_setup --skip-dependency-check
install    : |
    %python3_install
