# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-scikit-build
version    : 0.19.1
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/s/scikit_build/scikit_build-0.19.1.tar.gz : b9a8d07fca2d5d10d93220bc57a685161d72af1fc76285d55c564ddaa862e584
homepage   : https://github.com/scikit-build/scikit-build
license    : MIT
component  : programming.python
summary    : Improved build system generator for CPython C, C++, Cython and Fortran extensions
description: |
    Improved build system generator for CPython C/C++/Fortran/Cython extensions.
builddeps  :
    - python-build
    - python-hatch-fancy-pypi-readme
    - python-hatch-vcs
    - python-installer
rundeps    :
    - python-distro
    - python-packaging
    - python-wheel
build      : |
    %pyproject_build
install    : |
    %pyproject_install
