# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-test-fatal
version    : '0.018'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Test-Fatal-0.018.tar.gz : b8d2cccf9ee467271bc478f9cf7eba49545452be9302ae359bc538b8bf687cd6
homepage   : https://metacpan.org/pod/Test::Fatal
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Fatal incredibly simple helpers for testing code with exceptions
description: |
    Test::Fatal is an alternative to the popular Test::Exception. It does much less, but should allow greater flexibility in testing exception-throwing code with about the same amount of typing.
builddeps  :
    - perl-try-tiny
rundeps    :
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
patterns   : /*
