# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kcachegrind
version    : 26.04.2
release    : 55
source     :
    - https://download.kde.org/stable/release-service/26.04.2/src/kcachegrind-26.04.2.tar.xz : 89a4ee7ec8b0750067cc6e1826eab185cb97dd6b1b9ebcc04e5528b05e3b7078
homepage   : https://apps.kde.org/kcachegrind/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-only
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.kde
summary    : Visualization of Performance Profiling Data
description: |
    kcachegrind is a KDE GUI to visualize profiling data. It's mainly used as visualization frontend for data measured by Cachegrind/Callgrind tools from the Valgrind package, but there are converters for other measurement tools available.
builddeps  :
    - kf6-karchive-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-kwidgetsaddons-devel
    - kf6-kxmlgui-devel
    - qt6-base-private-devel
rundeps    :
    - valgrind
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
patterns   :
    - docs : /usr/share/doc
