# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : recoll
version    : 1.43.17
release    : 36
source     :
    - https://www.recoll.org/recoll-1.43.17.tar.gz : 2e70740a016bd9d337aca5ee407891ee86736457020c19408f33121354776e2d
homepage   : https://www.recoll.org
license    : GPL-2.0-or-later
component  : desktop
summary    : Recoll is a desktop full-text search tool
description: |
    Recoll finds keywords inside documents as well as file names.
clang      : true
libsplit   : false
builddeps  :
    - pkgconfig(Qt6UiTools)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(jsoncpp)
    - pkgconfig(libxslt)
    - pkgconfig(python3)
    - pkgconfig(x11)
    - pkgconfig(xapian-core)
    - chmlib-devel
    - python-setuptools
rundeps    :
    - djvulibre
    - ghostscript
    - mutagen
    - perl-image-exiftool
    - poppler-utils
    - python-beautifulsoup4
    - python-chardet
    - python-rarfile
environment: |
    export QMAKE=qmake6
setup      : |
    %meson_configure \
        -Dwebkit=false \
        -Dwebengine=true \
        -Daspell=false \
        -Dpython-aspell=false \
        -Drecollq=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
check      : |
    %ninja_check
