# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : geonkick
version    : 3.9.0
release    : 28
source     :
    - https://github.com/Geonkick-Synthesizer/geonkick/archive/refs/tags/v3.9.0.tar.gz : 57aa7091a7b90f7c649b1abc932dd9e90ced9633beaf60f5165e137ddf50973f
homepage   : https://geonkick.org/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A free software percussion synthesizer
description: |
    Geonkick is a synthesizer that can synthesize elements of percussion. The most basic examples are: kicks, snares, hit-hats, shakers, claps, sticks. Also, it can play samples.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(sndfile)
    - pkgconfig(x11)
    - rapidjson-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Install appstream metadata
    install -Dm00644 $pkgfiles/org.geonkick.geonkick.metainfo.xml -t $installdir/usr/share/metainfo
    # Remove all header files and static libs, it is only needed during build time
    rm -rf $installdir/usr/include $installdir/usr/lib
    %install_license LICENSE AUTHORS
