# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : clblast
version    : 1.7.0
release    : 2
source     :
    - https://github.com/CNugteren/CLBlast/archive/refs/tags/1.7.0.tar.gz : cac83330a6110214f2b7efc8e46062536f40ba96122f3b2a074a51497d8ca9e7
homepage   : https://cnugteren.github.io/clblast
license    : Apache-2.0
component  : programming.library
summary    : Tuned OpenCL BLAS
description: |
    CLBlast is a lightweight, performant and tunable OpenCL BLAS library written in C++11. It is designed to leverage the full performance potential of a wide variety of OpenCL devices from different vendors, including desktop and laptop GPUs, embedded GPUs, and other accelerators. CLBlast implements BLAS routines: basic linear algebra subprograms operating on vectors and matrices.
avx2       : true
clang      : true
builddeps  :
    - pkgconfig(OpenCL)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
