# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : sonivox
version    : 4.0.1
release    : 5
source     :
    - https://github.com/pedrolcl/sonivox/archive/refs/tags/v4.0.1.tar.gz : dabdbd54bd6ba8d5be995bd9ef504c2a34bdf654f41a389510c99043cfc237ca
homepage   : https://github.com/pedrolcl/sonivox
license    : Apache-2.0
summary    : Library for wavetable and realtime GM synthesis
component  : programming.library
description: |
    A library for wavetable and realtime GM synthesis. A fork of the AOSP 'platform_external_sonivox' project.
setup      : |
    %cmake_ninja -DBUILD_SONIVOX_STATIC=OFF -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
