# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-parameterized
version    : 0.9.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/p/parameterized/parameterized-0.9.0.tar.gz : 7fc905272cefa4f364c1a3429cbbe9c0f98b793988efb5bf90aac80f08db09b1
homepage   : https://github.com/wolever/parameterized
license    : MIT
component  : programming.python
summary    : Parameterized testing with any Python test framework
description: |
    Parameterized testing in Python sucks.
    parameterized fixes that. For everything. Parameterized testing for nose, parameterized testing for py.test, parameterized testing for unittest.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
