# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libconfuse
version    : '3.4'
release    : 9
source     :
    - https://github.com/libconfuse/libconfuse/releases/download/v3.4/confuse-3.4.tar.xz : 36bfa3928f9c323914c7c8317e8722cb22f41db69d7c9d4c24b4689fa955445d
homepage   : https://github.com/libconfuse/libconfuse
license    : ISC
component  : desktop.library
summary    : C-library for parsing configuration files
description: |
    C-library for parsing configuration files
setup      : |
    %configure \
        --disable-static \
        --enable-shared
build      : |
    %make
install    : |
    %make_install
    %install_license LICENSE
