# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : OTPClient
version    : 5.2.2
release    : 21
source     :
    - https://github.com/paolostivanin/OTPClient/archive/refs/tags/v5.2.2.tar.gz : 59504287fb5a5a00f98a1fac433e3f0354c0ef7c42c7ad992fe94ac37cde8539
homepage   : https://github.com/paolostivanin/OTPClient
license    : GPL-3.0-or-later
component  : security
summary    : Highly secure and easy to use OTP client written in C/GTK that supports both TOTP and HOTP
description: |
    Highly secure and easy to use GTK+ software for two-factor authentication that supports both Time-based One-time Passwords (TOTP) and HMAC-Based One-Time Passwords (HOTP).
builddeps  :
    - pkgconfig(cotp)
    - pkgconfig(jansson)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgcrypt)
    - pkgconfig(libpng)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(libqrencode)
    - pkgconfig(libsecret-1)
    - pkgconfig(protobuf)
    - pkgconfig(zbar)
    - crossguid-devel
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
