# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : OTPClient
version    : 5.1.4
release    : 17
source     :
    - https://github.com/paolostivanin/OTPClient/archive/refs/tags/v5.1.4.tar.gz : ca9b93ea3ada2a1d582bc469079803726fc7941d70b50c7d8c9f829f28c00ee4
homepage   : https://github.com/paolostivanin/OTPClient
license    : GPL-3.0-or-later
component  : security
summary    : Highly secure and easy to use OTP client written in C/GTK that supports both TOTP and HOTP
description: |
    Highly secure and easy to use GTK+ software for two-factor authentication that supports both Time-based One-time Passwords (TOTP) and HMAC-Based One-Time Passwords (HOTP).
builddeps  :
    - pkgconfig(cotp)
    - pkgconfig(jansson)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgcrypt)
    - pkgconfig(libpng)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(libqrencode)
    - pkgconfig(libsecret-1)
    - pkgconfig(protobuf)
    - pkgconfig(zbar)
    - crossguid-devel
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
