name       : python-proton-vpn-network-manager
version    : 0.4.2
release    : 1
source     :
    - https://github.com/ProtonVPN/python-proton-vpn-network-manager/archive/refs/tags/v0.4.2.tar.gz : b2666012e1d6d25ba9e6ad2da0d2ee664becf02013596fb2686a81139360339b
homepage   : https://github.com/ProtonVPN/python-proton-vpn-network-manager
license    : GPL-3.0-or-later
component  : programming.python
summary    : The proton-vpn-network-manager component
description: |
    The proton-vpn-network-manager component provides the necessary functionality for other components to interact with NetworkManager.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
