# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-karchive
version    : 6.28.0
release    : 35
source     :
    - https://download.kde.org/stable/frameworks/6.28/karchive-6.28.0.tar.xz : ff36137e6b171906b4bde4006558739c5d7771dc30b9a037b65e62b2674a1b13
homepage   : https://community.kde.org/Frameworks
license    :
    - Apache-2.0
    - BSD-2-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
component  : programming.library
summary    : Reading, creating, and manipulating file archives.
description: |
    Reading, creating, and manipulating file archives.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(bzip2)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-tools-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
