# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-gevent
version    : 26.7.0
release    : 10
source     :
    - https://pypi.io/packages/source/g/gevent/gevent-26.7.0.tar.gz : 5b333a556e38a302b1b8c80525bef16d437e16f1e7767947789406841856a102
homepage   : https://www.gevent.org/
license    : MIT
component  : programming.python
summary    : Coroutine-based network library
description: |
    gevent is a coroutine -based Python networking library that uses greenlet to provide a high-level synchronous API on top of the libev or libuv event loop.
builddeps  :
    - pkgconfig(libcares)
    - pkgconfig(libuv)
    - pkgconfig(python3)
    - cython
    - libev-devel
    - python-build
    - python-cffi
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - dnspython
    - lsof
    - python-greenlet
    - python-psutil
    - python-requests
    - python-zope.event
    - python-zope.interface
rundeps    :
    - python-cffi
    - python-greenlet
    - python-zope.event
    - python-zope.interface
environment: |
    export CFLAGS="${CFLAGS} -Wno-incompatible-pointer-types"

    # http://www.gevent.org/development/installing_from_source.html#embedding-libraries
    export GEVENTSETUP_EMBED=0
setup      : |
    # Upstream intentionally includes C extension sources in the built package,
    # because... reasons (PyPy I think?) however we do not want that. Sources will
    # go into debuginfo as normal.
    sed -i -e 's/include_package_data=True/include_package_data=False/' setup.py

    # No linters
    sed -i -e '/coverage/d' -e '/objgraph/d' setup.py

    # Force re-cythonizing the sources - missing with github tarballs
    rm -f $(grep -rl '/\* Generated by Cython')
    rm -f src/gevent/_generated_include/*
build      : |
    %pyproject_build
install    : |
    %pyproject_install
# 3 tests fail with the following:
# TypeError: exceptions must be classes, or instances, not OldStyle
# check      : |
#     _args=(
#         -unone
#         --ignore=test__getaddrinfo_import.py
#         --ignore=test__core_timer.py
#     )
#
#     %python3_test -m gevent.tests "${_args[@]}"
