# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnupg
version    : 2.5.24
release    : 54
source     :
    - https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.5.24.tar.bz2 : bf149d01a2b9fcc0e4589b8ae8697d3d5c557ea48ed95a3fa55dd3b1187e6039
license    : GPL-3.0-or-later
homepage   : https://www.gnupg.org
summary    : Complete and free implementation of OpenPGP
component  : security
description: |
    GnuPG is a complete and free implementation of OpenPGP standard as defined by RFC4880. It allows encryption and signing of data and communications, a key management system, and access modules for public key directories.
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(gnutls)
    - pkgconfig(gpg-error)
    - pkgconfig(ksba)
    - pkgconfig(libassuan)
    - pkgconfig(libgcrypt)
    - pkgconfig(sqlite3)
    - npth-devel
    - pinentry
rundeps    :
    - pinentry
setup      : |
    %configure \
               --enable-symcryptrun \
               --enable-gpgtar \
               --enable-all-tests
build      : |
    %make
install    : |
    %make_install DESTDIR=$installdir
    %install_license COPYING*
    ln -s /usr/bin/gpg $installdir/usr/bin/gpg2
check      : |
    # If tests last too long, you can remove --enable-all-tests
    %make check
