# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libgnome-desktop
version    : '51.0'
release    : 63
source     :
    - https://download.gnome.org/sources/gnome-desktop/51/gnome-desktop-51.0.tar.xz : 9ebeb9f1769d3c310caeadd921ab34c8f264b92937740518b3bc859a579a6912
homepage   : https://gitlab.gnome.org/GNOME/gnome-desktop/-/tree/master/libgnome-desktop
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME utility runtime library
description: |
    GNOME utility runtime library
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(libseccomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - gtk-doc
    - itstool
rundeps    :
    - bubblewrap
setup      : |
    %meson_configure -Dbuild_gtk4=true -Dlegacy_library=true -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
