# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnumeric
version    : 1.12.60
release    : 49
source     :
    - https://download.gnome.org/sources/gnumeric/1.12/gnumeric-1.12.60.tar.xz : bb02feb286062805564438534e1fea459f97cebac8a090b1a7e47ca251e07467
homepage   : https://gnome.pages.gitlab.gnome.org/gnumeric-web/
license    :
    - GPL-2.0-only
    - GPL-3.0-only
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - itstool
    - yelp-tools
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING*
patterns   :
    - /usr/lib64/*.so