# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ledger
version    : 3.4.1
release    : 21
source     :
    - https://github.com/ledger/ledger/archive/refs/tags/v3.4.1.tar.gz : 1cf012cdc8445cab0efc445064ef9b2d3f46ed0165dae803c40fe3d2b23fdaad
homepage   : https://www.ledger-cli.org/
license    : BSD-3-Clause
component  : office.finance
summary    : A double-entry UNIX command-line accounting system
description: |
    Ledger is a powerful, double-entry accounting system that is accessed from the UNIX command-line.
builddeps  :
    - pkgconfig(gmp)
    - pkgconfig(mpfr)
    - pkgconfig(python3)
    - libboost-devel
setup      : |
    %patch -p1 -i ${pkgfiles}/0001-cmake-Fix-GMP-version-detection.patch

    %cmake_ninja \
        -DUSE_PYTHON=on \
        -DUSE_PYTHON37_COMPONENT=yes
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE.md
    install -Dm00644 contrib/ledger-completion.bash ${installdir}/usr/share/bash-completion/completions/ledger
check      : |
    # Failing test
    #test/regress/BF3C1F82-2.test
    %make check || :
