# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-module-pluggable
version    : '6.4'
release    : 10
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SI/SIMONW/Module-Pluggable-6.4.tar.gz : 970fd13accd3d538e637db080ebbd9898020c8b5591837c8493a39edd737922d
homepage   : https://metacpan.org/pod/Module::Pluggable
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Module::Pluggable - automatically give your module the ability to have plugins
description: |
    Module::Pluggable - automatically give your module the ability to have plugins
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
patterns   : /*
