# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : liboqs
version    : 0.15.0
release    : 1
source     :
    - https://github.com/open-quantum-safe/liboqs/archive/refs/tags/0.15.0.tar.gz : 3983f7cd1247f37fb76a040e6fd684894d44a84cecdcfbdb90559b3216684b5c
homepage   : https://openquantumsafe.org/
license    : MIT
component  : security.library
summary    : A quantum-safe C cryptography library
description: |
    Liboqs is a C library for quantum-safe cryptographic algorithms. It is part of the Open Quantum Safe (OQS) project, and is supported by the Post-Quantum Cryptography Alliance as part of the Linux Foundation.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(openssl)
build      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
install    : |
    %ninja_install
    %install_license LICENSE.txt
