# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : umbrello
version    : 26.04.1
release    : 114
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/umbrello-26.04.1.tar.xz : d5ccce924091558d76b6bf0245deb342cb7afcc8dbfae5205bb3668114ed2060
homepage   : https://kde.org/applications/development/org.kde.umbrello
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(libxslt)
    - karchive-devel
    - kcrash-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - kdoctools-devel
    - kiconthemes-devel
    - ktexteditor-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #Remove docs
    rm -rfv $installdir/usr/share/doc
    rm -rfv $installdir/usr/share/umbrello5/apidoc
