# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-service-identity
version    : 26.1.0
release    : 17
source     :
    - https://files.pythonhosted.org/packages/source/s/service_identity/service_identity-26.1.0.tar.gz : 6358c52882c96e66ac4a55eb3a72c7dd4a70763f8cc6fa4e70abde2656f4bf3b
homepage   : https://github.com/pyca/service-identity
license    : MIT
component  : programming.python
summary    : Service identity verification for pyOpenSSL
description: |
    Service identity verification for pyOpenSSL.
builddeps  :
    - python-asn1-modules # check
    - python-build
    - python-cryptography
    - python-hatch-fancy-pypi-readme
    - python-hatch-vcs
    - python-idna         # check
    - python-installer
    - python-pytest       # check
rundeps    :
    - python-asn1-modules
    - python-attrs
    - python-cryptography
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
