# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : onedrive-gui
version    : 1.3.0
release    : 7
source     :
    - https://github.com/bpozdena/OneDriveGUI/archive/refs/tags/v1.3.0.tar.gz : be325a873055269fd31856b921b7326de0013486d5ea0e0b40e424f220bf35ee
homepage   : https://github.com/bpozdena/OneDriveGUI
license    : GPL-3.0-or-later
component  : network.clients
summary    : A simple GUI for Linux OneDrive Client, with multi-account support.
description: |
    A simple GUI for Linux OneDrive Client, with multi-account support.
builddeps  :
    - python-build
    - python-installer
    - python-pyside6
    - python-requests
    - python-setuptools
    - python-wheel
rundeps    :
    - onedrive
    - python-pyside6
    - python-requests
setup      : |
    %patch -p1 -i $pkgfiles/0001-Rebase-patches-onto-new-version.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m00644 src/onedrive_gui/resources/OneDriveGUI.desktop $installdir/usr/share/applications/OneDriveGUI.desktop
    install -D -m00644 src/onedrive_gui/resources/images/OneDriveGUI.png $installdir/usr/share/icons/OneDriveGUI.png
    install -D -m00644 src/onedrive_gui/resources/images/OneDriveGUI.ico $installdir/usr/share/icons/OneDriveGUI.ico
