# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : onedrive-gui
version    : 1.3.0
release    : 8
source     :
    - https://github.com/bpozdena/OneDriveGUI/archive/refs/tags/v1.3.0.tar.gz : be325a873055269fd31856b921b7326de0013486d5ea0e0b40e424f220bf35ee
homepage   : https://github.com/bpozdena/OneDriveGUI
license    : GPL-3.0-or-later
component  : network.clients
summary    : A simple GUI for Linux OneDrive Client, with multi-account support.
description: |
    A simple GUI for Linux OneDrive Client, with multi-account support.
builddeps  :
    - desktop-file-utils
    - python-build
    - python-installer
    - python-pyside6
    - python-requests
    - python-setuptools
    - python-wheel
rundeps    :
    - onedrive
    - python-requests
    - shiboken6
setup      : |
    %apply_patches
    install -D -m00644 $pkgfiles/MANIFEST.in $workdir/MANIFEST.in
    install -D -m00644 $pkgfiles/pyproject.toml $workdir/pyproject.toml
    desktop-file-edit --set-key=Exec --set-value="onedrive-gui" $workdir/src/onedrive_gui/resources/OneDriveGUI.desktop
build      : |
    %python3_setup
install    : |
    %python3_install
    install -D -m00644 src/onedrive_gui/resources/OneDriveGUI.desktop $installdir/usr/share/applications/OneDriveGUI.desktop
    install -D -m00644 $pkgfiles/io.github.bpozdena.onedrivegui.metainfo.xml $installdir/usr/share/metainfo/io.github.com.bpozdena.onedrivegui.metainfo.xml
    install -D -m00644 src/onedrive_gui/resources/images/OneDriveGUI.png $installdir/usr/share/icons/hicolor/80x80/apps/OneDriveGUI.png
