name       : gnome-software
version    : '45.1'
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-software/45/gnome-software-45.1.tar.xz : d72485f7a6e0917f64edbedd68fd7b57246c6ebf10c5a45108b63946635778a2
homepage   : https://apps.gnome.org/Software/
license    : GPL-2.0-or-later # CHECK ME
component  : desktop.gnome
summary    : Software allows users to easily find, discover and install apps.
description: |
    Software allows users to easily find, discover and install apps. It also keeps their OS, apps and devices up to date without them having to think about it, and gives them confidence that their system is up to date. It supports popular distributions, subject to those distributions maintaining their own distro-specific integration code.
networking : yes
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(flatpak)
    - pkgconfig(fwupd)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(xmlb)
    - gtk-doc
setup      : |
    %patch -p1 -i $pkgfiles/1820.diff
    %patch -p1 -i $pkgfiles/0001-gs-appstream-Check-against-kernel-relation-types.patch
    %patch -p1 -i $pkgfiles/0001-packagekit-Hardcode-some-solus-thingies.patch
    %meson_configure \
        -Dpackagekit_autoremove=true \
        -Dmalcontent=false \
        -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
