# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lazygit
version    : 0.64.1
release    : 62
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.64.1.tar.gz : b1df6ee72f17efc0ef95fc20a64821cd9eda3935b81cb98b1719c8266163bd07
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : true
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
    %install_license LICENSE
