# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lazygit
version    : 0.62.2
release    : 58
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.62.2.tar.gz : 0bd1cdbaf1a584d2eb2fd14f068a8eaaeaeb80d3e2713c72005de9e4feaf6844
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : true
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
    %install_license LICENSE
