# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lazygit
version    : 0.65.1
release    : 64
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.65.1.tar.gz : df30ec1a5032b3c5672a30090fe787fb32d4122fd996d6d85e1d10135acfbc89
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : true
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit
install    : |
    %install_bin $workdir/lazygit
    %install_license LICENSE
