# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : cairomm
version    : 1.14.6
release    : 21
source     :
    - https://www.cairographics.org/releases/cairomm-1.14.6.tar.xz : 7e0d5c7f29175d573a03ab5c45aef63f48dd91a5caf335a404cd763e4b7cea4a
homepage   : https://www.cairographics.org/cairomm/
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : C++ bindings to Cairo
description: |
    C++ bindings to Cairo
replaces   :
    - libcairomm
    - devel : libcairomm-devel
    - docs : libcairomm-docs
optimize   :
    - speed
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glibmm-2.4)
    - doxygen
    - graphviz
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib64/cairomm-1.0/include
setup      : |
    %meson_configure -Dbuild-documentation=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
