# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : certbot
version    : 5.6.0
release    : 30
source     :
    - https://pypi.python.org/packages/source/c/certbot/certbot-5.6.0.tar.gz : 89052854e28cd2fcac72a8857aad6dfc6b02ba992f4b8f255062fe29c8aed3ee
homepage   : https://github.com/certbot/certbot
license    : Apache-2.0
component  : security.crypto
summary    : A free, automated certificate authority client
description: |
    Certbot, previously the Let's Encrypt Client, is EFF's tool to obtain certs from Let's Encrypt, and (optionally) auto-enable HTTPS on your server. It can also act as a client for any other CA that uses the ACME protocol.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - pyparsing
    - python-acme
    - python-configargparse
    - python-configobj
    - python-distro
    - python-parsedatetime
    - python-pytest
rundeps    :
    - pyparsing
    - python-acme
    - python-configargparse
    - python-configobj
    - python-distro
    - python-parsedatetime
networking : true # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # https://github.com/certbot/certbot/issues/9606
    pytest_args=(
        -W ignore::DeprecationWarning
        --import-mode=importlib
    )

    %python3_test pytest -v "${pytest_args[@]}"
