# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : fq
version    : 0.18.0
release    : 7
source     :
    - https://github.com/wader/fq/archive/refs/tags/v0.18.0.tar.gz : 2580de6fb21281a262f99f24d585a925cef71f158c2b24a34125e1b29bc612ef
homepage   : https://github.com/wader/fq
license    : MIT
component  : programming.tools
summary    : tool, language and decoders for working with binary and text formats
description: |
    jq for binary formats - tool, language and decoders for working with binary and text formats
networking : true
builddeps  :
    - golang
build      : |
    %make
install    : |
    install -Dm00755 fq -t $installdir/usr/bin/
    %install_license LICENSE
