# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : budgie-desktop
version    : 10.10.3
release    : 287
source     :
    - https://github.com/BuddiesOfBudgie/budgie-desktop/releases/download/v10.10.3/budgie-desktop-v10.10.3.tar.xz : 5dae4e311bc95ad982b6256265537c2c6e2bcd19dd35efd19bdbb33633516b74
homepage   : https://blog.buddiesofbudgie.org
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
summary    : A luxurious home computing experience
description: |
    Budgie Desktop is a modern desktop environment developed by the Buddies of Budgie.
component  : desktop.budgie
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(alsa)
    - pkgconfig(gee-0.8)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(gtk-layer-shell-0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-2)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libwacom)
    - pkgconfig(libxfce4windowing-0)
    - pkgconfig(upower-glib)
    - gammastep
    - grim
    - gtklock
    - mesa-demos
    - python-psutil
    - python-systemd
    - python3-dbus
    - sassc
    - slurp
    - swaybg
    - swayidle
    - vala
    - wlopm
rundeps    :
    - budgie-control-center
    - budgie-desktop-services
    - budgie-session
    - gammastep
    - gnome-settings-daemon
    - grim
    - gtklock
    - labwc
    - mesa-demos
    - mutter-common
    - network-manager-applet
    - pipewire
    - python-gobject
    - python-psutil
    - python-systemd
    - python3-dbus
    - slurp
    - swaybg
    - swayidle
    - switcheroo-control
    - wlopm
    - xdg-desktop-portal-gtk
    - xdg-desktop-portal-wlr
setup      : |
    %patch -p1 -i ${pkgfiles}/no-root-menu-on-left-click.patch

    # We have to override the usual Solus libexexdir
    # because Budgie needs to know where other package's
    # binaries in libexecdir are.
    %meson_configure \
        --libexecdir="lib%LIBSUFFIX%" \
        -Dbudgie-session-libexecdir="/usr/lib64/budgie-session" \
        -Dgsd-libexecdir="/usr/lib64/gnome-settings-daemon" \
        -Dxdp-libexecdir="/usr/lib64/xdg-desktop-portal" \
        -Dwith-stateless=true
build      : |
    %meson_build
install    : |
    %meson_install
    %install_license LICENSE LICENSE.*
