# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-http-cookiejar
version    : '0.014'
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/HTTP-CookieJar-0.014.tar.gz : 7094ea5c91f536d263b85e83ab4e9a963e11c4408ce08ecae553fa9c0cc47e73
homepage   : https://metacpan.org/pod/HTTP::CookieJar
license    : Apache-2.0
component  : programming.perl
summary    : A minimalist HTTP user agent cookie jar
description: |
    This module implements a minimalist HTTP user agent cookie jar in conformance with RFC 6265.
builddeps  :
    - perl-http-date
    - perl-test-deep
    - perl-test-requires
    - perl-uri
rundeps    :
    - perl-http-date
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
check      : |
    %perl_build test
patterns   : /*
