# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gjs
version    : 1.90.0
release    : 70
source     :
    - https://download.gnome.org/sources/gjs/1.90/gjs-1.90.0.tar.xz : 47e9f22b1d4aca841c6c492b449b6de32ff680972183e26fe7b98a45c5c3fee1
component  : desktop.gnome.core
homepage   : https://gjs.guide/
license    :
    - MIT OR LGPL-2.0-or-later
summary    : GNOME JavaScript
description: |
    GJS is a JavaScript runtime built on Firefox's SpiderMonkey JavaScript engine and the GNOME platform libraries.
optimize   :
    - lto
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(mozjs-140)
rundeps    :
    - mozjs
setup      : |
    %patch -p1 -i $pkgfiles/0001-gi-Allow-optional-inout-arguments-to-be-null.patch
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
