# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gjs
version    : 1.88.1
release    : 69
source     :
    - https://download.gnome.org/sources/gjs/1.88/gjs-1.88.1.tar.xz : 767bab80e665d672cb00563c25f0b392a9ec8c2996ed1d4454c698b4c2f0a3d9
component  : desktop.gnome.core
homepage   : https://gjs.guide/
license    :
    - MIT OR LGPL-2.0-or-later
summary    : GNOME JavaScript
description: |
    GJS is a JavaScript runtime built on Firefox's SpiderMonkey JavaScript engine and the GNOME platform libraries.
optimize   :
    - lto
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(mozjs-140)
rundeps    :
    - mozjs
setup      : |
    %patch -p1 -i $pkgfiles/0001-gi-Allow-optional-inout-arguments-to-be-null.patch
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
