# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kmines
version    : 26.08.1
release    : 30
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/kmines-26.08.1.tar.xz : 0097fd3f17033f9a8ad518ce613ceb0920668a3c7fd6321af6ab18fa2c058074
homepage   : https://apps.kde.org/kmines/
license    :
    - BSD-3-Clause
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A Minesweeper game.
description: |
    KMines is a classic Minesweeper game. The idea is to uncover all the squares without blowing up any mines. When a mine is blown up, the game is over.
builddeps  :
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-ktextwidgets-devel
    - kf6-kwidgetsaddons-devel
    - kf6-kxmlgui-devel
    - libkdegames-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*

    # remove doc
    rm -rfv $installdir/usr/share/doc
