# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kmines
version    : 26.04.1
release    : 27
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/kmines-26.04.1.tar.xz : cf4a9826323620ae60998c2425b555a3b4d8fd8b4e1605bbaeb0ab3d99facd6a
homepage   : https://apps.kde.org/kmines/
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : A Minesweeper game.
description: |
    KMines is a classic Minesweeper game. The idea is to uncover all the squares without blowing up any mines. When a mine is blown up, the game is over.
builddeps  :
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-ktextwidgets-devel
    - kf6-kwidgetsaddons-devel
    - kf6-kxmlgui-devel
    - libkdegames-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rfv $installdir/usr/share/doc
