# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-hatch-vcs
version    : 0.5.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/h/hatch_vcs/hatch_vcs-0.5.0.tar.gz : 0395fa126940340215090c344a2bf4e2a77bcbe7daab16f41b37b98c95809ff9
homepage   : https://github.com/ofek/hatch-vcs
license    : MIT
component  : programming.python
summary    : Hatch plugin for versioning with your preferred VCS
description: |
    This provides a plugin for Hatch that uses your preferred version control system (like Git) to determine project versions.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
checkdeps  :
    - git
    - python-pytest
    - python-setuptools-scm
rundeps    :
    - python-hatchling
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
