# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : expat
version    : 2.8.5
release    : 43
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_8_5/expat-2.8.5.tar.xz : 1e727b8933ec51a77a9a9d9afcf8e688bce45d907c13e36ab7393fe36e703182
homepage   : https://libexpat.github.io/
license    : MIT
component  :
    - system.base
    - devel : system.devel
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
emul32     : true
setup      : |
    %configure --disable-static
build      : |
    %make
profile    : |
    %make check
install    : |
    %make_install
    %install_license COPYING
check      : |
    %make check
