# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : assimp
version    : 6.0.5
release    : 8
source     :
    - https://github.com/assimp/assimp/archive/refs/tags/v6.0.5.tar.gz : edf3749559c2b7d1f758ffb66fc5bec62186221e623b7f2e8969f17ee46ecb6f
homepage   : https://www.assimp.org/
license    : BSD-3-Clause
component  : programming
summary    : Open Asset Import Library
description: |
    A library to import and export various 3d-model-formats including scene-post-processing to generate missing render data.
setup      : |
    %cmake -B build \
        -DASSIMP_BUILD_ZLIB=OFF \
        -DASSIMP_WARNINGS_AS_ERRORS=OFF
build      : |
    %make -C build
install    : |
    %make_install -C build
    %install_license LICENSE
