# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : yubico-piv-tool
version    : 2.7.3
release    : 5
source     :
    - https://github.com/Yubico/yubico-piv-tool/archive/refs/tags/yubico-piv-tool-2.7.3.tar.gz : 57d041ea512fba36dedf27107e053ac6d09faa6c3d3ec8ae27eb0f490708b1ac
homepage   : https://developers.yubico.com/yubico-piv-tool
license    : BSD-2-Clause
component  : security
summary    : Command line tool for the YubiKey PIV application
description: |
    The Yubico PIV tool is used for interacting with the Personal Identity Verification (PIV) application on a YubiKey. With it you may generate keys on the device, importing keys and certificates, and create certificate requests, and other operations. A shared library and a command-line tool is included.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libpcsclite)
    - gengetopt
    - help2man
setup      : |
    %cmake_ninja -DBUILD_STATIC_LIB=OFF
build      : |
    %cmake_build
install    : |
    %cmake_install

    # Ensure p11tool from libgnutls-utils understands libykcs11 OOTB.
    %install_exe $pkgfiles/ykcs11.module $installdir/usr/share/defaults/pkcs11/modules/yubico-piv.module
check      : |
    %cmake_test
    %install_license COPYING
