# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-gpgme
version    : 2.0.0
release    : 1
source     :
    - git|https://github.com/gpg/gpgmepy.git : gpgmepy-2.0.0
homepage   : https://www.gnupg.org/
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python bindings for GPGME
description: |
  Python bindings for GPGME
builddeps  :
    - pkgconfig(gpgme)
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
    - swig
rundeps    :
    - gpgme
setup      : |
    %patch -p1 -i ${pkgfiles}/python-gpgme-2.0.0-fix-test.patch

    sed -e 's|, \"swig\"||' -i pyproject.toml
    %reconfigure
    mv src gpg
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    export TESTFLAGS="--python-libdir=${PWD}/$(ls -d build/lib*)"
    %make -C tests check
