# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libbpf
version    : 1.7.0
release    : 9
source     :
    - https://github.com/libbpf/libbpf/archive/refs/tags/v1.7.0.tar.gz : 7ab5feffbf78557f626f2e3e3204788528394494715a30fc2070fcddc2051b7b
homepage   : https://github.com/libbpf/libbpf
license    :
    - BSD-2-Clause
    - LGPL-2.1-only
component  : programming.library
summary    : Library for loading eBPF programs
description: |
    Library for loading eBPF programs and reading and manipulating eBPF objects from user-space
builddeps  :
    - pkgconfig(libelf)
clang      : true
optimize   :
    - speed
    - thin-lto
build      : |
    %make -C src
install    : |
    %make_install -C src install_headers
    %install_license LICENSE.LGPL-2.1 LICENSE.BSD-2-Clause
    rm $installdir/usr/lib64/libbpf.a
