# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : cmocka
version    : 2.0.2
release    : 5
source     :
    - https://cmocka.org/files/2.0/cmocka-2.0.2.tar.xz : 39f92f366bdf3f1a02af4da75b4a5c52df6c9f7e736c7d65de13283f9f0ef416
homepage   : https://cmocka.org/
license    : Apache-2.0
component  : programming.library
summary    : An elegant unit testing framework for C with support for mock objects.
description: |
    An elegant unit testing framework for C with support for mock objects.
setup      : |
    %cmake_ninja \
        -DUNIT_TESTING=ON
build      : |
    %cmake_build
install    : |
    %cmake_install
    %install_license LICENSE
check      : |
    %cmake_test
