# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : bash-completion
version    : 2.17.0
release    : 28
source     :
    - https://github.com/scop/bash-completion/archive/refs/tags/2.17.0.tar.gz : 529374d730caf3c8911438c5d13663fbb6134d01253012fcb865f9d68744d276
homepage   : https://github.com/scop/bash-completion
license    : GPL-2.0-or-later
component  :
    - system.base
    - devel : system.devel
summary    : Programmable Completion for Bash
description: |
    bash-completion is a collection of shell functions that take advantage
    of the programmable completion feature of Bash 2.04 and later
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 -i $pkgfiles/0001-Use-a-stateless-configuration.patch
    %reconfigure
build      : |
    %make
install    : |
    install -dDm00755 $installdir/usr/share/bash-completion/completions
    %make_install

    %install_license COPYING
    # provided by libsecret
    rm -fv $installdir/usr/share/bash-completion/completions/secret-tool
