# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mandown
version    : 1.1.1
release    : 3
source     :
    - https://gitlab.com/kornelski/mandown/-/archive/v1.1.1/mandown-v1.1.1.tar.gz : 
        0d732aeab3b18e511dbb8bc9b9e93da10c6209f3d93553eba1c1717514a7a4af
homepage   : https://gitlab.com/kornelski/mandown
license    : Apache-2.0
component  : programming.tools
summary    : Create man pages from Markdown markup
description: |
    Create man pages from markdown markup.
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
    %install_license LICENSE
