# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : upower
version    : 1.91.4
release    : 33
source     :
    - https://gitlab.freedesktop.org/upower/upower/-/archive/v1.91.4/upower-v1.91.4.tar.gz : 447dc57365821a8566ace9c9c6c3028c86708f1688c5dadb4dfe9f6b6b117b18
homepage   : https://upower.freedesktop.org/
license    :
    - GPL-2.0-or-later
component  : desktop.core
summary    : UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
description: |
    UPower is an abstraction for enumerating power devices, listening to device events and querying history and statistics.
builddeps  :
    - pkgconfig(gudev-1.0)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libusb-1.0)
    - docbook-xml
    - python-packaging # Check
    - python3-dbus # Check
setup      : |
    %apply_patches
    %meson_configure -Didevice=enabled \
                     -Dgtk-doc=false \
                     -Dman=false \
                     -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING

    %install_file -t ${installdir}/%libdir%/systemd/system-preset/ ${pkgfiles}/20-upower.preset

    # Stateless (this data directory is created by the systemd service unit)
    rmdir -v ${installdir}/var/lib/upower \
             ${installdir}/var/lib \
             ${installdir}/var/
check      : |
    %ninja_check
