# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : utfcpp
version    : 4.1.0
release    : 8
source     :
    - https://github.com/nemtrif/utfcpp/archive/refs/tags/v4.1.0.tar.gz : 9a45cbeefacf512879971eaf57fe52133b73a0152d5354f3adeaf8d103cff0f3
license    : BSL-1.0
component  : programming.library
homepage   : https://github.com/nemtrif/utfcpp
summary    : UTF-8 with C++ in a Portable Way.
description: |
    UTF-8 with C++ in a Portable Way.
patterns   :
    - /* # it's a header-only library
setup      : |
    %cmake_ninja -DUTF8_SAMPLES=OFF -DUTF8_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
