# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libdivide
version    : 5.3.0
release    : 1
source     :
    - https://github.com/ridiculousfish/libdivide/archive/refs/tags/v5.3.0.tar.gz : de3933bf2fd21300d99fcc6460a8a4a1343ae90b965d6893f044c350bac68c6e
homepage   : https://libdivide.com
license    :
    - Zlib
    - BSL-1.0
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
setup      : |
    %cmake_ninja -L \
      -DLIBDIVIDE_BUILD_TESTS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
patterns   : /*
