# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : clj-kondo
version    : 2026.08.04
release    : 11
source     :
    - https://github.com/clj-kondo/clj-kondo/archive/refs/tags/v2026.08.04.tar.gz : 65506931c5c4deadcb276d62b05945a8fef13fd6e6a4421b7829ee5fb44fe541
homepage   : https://github.com/clj-kondo/clj-kondo/
license    : EPL-1.0
component  : programming.tools
networking : true
summary    : Clojure(script) and EDN linting
description: |
    clj-kondo performs static analysis on Clojure, ClojureScript and EDN, without the need of a running REPL. It informs you about potential errors while you are typing.
builddeps  :
    - graalvm
    - leiningen
environment: |
    export GRAALVM_HOME=/usr/share/graalvm/
    export JAVA_HOME=/usr/share/graalvm/
    export JAVA_CMD=/usr/share/graalvm/bin/java
build      : |
    # make lein use a temporary location for deps
    sed -i '7 i :local-repo "/tmp/.m2/repo"' project.clj
    lein uberjar
    ./script/compile

install    : |
    %install_bin clj-kondo
    %install_license LICENSE
