# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-specio-exporter
version    : '0.53'
release    : 9
source     :
    - https://www.cpan.org/authors/id/D/DR/DROLSKY/Specio-0.53.tar.gz : 0d0eecfb9e89bd0f5f710fac42e1200a882d513a862f98497eaef5927ac6c183
homepage   : https://metacpan.org/pod/Specio::Exporter
license    : Artistic-2.0
component  : programming.perl
summary    : Base class for type libraries
description: |
    Base class for type libraries
builddeps  :
    - perl-clone
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-module-implementation
    - perl-module-runtime
    - perl-mro-compat
    - perl-role-tiny
    - perl-sub-quote
    - perl-test-fatal
    - perl-try-tiny
checkdeps  :
    - perl-test-needs
rundeps    :
    - perl-clone
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-module-implementation
    - perl-module-runtime
    - perl-mro-compat
    - perl-role-tiny
    - perl-sub-quote
    - perl-test-fatal
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
check      : |
    %perl_build test
patterns   : /*
