# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kwayland-integration
version    : 6.6.5
release    : 138
source     :
    - https://download.kde.org/stable/plasma/6.6.5/kwayland-integration-6.6.5.tar.xz : 2720764c73963fe06bd78e2eca329eba61fb625dff6d3dcf4a68ec167766ce6e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(KF5WaylandClient)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
    - kwindowsystem-devel
    - plasma-wayland-protocols-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
