# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xdpyinfo
version    : 1.4.0
release    : 12
source     :
    - https://www.x.org/releases/individual/app/xdpyinfo-1.4.0.tar.gz : bbbe0b75935285fbb4c795b4f1d3d4f9c91cd4c18f4b6fd7107c648094172f7b
license    : GPL-3.0
component  : xorg.apps
homepage   : https://www.x.org/
summary    : Display information utility for X
description: |
    Xdpyinfo is a utility for displaying information about an X server.  It is used to examine the capabilities of a server, the predefined values for various parameters used in communicating between clients and the server, and the different types of screens and visuals that are available
builddeps  :
    - pkgconfig(dmx)
    - pkgconfig(x11-xcb)
    - pkgconfig(xcomposite)
    - pkgconfig(xinerama)
    - pkgconfig(xproto)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - pkgconfig(xxf86dga)
    - pkgconfig(xxf86vm)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
