name       : oxygen-sounds
version    : 6.3.1
release    : 23
source     :
    - https://download.kde.org/stable/plasma/6.3.1/oxygen-sounds-6.3.1.tar.xz : fef11b91cb2dc330023c8cea54d520fc017bb2ba46cdf36f5192887e892ef0bf
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.theme
summary    : The Oxygen Sound Theme
description: The Oxygen Sound Theme
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
