# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : oxygen-sounds
version    : 6.7.2
release    : 47
source     :
    - https://download.kde.org/stable/plasma/6.7.2/oxygen-sounds-6.7.2.tar.xz : 441cccd2831e9e152c516ec3cb46878c87278bece1b68a875479151e81ed98d7
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-2-Clause
    - CC0-1.0
    - CC-BY-3.0
    - LGPL-3.0-or-later
component  : desktop.theme
summary    : The Oxygen Sound Theme
description: The Oxygen Sound Theme
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
