# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : docker
version    : 29.5.1
release    : 75
source     :
    - https://github.com/docker/cli/archive/refs/tags/v29.5.1.tar.gz : de3cdd74a66f4cfe843983e4ca8d2133cf5eecc8ad8b5450cec0b7ccd59f921d
homepage   : https://www.docker.com
license    : Apache-2.0
component  : virt
summary    : The open-source application container engine
description: |
    The open-source application container engine. This contains the docker cli.

    Docker is an open source project to pack, ship and run any application as a lightweight container.

    Docker containers are both hardware-agnostic and platform-agnostic. This means they can run anywhere, from your laptop to the largest cloud compute instance and everything in between - and they don't require you to use a particular language, framework or packaging system. This makes them great building blocks for deploying and scaling web apps, databases, and backend services without depending on a particular stack or provider.
strip      : false
networking : true
builddeps  :
    - git
    - go-md2man
    - golang
rundeps    :
    - docker-buildx
    - moby
environment: |
    export GOPATH="$workdir/src/github.com/docker/cli"
    export GO111MODULE=auto
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
    export DISABLE_WARN_OUTSIDE_CONTAINER=1
    export VERSION="$version"
    export PLATFORM="Docker Engine - Community"
setup      : |
    mkdir -p src/github.com/docker/
    ln -s ${PWD} src/github.com/docker/cli
build      : |
    cd src/github.com/docker/cli
    export GITCOMMIT="$(git ls-remote https://github.com/docker/cli.git refs/tags/v$version^{} | awk '{print $1}')"
    export DOCKER_GITCOMMIT=$GITCOMMIT

    %make dynbinary
    make manpages
install    : |
    # Install docker client
    install -Dm00755 build/docker-linux-amd64 ${installdir}/usr/bin/docker
    %install_license LICENSE

    install -Dm00644 man/man1/*.1 -t ${installdir}/usr/share/man/man1
    install -Dm00644 man/man5/*.5 -t ${installdir}/usr/share/man/man5

    # Install completions
    install -Dm00644 contrib/completion/bash/docker ${installdir}/usr/share/bash-completion/completions/docker
    install -Dm00644 contrib/completion/zsh/_docker ${installdir}/usr/share/zsh/site-functions/_docker
    install -Dm00644 contrib/completion/fish/docker.fish ${installdir}/usr/share/fish/vendor_completions.d/docker.fish

    # Install nanorc
    install -Dm00644 ${pkgfiles}/Dockerfile.nanorc -t ${installdir}/usr/share/nano/
