# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-aiohttp
version    : 3.14.1
release    : 27
source     :
    - https://files.pythonhosted.org/packages/source/a/aiohttp/aiohttp-3.14.1.tar.gz : 307f2cff90a764d329e77040603fa032db89c5c24fdad50c4c15334cba744035
homepage   : https://docs.aiohttp.org/
license    : Apache-2.0
component  : programming.python
summary    : Asynchronous HTTP client/server framework for asyncio and Python
description: |
    Asynchronous HTTP client/server framework for asyncio and Python
builddeps  :
    - cython
    - python-build
    - python-installer
    - python-packaging
    - python-pkgconfig
    - python-setuptools
    - python-wheel
checkdeps  :
    - python-aiohappyeyeballs
    - python-aiosignal
    - python-attrs
    - python-coverage
    - python-freezegun
    - python-frozenlist
    - python-propcache
    - python-pytest
    - python-pytest-asyncio
    - python-pytest-mock
    - python-pytest-timeout
    - python-yarl
rundeps    :
    - python-aiohappyeyeballs
    - python-aiosignal
    - python-attrs
    - python-frozenlist
    - python-propcache
    - python-yarl
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    export PYTEST_ADDOPTS="-o asyncio_default_fixture_loop_scope=function -W ignore::pytest.PytestDeprecationWarning"
    %python3_test pytest -m "not dev_mode and not autobahn and not internal and not network" \
        --ignore=tests/test_circular_imports.py \
        --deselect tests/test_connector.py::test_tcp_connector_ssl_shutdown_timeout_passed_to_create_connection \
        --deselect tests/test_connector.py::test_tcp_connector_ssl_shutdown_timeout_zero_not_passed \
        --deselect tests/test_connector.py::test_tcp_connector_ssl_shutdown_timeout_nonzero_passed \
        --deselect tests/test_http_parser.py::TestDeflateBuffer::test_feed_eof_no_err_brotli \
        --deselect tests/test_http_parser.py::TestDeflateBuffer::test_feed_eof_no_err_zstandard \
        --deselect tests/test_web_urldispatcher.py::test_static_directory_without_read_permission \
        --deselect tests/test_web_urldispatcher.py::test_static_file_without_read_permission \
        -o asyncio_default_fixture_loop_scope=function \
        -W ignore::pytest.PytestDeprecationWarning
