# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : chezmoi
version    : 2.70.4
release    : 24
source     :
    - https://github.com/twpayne/chezmoi/archive/refs/tags/v2.70.4.tar.gz : a184d87b2891e8ec5645d4a28a0e2f78c1a4e7738ad64fdfe07e8f7ce7782d59
homepage   : https://www.chezmoi.io
license    : MIT
component  : programming.tools
summary    : chezmoi helps you manage your personal configuration files across multiple machines
description: |
    chezmoi helps you manage your personal configuration files across multiple machines
networking : true
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
    %install_license LICENSE
