# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-autobahn
version    : 25.12.2
release    : 16
source     :
    - https://github.com/crossbario/autobahn-python/archive/refs/tags/v25.12.2.tar.gz : 4ad225a288c3115b8c577e442c329600eb412c16973a716c72dc3419633cd4d4
homepage   : https://github.com/crossbario/autobahn-python
license    : MIT
component  : programming.python
summary    : Real-time framework for Web, Mobile & Internet of Things
description: |
    Autobahn|Python is a subproject of Autobahn and provides open-source implementations of "The WebSocket Protocol" and "The Web Application Messaging Protocol (WAMP)", for Python 3.7+ and running on Twisted and asyncio.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-cffi
    - python-hatchling
    - python-installer
    - python-setuptools
    - python-twisted
    - python-txaio
rundeps    :
    - python-twisted
    - python-txaio
setup      : |
    %python3_setup
install    : |
    %python3_install
