# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libgit2
version    : 1.9.3
release    : 40
source     :
    - https://github.com/libgit2/libgit2/archive/refs/tags/v1.9.3.tar.gz : d532172d7ab24d2a25944e2434212d63ee85f3650e97b5f7579e7f201a78ad64
homepage   : https://libgit2.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods provided as a linkable library with a solid API, allowing to build Git functionality into your application.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
rundeps    :
    - devel :
        - libssh2-devel
setup      : |
    %cmake_ninja \
                 -DREGEX_BACKEND=pcre2 \
                 -DUSE_SSH:BOOL=ON \
                 -DUSE_THREADS:BOOL=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
