# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-sphinx-pytest
version    : 0.3.0
release    : 4
source     :
    - https://pypi.debian.net/sphinx_pytest/sphinx_pytest-0.3.0.tar.gz : 141a3d6b6cd8616ded72a949a2e7ba8b95e811e58f1118fa1ddeb8c61c3b6364
homepage   : https://github.com/chrisjsewell/sphinx-pytest
license    : MIT
component  : programming.python
summary    : Helpful pytest fixtures for sphinx extensions
description: |
    Helpful pytest fixtures for sphinx extensions
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
checkdeps  :
    - python-defusedxml
    - python-docutils
    - python-pytest
    - python-sphinx
rundeps    :
    - python-pytest
    - python-sphinx
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
