# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : paraview
version    : 6.1.0
release    : 46
source     :
    - https://www.paraview.org/files/v6.1/ParaView-v6.1.0.tar.gz : bcb9796a6c9355742cf9efed49b7e36f03cbdee24ece00458e6616c1747ea51b
homepage   : https://www.paraview.org/
license    : BSD-3-Clause
component  : office.scientific
summary    : Data analysis and visualization
description: |
    ParaView is an open-source, multi-platform data analysis and visualization application. ParaView users can quickly build visualizations to analyze their data using qualitative and quantitative techniques. The data exploration can be done interactively in 3D or programmatically using ParaView’s batch processing capabilities.
    ParaView was developed to analyze extremely large datasets using distributed memory computing resources. It can be run on supercomputers to analyze datasets of exascale size as well as on laptops for smaller data.
clang      : true
libsplit   : false
builddeps  :
    - pkgconfig(CLI11)
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Help)
    - pkgconfig(Qt6Svg)
    - pkgconfig(eigen3)
    - pkgconfig(fmt)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(hdf5)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libtiff-4)
    - pkgconfig(netcdf)
    - pkgconfig(nlohmann_json)
    - pkgconfig(proj)
    - pkgconfig(protobuf)
    - pkgconfig(pugixml)
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
    - pkgconfig(theora)
    - pkgconfig(xcursor)
    - VTK-devel
    - cgns-devel
    - double-conversion-devel
    - exprtk
    - fast-float
    - gl2ps-devel
    - libharu-devel
    - utfcpp
    - verdict-devel
setup      : |
    cmake_options=(
        -DCMAKE_INSTALL_LICENSEDIR=share/licenses/paraview
        -DCMAKE_CXX_STANDARD=17
        # RPATH is needed for loading plugins
        -DCMAKE_SKIP_INSTALL_RPATH=OFF
        -DPARAVIEW_ENABLE_GDAL=ON
        -DPARAVIEW_ENABLE_OPENVDB=ON
        -DPARAVIEW_ENABLE_PDAL=ON
        -DPARAVIEW_USE_MPI=ON
        -DPARAVIEW_USE_PYTHON=ON
        -DPARAVIEW_VERSIONED_INSTALL=OFF
        -DPARAVIEW_BUILD_WITH_EXTERNAL=ON
        -DPARAVIEW_USE_EXTERNAL_VTK=ON
        # workaround for https://gitlab.kitware.com/paraview/paraview/-/work_items/23235
        # (should be fixed in paraview 6.1.1)
        -DCMAKE_POLICY_DEFAULT_CMP0076=NEW
        -Wno-dev
    )

    %cmake_ninja "${cmake_options[@]}"
build      : |
    # Warning the build takes ~1.5GB RAM per Core for building
    %ninja_build
install    : |
    %ninja_install
