# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : zulip-desktop
version    : 5.12.3
release    : 3
source     :
    - https://github.com/zulip/zulip-desktop/archive/refs/tags/v5.12.3.tar.gz : f9da4a31973ca8efb53ddb3dc3ab94b70238c0bc7a922e830279daaf90c3676f
homepage   : https://zulip.com/
license    : Apache-2.0
component  : network.im
summary    : Zulip Desktop Client for Linux
description: |
    Zulip is an organized team chat app designed for live and asynchronous conversations. It combines the immediacy of real-time chat with an email-style threading model.
networking : true
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - pnpm
    - python3
setup      : |
    %patch -p1 -i ${pkgfiles}/0001-Disable-auto-update.patch
    sed -i 's/"electron-vite": "^5.0.0",/"electron-vite": "^6.0.0-beta.1",/' package.json
    pnpm install
build      : |
    pnpm run pack
install    : |
    zulip_installdir=${installdir}/usr/share/zulip
    install -dm00755 ${zulip_installdir}
    cp -a dist/linux-unpacked/. ${zulip_installdir}/

    install -Dm00755 ${pkgfiles}/zulip.sh ${installdir}/usr/bin/zulip
    install -Dm00644 ${pkgfiles}/org.zulip.Zulip.desktop -t ${installdir}/usr/share/applications
    install -Dm00644 ${pkgfiles}/org.zulip.Zulip.metainfo.xml -t ${installdir}/usr/share/metainfo
    install -Dm00644 build/zulip.png ${installdir}/usr/share/icons/hicolor/512x512/apps/org.zulip.Zulip.png

    %install_license LICENSE
