# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : git-cola
version    : 4.18.2
release    : 51
source     :
    - https://github.com/git-cola/git-cola/archive/refs/tags/v4.18.2.tar.gz : 31a69fbd4235acb36f604f0eba379de0cb3f808e64e64996787a0c2c291ffe59
homepage   : https://git-cola.github.io
license    : GPL-2.0-or-later
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    git-cola is a powerful Git GUI with a slick and intuitive user interface.
networking : true
builddeps  :
    - pkgconfig(python3)
    - git
    # pip TODO 3.14
    - python-qtpy
    - python3-qt5
rundeps    :
    - git
    - meld
    - python-polib
    - python-qtpy
    - python3-qt5
build      : |
    %make
install    : |
    %make_install prefix=/usr PIP=pip3

    # No, you will not handle every single folder I want to open.
    rm $installdir/usr/share/applications/git-cola-folder-handler.desktop
