# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : wireshark
version    : 4.6.5
release    : 103
source     :
    - https://gitlab.com/wireshark/wireshark/-/archive/v4.6.5/wireshark-v4.6.5.tar.gz : b4d5c560a679c25d12e0087ba67cd1494853f8d8b912df99e22645c7bf3dbd9e
homepage   : https://www.wireshark.org/
license    :
    - GPL-2.0-or-later
    - BSD-2-Clause
    - BSD-3-Clause
component  : network.util
libsplit   : false
summary    : Wireshark is the world's foremost network protocol analyzer.
description: |
    Wireshark is the world's foremost network protocol analyzer. It lets you see what's happening on your network at a microscopic level.
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Help)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Svg)
    - pkgconfig(gnutls)
    - pkgconfig(krb5)
    - pkgconfig(libbrotlicommon)
    - pkgconfig(libcares)
    - pkgconfig(libgcrypt)
    - pkgconfig(liblz4)
    - pkgconfig(libmaxminddb)
    - pkgconfig(libnghttp2)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcap)
    - pkgconfig(libssh)
    - pkgconfig(libzstd)
    - pkgconfig(lua-5.1)
    - pkgconfig(minizip)
    - pkgconfig(opus)
    - pkgconfig(sbc)
    - pkgconfig(snappy)
    - pkgconfig(speexdsp)
    - asciidoctor
rundeps    :
    - qt6-multimedia
    - qt6-svg
setup      : |
    %cmake_ninja -D BUILD_tfshark=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING

    install -Dm00644 $pkgfiles/wireshark.sysusers $installdir/%libdir%/sysusers.d/wireshark.conf
    chmod 750  $installdir/usr/bin/dumpcap
    chown :150 $installdir/usr/bin/dumpcap

    setcap 'CAP_NET_RAW=ep CAP_NET_ADMIN=ep' $installdir/usr/bin/dumpcap
