# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kfind
version    : 26.08.1
release    : 60
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/kfind-26.08.1.tar.xz : 946df18e730a5b97c421816163533b3511aae361d69e4e9856dc5b9f549be8af
homepage   : https://www.kde.org/applications/utilities/kfind
license    : GPL-2.0-or-later
component  : system.utils
summary    : Find Files/Folders
description: |
    KFind allows you to search for directories and files
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - kf6-karchive-devel
    - kf6-kdoctools-devel
    - kf6-kfilemetadata-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*

    #remove HTML docs
    rm -rfv $installdir/usr/share/doc
