# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kfind
version    : 26.04.1
release    : 57
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/kfind-26.04.1.tar.xz : f26fccc4652e593dcc70d688f042a4975193b955362ff7c2144208cb1130980d
homepage   : https://www.kde.org/applications/utilities/kfind
license    : GPL-2.0-or-later
component  : system.utils
summary    : Find Files/Folders
description: |
    KFind allows you to search for directories and files
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - kf6-karchive-devel
    - kf6-kdoctools-devel
    - kf6-kfilemetadata-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove HTML docs
    rm -rfv $installdir/usr/share/doc
