# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-xmltodict
version    : 1.0.4
release    : 10
source     :
    - https://pypi.python.org/packages/source/x/xmltodict/xmltodict-1.0.4.tar.gz : 6d94c9f834dd9e44514162799d344d815a3a4faec913717a9ecbfa5be1bb8e61
homepage   : https://github.com/martinblech/xmltodict
license    : MIT
component  : programming.python
summary    : Python module that makes working with XML feel like you are working with JSON
description: |
    xmltodict is a python module that makes working with XML feel like you are working with JSON
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
