# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kcalutils
version    : 26.08.2
release    : 101
source     :
    - https://download.kde.org/stable/release-service/26.08.2/src/kcalutils-26.08.2.tar.xz : 5e5ca87267867f203a5ffd87c88e1ab97884b66f81ff4e6ce8d0d6c087a0c450
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - MIT
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - pkgconfig(KF6CalendarCore)
    - kf6-kiconthemes-devel
    - kf6-ktexttemplate-devel
    - kidentitymanagement-devel
rundeps    :
    - devel :
        - kf6-kcalendarcore-devel
        - kf6-kconfig-devel
        - kf6-kcoreaddons-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
