# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kldap
version    : 26.04.1
release    : 100
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/kldap-26.04.1.tar.xz : 4a63ce62cbb12d9c0dfc7502f1f83cf79296e2ee6785ba283e7872c527c3dc59
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Allows LDAP accessing with a convenient Qt style C++ API
description: |
    Allows LDAP accessing with a convenient Qt style C++ API.
builddeps  :
    - pkgconfig(ldap)
    - pkgconfig(libsasl2)
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - qtkeychain-qt6-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rfv $installdir/usr/share/doc
