# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : convmv
version    : '2.06'
release    : 3
source     :
    - https://www.j3e.de/linux/convmv/convmv-2.06.tar.gz : a37192e266742e7fe33ec19a3be49aea7fd4d066887863a6e193fa345bf2e592
homepage   : https://www.j3e.de/linux/convmv/
license    : GPL-2.0-or-later
component  : system.utils
summary    : converts filenames from one encoding to another
description: |
    converts filenames from one encoding to another
builddeps  :
    - gcc
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
    %install_license GPL2
