# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-http-cookies
version    : '6.12'
release    : 12
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Cookies-6.12.tar.gz : 4e460c4bae76285bfc726f641349402fc9038fcd9ca0f33346bec036d73876b8
homepage   : https://metacpan.org/pod/HTTP::Cookies
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : HTTP::Cookies - HTTP cookie jars
description: |
    This class is for objects that represent a "cookie jar" -- that is, a database of all the HTTP cookies that a given LWP::UserAgent object knows about.
builddeps  :
    - perl-clone
    - perl-http-date
    - perl-http-message
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
check      : |
    %perl_build test
patterns   : /*