# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-gphoto2
version    : 2.6.4
release    : 25
source     :
    - https://github.com/jim-easterbrook/python-gphoto2/archive/refs/tags/v2.6.4.tar.gz : 890280dfaa964b58095dfc874fea697791a85ad80635de8cdf48a1b55fb91e21
homepage   : https://github.com/jim-easterbrook/python-gphoto2
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Python interface to libgphoto2
description: |
    python-gphoto2 is a comprehensive Python interface (or binding) to libgphoto2. It is built using SWIG to automatically generate the interface code. This gives direct access to nearly all the libgphoto2 functions, but sometimes in a rather un-Pythonic manner.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
