# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kio-gdrive
version    : 26.08.1
release    : 83
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/kio-gdrive-26.08.1.tar.xz : ce1a91277edf256e9fc6a90fbc486dabd951b329c81d1c9328b0fa3bf06474c8
homepage   : https://apps.kde.org/kio_gdrive/
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - GPL-3.0-or-later
component  : desktop.kde
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - kaccounts-integration-devel
    - kf6-kcontacts-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-purpose-devel
    - libkgapi-devel
    - qt6-base-private-devel
rundeps    :
    - kaccounts-providers
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
