# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : runc
version    : 1.5.0
release    : 41
source     :
    - https://github.com/opencontainers/runc/archive/refs/tags/v1.5.0.tar.gz : 1bcd55af6081cf080557b148d906f64e6e4ca886d8345fe4b5510a90b52815d1
homepage   : https://runc.io/
license    : Apache-2.0
component  : virt
summary    : CLI tool for managing OCI compliant containers
description: |
    CLI tool for managing OCI compliant containers
builddeps  :
    - pkgconfig(libseccomp)
    - pkgconfig(pathrs)
    - git
    - go-md2man
    - golang
networking : true
setup      : |
    mkdir -p src/github.com/opencontainers/runc
    find ./* -prune ! -name src -exec mv {} src/github.com/opencontainers/runc/ \;
environment: |
    export GOPATH="`pwd`"
    export RUNC_BUILDTAGS='seccomp apparmor'
    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_CFLAGS="${CFLAGS}"
    export CGO_CXXFLAGS="${CXXFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"
build      : |
    export COMMIT="$(git ls-remote https://github.com/opencontainers/runc.git refs/tags/v$version^{} | awk '{print $1}')"
    cd src/github.com/opencontainers/runc
    %make runc man
install    : |
    cd src/github.com/opencontainers/runc/
    install -Dm00755 runc ${installdir}/usr/bin/runc
    %install_license LICENSE

    install -Dm00644 contrib/completions/bash/runc ${installdir}/usr/share/bash-completion/completions/runc

    install -d ${installdir}/usr/share/man/man8
    install -m644 man/man8/*.8 ${installdir}/usr/share/man/man8
