# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libhunspell
version    : 1.7.3
release    : 12
source     :
    - https://github.com/hunspell/hunspell/releases/download/v1.7.3/hunspell-1.7.3.tar.gz : 433274dac0619cb00c2e18b43a3dd3a9d50da5b5613fa9b5c21781e35dd76bc1
homepage   : https://hunspell.github.io/
license    :
    - MPL-1.1
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : office
summary    : Hunspell spelling checker
description: |
    Hunspell is a spell checker and morphological analyzer library and program designed for languages with rich morphology and complex word compounding or character encoding.
setup      : |
    %configure \
        --disable-static \
        --with-ui \
        --with-readline
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING*
    # Fix packages that put `-lhunspell` in their build systems without using the pkgconfig file
    pushd $installdir/%libdir%
    ln -s libhunspell-?.?.so libhunspell.so
    popd
check      : |
    # 2 tests failed on the server
    %make check || :
