# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kcoreaddons
version    : 6.24.0
release    : 35
source     :
    - https://download.kde.org/stable/frameworks/6.24/kcoreaddons-6.24.0.tar.xz : bc2fb0d94de859f6e6bc7413620584f072ace1487e302c65b3398d7c6b0eff7c
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Qt addon library with a collection of non-GUI utilities.
description: |
    Qt addon library with a collection of non-GUI utilities.
optimize   : thin-lto
clang      : true
builddeps  :
    - pkgconfig(Qt6Designer)
    - extra-cmake-modules
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-tools-devel
setup      : |
    %cmake_kf6 -DBUILD_PYTHON_BINDINGS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
