# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tmux
version    : 3.7c
release    : 35
source     :
    - https://github.com/tmux/tmux/archive/refs/tags/3.7c.tar.gz : 5e7b0f533b66e5633e2b72a9d483f9534a343ab7011eb2621b6309dfba553daa
homepage   : https://github.com/tmux/tmux/wiki
license    : 0BSD
component  : system.utils
summary    : terminal multiplexer
description: |
    tmux is a "terminal multiplexer", it enables a number of terminals (or windows)
    to be accessed and controlled from a single terminal. tmux is intended to be a
    simple, modern, BSD-licensed alternative to programs such as GNU screen.
builddeps  :
    - pkgconfig(libevent)
setup      : |
    %reconfigure \
        --enable-sixel
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING logo/LICENSE
