# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tmux
version    : '3.7'
release    : 32
source     :
    - https://github.com/tmux/tmux/archive/refs/tags/3.7.tar.gz : 123b9ed37c7ee957327a483024ea6ae0e6032348c02680be2ac91b9350e62d36
homepage   : https://github.com/tmux/tmux/wiki
license    : 0BSD
component  : system.utils
summary    : terminal multiplexer
description: |
    tmux is a "terminal multiplexer", it enables a number of terminals (or windows)
    to be accessed and controlled from a single terminal. tmux is intended to be a
    simple, modern, BSD-licensed alternative to programs such as GNU screen.
builddeps  :
    - pkgconfig(libevent)
setup      : |
    %reconfigure --enable-sixel
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING logo/LICENSE
