# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ntfs-3g
version    : 2026.9.18
release    : 23
source     :
    - https://github.com/tuxera/ntfs-3g/archive/refs/tags/2026.9.18.tar.gz : 764b1cde7e90c40a8e32fb016fbea47422d9e23aa6ff79740426e994d316ddba
homepage   : https://github.com/tuxera/ntfs-3g/wiki
license    : GPL-2.0-or-later
component  : system.utils
summary    : Open source, driver for Windows NTFS file system
description: |
    Open source, driver for Windows NTFS file system. This can mount Windows partitions so that they are writeable and allows you edit or delete Windows files from Linux.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gnutls)
    - pkgconfig(libacl)
    - pkgconfig(libattr)
setup      : |
    %patch -p1 -i ${pkgfiles}/build.patch

    %reconfigure \
        --disable-static \
        --disable-ldconfig \
        --enable-crypto \
        --enable-extras \
        --enable-posix-acls \
        --enable-xattr-mappings \
        --with-fuse=external \
        --sbin=/usr/sbin
build      : |
    %make
install    : |
    %make_install rootbindir=/usr/bin rootsbindir=/usr/sbin rootlibdir=%libdir%
    %install_license COPYING COPYING.LIB

    rmdir ${installdir}/sbin -v

    ln -srv $installdir/usr/bin/ntfs-3g $installdir/usr/sbin/mount.ntfs
