# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-sphinxygen
version    : 1.0.12
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/s/sphinxygen/sphinxygen-1.0.12.tar.gz : 4dfc9cd1c89448f1c98c59a3ec63e0c5df2dafcc631ce48de793692b244451b9
homepage   : https://pypi.org/project/sphinxygen/
license    : ISC
component  : programming.python
summary    : Sphinxygen is a Python module/script that generates Sphinx markup to describe a C API, from an XML description extracted by Doxygen.
description: |
    Sphinxygen is a Python module/script that generates Sphinx markup to describe a C API, from an XML description extracted by Doxygen.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
build      : |
    %pyproject_build
install    : |
    %pyproject_install
