# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kio-admin
version    : 26.08.2
release    : 34
source     :
    - https://download.kde.org/stable/release-service/26.08.2/src/kio-admin-26.08.2.tar.xz : f12aff98913c91e6eb6a09cafdedbea3ee2e43a6d559e8ec98d0b72b54cc32ea
homepage   : https://invent.kde.org/system/kio-admin
license    :
    - BSD-3-Clause
    - CC0-1.0
    - FSFAP
    - GPL-2.0-only
    - GPL-3.0-only
component  : desktop.kde
summary    : Manage files as administrator using the admin:// KIO protocol.
description: |
    Manage files as administrator using the admin:// KIO protocol.
builddeps  :
    - pkgconfig(polkit-qt6-1)
    - kf6-ki18n-devel
    - kf6-kio-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6 -DQT_MAJOR_VERSION=6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
