# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-sentry-sdk
version    : 2.66.1
release    : 9
source     :
    - https://pypi.debian.net/sentry-sdk/sentry_sdk-2.66.1.tar.gz : f882fb08710c5f8bfc603aafa3e901b384009a19cc3f76a572b863392ee81cdc
license    : MIT
component  : programming.python
homepage   : https://sentry.io/for/python
summary    : The official Python SDK for Sentry.io
description: |
    The official Python SDK for Sentry.io
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - python-certifi
    - python-urllib3
build      : |
    %pyproject_build
install    : |
    %pyproject_install
