# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libraw
version    : 0.22.1
release    : 22
source     :
    - https://github.com/LibRaw/LibRaw/archive/refs/tags/0.22.1.tar.gz : e676248284075605aa2697a66eeed7dc258820bd1d4988c724d29edffd726726
homepage   : https://www.libraw.org/
license    :
    - CDDL-1.0
    - LGPL-2.1-or-later
component  :
    - multimedia.library
    - utils : multimedia.graphics
summary    :
    - LibRaw is a library for reading RAW files from digital cameras
    - utils : Tools for Libraw
description:
    - LibRaw is a library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others).
    - utils : Tools for Libraw
avx2       : true
optimize   :
    - speed
builddeps  :
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - pkgconfig(libturbojpeg)
patterns   :
    - utils : /usr/bin
setup      : |
    %reconfigure --disable-static --enable-jasper
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share
