# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libkleo
version    : 26.04.2
release    : 99
source     :
    - https://download.kde.org/stable/release-service/26.04.2/src/libkleo-26.04.2.tar.xz : fa2ee37491410508db5eb05bbd2f657be081271b8e0e7183849e9657249ac49f
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-only
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : KDE PIM cryptographic library
description: |
    KDE PIM cryptographic library.
builddeps  :
    - gpgmeqt-qt6-devel
    - kf6-kcodecs-devel
    - kf6-kcolorscheme-devel
    - kf6-kcompletion-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - kf6-kitemmodels-devel
    - kf6-kwidgetsaddons-devel
    - libboost-devel
rundeps    :
    - devel :
        - gpgmeqt-qt6-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
