# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-dill
version    : 0.4.1
release    : 11
source     :
    - https://github.com/uqfoundation/dill/releases/download/0.4.1/dill-0.4.1.tar.gz : 423092df4182177d4d8ba8290c8a5b640c66ab35ec7da59ccfa00f6fa3eea5fa
homepage   : https://github.com/uqfoundation/dill
license    : BSD-3-Clause
component  : programming.python
summary    : serialize all of python
description: |
    dill extends python's pickle module for serializing and de-serializing python objects to the majority of the built-in python types. Serialization is the process of converting an object to a byte stream, and the inverse of which is converting a byte stream back to a python object hierarchy.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    export PYTHONPATH="%python3-sitepackages%:${PYTHONPATH}"
    python dill/tests/__main__.py
