# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gopass
version    : 1.17.0
release    : 44
source     :
    - https://github.com/gopasspw/gopass/archive/refs/tags/v1.17.0.tar.gz#gopass.tar.gz : ce004c82b65ffac44de2991020843828b38bb510909506f2fa0f40bec05b7c75
    - https://github.com/gopasspw/git-credential-gopass/archive/refs/tags/v1.17.0.tar.gz#git-credential-gopass.tar.gz : 2efe7cc34ad18f4e12368d24528c5b589c9d0796a606ede8154ad6a412b05ad0
    - https://github.com/gopasspw/gopass-hibp/archive/refs/tags/v1.17.0.tar.gz#gopass-hibp.tar.gz : db4ece704ea3ec62735da34967347206215674668ab8992567654dd4751940c0
    - https://github.com/gopasspw/gopass-jsonapi/archive/refs/tags/v1.17.0.tar.gz#gopass-jsonapi.tar.gz : eb8f48f23219ef4cbc16944976a42bdcd5f1e74cb892cde3bd8a5aacf451f094
    - https://github.com/gopasspw/gopass-summon-provider/archive/refs/tags/v1.17.0.tar.gz#gopass-summon-provider.tar.gz : 882a4f2eb927e3e256b109400797929560faed14e89737bde6d51f61a62c1005
homepage   : https://www.gopass.pw
license    : MIT
component  : security
networking : true
summary    : The slightly more awesome standard unix password manager for teams
description: |
    gopass is a rewrite of the pass password manager in Go with the aim of making it cross-platform and adding additional features.
builddeps  :
    - golang
rundeps    :
    - git
    - gnupg
    - xdotool
    - xsel
setup      : |
    mkdir -p integrations
    for i in git-credential-gopass gopass-{hibp,jsonapi,summon-provider}; do
        tar -x -C integrations -f $sources/$i.tar.gz
    done
build      : |
    %make
    for i in integrations/*; do
        pushd $i; go mod tidy; popd
        %make -C $i
    done
install    : |
    %make_install PREFIX=/usr
    for i in integrations/*; do
        %make_install -C $i PREFIX=/usr
    done

    # Set correct permission bits for the shell completion files
    chmod 644 $installdir/usr/share/zsh/site-functions/_gopass
    chmod 644 $installdir/usr/share/bash-completion/completions/gopass
    chmod 644 $installdir/usr/share/fish/vendor_completions.d/gopass.fish

    %install_license LICENSE
