# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : budgie-control-center
version    : 2.1.3
release    : 39
source     :
    - https://github.com/BuddiesOfBudgie/budgie-control-center/releases/download/v2.1.3/budgie-control-center-2.1.3.tar.xz : ad173a72bc8e06b9e256589593a9c2853bc46746e74076d0052af0150d14600a
homepage   : https://buddiesofbudgie.org
license    : GPL-2.0-or-later
component  : desktop.budgie
summary    : Budgie Control Center is a fork of GNOME Control Center for the Budgie 10 Series
description: |
    Budgie Control Center is a fork of GNOME Settings / GNOME Control Center with the intent of providing a simplified list of settings that are applicable to the Budgie 10 series, along with any small quality-of-life settings.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(accountsservice)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(colord-gtk)
    - pkgconfig(com_err)
    - pkgconfig(cups)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gnutls)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gsound)
    - pkgconfig(ibus-1.0)
    - pkgconfig(krb5)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libnma)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(tecla)
    - pkgconfig(smbclient)
    - pkgconfig(udisks2)
    - pkgconfig(upower-glib)
    - bluez
    - docbook-xml
    - gnome-common
rundeps    :
    - bolt # Thunderbolt support
    - cups-pk-helper
    - glib-networking
    - gnome-color-manager
    - gnome-keyring
    - sound-theme-freedesktop
    - tecla
    - wdisplays
setup      : |
    %meson_configure \
        -Ddocumentation=true \
        -Dprivileged_group=wheel
build      : |
    %meson_build
install    : |
    %meson_install
    %install_license LICENSE

    # Consistent polkit rules naming
    mv ${installdir}/usr/share/polkit-1/rules.d/budgie-control-center.rules ${installdir}/usr/share/polkit-1/rules.d/org.buddiesofbudgie.controlcenter.rules
