# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libfreexl
version    : 2.0.0
release    : 1
source     :
    - https://www.gaia-gis.it/gaia-sins/freexl-2.0.0.tar.gz : 176705f1de58ab7c1eebbf5c6de46ab76fcd8b856508dbd28f5648f7c6e1a7f0
homepage   : https://www.gaia-gis.it/fossil/freexl/index
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : programming.library
summary    : Open source library to extract valid data from within an Excel spreadsheet
description: |
    FreeXL is a simple library intended for extracting the contents and some metadata from Microsoft Excel (.xls) format files.
clang      : true
builddeps  :
    - pkgconfig(minizip)
setup      : |
    %configure \
        --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
