# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : podofo
version    : 0.10.6
release    : 19
source     :
    - https://github.com/podofo/podofo/archive/refs/tags/0.10.6.tar.gz : 276c7de843a4126c092cdf13935a2b01ec1b6415c10415fb97e04a12195c030a
homepage   : https://github.com/podofo/podofo
license    :
    - MPL-2.0
    - LGPL-2.0-or-later
component  : programming
summary    : PoDoFo is a library to work with the PDF file format
description: |
    The PoDoFo library is a free, portable C++ library which includes classes to parse PDF files and modify their contents into memory. The changes can be written back to disk easily. The parser can also be used to extract information from a PDF file (for example the parser could be used in a PDF viewer). Besides parsing PoDoFo includes also very simple classes to create your own PDF files. All classes are documented so it is easy to start writing your own application using PoDoFo.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(libidn)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lua)
setup      : |
    %cmake_ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DPODOFO_BUILD_TOOLS=True \
        -DPODOFO_HAVE_JPEG_LIB=1 \
        -DPODOFO_HAVE_PNG_LIB=1 \
        -DPODOFO_HAVE_TIFF_LIB=1
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING*
    install -dm00644 ${installdir}/usr/share/man/man1/
    cp -R man/*.1 ${installdir}/usr/share/man/man1/
check      : |
    %make test
