# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-pymad
version    : 0.11.3
release    : 1
source     :
    - https://github.com/jaqx0r/pymad/releases/download/v0.11.3/pymad-0.11.3.tar.gz : c5b9be3b625ce9257e07877b66b1f0bd8a957fb967d18cb2393a7e09cf6ce7aa
homepage   : https://spacepants.org/src/pymad
license    : GPL-2.0-or-later
component  : programming.python
summary    : A Python wrapper for the MPEG Audio Decoder (MAD) library
description: |
    A Python module that allows Python programs to use the MPEG Audio Decoder library. pymad provides a high-level API, similar to the pyogg module, which makes reading PCM data from MPEG audio streams a piece of cake.
builddeps  :
    - pkgconfig(mad)
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools-scm
checkdeps  :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
