# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-dpcontracts
version    : 0.6.0
release    : 1
source     :
    - https://pypi.io/packages/source/d/dpcontracts/dpcontracts-0.6.0.tar.gz : 6cf9df1f16beaa48523b798b41170dabf7a536a6133328731665cdb29c42234a
homepage   : https://github.com/deadpixi/contracts
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A simple implementation of contracts for Python
description: |
    A simple implementation of contracts for Python
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - python-pytest
setup      : |
    %patch -p1 -i ${pkgfiles}/0001-fixing-tox-test-of-README.patch
    %patch -p1 -i ${pkgfiles}/fix-missing-eventloop.patch
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v README.rst
