# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : activate-linux
version    : 1.2.0
release    : 4
source     :
    - https://github.com/MrGlockenspiel/activate-linux/archive/refs/tags/v1.2.0.tar.gz : 5c1ab8dc9ddfc3984398f410cd5cf6169609650659d9474b88b1d852a1c3c32b
homepage   : https://github.com/MrGlockenspiel/activate-linux
license    : GPL-3.0-only
component  : desktop
summary    : The "Activate Windows" watermark ported to Linux.
description: |
    The "Activate Windows" watermark ported to Linux with cairo in C.
builddeps  :
    - pkgconfig(cairo-xcb)
    - pkgconfig(pango)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(x11-xcb)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xt)
build      : |
    %make
install    : |
    install -Dm00755 activate-linux $installdir/usr/bin/activate-linux
    install -Dm00644 activate-linux.1 $installdir/usr/share/man/man1/activate-linux.1
    %install_license LICENSE.md
