# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tumbler
version    : 4.20.2
release    : 24
source     :
    - https://archive.xfce.org/src/xfce/tumbler/4.20/tumbler-4.20.2.tar.bz2 : aa77fd90a88b83467cd8d2b39d80e4518ba2903d2e4ca50d32d1b96996685015
homepage   : https://docs.xfce.org/xfce/tumbler/start
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.library
summary    : D-Bus service for applications to request thumbnails
description: |
    The Tumbler package contains a D-Bus thumbnailing service based on the thumbnail management D-Bus specification. This is useful for generating thumbnail images of files.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(libgsf-1)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libxfce4util-1.0)
    - pkgconfig(poppler-glib)
setup      : |
    %configure \
        --disable-static \
        --disable-debug \
        --disable-gstreamer-thumbnailer \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
