# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kunitconversion
version    : 6.27.0
release    : 33
source     :
    - https://download.kde.org/stable/frameworks/6.27/kunitconversion-6.27.0.tar.xz : 404e064114c95eca0ef759b96ca4e0ba5f9b8bc563138574358270963f3f5554
homepage   : https://community.kde.org/Frameworks
license    :
    - CC0-1.0
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Converting physical units
description: |
    KUnitConversion provides functions to convert values in different physical units. It supports converting different prefixes (e.g. kilo, mega, giga) as well as converting between different unit systems (e.g. liters, gallons).
builddeps  :
    - kf6-ki18n-devel
rundeps    :
    - devel :
        - qt6-base-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6 -DBUILD_PYTHON_BINDINGS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
