# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libvoikko
version    : 4.3.3
release    : 17
source     :
    - https://www.puimula.org/voikko-sources/libvoikko/libvoikko-4.3.3.tar.gz : d1162965c61de44f72162fd87ec1394bd4f90f87bc8152d13fe4ae692fdc73fa
homepage   : https://voikko.puimula.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : programming.library
summary    : Libvoikko provides spell checking, hyphenation, grammar checking and morphological analysis for Finnish language
description: |
    Libvoikko provides spell checking, hyphenation, grammar checking and morphological analysis for Finnish language.
setup      : |
    %configure \
        --disable-hfst \
        --disable-static \
        --with-dictionary-path=/usr/share/voikko
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 python/libvoikko.py $installdir/usr/lib/python%python3_version%/site-packages/libvoikko.py
    %install_license COPYING
    %install_license LICENSE.CORE
