# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : thinkfan
version    : 2.0.0
release    : 1
source     :
    - https://github.com/vmatare/thinkfan/archive/refs/tags/2.0.0.tar.gz : 0fc94eb378dcba8c889e91f41dab3a8d6eebc7324a59a0704cc39aa66551987e
homepage   : https://github.com/vmatare/thinkfan
license    : GPL-3.0-or-later
component  : system.utils
summary    : The minimalist fan control program
description: |
    Thinkfan is a simple, lightweight fan control program.
builddeps  :
    - pkgconfig(yaml-cpp)
    - lm_sensors-devel
setup      : |
    %cmake_ninja -D CMAKE_BUILD_TYPE:STRING=Release
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Correct libdir
    mv $installdir/usr/lib $installdir/%libdir%

    # Remove non-stateless files
    rm -rf $installdir/etc

    # Enable by default, users can disable now with systemctl mask tlp
    install -Ddm 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../thinkfan.service $installdir/%libdir%/systemd/system/multi-user.target.wants
