# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kitemviews
version    : 6.28.0
release    : 35
source     :
    - https://download.kde.org/stable/frameworks/6.28/kitemviews-6.28.0.tar.xz : 2b474a0a0ca1d59111ab864d4f05100e0056b5204d52dfbab6776ca0fbfdd402
homepage   : https://community.kde.org/Frameworks
license    :
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : Set of item views extending the Qt model-view framework.
description: |
    Set of item views extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt6Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-tools-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
