# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : freerdp
version    : 3.30.0
release    : 55
source     :
    - https://pub.freerdp.com/releases/freerdp-3.30.0.tar.xz : 1a1df431fd35ec85706fb6c1729cda4ce82379ed87a4c880f8dd570c5625583a
homepage   : https://www.freerdp.com/
license    : Apache-2.0
component  :
    - network.util
    - libs : programming.library
summary    :
    - FreeRDP is a free remote desktop protocol client
    - libs : FreeRDP shared libraries
description: |
    FreeRDP is a free implementation of the Remote Desktop Protocol (RDP).
builddeps  :
    - pkgconfig(SDL2_ttf)
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(cups)
    - pkgconfig(fuse3)
    - pkgconfig(json-c)
    - pkgconfig(libavcodec)
    - pkgconfig(libcjson)
    - pkgconfig(libpcsclite)
    - pkgconfig(libpkcs11-helper-1)
    - pkgconfig(libpulse)
    - pkgconfig(libusbredirhost)
    - pkgconfig(mit-krb5)
    - pkgconfig(sdl2)
    - pkgconfig(wayland-client)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - docbook-xml
rundeps    :
    - devel :
        - freerdp-libs
        - fuse-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_ninja \
        -DWITH_MANPAGES=ON \
        -DWITH_SIMD=ON \
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
patterns   :
    - libs :
        - /usr/lib64/libfreerdp*.so.*
        - /usr/lib64/libwinpr*.so.*
        - /usr/lib64/libuwac0.so.*
        - /usr/lib64/freerdp3/
