# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : homebank
version    : 5.10.3
release    : 43
source     :
    - https://www.gethomebank.org/public/sources/homebank-5.10.3.tar.gz : 9597b4f30ffa71fefe49613fabbd1513725ab21185ff327716cef6274999227d
homepage   : https://www.gethomebank.org/en/index.php
license    : GPL-2.0-or-later
component  : office.finance
summary    : HomeBank assists you to manage your personal accounting
description: |
    HomeBank is a free software (as in "free speech" and also as in "free beer") that will assist you to manage your personal accounting.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libofx)
    - pkgconfig(libsoup-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
