# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-devel-hide
version    : '0.0016'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/D/DC/DCANTRELL/Devel-Hide-0.0016.tar.gz : 7830b4a57f7ec7410620d6c0150185449d7b4c9964c39a7dc397056032c32a08
homepage   : https://metacpan.org/pod/Devel::Hide
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Devel::Hide - Forces the unavailability of specified Perl modules (for testing)
description: |
    Simple tool for developers which allows to hide installed Perl modules.
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
patterns   : /*
