# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libcap-ng
version    : 0.9.3
release    : 14
source     :
    - https://github.com/stevegrubb/libcap-ng/archive/refs/tags/v0.9.3.tar.gz : fe11ebbb55904763b3532f19069f13ec319042634620180a03bd4653d301563e
homepage   : https://github.com/stevegrubb/libcap-ng
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  :
    - system.base
    - ^python-capng : programming.python
summary    :
    - Libcap-ng is a library that makes using posix capabilities easier
    - ^python-capng : Libcap-ng is a library that makes using posix capabilities easier - Python library
description: |
    The libcap-ng library should make programming with posix capabilities easier. The library has some utilities to help you analyse a system for apps that may have too much privileges.
builddeps  :
    - pkgconfig(libattr)
    - pkgconfig(python3)
    - swig
optimize   :
    - size
setup      : |
    touch NEWS # autoconf is a goober
    %reconfigure --disable-static --with-python3
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING COPYING.LIB
check      : |
    %make check
patterns   :
    - ^python-capng :
        - /usr/lib/python3*
