# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : less
version    : '704'
release    : 24
source     :
    - https://www.greenwoodsoftware.com/less/less-704.tar.gz : 20a0b0a2bb2525fa53c7eee9beb854b4c9cf172eabb209af7020743547bfe9fb
license    :
    - GPL-3.0-only
    - BSD-2-Clause
homepage   : https://www.greenwoodsoftware.com/less/
component  : system.base
summary    : less (file pager)
description: |
    less is a free open-source file pager. It is used to read files, but not modify them.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
