# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-pyproject-api
version    : 1.11.0
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/p/pyproject-api/pyproject_api-1.11.0.tar.gz : b8807d85a293e6c9f133e6575946fed45f1d42b22d58c780b33aa2421a799549
homepage   : https://github.com/tox-dev/pyproject-api
license    : MIT
component  : programming.python
summary    : API to interact with the python pyproject.toml based projects
description: |
    API to interact with the python pyproject.toml based projects
builddeps  :
    - python-build
    - python-hatch-vcs
    - python-hatchling
    - python-installer
    - python-packaging
    - python-wheel
checkdeps  :
    - python-pytest-mock
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest --deselect tests/test_frontend_setuptools.py::test_result_missing
