# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ffmpegthumbs
version    : 25.12.3
release    : 100
source     :
    - https://download.kde.org/stable/release-service/25.12.3/src/ffmpegthumbs-25.12.3.tar.xz : eeb38acc65a955c16532b83a20bca08fce3e484674dbb0ccaecae44277ef8de8
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libavcodec)
    - kf6-kio-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
