# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kmag
version    : 26.04.1
release    : 93
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/kmag-26.04.1.tar.xz : bc035addd99422d3e467adb36736577b5aec2d8ad5c7c043647f8f8cb9ba5e6f
homepage   : https://kde.org/applications/utilities/org.kde.kmag
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : KMag is a screen magnifier
description: |
    KMag is a screen magnifier.
builddeps  :
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - libqaccessibilityclient-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rfv $installdir/usr/share/doc
