# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kmag
version    : 26.04.3
release    : 95
source     :
    - https://download.kde.org/stable/release-service/26.04.3/src/kmag-26.04.3.tar.xz : 42a0245819c671f3ef23f80b1d75666045c9830bb287114fc73b3bd702d085ec
homepage   : https://kde.org/applications/utilities/org.kde.kmag
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde
summary    : KMag is a screen magnifier
description: |
    KMag is a screen magnifier.
builddeps  :
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - libqaccessibilityclient-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*

    # remove docs
    rm -rfv $installdir/usr/share/doc
