# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-rarfile
version    : '4.5'
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/r/rarfile/rarfile-4.5.tar.gz : 7425d0afa180f0092db903abb1526a130b36858980aad90b3694f48e41420155
homepage   : https://github.com/markokr/rarfile
license    : ISC
component  : programming.python
summary    : This is Python module for RAR archive reading
description: |
    This is Python module for RAR archive reading. The interface follows the style of zipfile.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - python-pycryptodome
build      : |
    %pyproject_build
install    : |
    %pyproject_install
