# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : capnproto
version    : 1.5.0
release    : 8
source     :
    - https://github.com/capnproto/capnproto/archive/refs/tags/v1.5.0.tar.gz : d5ebdf858e9885c33d4b3f765006d68bd66e9b002bf4d607ff4317ef9c1aac6a
homepage   : https://capnproto.org/
license    : MIT
component  :
    - programming
    - libs : programming.library
summary    :
    - Cap’n Proto is an insanely fast data interchange format and capability-based RPC system
    - libs : Shared libraries for Cap’n Proto
description: |
    Cap’n Proto is an insanely fast data interchange format and capability-based RPC system. Think JSON, except binary. Or think Protocol Buffers, except faster. In fact, in benchmarks, Cap’n Proto is INFINITY TIMES faster than Protocol Buffers.
setup      : |
    %cmake_ninja \
        -DBUILD_SHARED_LIBS:FEAT=ON \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
build      : |
    %cmake_build
install    : |
    %cmake_install
    %install_license LICENSE
patterns   :
    - libs : /usr/lib64/lib*.so.*
