# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : broot
version    : 1.56.3
release    : 34
source     :
    - https://github.com/Canop/broot/archive/refs/tags/v1.56.3.tar.gz : 48f7fdc6e68539a951207d892916824bb08e8752d2c6aa414ef994f08b6ba43c
homepage   : https://dystroy.org/broot/
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : true
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(xcb)
    - rust
setup      : |
    %cargo_fetch
build      : |
    export LIBGIT2_NOVENDOR=1
    %cargo_build --features clipboard
install    : |
    %cargo_install
    %install_license LICENSE

    # Install manpage
    sed -i "s/#date//" man/page
    sed -i "s/#version/%version%/" man/page
    install -Dm00644 man/page $installdir/usr/share/man/man1/broot.1

    # Install font
    install -Dm00644 resources/icons/vscode/vscode.ttf $installdir/usr/share/fonts/truetype/vscode.ttf
check      : |
    %cargo_test
