# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-term-readline-gnu
version    : '1.47'
release    : 12
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAYASHI/Term-ReadLine-Gnu-1.47.tar.gz : 3b07ac8a9b494c50aa87a40dccab3f879b92eb9527ac0f2ded5d4743d166b649
homepage   : https://metacpan.org/pod/Term::ReadLine::Gnu
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Term::ReadLine::Gnu - Perl extension for the GNU Readline/History Library
description: |
    This is an implementation of Term::ReadLine using the GNU Readline/History Library. For basic functions object oriented interface is provided. These are described in the section "Standard Methods" and "Term::ReadLine::Gnu Functions". This package also has the interface with the almost all functions and variables which are documented in the GNU Readline/History Library Manual. They are documented in the section "Term::ReadLine::Gnu Functions" and "Term::ReadLine::Gnu Variables" briefly. For further details of the GNU Readline/History Library, see GNU Readline Library Manual and GNU History Library Manual.
extract    : false
setup      : |
    # https://github.com/getsolus/solbuild/issues/126
    tar --strip-components=1 -xf $sources/Term-ReadLine-Gnu-%version%.tar.gz
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
patterns   : /*
