# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kcrash
version    : 6.31.0
release    : 38
source     :
    - https://download.kde.org/stable/frameworks/6.31/kcrash-6.31.0.tar.xz : 8883c740d5de9aea232060f10c7f3bfdc3f83914b2d91d757ce2c8ed535621a6
homepage   : https://community.kde.org/Frameworks
license    :
    - CC0-1.0
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(x11)
    - kf6-kcoreaddons-devel
rundeps    :
    - devel :
        - kf6-kcoreaddons-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
