# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kcrash
version    : 6.27.0
release    : 34
source     :
    - https://download.kde.org/stable/frameworks/6.27/kcrash-6.27.0.tar.xz : f8e1083863dac2c07068b10614ca7d4b52c6920df0228854cfc37e0d6578d902
homepage   : https://community.kde.org/Frameworks
license    :
    - CC0-1.0
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Graceful handling of application crashes.
description: |
    Graceful handling of application crashes.
builddeps  :
    - pkgconfig(x11)
    - kf6-kcoreaddons-devel
rundeps    :
    - devel :
        - kf6-kcoreaddons-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
