# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kcompletion
version    : 6.28.0
release    : 35
source     :
    - https://download.kde.org/stable/frameworks/6.28/kcompletion-6.28.0.tar.xz : 8aa9cbc36139adfa8e3b2c744cc94714afe154d21cef8a3a2d5f4d311be7cc3c
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - kf6-kcodecs-devel
    - kf6-kconfig-devel
    - kf6-kwidgetsaddons-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
