# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kcompletion
version    : 6.26.0
release    : 33
source     :
    - https://download.kde.org/stable/frameworks/6.26/kcompletion-6.26.0.tar.xz : 95f71eb807e4de40ecdfe7234c9c3d844423171ac52588aecca642f78d904e48
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Powerful completion framework, including completion-enabled lineedit and combobox.
description: |
    Powerful completion framework, including completion-enabled lineedit and combobox.
builddeps  :
    - kf6-kcodecs-devel
    - kf6-kconfig-devel
    - kf6-kwidgetsaddons-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
