# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-datetime-format-strptime
version    : '1.80'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Format-Strptime-1.80.tar.gz : efe5e2be70425efc123a4e57f4b96b2d23beb03200c8326495b5b433b6b77158
homepage   : https://metacpan.org/pod/DateTime::Format::Strptime
license    : Artistic-2.0
component  : programming.perl
summary    : DateTime::Format::Strptime - Parse and format strp and strf time patterns
description: |
    This module implements most of strptime(3), the POSIX function that is the reverse of strftime(3), for DateTime. While strftime takes a DateTime and a pattern and returns a string, strptime takes a string and a pattern and returns the DateTime object associated.
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-singleton
    - perl-datetime
    - perl-datetime-locale
    - perl-datetime-timezone
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-exception-class
    - perl-file-sharedir
    - perl-module-implementation
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-deprecationmanager
    - perl-package-stash
    - perl-params-util
    - perl-params-validationcompiler
    - perl-role-tiny
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-sub-install
    - perl-sub-name
    - perl-test-fatal
    - perl-test-warnings
    - perl-try-tiny
    - perl-variable-magic
rundeps    :
    - perl-datetime
    - perl-package-deprecationmanager
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
check      : |
    %perl_build test
patterns   : /*
