# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-workspace-wallpapers
version    : 6.7.2
release    : 49
source     :
    - https://download.kde.org/stable/plasma/6.7.2/plasma-workspace-wallpapers-6.7.2.tar.xz : 9d9c95832ac0b478ee94cb49fcadfbbf8d581bf0d44f4d6c72e12e39a8048b98
homepage   : https://kde.org/plasma-desktop
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : desktop.kde
summary    : Wallpapers for Plasma Workspaces
description: |
    Wallpapers for Plasma Workspaces
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING COPYING.LGPL3
