name       : plasma-workspace-wallpapers
version    : 6.2.1
release    : 18
source     :
    - https://download.kde.org/stable/plasma/6.2.1/plasma-workspace-wallpapers-6.2.1.tar.xz : 5cc6d5fcd265eae0285b3a9b7cfa1aacb6219abe8f71656a2824cd3ee3e4f221
homepage   : https://kde.org/plasma-desktop
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : desktop.kde
summary    : Wallpapers for Plasma Workspaces
description: |
    Wallpapers for Plasma Workspaces
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
