# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libphonenumber
version    : 9.0.38
release    : 18
source     :
    - https://github.com/google/libphonenumber/archive/refs/tags/v9.0.38.tar.gz : 75e0a15fdc8fab9efc8a101d1d36ba3866c407889faae6c025e6aac58957da77
homepage   : https://github.com/googlei18n/libphonenumber
license    :
    - Apache-2.0
    - BSD-3-Clause
component  : desktop.library
summary    : library for working with international phone numbers
description: |
    Google's common library for parsing, formatting, and validating international phone numbers
builddeps  :
    - pkgconfig(absl_base)
    - pkgconfig(protobuf)
    - libboost-devel
    - openjdk-25-devel
checkdeps  :
    - pkgconfig(gtest)
rundeps    :
    - devel :
        - abseil-cpp-devel
        - libboost-devel
        - protobuf-devel
clang      : true
optimize   :
    - thin-lto
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-25
    export PATH=$JAVA_HOME/bin:$PATH
    export CLANG_IGNORE_WERROR=1
setup      : |
    %patch -p1 -i ${pkgfiles}/0001-Fix-BUILD_STATIC_LIB-OFF.patch
    %patch -p1 -i ${pkgfiles}/0002-Do-not-require-Boost.System.patch

    %cmake_ninja -S cpp -DBUILD_STATIC_LIB=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE LICENSE.Chromium
check      : |
    cmake --build solusBuildDir --target tests -j %YJOBS%
