# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gtk4-layer-shell
version    : 1.3.0
release    : 2
source     :
    - https://github.com/wmww/gtk4-layer-shell/archive/refs/tags/v1.3.0.tar.gz : 1ebb01ab14e98afd1727f68f64981c37bd23305b1f131f5667c02b94cf593192
homepage   : https://github.com/wmww/gtk4-layer-shell
license    : MIT
component  : programming.library
summary    : Library to create panels and other desktop components for Wayland
description: |
    A library for using the Layer Shell and Session Lock Wayland protocols with GTK4. Compatible with C, C++, and any language that supports GObject introspection files.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk4)
    - pkgconfig(vapigen)
    - pkgconfig(wayland-protocols)
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
    %install_license LICENSE
