# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : alglib
version    : 4.08.0
release    : 4
source     :
    - https://www.alglib.net/translator/re/alglib-4.08.0.cpp.gpl.tgz : 98a3ed084fb02c56a0bc154389d6bca100b23bb3749255a4c87163922a776a86
homepage   : https://www.alglib.net
license    : GPL-2.0-or-later
component  : programming.library
summary    : A numerical analysis and data processing library (free edition)
description: |
    ALGLIB is a cross-platform numerical analysis and data processing library.

    ALGLIB features include:
    * Data analysis (classification/regression, statistics)
    * Optimization and nonlinear solvers
    * Interpolation and linear/nonlinear least-squares fitting
    * Linear algebra (direct algorithms, EVD/SVD), direct and iterative linear solvers
    * Fast Fourier Transform and many other algorithms
setup      : |
    # Borrowed from Fedora
    cp ${pkgfiles}/CMakeLists.txt .

    %cmake_ninja \
        -DALGLIB_VERSION=${version}
build      : |
    %cmake_build
install    : |
    %cmake_install
    %install_license gpl2.txt
check      : |
    %cmake_test
