# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kmime
version    : 26.04.1
release    : 98
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/kmime-26.04.1.tar.xz : 79616a7bc28710f8f2fc4e7eee53342e83c58969eef09ba70e63ee2017472e6a
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - kf6-kcodecs-devel
rundeps    :
    - devel :
        - kf6-kcodecs-devel
        - qt6-base-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
