# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mako-notify
version    : 1.11.0
release    : 2
source     :
    - https://github.com/emersion/mako/releases/download/v1.11.0/mako-1.11.0.tar.gz : e97eb5bd0dc6a9159019949f48b3db4e8781b56bd6377bd65827e1cb440a7def
homepage   : https://github.com/emersion/mako
license    : MIT
component  : desktop
summary    : A lightweight Wayland notification daemon
description: |
    A lightweight Wayland notification daemon.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(pango)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - scdoc
setup      : |
    %meson_configure \
        -Dsd-bus-provider='libsystemd'
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE

    install -Dm00644 -t ${installdir}/usr/lib/systemd/user contrib/systemd/mako.service
