# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : iio-sensor-proxy
version    : '3.9'
release    : 8
source     :
    - https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/archive/3.9/iio-sensor-proxy-3.9.tar.gz : af5edd307dcfa52dc3a242d13b7cc756e90a71640caf332efbad960e21649ae4
homepage   : https://gitlab.freedesktop.org/hadess/iio-sensor-proxy
license    : GPL-3.0-only
component  : desktop.util
summary    : IIO sensors (ambient light, compass, orientation) to D-Bus proxy
description: |
    IIO sensors (ambient light, compass, orientation) to D-Bus proxy
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
checkdeps  :
    - python-dbusmock
    - python-psutil
    - umockdev
setup      : |
    %meson_configure --sysconfdir=/usr/share
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
    %install_license COPYING
