# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kmenuedit
version    : 6.7.3
release    : 139
source     :
    - https://download.kde.org/stable/plasma/6.7.3/kmenuedit-6.7.3.tar.xz : dd92ee9c3bf3fde6d7bc4990453b9c72238b51b86d510d943d68bb1d1602e2ec
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - CC0-1.0
    - GPL-2.0-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
builddeps  :
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - kf6-sonnet-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc

    %install_license LICENSES/*
