# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : 7zip
version    : '26.02'
release    : 2
source     :
    - https://github.com/ip7z/7zip/archive/refs/tags/26.02.tar.gz : 7e5600ad0b21918bc41803bd84d0c2967e097fb7fbaa2e7aeb90beeb1121e54b
homepage   : https://www.7-zip.org/
license    :
    - LGPL-2.1-or-later
    - BSD-3-Clause
component  : system.utils
summary    : 7-Zip is a file archiver with a high compression ratio
description: |
    7-Zip is a file archiver with a high compression ratio. This package provides the official Linux port of 7-Zip, natively compiled from the upstream developer, replacing the deprecated and vulnerable p7zip fork.
setup      : |
    # Apply Fedora's patch to rewrite the plugin search path
    %patch -p1 -i $pkgfiles/7zip-find-so-in-libexec.diff
        
    sed -i -e 's|-Werror||' CPP/7zip/7zip_gcc.mak
build      : |
    # 7zz
    %make -C CPP/7zip/Bundles/Alone2 -f ../../cmpl_gcc.mak CXX="$CXX $CXXFLAGS" CC="$CC $CFLAGS"

    # 7za
    %make -C CPP/7zip/Bundles/Alone -f ../../cmpl_gcc.mak CXX="$CXX $CXXFLAGS" CC="$CC $CFLAGS"

    # 7zr
    %make -C CPP/7zip/Bundles/Alone7z -f ../../cmpl_gcc.mak CXX="$CXX $CXXFLAGS" CC="$CC $CFLAGS"

    # 7z.so
    %make -C CPP/7zip/Bundles/Format7zF -f ../../cmpl_gcc.mak CXX="$CXX $CXXFLAGS" CC="$CC $CFLAGS"

    # 7z 
    %make -C CPP/7zip/UI/Console -f ../../cmpl_gcc.mak LOCAL_FLAGS="-DZ7_EXTERNAL_CODECS" CXX="$CXX $CXXFLAGS" CC="$CC $CFLAGS"

install    : |
    install -D -m 00755 CPP/7zip/UI/Console/b/g/7z $installdir/usr/bin/7z
    install -D -m 00755 CPP/7zip/Bundles/Alone/b/g/7za $installdir/usr/bin/7za
    install -D -m 00755 CPP/7zip/Bundles/Alone7z/b/g/7zr $installdir/usr/bin/7zr
    install -D -m 00755 CPP/7zip/Bundles/Alone2/b/g/7zz $installdir/usr/bin/7zz

    # Install the plugin to /usr/lib64/7zip/
    install -D -m 00755 CPP/7zip/Bundles/Format7zF/b/g/7z.so $installdir%libdir%/7zip/7z.so

    %install_license DOC/copying.txt
    %install_license DOC/License.txt

replaces   :
    - p7zip
    - dbginfo : p7zip-dbginfo
