# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : putty
version    : '0.84'
release    : 17
source     :
    - https://the.earth.li/~sgtatham/putty/latest/putty-0.84.tar.gz : 06057862ae198f1dbd219d0c7493080d59f606194bb5056c549e342aa01b69fe
homepage   : https://www.chiark.greenend.org.uk/~sgtatham/putty
license    : MIT
component  : network.remote
summary    : PuTTY is a free implementation of SSH and Telnet
description: |
    PuTTY is a free SSH, Telnet, rlogin and serial console client. It includes
    graphical and command-line tools for remote access, file transfer, key
    management and local terminal emulation.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - imagemagick
rundeps    :
    - hicolor-icon-theme
setup      : |
    export CFLAGS="${CFLAGS} -DNOT_X_WINDOWS"
    %cmake_ninja
build      : |
    %ninja_build
    make -C icons putty-16.png putty-32.png putty-48.png putty-64.png putty-128.png
install    : |
    %ninja_install
    %install_license LICENCE

    install -Dm00644 ${pkgfiles}/uk.org.greenend.chiark.sgtatham.putty.desktop -t ${installdir}/usr/share/applications/
    install -Dm00644 ${pkgfiles}/uk.org.greenend.chiark.sgtatham.putty.metainfo.xml -t ${installdir}/usr/share/metainfo/

    for size in 16 32 48 64 128; do
        install -Dm00644 icons/putty-${size}.png ${installdir}/usr/share/icons/hicolor/${size}x${size}/apps/putty.png
    done
