# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kconfig
version    : 6.24.0
release    : 34
source     :
    - https://download.kde.org/stable/frameworks/6.24/kconfig-6.24.0.tar.xz : 45cfbdd8419bd1ade54a6f54050f2465de76a4f91b7a702b806930e6fbb3651f
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6Qml)
    - extra-cmake-modules
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-tools-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
