# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kconfig
version    : 6.29.0
release    : 40
source     :
    - https://download.kde.org/stable/frameworks/6.29/kconfig-6.29.0.tar.xz : a0e902865763fd4cd1c86973c316069f210492923d7b8065d5052c539ae46b91
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
    - MIT
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6Qml)
    - extra-cmake-modules
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-tools-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
