name       : libxfce4util
version    : 4.19.4
release    : 11
source     :
    - https://archive.xfce.org/xfce/4.20pre1/src/libxfce4util-4.19.4.tar.bz2 : f405ba1cd613d7ecb84c9bec16146af8fe68605aebdb245c0273af651983e1e9
homepage   : https://docs.xfce.org/xfce/libxfce4util/start
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Extension library for Xfce
description: |
    Libxfce4util is used to share commonly used non-GTK+ utilities among the Xfce applications.
builddeps  :
    - gettext-devel
    - gtk-doc
    - xfce4-dev-tools-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-sysconfdir-change.patch
    autoreconf -fiv
    %configure --sysconfdir=/usr/share/
build      : |
    %make
install    : |
    %make_install
