# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : rocm-cmake
version    : 7.2.0
release    : 9
source     :
    - https://github.com/ROCm/rocm-cmake/archive/refs/tags/rocm-7.2.0.tar.gz : 3f3899e84d78a0fecab62a35eed0014bb503c04d2cf76d263b29daf17f178636
homepage   : https://github.com/RadeonOpenCompute
license    : MIT
component  : programming.devel
summary    : ROCm cmake modules
description: |
    ROCm cmake modules provides cmake modules for common build tasks needed for the ROCM software stack.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
