name       : rocm-cmake
version    : 6.4.0
release    : 8
source     :
    - https://github.com/ROCm/rocm-cmake/archive/refs/tags/rocm-6.4.0.tar.gz : be8109c52e9309d1ae9553e067346ecdf1a25f653cc21974ddc542f31ce54615
homepage   : https://github.com/RadeonOpenCompute
license    : MIT
component  : programming.devel
summary    : ROCm cmake modules
description: |
    ROCm cmake modules provides cmake modules for common build tasks needed for the ROCM software stack.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
