# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-test-differences
version    : '0.72'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/D/DC/DCANTRELL/Test-Differences-0.72.tar.gz : 648844b9dcb7dae6f9b5a15c9359d0f09de247a624b65c4620ebff249558f913
homepage   : https://metacpan.org/pod/Test::Differences
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Differences - Test strings and data structures and show differences if not ok
description: |
    Test::Differences - Test strings and data structures and show differences if not ok. When the code you're testing returns multiple lines, records or data structures and they're just plain wrong, an equivalent to the Unix diff utility may be just what's needed.
builddeps  :
    - perl-capture-tiny
    - perl-module-build
    - perl-text-diff
checkdeps  :
    - perl-test-pod
    - perl-test-pod-coverage
rundeps    :
    - perl-capture-tiny
    - perl-text-diff
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
patterns   : /*
