# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-audioread
version    : 3.1.0
release    : 6
source     :
    - https://github.com/beetbox/audioread/archive/refs/tags/v3.1.0.tar.gz : 73a31af0d329e633d6166ff70cab31aec3e33b35c05c80d183337fcc2b417f42
homepage   : https://github.com/beetbox/audioread
license    : MIT
component  : programming.python
summary    : multi-library, cross-platform audio decoding
description: |
    cross-library (GStreamer + Core Audio + MAD + FFmpeg) audio decoding for Python
builddeps  :
    - python-build
    - python-installer
    - python-poetry-core
    - python-wheel
checkdeps  :
    - python-audioop-lts
    - python-gobject
    - python-gstreamer
    - python-pymad
    - python-pytest
    - python-standard-aifc
    - python-standard-sunau
rundeps    :
    - python-audioop-lts
    - python-standard-aifc
    - python-standard-sunau
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
