# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dankcalendar
version    : 0.3.1
release    : 7
source     :
    - https://github.com/AvengeMedia/dankcalendar/releases/download/v0.3.1/dankcalendar-0.3.1.tar.gz : fcbac8bdd9edba67ddebd8f8d219b77fcc981ae478bfb62e752051e6e772fea0
homepage   : https://danklinux.com
license    : MIT
component  : desktop
summary    : Calendar from the Dank Linux Suite
description: |
    DankCalendar is a standalone calendar app that brings your Local, Google, Microsoft, CalDAV, and iCloud calendars together in one place. It runs as a lightweight daemon with a tray icon, keeps your accounts in sync, and reminds you about events — all with the look and feel of DankMaterialShell.
builddeps  :
    - golang
rundeps    :
    - quickshell
networking : true
build      : |
    pushd core
    %make sync-shell

    go build -o bin/dcal \
        -tags withshell \
        -ldflags="-s -w -X main.Version=${version}" \
        ./cmd/dcal/*.go

    mkdir ../completions
    bin/dcal completion bash > ../completions/dcal
    bin/dcal completion zsh > ../completions/_dcal
    bin/dcal completion fish > ../completions/dcal.fish
install    : |
    %make_install install-systemd \
        PREFIX=%PREFIX% \
        SYSTEMD_USER_DIR=${installdir}/usr/lib/systemd/user
    %install_license LICENSE

    # Fix the systemd service
    sed -i "s|${installdir}||g" ${installdir}/usr/lib/systemd/user/dcal.service

    # Install completions
    %install_file -t ${installdir}/usr/share/bash-completion/completions completions/dcal
    %install_file -t ${installdir}/usr/share/fish/vendor_completions.d completions/dcal.fish
    %install_file -t ${installdir}/usr/share/zsh/site-functions completions/_dcal
