# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dankcalendar
version    : 0.2.6
release    : 4
source     :
    - https://github.com/AvengeMedia/dankcalendar/releases/download/v0.2.6/dankcalendar-0.2.6.tar.gz : 9e8047a325db5f2e3f82511dd1026255b4d7102355d0be0c952477a98f191e24
homepage   : https://danklinux.com
license    : MIT
component  : desktop
summary    : Calendar from the Dank Linux Suite
description: |
    DankCalendar is a standalone calendar app that brings your Local, Google, Microsoft, CalDAV, and iCloud calendars together in one place. It runs as a lightweight daemon with a tray icon, keeps your accounts in sync, and reminds you about events — all with the look and feel of DankMaterialShell.
builddeps  :
    - golang
rundeps    :
    - quickshell
networking : true
setup      : |
    %patch -p1 -i ${pkgfiles}/0001-build-Add-target-to-install-AppStream-metainfo-file.patch
build      : |
    pushd core
    %make sync-shell

    go build -o bin/dcal \
        -tags withshell \
        -ldflags="-s -w -X main.Version=${version}" \
        ./cmd/dcal/*.go

    mkdir ../completions
    bin/dcal completion bash > ../completions/dcal
    bin/dcal completion zsh > ../completions/_dcal
    bin/dcal completion fish > ../completions/dcal.fish
install    : |
    %make_install install-systemd \
        PREFIX=%PREFIX% \
        SYSTEMD_USER_DIR=${installdir}/usr/lib/systemd/user
    %install_license LICENSE

    # Fix the systemd service
    sed -i "s|${installdir}||g" ${installdir}/usr/lib/systemd/user/dcal.service

    # Install completions
    install -Dm 00644 -t ${installdir}/usr/share/bash-completion/completions completions/dcal
    install -Dm 00644 -t ${installdir}/usr/share/fish/vendor_completions.d completions/dcal.fish
    install -Dm 00644 -t ${installdir}/usr/share/zsh/site-functions completions/_dcal
