# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-dogpile-cache
version    : 1.5.0
release    : 15
source     :
    - https://github.com/sqlalchemy/dogpile.cache/archive/refs/tags/rel_1_5_0.tar.gz :
        41537b0b8540056c7725a1570ee01ad821afa6272269408ef1e95e521a115c4f
homepage   : https://github.com/sqlalchemy/dogpile.cache
license    : BSD-3-Clause
component  : programming.python
summary    : A caching front-end based on the Dogpile lock
description: |
    dogpile.cache is a Python caching API which provides a generic interface to caching backends of any variety.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - mako
    - python-decorator
    - python-pytest
    - python-pytest-xdist
    - python-stevedore
rundeps    :
    - python-decorator
    - python-stevedore
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
