# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : wild
version    : 0.10.0
release    : 2
source     :
    - https://github.com/wild-linker/wild/archive/refs/tags/0.10.0.tar.gz : 99ec83404558d4d0cbde9dd44b8c6fa2a511a2f8bb04a31f54c0929ec4491990
homepage   : https://github.com/wild-linker/wild
license    :
    - Apache-2.0
    - MIT
component  : programming.tools
summary    : A very fast linker for Linux
description: |
    Wild is a linker with the goal of being very fast for iterative development.
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
    %install_license LICENSE-*
    
    ln -sv /usr/bin/wild $installdir/usr/bin/ld.wild
