# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-elementpath
version    : 5.1.3
release    : 12
source     :
    - https://github.com/sissaschool/elementpath/archive/refs/tags/v5.1.3.tar.gz : c5f6035e3914091f630d0e9970084e6ee3766bb3f29c758c488cfc24907dd97a
homepage   : https://github.com/sissaschool/elementpath
license    : MIT
component  : programming.python
summary    : XPath 1.0/2.0 parsers and selectors for ElementTree and lxml
description: |
    The proposal of this package is to provide XPath 1.0 and 2.0 selectors for Python's ElementTree XML data structures, both for the standard ElementTree library and for the lxml.etree library.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps:
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
