name       : lsfg-vk
version    : 1.0.0
release    : 1
source     :
    - git|https://github.com/PancakeTAS/lsfg-vk.git : v1.0.0
homepage   : https://github.com/PancakeTAS/lsfg-vk/?tab=readme-ov-file
license    : MIT
component  : games
summary    : Lossless Scaling Frame Generation on Linux via DXVK/Vulkan
description: |
    Lossless Scaling is a Windows-exclusive app with the goal of bringing frame generation (among other features) to every single game or app.
    lsfg-vk brings this frame generation to Linux users by acting as a Vulkan layer inbetween your game and your graphics card.
clang: yes
networking: yes
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(vulkan)
    - rust
    - vulkan-headers

setup      : |
    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=On

    cd ui
    %cargo_fetch
build      : |
    %ninja_build

    cd ui
    %cargo_build
install    : |
    %ninja_install

    cd ui
    %cargo_install lsfg-vk-ui
    cd ..

    install -Dm00644 $pkgfiles/lsfg-vk-ui.desktop -t $installdir/usr/share/applications