# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kquickimageeditor
version    : 0.6.2.1
release    : 12
source     :
    - https://download.kde.org/stable/kquickimageeditor/kquickimageeditor-0.6.2.1.tar.xz : 6d37a479463dcd16e4746d8b43d4adb05640e8b49056baabc82c865e2e1a4c85
license    :
    - BSD-2-Clause
    - CC0-1.0
    - LGPL-2.1-or-later
component  : programming.library
homepage   : https://invent.kde.org/libraries/kquickimageeditor
summary    : KQuickImageEditor is a set of QtQuick components providing basic image editing capabilities.
description: |
    KQuickImageEditor is a set of QtQuick components providing basic image editing capabilities.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(opencv4)
    - extra-cmake-modules
    - kf6-kconfig-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
