# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kquickimageeditor
version    : 0.7.0
release    : 14
source     :
    - https://download.kde.org/stable/kquickimageeditor/kquickimageeditor-0.7.0.tar.xz : 56789a323250a52cfaa14175c6836e66cef9f2fbb4e56f8cac9f526c243633ae
license    :
    - BSD-2-Clause
    - CC0-1.0
    - LGPL-2.1-or-later
component  : programming.library
homepage   : https://invent.kde.org/libraries/kquickimageeditor
summary    : KQuickImageEditor is a set of QtQuick components providing basic image editing capabilities.
description: |
    KQuickImageEditor is a set of QtQuick components providing basic image editing capabilities.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(libhwy)
    - extra-cmake-modules
    - kf6-kconfig-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
