# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-zope.event
version    : '6.2'
release    : 15
source     :
    - https://github.com/zopefoundation/zope.event/archive/refs/tags/6.2.tar.gz : ddef7f4e82a52b24e4e0fabfe8d933ffe608a06d4c92fd56f432fad88b52e978
homepage   : https://github.com/zopefoundation/zope.event
license    : ZPL-2.1
component  : programming.python
summary    : Provides a simple event system
description: |
    Provides a simple event system
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
build      : |
    # skip dep check for setuptools 82.0, remove on update
    %python3_setup --skip-dependency-check
install    : |
    %python3_install
