# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : josm
version    : '19481'
release    : 14
source     :
    - https://github.com/JOSM/josm/archive/refs/tags/19481-tested.tar.gz : b9a24c1962f6b9369ab3df43b3e7a2ee2288f0fa3cb02bceb8e2b1a267c7275b
homepage   : https://josm.openstreetmap.de/
license    : GPL-2.0-or-later
component  : office
summary    : An extensible editor for OpenStreetMap
description: |
    JOSM is an extensible editor for OpenStreetMap. It supports loading GPX tracks, background imagery and OSM data from local sources as well as from online sources and allows to edit the OSM data (nodes, ways, and relations) and their metadata tags.
networking : true
builddeps  :
    - apache-ant
rundeps    :
    - openjdk-21
setup      : |
    sed -e "s|\${version.entry.commit.revision}|$version|g" -i build.xml
build      : |
    ant dist -Divy.default.ivy.user.dir=$workdir/.ivy2
install    : |
    install -Dm00755 dist/josm-custom.jar $installdir/usr/share/josm/josm.jar
    install -Dm00755 $pkgfiles/josm -t $installdir/usr/bin

    find native/linux/tested/usr/share -type d -empty -delete
    rm -rf native/linux/tested/usr/share/doc
    cp -a native/linux/tested/usr/share $installdir/usr
    %install_license gpl-2.0.txt gpl-3.0.txt
