# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : haruna
version    : 1.8.1
release    : 38
source     :
    - https://download.kde.org/stable/haruna/1.8.1/haruna-1.8.1.tar.xz : 01f154e3161292da606899c3017f863362e00bb2402a2796be5e8d6849fc4b4b
homepage   : https://invent.kde.org/multimedia/haruna/
license    :
    - BSD-3-Clause
    - CC-BY-4.0
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : multimedia.audio
summary    : Video player built with Qt/QML on top of libmpv.
description: |
    Video player built with Qt/QML on top of libmpv.
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(libavformat)
    - pkgconfig(mpv)
    - breeze-devel
    - kdsingleapplication-devel
    - kf6-kdoctools-devel
    - kf6-kfilemetadata-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - mpvqt-devel
    - qt6-base-private-devel
rundeps    :
    - breeze
    - breeze-icons
    - kf6-kirigami
    - kf6-kitemmodels
    - kf6-qqc2-desktop-style
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rfv $installdir/usr/share/doc

    %install_license LICENSES/*
