# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ghostwriter
version    : 26.04.1
release    : 62
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/ghostwriter-26.04.1.tar.xz : fbe2ba851cd71ed64bd2f86fc544c02bc06547ddc4c9cec9a1d658c5de15e1a3
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : editor
homepage   : https://ghostwriter.kde.org/
summary    : Cross-platform, aesthetic, distraction-free Markdown editor.
description: |
    ghostwriter is a Windows and Linux text editor for Markdown, ghostwriter provides a relaxing, distraction-free writing environment, whether your masterpiece be that next blog post, your school paper, or your NaNoWriMo novel.
builddeps  :
    - pkgconfig(Qt6Positioning)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(hunspell)
    - kf6-kcoreaddons-devel
    - kf6-kdoctools-devel
    - kf6-kxmlgui-devel
    - kf6-sonnet-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
