# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libopenshot
version    : 1.0.1
release    : 51
source     :
    - https://github.com/OpenShot/libopenshot/archive/refs/tags/v1.0.1.tar.gz : 57abb1b0bc3a59cba9d1e11415024dc3e9a5e4d542caf3a1a9ddd934cd001ce6
homepage   : https://www.openshot.org/
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : A high quality, open-source video editing, animation, and playback library for C++, Python and Ruby
description: |
    libopenshot is an open-source, cross-platform C++ library dedicated to delivering high quality video editing, animation, and playback solutions to the world. This is the same library which powers OpenShot Video Editor (version 2.0+) and it could power your next video editing application!
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Svg)
    - pkgconfig(alsa)
    - pkgconfig(cppzmq)
    - pkgconfig(gl)
    - pkgconfig(jsoncpp)
    - pkgconfig(libavcodec)
    - pkgconfig(opencv4)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - pkgconfig(ruby-4.0)
    - pkgconfig(x264)
    - doxygen
    - libopenshot-audio-devel
    - python-setuptools
    - swig
checkdeps  :
    - pkgconfig(catch2)
setup      : |
    # Fix build against FFmpeg 7.1+
    %patch -p1 -i $pkgfiles/ffmpeg7-fixes.patch

    # Sometimes build fails with ruby enabled.
    # Use -DENABLE_RUBY=OFF to disable it and reenable at a later date.
    %cmake_ninja \
        -DUSE_QT6=ON \
        -DUSE_SYSTEM_JSONCPP=ON \
        -DLIB_SUFFIX=%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
# Tests are very flaky and prone to hang at random points, disable it https://github.com/OpenShot/libopenshot/issues/964
#check      : |
#    %ninja_check || :
