# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : solseek
version    : 1.4.15
release    : 46
source     :
    - https://github.com/clintre/solseek/archive/refs/tags/v1.4.15.tar.gz : d77ace44a0c832529abc8393d573f7a6c843f3f0d59ff1cfa7b301d85c4fffb8
homepage   : https://github.com/clintre/solseek
license    : GPL-3.0-or-later
component  : system.utils
summary    : A TUI Package Manager for Solus
description: |
    Solseek is a simple terminal user interface that allows you to browse, search, and manage packages from the Solus packages.
rundeps    :
    - appstream
    - font-firacode-nerd
    - fzf
    - libayatana-appindicator
    - packagekit
    - python3
    - xdg-terminal-exec
install    : |-
    install -Dm00755 $workdir/package/bin/solseek $installdir/usr/bin/solseek
    install -dm00755 $installdir/usr/share
    cp -r $workdir/package/share/solseek $installdir/usr/share/
    chmod 00755 $installdir/usr/share/solseek/helpers/eopkg-info.py
    chmod 00755 $installdir/usr/share/solseek/helpers/solseek-tray.py

    install -Dm00644 $workdir/package/share/applications/Solseek.desktop $installdir/usr/share/applications/Solseek.desktop
    install -Dm00644 $workdir/package/share/icons/hicolor/scalable/apps/solseek.svg $installdir/usr/share/icons/hicolor/scalable/apps/solseek.svg
    install -Dm00644 $workdir/package/share/metainfo/solseek.metainfo.xml $installdir/usr/share/metainfo/solseek.metainfo.xml

    install -Dm00644 $workdir/package/share/applications/solseek-uc.service $installdir/%libdir%/systemd/user/solseek-uc.service
    install -Dm00644 $workdir/package/share/applications/solseek-uc.timer $installdir/%libdir%/systemd/user/solseek-uc.timer
    install -Dm00644 $workdir/package/share/applications/60-solseek-uc.preset $installdir/%libdir%/systemd/user-preset/60-solseek-uc.preset

    %install_license LICENSE
