# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kew
version    : 4.2.7
release    : 6
source     :
    - https://codeberg.org/ravachol/kew/archive/v4.2.7.tar.gz : 016c588429e9658251b51821607a0f13a5c3f6867266392b3386cbbdee59a553
homepage   : https://kewplayer.com/
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Terminal music player
description: |
    kew is a terminal music player with themes and cover-derived colors,
    lyrics support (.lrc, SYLT, Vorbis comments), MPRIS desktop integration,
    and support for MP3, FLAC, M4A/AAC, Opus, Ogg, WebM and WAV. It can search
    and browse your library with gapless playback, playlist editing, and a
    visualizer. Album art can be shown in sixel-capable terminals via Chafa.
builddeps  :
    - pkgconfig(chafa)
    - pkgconfig(faad2)
    - pkgconfig(fftw3)
    - pkgconfig(glib-2.0)
    - pkgconfig(ogg)
    - pkgconfig(opus)
    - pkgconfig(opusfile)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    %install_license LICENSE
    install -Dm00644 ${pkgfiles}/io.codeberg.ravachol.kew.metainfo.xml -t ${installdir}/usr/share/metainfo/
