# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : knighttime
version    : 6.7.3
release    : 16
source     :
    - https://download.kde.org/stable/plasma/6.7.3/knighttime-6.7.3.tar.xz : 22295cf3640e15eb04d28350934a1d457a4ec578033af8c28948bd10a8c75387
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-only
    - GPL-3.0-only
    - LGPL-2.1-only
    - LGPL-3.0-only
summary    : Helpers for scheduling the dark-light cycle
description: |
    Helpers for scheduling the dark-light cycle
builddeps  :
    - pkgconfig(Qt6Positioning)
    - extra-cmake-modules
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kdbusaddons-devel
    - kf6-kholidays-devel
    - kf6-ki18n-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - thin-lto
    - speed
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
patterns   :
    - devel :
        - /usr/share/dbus-1/interfaces/
