# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libboost
version    : 1.91.0
release    : 47
source     :
    - https://archives.boost.io/release/1.91.0/source/boost_1_91_0.tar.gz : 5734305f40a76c30f951c9abd409a45a2a19fb546efe4162119250bbe4d3a463
homepage   : https://www.boost.org/
license    : BSL-1.0
component  :
    - programming.library
    - atomic : programming.library
    - charconv : programming.library
    - chrono : programming.library
    - container : programming.library
    - context : programming.library
    - contract : programming.library
    - coroutine : programming.library
    - date-time : programming.library
    - devel : programming.devel
    - fiber : programming.library
    - filesystem : programming.library
    - graph : programming.library
    - iostreams : programming.library
    - json : programming.library
    - locale : programming.library
    - log : programming.library
    - math : programming.library
    - nowide : programming.library
    - numpy3 : programming.library
    - process : programming.library
    - program-options : programming.library
    - python3 : programming.library
    - random : programming.library
    - regex : programming.library
    - serialization : programming.library
    - stacktrace : programming.library
    - staticlib : programming.devel
    - system : programming.library
    - test : programming.library
    - thread : programming.library
    - timer : programming.library
    - type-erasure : programming.library
    - url : programming.library
    - wave : programming.library
summary    :
    - Virtual package that depends on all Boost libraries
    - atomic : Run-time component of the Boost atomic library
    - charconv : Run-time component of the Boost charconv library
    - chrono : Run-time component of the Boost chrono library
    - container : Run-time component of the Boost container library
    - context : Run-time component of the Boost context library
    - contract : Run-time component of the Boost contract library
    - coroutine : Run-time component of the Boost coroutine library
    - date-time : Run-time component of the Boost date-time library
    - devel : Development files for Boost
    - fiber : Run-time component of the Boost fiber library
    - filesystem : Run-time component of the Boost filesystem library
    - graph : Run-time component of the Boost graph library
    - iostreams : Run-time component of the Boost iostreams library
    - json : Run-time component of the Boost json library
    - locale : Run-time component of the Boost locale library
    - log : Run-time component of the Boost log library
    - math : Run-time component of the Boost math library
    - nowide : Run-time component of the Boost nowide library
    - numpy3 : Run-time component of the Boost numpy3 library
    - process : Run-time component of the Boost process library
    - program-options : Run-time component of the Boost program-options library
    - python3 : Run-time component of the Boost python3 library
    - random : Run-time component of the Boost random library
    - regex : Run-time component of the Boost regex library
    - serialization : Run-time component of the Boost serialization library
    - stacktrace : Run-time component of the Boost stacktrace library
    - staticlib : Static libraries for Boost
    - system : Run-time component of the Boost system library (deprecated)
    - test : Run-time component of the Boost test library
    - thread : Run-time component of the Boost thread library
    - timer : Run-time component of the Boost timer library
    - type-erasure : Run-time component of the Boost type-erasure library
    - url : Run-time component of the Boost url library
    - wave : Run-time component of the Boost wave library
description: |
    Boost provides a set of free peer-reviewed portable C++ source libraries. It includes libraries for linear algebra, pseudorandom number generation, multithreading, image processing, regular expressions and unit testing.
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - pkgconfig(zlib)
    - numpy
rundeps    :
    - libboost-atomic
    - libboost-charconv
    - libboost-chrono
    - libboost-container
    - libboost-context
    - libboost-contract
    - libboost-coroutine
    - libboost-date-time
    - libboost-fiber
    - libboost-filesystem
    - libboost-graph
    - libboost-iostreams
    - libboost-json
    - libboost-locale
    - libboost-log
    - libboost-math
    - libboost-nowide
    - libboost-numpy3
    - libboost-process
    - libboost-program-options
    - libboost-python3
    - libboost-random
    - libboost-regex
    - libboost-serialization
    - libboost-stacktrace
    - libboost-test
    - libboost-thread
    - libboost-timer
    - libboost-type-erasure
    - libboost-url
    - libboost-wave
    - staticlib :
        - libboost-devel
environment: |
    function run_b2() {
        ./b2 \
            -j %YJOBS% \
            --layout=system \
            cflags="${CFLAGS}" \
            cxxflags="${CXXFLAGS}" \
            debug-symbols=off \
            linkflags="${LDFLAGS}" \
            link=shared,static \
            runtime-link=shared \
            threading=multi \
            variant=release \
            "$@"
    }
setup      : |
    ./bootstrap.sh --prefix=${installdir}/usr \
        --libdir=${installdir}/%libdir% \
        --with-python=/usr/bin/python3
build      : |
    run_b2
install    : |
    run_b2 install
    %install_license LICENSE_1_0.txt

    # Make meta/transitional packages
    install -dm00755 ${installdir}/usr/share/doc
    echo "Boost Meta Package" > ${installdir}/usr/share/doc/libboost
    echo "Deprecated Boost.System Package" > ${installdir}/usr/share/doc/libboost-system
patterns   :
    - atomic :
        - /usr/lib64/libboost_atomic.so.*
    - charconv :
        - /usr/lib64/libboost_charconv.so.*
    - chrono :
        - /usr/lib64/libboost_chrono.so.*
    - container :
        - /usr/lib64/libboost_container.so.*
    - context :
        - /usr/lib64/libboost_context.so.*
    - contract :
        - /usr/lib64/libboost_contract.so.*
    - coroutine :
        - /usr/lib64/libboost_coroutine.so.*
    - date-time :
        - /usr/lib64/libboost_date_time.so.*
    - devel :
        - /usr/include/boost/
        - /usr/lib64/cmake/Boost-*/
        - /usr/lib64/cmake/boost_*/
        - /usr/lib64/libboost_*.so
        - /usr/lib64/pkgconfig/*.pc
        - /usr/share/boost_predef/
    - fiber :
        - /usr/lib64/libboost_fiber.so.*
    - filesystem :
        - /usr/lib64/libboost_filesystem.so.*
    - graph :
        - /usr/lib64/libboost_graph.so.*
    - iostreams :
        - /usr/lib64/libboost_iostreams.so.*
    - json :
        - /usr/lib64/libboost_json.so.*
    - locale :
        - /usr/lib64/libboost_locale.so.*
    - log :
        - /usr/lib64/libboost_log.so.*
        - /usr/lib64/libboost_log_setup.so.*
    - math :
        - /usr/lib64/libboost_math_c99*.so.*
        - /usr/lib64/libboost_math_tr1*.so.*
    - nowide :
        - /usr/lib64/libboost_nowide.so.*
    - numpy3 :
        - /usr/lib64/libboost_numpy3*.so.*
    - process :
        - /usr/lib64/libboost_process.so.*
    - program-options :
        - /usr/lib64/libboost_program_options.so.*
    - python3 :
        - /usr/lib64/libboost_python3*.so.*
    - random :
        - /usr/lib64/libboost_random.so.*
    - regex :
        - /usr/lib64/libboost_regex.so.*
    - serialization :
        - /usr/lib64/libboost_serialization.so.*
        - /usr/lib64/libboost_wserialization.so.*
    - stacktrace :
        - /usr/lib64/libboost_stacktrace_*.so.*
    - staticlib :
        - /usr/lib64/libboost_*.a
    - system :
        - /usr/share/doc/libboost-system
    - test :
        - /usr/lib64/libboost_prg_exec_monitor.so.*
        - /usr/lib64/libboost_unit_test_framework.so.*
    - thread :
        - /usr/lib64/libboost_thread.so.*
    - timer :
        - /usr/lib64/libboost_timer.so.*
    - type-erasure :
        - /usr/lib64/libboost_type_erasure.so.*
    - url :
        - /usr/lib64/libboost_url.so.*
    - wave :
        - /usr/lib64/libboost_wave.so.*
