# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xsimd
version    : 14.2.0
release    : 1
source     :
    - https://github.com/xtensor-stack/xsimd/archive/refs/tags/14.2.0.tar.gz : 21e841ab684b05331e81e7f782431753a029ef7b7d9d6d3ddab837e7782a40ee
homepage   : https://github.com/xtensor-stack/xsimd 
license    : BSD-3-Clause
component  : programming.library
summary    : C++ wrappers for SIMD intrinsics and parallelized, optimized mathematical functions
description: |
    xsimd provides a unified means for using SIMD features for library authors. Namely, it enables manipulation of batches of numbers with the same arithmetic operators as for single values. It also provides accelerated implementation of common mathematical functions operating on batches. 
builddeps  :
    - pkgconfig(xtl)
setup      : |
    %cmake_ninja -L \
      -DENABLE_XTL_COMPLEX=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
patterns   : /*
