# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : draco
version    : 1.5.7
release    : 4
source     :
    - https://github.com/google/draco/archive/refs/tags/1.5.7.tar.gz : bf6b105b79223eab2b86795363dfe5e5356050006a96521477973aba8f036fe1
homepage   : https://google.github.io/draco/
license    : Apache-2.0
component  : multimedia.library
summary    : Draco 3D data compressor
description: |
    Draco is an open-source library for compressing and decompressing 3D geometric meshes and point clouds. It is intended to improve the storage and transmission of 3D graphics.
setup      : |
    %cmake_ninja \
        -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
        -DCMAKE_UNITY_BUILD=ON \
        -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/lib*/*.a
    %install_license LICENSE
