# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kpipewire
version    : 6.6.5
release    : 65
source     :
    - https://download.kde.org/stable/plasma/6.6.5/kpipewire-6.6.5.tar.xz : 7aed7f721c5ba05f20812ea8cde047dcc6e3375ba521bbddd82c25915abf334d
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.kde.core
summary    : Components relating to pipewire use in Plasma
description: |
    Components relating to pipewire use in Plasma
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(epoxy)
    - pkgconfig(gbm)
    - pkgconfig(libavcodec)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libva)
    - extra-cmake-modules
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        # For epoxy/egl.h
        - libepoxy-devel
        - pipewire-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
