# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kauth
version    : 6.28.0
release    : 36
source     :
    - https://download.kde.org/stable/frameworks/6.28/kauth-6.28.0.tar.xz : fb4d90ee46a2f6202e53cdd5af8f77069c380955e3f340881f2f36ec8312079b
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(polkit-qt6-1)
    - kf6-kcoreaddons-devel
rundeps    :
    - devel :
        - kf6-kcoreaddons-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
