# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kauth
version    : 6.27.0
release    : 35
source     :
    - https://download.kde.org/stable/frameworks/6.27/kauth-6.27.0.tar.xz : 741934765f0c9f1c535598203fbad3f1b97231cc683a218a7f39fab948c13eab
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(polkit-qt6-1)
    - kf6-kcoreaddons-devel
rundeps    :
    - devel :
        - kf6-kcoreaddons-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
