# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-fonttools
version    : 4.63.0
release    : 10
source     :
    - https://github.com/fonttools/fonttools/archive/refs/tags/4.63.0.tar.gz : fa9b285d407536e620b02365adb2c911d9d93237ea66404dfbbeb197199b9c8e
homepage   : https://github.com/fonttools/fonttools
license    : MIT
component  : programming.python
summary    : Tools to manipulate font files
description: |
    fontTools is a library for manipulating fonts, written in Python. The project includes the TTX tool, that can convert TrueType and OpenType fonts to and from an XML text format, which is also called TTX. It supports TrueType, OpenType, AFM and to an extent Type 1 and some Mac-specific formats.
builddeps  :
    - cython
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - python-brotli
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v --deselect Tests/svgLib/path/path_test
