# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : cppcheck
version    : 2.20.0
release    : 37
source     :
    - https://github.com/danmar/cppcheck/archive/refs/tags/2.20.0.tar.gz : 7be7992439339017edb551d8e7d2315f9bb57c402da50c2cee9cd0e2724600a1
homepage   : https://cppcheck.sourceforge.io/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Static source code analysis tool for C and C++ code
description: |
    Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives).
builddeps  :
    - pkgconfig(Qt6Gui)
    - pkgconfig(Qt6Linguist)
    - pcre2
patterns   :
    - gui  :
        - /usr/bin/cppcheck-gui
        - /usr/share/Cppcheck/lang/*
        - /usr/share/applications/*
        - /usr/share/icons/*
setup      : |
    %patch -p1 -i $pkgfiles/cppcheck-2.11-translations.patch
    %cmake_ninja . -DBUILD_TESTS=ON -DHAVE_RULES=OFF -DUSE_MATCHCOMPILER=On -DBUILD_GUI=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
