# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libnova
version    : 0.16
release    : 1
source     :
    - git|https://git.code.sf.net/p/libnova/libnova.git : v0.16
homepage   : http://libnova.sourceforge.net/
license    : LGPL-2.0-or-later
component  : programming.library
summary    : Celestial Mechanics, Astrometry and Astrodynamics Library
description: |
    libnova is a general purpose, double precision, Celestial Mechanics, Astrometry and Astrodynamics library.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install

    rm -v $installdir/%libdir%/*.a

    %install_license COPYING
patterns   :
    - devel :
        - /usr/bin/libnovaconfig
