# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : voikko-fi
version    : '2.6'
release    : 4
source     :
    - https://www.puimula.org/voikko-sources/voikko-fi/voikko-fi-2.6.tar.gz : 5c147c1c92323941e5847b5c46d00b35ff6b62dc3cf348516bc0fbdc87340220
homepage   : https://voikko.puimula.org/
license    : GPL-2.0
component  : office
summary    : Voikko-fi (previously know as Suomi-malaga) is a description of Finnish morphology written for libvoikko.
description: |
    Voikko-fi (previously know as Suomi-malaga) is a description of Finnish morphology written for libvoikko.
builddeps  :
    - pkgconfig(libvoikko)
    - foma-devel
rundeps    :
    - foma
    - libvoikko
build      : |
    %make vvfst
install    : |
    %make DESTDIR="$installdir/usr/share/voikko/" vvfst-install
    %install_license COPYING
