# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libgpg-error
version    : '1.59'
release    : 27
source     :
    - https://gnupg.org/ftp/gcrypt/gpgrt/libgpg-error-1.59.tar.bz2 : a19bc5087fd97026d93cb4b45d51638d1a25202a5e1fbc3905799f424cfa6134
license    : LGPL-2.1-or-later
component  : system.base
devel      : true
emul32     : true
homepage   : https://www.gnupg.org
summary    : library with error codes for GnuPG related software
description: |
    Libgpg-error is a small library with error codes and descriptions shared by most GnuPG related software.
setup      : |
    %apply_patches
    %reconfigure --disable-static \
                 --enable-install-gpg-error-config
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
patterns   :
    - devel : /usr/share/aclocal
