# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dash
version    : 0.5.13.3
release    : 19
source     :
    - https://git.kernel.org/pub/scm/utils/dash/dash.git/snapshot/dash-0.5.13.3.tar.gz : f7ab491177d696e42f93342abe9eb6d183adbd066e37e26056e0fa91e2f29c00
homepage   : https://git.kernel.org/pub/scm/utils/dash/dash.git/
license    : GPL-3.0-or-later
component  : system.utils
summary    : POSIX compliant shell
description: |
    Dash is a POSIX compliant shell. It can be installed as /bin/sh or as the default shell for either root or a second user with a userid of 0. It depends on fewer libraries than the Bash shell and is therefore less likely to be affected by an upgrade problem or disk failure. Dash is also useful for checking that a script is completely compatible with POSIX syntax.
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig(libedit)
setup      : |
    %reconfigure --with-libedit
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
