# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : stripe-cli
version    : 1.50.11
release    : 4
source     :
    - https://github.com/stripe/stripe-cli/archive/refs/tags/v1.50.11.tar.gz : 60571665ca0b7021a33a90a0b99adf7d13cbb6f9d28a398a9ac80d646a303f11
homepage   : https://stripe.com
license    : Apache-2.0
component  : programming.tools
summary    : Stripe command line interface (CLI) allows you to build, test, and manage your Stripe integration.
description: |
    The Stripe CLI helps you build, test, and manage your Stripe integration right from the terminal. It lets you securely test webhooks without relying on 3rd party software, trigger webhook events or resend events for easy testing, tail your API request logs in real-time, create, retrieve, update, or delete API objects.
networking : true
builddeps  :
    - golang
setup      : |
    %patch -p1 -i $pkgfiles/0001-version.patch
build      : |
    %make
install    : |
    %install_bin ./stripe
    %install_license LICENSE
