# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libqalculate
version    : 5.11.0
release    : 30
source     :
    - https://github.com/Qalculate/libqalculate/releases/download/v5.11.0/libqalculate-5.11.0.tar.gz : 6217a634eeb9659ebb4080c265dfab47d8f8dd4c33394b48fd5a1f83ef4538c4
homepage   : https://qalculate.github.io/
license    : GPL-2.0-or-later
component  :
    - ^qalculate : programming.tools
    - programming.library
summary    :
    - ^qalculate : Multi-purpose calculator, text mode interface
    - Qalculate! library
description:
    - ^qalculate : Multi-purpose calculator, text mode interface
    - Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple to use but provides power and versatility normally reserved for complicated math packages, as well as useful tools for everyday needs (such as currency conversion and percent calculation). Features include a large library of customizable functions, unit calculations and conversion, symbolic calculations (including integrals and equations), arbitrary precision, interval arithmetic, plotting, and a user-friendly interface.
builddeps  :
    - pkgconfig(icu-uc)
    - pkgconfig(libcurl)
rundeps    :
    - gnuplot
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
patterns   :
    - ^qalculate :
        - /usr/bin/qalc
        - /usr/share/man/man1/qalc*
