# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : rocthrust
version    : '7.14'
release    : 5
source     :
    - https://github.com/ROCm/rocm-libraries/archive/refs/tags/therock-7.14.tar.gz : 
        7bd30a64e1ac823861db07d9fe115256a16f02c527de49a6ecbdbbcb4018c0d8
homepage   : https://github.com/ROCmSoftwarePlatform/rocThrust
license    : MIT
component  : programming.library
summary    : ROCm Thrust - run Thrust dependent software on AMD GPUs
description: |
    Thrust is a parallel algorithm library. This library has been ported to HIP/ROCm platform, which uses the rocPRIM library. The HIP ported library works on HIP/ROCm platforms. Currently there is no CUDA backend in place.
clang      : true
builddeps  :
    - rocm-cmake
    # We don't build anything, but CMake still checks for HIP
    - rocm-hip
    - rocm-llvm
    - rocprim
environment: |
    export ROCM_PATH=/usr
    export HIP_DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
    export HIP_CLANG_PATH=/usr/lib64/llvm-rocm/bin
setup      : |
    sed -i 's|set(ROCM_INSTALL_LIBDIR lib)|set(ROCM_INSTALL_LIBDIR ${CMAKE_INSTALL_LIBDIR})|' projects/rocthrust/cmake/ROCMExportTargetsHeaderOnly.cmake

    %cmake_ninja -S projects/rocthrust -L \
      -DCMAKE_CXX_COMPILER=amdclang++ \
      -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
      -DROCM_SYMLINK_LIBS=OFF
install    : |
    %ninja_install
patterns   : /*
