# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hunspell-uk
version    : 6.8.5
release    : 16
source     :
    - https://github.com/brown-uk/dict_uk/releases/download/v6.8.5/hunspell-uk_UA_6.8.5.zip : 25563d417d1c114a9fb9cbca1b23a68289f7c2c7e0d622429b42b1ddededa12a
homepage   : https://github.com/brown-uk/dict_uk/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : office.spelling
summary    : Ukrainian hunspell dictionary
description: |
    Ukrainian spelling dictionary for hunspell.
install    : |
    %install_file uk_UA.{aff,dic} -t $installdir/usr/share/hunspell
