# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hunspell-uk
version    : 6.8.0
release    : 15
source     :
    - https://github.com/brown-uk/dict_uk/releases/download/v6.8.0/hunspell-uk_UA_6.8.0.zip : bf1e25cccec616b3fd64d3509184f654c55b789931c5166c9677ca6de42b491d
homepage   : https://github.com/brown-uk/dict_uk/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : office.spelling
summary    : Ukrainian hunspell dictionary
description: |
    Ukrainian spelling dictionary for hunspell.
install    : |
    install -Dm00644 uk_UA.{aff,dic} -t $installdir/usr/share/hunspell
