# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-business-issn
version    : '1.008'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/B/BR/BRIANDFOY/Business-ISSN-1.008.tar.gz : b16b3a1b0e53cd45ed3328906d33ad4d59a13b57abf341424553aecf3e443aac
homepage   : https://metacpan.org/pod/Business::ISSN
license    : Artistic-2.0
component  : programming.perl
summary    : Business::ISSN - Perl extension for International Standard Serial Numbers
description: |
    Business::ISSN - Perl extension for International Standard Serial Numbers
checkdeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
check      : |
    %perl_build test
patterns   : /*
