# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-grpcio
version    : 1.81.1
release    : 17
source     :
    - https://pypi.io/packages/source/g/grpcio/grpcio-1.81.1.tar.gz : 6fa10a767143a5e82e8eaab53918af0cd8909a57a27f8cb2288b80a613ac671b
homepage   : https://github.com/grpc/grpc
license    : Apache-2.0
component  : programming.python
summary    : HTTP/2-based RPC framework
description: |
    gRPC is a modern, open source, high-performance remote procedure call (RPC) framework that can run anywhere. gRPC enables client and server applications to communicate transparently, and simplifies the building of connected systems.
builddeps  :
    - pkgconfig(python3)
    - cython
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
build      : |
    sed -i 's/cython==3.1.1/cython>=3.1.1/' pyproject.toml
    %python3_setup
install    : |
    %python3_install
