# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ocean-sound-theme
version    : 6.7.1
release    : 47
source     :
    - https://download.kde.org/stable/plasma/6.7.1/ocean-sound-theme-6.7.1.tar.xz : 7ff1b7371fc63eaa9b98475095918030a9438aae67d32c66ee0cb4d72372d625
homepage   : https://kde.org/plasma-desktop
license    :
    - BSD-2-Clause
    - CC0-1.0
    - CC-BY-SA-4.0
component  : desktop
summary    : Ocean Sound Theme for Plasma
description: |
    Ocean Sound Theme for Plasma
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
