# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ocean-sound-theme
version    : 6.7.2
release    : 48
source     :
    - https://download.kde.org/stable/plasma/6.7.2/ocean-sound-theme-6.7.2.tar.xz : 791cb35d4bd7c8cc6adcacca92bd84d659218008a0e32b0bb0a5b7674176fb1a
homepage   : https://kde.org/plasma-desktop
license    :
    - BSD-2-Clause
    - CC0-1.0
    - CC-BY-SA-4.0
component  : desktop
summary    : Ocean Sound Theme for Plasma
description: |
    Ocean Sound Theme for Plasma
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
