name       : ocean-sound-theme
version    : 6.3.1
release    : 24
source     :
    - https://download.kde.org/stable/plasma/6.3.1/ocean-sound-theme-6.3.1.tar.xz : 170b2371bc4a9a1263f778714a2ccbf47af7c63b4de975b29b07b036ddfcedc1
homepage   : https://kde.org/plasma-desktop
license    :
    - BSD-2-Clause
    - CC-BY-SA-4.0
    - CC0-1.0
component  : desktop
summary    : Ocean Sound Theme for Plasma
description: |
    Ocean Sound Theme for Plasma
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
