# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kdbusaddons
version    : 6.26.0
release    : 37
source     :
    - https://download.kde.org/stable/frameworks/6.26/kdbusaddons-6.26.0.tar.xz : 894bb2e032c6f6d9b4a58b8b24678692a9f4e70e953ff4dabda2ed4e9b5431e2
homepage   : https://community.kde.org/Frameworks
license    :
    - CC0-1.0
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Convenience classes for DBus.
description: |
    Convenience classes for DBus.
builddeps  :
    - pkgconfig(Qt6Designer)
    - extra-cmake-modules
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-tools-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
