# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : cargo-audit
version    : 0.22.2
release    : 4
source     :
    - https://github.com/rustsec/rustsec/archive/refs/tags/cargo-audit/v0.22.2.tar.gz : 85c368a4d166b2cc4972108d50abc5fad605013b65098929a06122439488beb5
license    :
    - Apache-2.0
    - MIT
component  : security
homepage   : https://github.com/RustSec/cargo-audit
summary    : Audit Cargo.lock for crates with security vulnerabilities
description: |
    Audit Cargo.lock for crates with security vulnerabilities
builddeps  :
    - rust
networking : true
setup      : |
    %cargo_fetch
build      : |
    %cargo_build --features fix
install    : |
    %cargo_install
    %install_license cargo-audit/LICENSE-*
check      : |
    %cargo_test --  \
    --skip "cvss_v3_random" \
    --skip "cvss_v3_simple" \
    --skip "cvss_v4_base" \
    --skip "cvss_v4_modified" \
    --skip "cvss_v4_random" \
    --skip "cvss_v4_security" \
    --skip "cvss_v4_supplemental" \
    --skip "cvss_v4_threat" \
