name       : xfce4-dev-tools
version    : 4.19.4
release    : 3
source     :
    - https://archive.xfce.org/xfce/4.20pre1/src/xfce4-dev-tools-4.19.4.tar.bz2 : 18cd68b2b077b8fa4443d7111c54657f67c6f131b226322a809b27f4327cb9ca
homepage   : https://docs.xfce.org/xfce/xfce4-dev-tools/start
license    : GPL-2.0-or-later
component  : desktop.xfce.core
summary    : The Xfce development tools are a collection of tools and macros for Xfce developers.
description: |
    The Xfce development tools are a collection of tools and macros for Xfce developers.
builddeps  :
    - pkgconfig(glib-2.0)
    - gtk-doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
