# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-rich-click
version    : 1.9.9
release    : 1
source     :
    - https://github.com/ewels/rich-click/archive/refs/tags/v1.9.9.tar.gz : fd6df55fb03b09f4e6251628aba08397ce28c3418fe6cac3a0f28731833dca60
homepage   : https://ewels.github.io/rich-click/
license    : MIT
component  : programming.python
summary    : Format click help output nicely with rich
description: |
    rich-click is a wrapper around Click that renders help output nicely using Rich.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - python-click
    - python-rich
build      : |
    %python3_setup
install    : |
    %python3_install
