# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : vhs
version    : 0.12.1
release    : 3
source     :
    - https://github.com/charmbracelet/vhs/archive/refs/tags/v0.12.1.tar.gz : ba9fbcb40133d1734c580ccb6b0fcae9673bf51d227f00877ac581c56ad15b77
homepage   : https://github.com/charmbracelet/vhs
license    : MIT
component  : programming.tools
summary    : Your CLI home video recorder
description: |
    Write terminal GIFs as code for integration testing and demoing your CLI tools.
networking : true
builddeps  :
    - golang
rundeps    :
    - ffmpeg
    - ttyd
setup      : |
    go mod vendor
build      : |
    export GOFLAGS="-buildmode=pie -trimpath -mod=vendor -modcacherw"
    # Refresh embedded themes (see Makefile)
    %make all

    go build -v -ldflags "-linkmode=external -X main.Version=%version%" -o vhs .

    # Generate shell completions and manual page artifacts.
    ./vhs completion bash > vhs.bash
    ./vhs completion zsh > _vhs
    ./vhs completion fish > vhs.fish
    ./vhs manual > vhs.1
install    : |
    %install_license LICENSE
    %install_exe vhs ${installdir}/usr/share/vhs/vhs
    %install_exe ${pkgfiles}/vhs.sh ${installdir}/usr/bin/vhs

    # Completions and man page
    %install_file vhs.bash ${installdir}/usr/share/bash-completion/completions/vhs
    %install_file _vhs ${installdir}/usr/share/zsh/site-functions/_vhs
    %install_file vhs.fish ${installdir}/usr/share/fish/vendor_completions.d/vhs.fish
    %install_file vhs.1 ${installdir}/usr/share/man/man1/vhs.1
