# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : source-code-pro
version    : '2.038'
release    : 7
source     :
    - https://github.com/adobe-fonts/source-code-pro/archive/refs/tags/2.038R-ro/1.058R-it/1.018R-VAR.tar.gz : d8f879fefd66ecb7291ea2d73984b9c0a97fb499424e58290ba6b81787d0c725
license    : OFL-1.1-RFN
component  : desktop.font
homepage   : https://fonts.adobe.com/fonts/source-code-pro
summary    : Source Code Pro Font Set
description: |
    Source Code Pro Font Set
install    : |
    %install_dir $installdir/usr/share/fonts/truetype/source-code-pro
    %install_file TTF/*.ttf %installroot%/usr/share/fonts/truetype/source-code-pro/
    %install_file $pkgfiles/source-code-pro.metainfo.xml $installdir/usr/share/metainfo/source-code-pro.metainfo.xml
    %install_license LICENSE.md
