TOPLVL = $(abspath ".")

SHELL = /bin/bash

.PHONY: help

help:
	@echo "clone     - Clone all repos"
	@echo "cvecheck  - Check all packages for CVEs"
	@echo "pull      - Pull all repos"

clone:
	@bash $(TOPLVL)/common/Scripts/clone_repos.sh

pull:
	@bash $(TOPLVL)/common/Scripts/pull_repos.sh

cvecheck:
	cve-check-tool -n $(TOPLVL)/common/packages -M $(TOPLVL)/common/mapping -o report.html; \
