SHELL = /bin/bash
TOPLVL = "../."

build:
	sudo python $(TOPLVL)/common/image/solus-image-creator.py

pull:
	git pull --rebase

help:
	@echo "build     - Build the current ISO"
	@echo "pull      - Pull/rebase latest changes"


.PHONY:
	build
