# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : jellyfin-desktop
version    : 2.0.0
release    : 1
source     :
    - git|https://github.com/jellyfin/jellyfin-desktop.git : v2.0.0
homepage   : https://jellyfin.org/
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : Jellyfin Desktop Client
description: |
    Desktop client using jellyfin-web with embedded MPV player. Media plays within the same window using the jellyfin-web interface. Supports audio passthrough.
builddeps  :
    - pkgconfig(Qt6DBus)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6WebChannel)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(Qt6WebEngineQuick)
    - pkgconfig(libcec)
    - pkgconfig(mpv)
    - pkgconfig(python3)
    - pkgconfig(sdl2)
    - pkgconfig(xrandr)
    - mpvqt-devel
    - qt6-base-private-devel
rundeps    :
    - qt6-declarative
clang      : true
optimize   :
    - thin-lto
setup      : |
    %patch -p1 -i ${pkgfiles}/0001-Fix-build-with-mpvqt-1.2.0.patch
    %cmake_ninja \
        -DCHECK_FOR_UPDATES=OFF \
        -DUSE_STATIC_MPVQT=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
replaces   :
    - jellyfin-media-player
    - dbginfo : jellyfin-media-player-dbginfo
