# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : keychain
version    : 3.0.4
release    : 4
source     :
    - https://github.com/danielrobbins/keychain/archive/refs/tags/3.0.4.tar.gz : e38da6a078d187de13615fafb878167fd1fa1c4c9c466e100ead1981be5f12b7
homepage   : https://kernel-seeds.org/projects/keychain/
license    : GPL-3.0-or-later
component  : network.util
summary    : agent manager for ssh and gnupg
description: |
    Helps you to manage ssh and GPG keys in a convenient and secure manner. It acts as a frontend to ssh-agent and ssh-add, but allows you to easily have one long running ssh-agent process per system, rather than the norm of one ssh-agent per login session.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-setuptools
    - python-wheel
rundeps    :
    - python3
checkdeps  :
    - openssh
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest
