# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : sddm-kcm
version    : 6.7.1
release    : 134
source     :
    - https://download.kde.org/stable/plasma/6.7.1/sddm-kcm-6.7.1.tar.xz : bf0a4475f684e7d5cc390e005fe3d1bf25dbc0ffa4a34814b6a9e1748596c71e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - CC0-1.0
    - GPL-2.0-or-later
    - GPL-3.0-only
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(xcb-cursor)
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
