# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : niri
version    : '26.04'
release    : 6
source     :
    - https://github.com/niri-wm/niri/archive/refs/tags/v26.04.tar.gz : 134c602d8e0d53413a52d6cd58f9ce7e79a07d03288ee0a51ba1abd5db1b1ad9
homepage   : https://niri-wm.github.io/niri/
license    : GPL-3.0-or-later
component  : desktop
summary    :
    - session : Session files for Niri
    - A scrollable-tiling Wayland compositor
description:
    - session : Session files for Niri.
    - A scrollable-tiling Wayland compositor.
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(libdisplay-info)
    - pkgconfig(libinput)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libseat)
    - pkgconfig(pangocairo)
    - pkgconfig(xkbcommon)
    - rust
checkdeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
rundeps    :
    - session :
        - niri
    - xdg-desktop-portal-gnome
    - xwayland-satellite
networking : true
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
    %install_license LICENSE

    install -Dm00755 -t $installdir/usr/bin resources/niri-session
    install -Dm00644 -t $installdir/usr/share/wayland-sessions resources/niri.desktop
    install -Dm00644 -t $installdir/usr/share/xdg-desktop-portal resources/niri-portals.conf

    install -Dm00644 -t $installdir/usr/lib/systemd/user resources/niri.service
    install -Dm00644 -t $installdir/usr/lib/systemd/user resources/niri-shutdown.target
check      : |
    # Exclude tests that require a session.
    # Limit threads to avoid too many open files error.
    export RAYON_NUM_THREADS=2
    %cargo_test --exclude niri-visual-tests -- --test-threads 2
patterns   :
    - session :
        - /usr/bin/niri-session
        - /usr/share/wayland-sessions/niri.desktop
