# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-data-uuid
version    : '1.227'
release    : 10
source     :
    - https://github.com/rjbs/Data-UUID/archive/1.227.tar.gz : 0b8901706a0cedca2c3632ecdc46ec5f20118a4c60406b36e59286acd00043e3
homepage   : https://github.com/rjbs/Data-UUID
license    : BSD-4-Clause
component  : programming.perl
summary    : Perl extension for generating Globally/Universally Unique Identifiers
description: |
    This module provides a framework for generating UUIDs (Universally Unique Identifiers, also known as GUIDs (Globally Unique Identifiers).
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
check      : |
    %perl_build test
patterns   : /*
