# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libkgapi
version    : 26.08.1
release    : 104
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/libkgapi-26.08.1.tar.xz : 435dd7b20d0547d45627a471e12d9695119dc044f770046cb33017757af375de
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.1-or-later
    - LGPL-3.0-only
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(KF6CalendarCore)
    - pkgconfig(libsasl2)
    - kf6-kcontacts-devel
    - kf6-kwallet-devel
rundeps    :
    - devel :
        - kf6-kcalendarcore-devel
        - kf6-kcontacts-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
