# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : synfig
version    : 1.5.5
release    : 38
source     :
    - https://github.com/synfig/synfig/releases/download/v1.5.5/synfig-1.5.5.tar.gz : 95783c92925bd8ae494e00fdab0340caba9b19d2a0aac989fd8c200434b26f06
homepage   : https://www.synfig.org/
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : Renderer used to convert .sif files to raster images
description: |
    Renderer used to convert synfig .sif files to raster images, videos and other formats.
builddeps  :
    - pkgconfig(ETL)
    - pkgconfig(Magick++)
    - pkgconfig(OpenEXR)
    - pkgconfig(fftw3)
    - pkgconfig(fontconfig)
    - pkgconfig(fribidi)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(harfbuzz)
    - pkgconfig(libavcodec)
    - pkgconfig(libjpeg)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(mlt++-7)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
check      : |
    %make check
