# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : fcft
version    : 3.3.3
release    : 3
source     :
    - https://codeberg.org/dnkl/fcft/releases/download/3.3.3/fcft-3.3.3.tar.gz : bb298772d625e7d917373d541456f34f1957a9e22b16f17f64158b2c3816563c
homepage   : https://codeberg.org/dnkl/fcft
license    : MIT
component  : desktop.library
summary    : A simple library for font loading and glyph rasterization using FontConfig, FreeType and pixman
description: |
    A simple library for font loading and glyph rasterization using FontConfig, FreeType and pixman.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(libutf8proc)
    - pkgconfig(pixman-1)
    - pkgconfig(tllist)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
    %install_license LICENSE
