# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hipcub
version    : '7.14'
release    : 8
source     :
    - https://github.com/ROCm/rocm-libraries/archive/refs/tags/therock-7.14.tar.gz : 
        7bd30a64e1ac823861db07d9fe115256a16f02c527de49a6ecbdbbcb4018c0d8
homepage   : https://github.com/ROCmSoftwarePlatform/hipCUB
license    : MIT
component  : programming.library
summary    : Reusable software components for ROCm developers
description: |
    hipCUB is a thin wrapper library on top of rocPRIM or CUB. It enables developers to port a project using the CUB library to the HIP layer to run on AMD hardware. In the ROCm environment, hipCUB uses the rocPRIM library as the backend. However, on CUDA platforms it uses CUB instead.
clang      : true
builddeps  :
    - rocprim
    - rocm-cmake
    - rocm-hip
    - rocm-llvm
environment: |
    export CXXFLAGS="${CXXFLAGS/-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32/-fcf-protection=none}"

    export ROCM_PATH=/usr
    export HIP_CLANG_PATH=/usr/lib64/llvm-rocm/bin
    export HIP_DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
setup      : |
    pushd projects/hipcub
        sed -i 's|set(ROCM_INSTALL_LIBDIR lib)|set(ROCM_INSTALL_LIBDIR lib%LIBSUFFIX%)|' cmake/ROCMExportTargetsHeaderOnly.cmake
    popd

    %cmake_ninja projects/hipcub -L \
      -DCMAKE_CXX_COMPILER=amdclang++ \
      -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
      -DROCM_SYMLINK_LIBS=OFF \
      -DAMDGPU_TARGETS="%AMDGPUTARGETS%"
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   : /*
