# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-qt-material
version    : 2.17
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/q/qt-material/qt_material-2.17.tar.gz : b500a0c1f5ef8f46a8cf037d1aa5bdf9ea4eb618180b6332539dfbdd0647ad0d
homepage   : https://github.com/dunderlab/qt-material
license    : BSD-2-Clause
component  : programming.python
summary    : Material inspired stylesheet for PySide6 and PyQt6
description: |
    This is another stylesheet for PySide6 and PyQt6, which looks like Material Design (close enough).
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
rundeps    :
    - python-jinja
build      : |
    %python3_setup
install    : |
    %python3_install
