# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-keyboard
version    : 6.6.2
release    : 2
source     :
    - https://download.kde.org/stable/plasma/6.6.2/plasma-keyboard-6.6.2.tar.xz : 500a28f8cf92afe5f38d9a89f733441c72201d3ce45b92f12c3bfc98155b5cb7
homepage   : https://kde.org/plasma-desktop/
license    :
    - CC0-1.0
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - GPL-3.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.kde
summary    : Virtual keyboard for Plasma
description: |
    Virtual keyboard for Plasma
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6VirtualKeyboard)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(wayland-protocols)
    - extra-cmake-modules
    - kf6-kcmutils-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    %install_license LICENSES/*
