# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : alsa-lib
version    : 1.2.15.3
release    : 42
source     :
    - https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.15.3.tar.bz2 : 7b079d614d582cade7ab8db2364e65271d0877a37df8757ac4ac0c8970be861e
    - https://www.alsa-project.org/files/pub/lib/alsa-topology-conf-1.2.5.1.tar.bz2 : f7c5bae1545abcd73824bc97f4e72c340e11abea188ba0f1c06f5e0ad776b179
homepage   : https://www.alsa-project.org
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : The ALSA Sound Interface
description: |
    The ALSA Library package contains the ALSA library used by programs (including ALSA Utilities) requiring access to the ALSA sound interface.
emul32     : true
rundeps    :
    - alsa-ucm-conf
setup      : |
    %patch -p1 -i $pkgfiles/0001-Support-a-stateless-configuration.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
    install -Dm00644 $pkgfiles/asound.conf $installdir/usr/share/defaults/alsa/asound.conf
    install -dm00755 $installdir/usr/share/alsa/topology
    install -dm00755 $installdir/usr/share/licenses/alsa-topology
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        pushd $installdir/usr/share/alsa/
        tar xvjf $sources/alsa-topology-conf-*.tar.bz2 --strip-components=1
         install -Dm00644 LICENSE $installdir/usr/share/licenses/alsa-topology
        find -path "*.md" -prune -exec rm -r '{}' \; \
            -or -name "LICENSE" -prune -exec rm -r '{}' \;
        popd
    fi
check      : |
    # Fails on test/lsb so just ignore
    %make check || :
patterns   :
    - devel : /usr/share/aclocal/alsa.m4
