# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : newsboat
version    : '2.45'
release    : 13
source     :
    - https://github.com/newsboat/newsboat/archive/refs/tags/r2.45.tar.gz : 2efe2b0e86ac1c0e58e1a619a27edb7aa56e58d75381edd0e2ea0ec2e11e37d9
homepage   : https://newsboat.org/
license    : MIT
component  : network.news
summary    : RSS/Atom feed reader for the text console
description: |
    Newsboat is an RSS/Atom feed reader for the text console. It's an actively maintained fork of Newsbeuter.
networking : true
builddeps  :
    - pkgconfig(json-c)
    - pkgconfig(libcurl)
    - pkgconfig(libxml-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(stfl)
    - asciidoctor
    - gawk
    - gettext
    - rust
setup      : |
    ./config.sh
build      : |
    %make prefix=/usr
install    : |
    %make_install prefix=/usr
    %install_license LICENSE
