# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : stellarsolver
version    : '2.8'
release    : 4
source     :
    - https://github.com/rlancaste/stellarsolver/archive/refs/tags/2.8.tar.gz : 1456cac5cd67353e19e1c6e57546af052a9302b7fbe2deaa649a44eec45fbec8
homepage   : https://github.com/rlancaste/stellarsolver
license    : GPL-3.0-or-later
component  : office.scientific
summary    : The Cross Platform SEP-based Star Extractor and Astrometry.net-Based Internal Astrometric Solver
description: |
    The Cross Platform SEP-based Star Extractor and Astrometry.net-Based Internal Astrometric Solver
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(cfitsio)
    - pkgconfig(gsl)
    - pkgconfig(wcslib)
setup      : |
    %cmake_ninja -DUSE_QT5=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
