# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kirigami-app-components
version    : 1.1.0
release    : 2
source     :
    - https://download.kde.org/stable/kirigami-app-components/kirigami-app-components-1.1.0.tar.xz : f83f92ecfab89fa8b75867c47c291f1619e1a3970afc30437b3374aa75f6530f
homepage   : https://invent.kde.org/libraries/kirigami-app-components
license    :
    - BSD-3-Clause
    - CC0-1.0
    - FSFAP
    - LGPL-2.0-or-later
    - LGPL-2.1
component  : programming.library
summary    : Kirigami addons and modules necessary to do a full featured KDE application
description: |
    Kirigami addons and modules necessary to do a full featured KDE application
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6QmlCore)
    - kf6-kconfig-devel
    - kf6-kguiaddons-devel
    - kf6-ki18n-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
setup      : |
    %cmake_ninja
build      : |
    %cmake_build
install    : |
    %cmake_install
    %install_license LICENSES/*
