# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kirigami-app-components
version    : 1.0.2
release    : 1
source     :
    - https://download.kde.org/stable/kirigami-app-components/kirigami-app-components-1.0.2.tar.xz : 6bfd9e0a3a4b7d17505f0c3c0c395628165973b6f4cf1e4a7a1f3342873b44d0
homepage   : https://invent.kde.org/libraries/kirigami-app-components
license    :
    - BSD-3-Clause
    - CC0-1.0
    - FSFAP
    - LGPL-2.0-or-later
    - LGPL-2.1
component  : programming.library
summary    : Kirigami addons and modules necessary to do a full featured KDE application
description: |
    Kirigami addons and modules necessary to do a full featured KDE application
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6QmlCore)
    - kf6-kconfig-devel
    - kf6-kguiaddons-devel
    - kf6-ki18n-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
setup      : |
    %cmake_ninja
build      : |
    %cmake_build
install    : |
    %cmake_install
    %install_license LICENSES/*
