# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-test-deep
version    : '1.205'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Test-Deep-1.205.tar.gz : 42781e9943a7a215e662c4973b9feafdc019fd16469bdb849a8537ee58956273
homepage   : https://metacpan.org/pod/Test::Deep
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : This module gives you lots of flexibility when testing deep structres
description: |
    This module gives you lots of flexibility when testing deep structres.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
patterns   : /*
