# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : helvum
version    : 0.6.2
release    : 2
source     :
    - https://gitlab.freedesktop.org/-/project/8123/uploads/720b9e2789c0cc37aae18bd91c9fa153/helvum-0.6.2.tar.xz : 288a9c94ddc507b1f85e576c3042ed795584cc09b05894e6bc7fdaaed9ff10ee
homepage   : https://gitlab.freedesktop.org/pipewire/helvum
license    : GPL-3.0-only
component  : multimedia.audio
summary    : GTK patchbay for PipeWire
description: |
    GTK patchbay for PipeWire
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libpipewire-0.3)
    - desktop-file-utils
    - rust
clang      : true
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
