# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : sdl3-ttf
version    : 3.2.2
release    : 1
source     :
    - https://github.com/libsdl-org/SDL_ttf/archive/refs/tags/release-3.2.2.tar.gz : ff6b81d3dc39d843cc3ead6dedd68043a79513d266792ea89445547ef4e9b073
homepage   : https://www.libsdl.org/
license    : Zlib
component  : multimedia.library
summary    : A sample library which allows you to use TrueType fonts in SDL3 applications.
description: |
    A sample library which allows you to use TrueType fonts in SDL3 applications.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(harfbuzz)
    - pkgconfig(sdl3)
    - pkgconfig(xshmfence)
optimize   :
    - speed
setup      : |
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DSDLTTF_VENDORED=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE.txt
