# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kgpg
version    : 26.08.1
release    : 84
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/kgpg-26.08.1.tar.xz : 76b71fa853e24d6ab521caaf0e180faca06aa5a0e4103c78a59bc932f4c55381
homepage   : https://kde.org/applications/utilities/org.kde.kgpg
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
component  : desktop.kde
summary    : Graphical interface for GnuPG
description: |
    KGpg is a GUI frontend for GnuPG based on the KDE stack.
builddeps  :
    - akonadi-contacts-devel
    - gpgme-devel
    - kf6-karchive-devel
    - kf6-kcontacts-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-ktextwidgets-devel
    - kf6-kxmlgui-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*

    # remove doc
    rm -rfv $installdir/usr/share/doc
