# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : groff
version    : 1.24.2
release    : 8
source     :
    - https://ftpmirror.gnu.org/gnu/groff/groff-1.24.2.tar.gz : f9c1efd5bebbe37fc6e1063db7473ce8df1e3e0be4ff0f43ce04fce57e9c5dd9
homepage   : https://www.gnu.org/software/groff/
license    : GPL-3.0-or-later
summary    : groff (Typesetting package to read formatted files)
component  : desktop.core
description: |
    groff (GNU troff) is a typesetting package which reads plain text mixed with formatting commands and produces formatted output
setup      : |
    %configure \
        --with-awk=/usr/bin/awk \
        --with-gnu-ld \
        --without-x
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING LICENSES

    ln -s eqn %installroot%/usr/bin/geqn
    ln -s tbl %installroot%/usr/bin/gtbl
patterns   :
    - docs :
        - /usr/share/doc
