# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dgop
version    : 1.6.0
release    : 3
source     :
    - https://github.com/AvengeMedia/dgop/releases/download/v1.6.0/dgop-1.6.0.tar.gz : 3d6db30092fa10334f497bb56f2a38f055295a60f86128471c043fd802ae8e38
homepage   : https://github.com/AvengeMedia/dgop
license    : MIT
component  : desktop
summary    : API & CLI for System & Process Monitoring
description: |
    System monitoring tool with CLI and REST API built in Go. Fast, single binary, JSON output, OpenAPI spec.
networking : true
builddeps  :
    - golang
setup      : |
    go mod vendor
build      : |
    go build \
        -ldflags="-s -w -X main.Version=${version}" \
        -o bin/dgop cmd/dgop/*.go
install    : |
    %install_bin bin/dgop
    %install_license LICENSE
