# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-css-parser
version    : 1.1.1
release    : 14
source     :
    - https://github.com/ebook-utils/css-parser/archive/refs/tags/v1.1.1.tar.gz : e03a9a98c2b2150fc767fc485c3e6fc7fc4a17cee207c036db7f3546d656b137
homepage   : https://github.com/ebook-utils/css-parser
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : programming.python
summary    : A CSS Cascading Style Sheets library for Python
description: |
    CSS related utilities (parsing, serialization, etc) for python.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
