# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : meson-python
version    : 0.20.0
release    : 11
source     :
    - https://pypi.debian.net/meson-python/meson_python-0.20.0.tar.gz : 6d9726ae6cd37e22f210c74b364b30180a68c20442e97ff09f3c566a414af738
homepage   : https://github.com/mesonbuild/meson-python
license    : MIT
component  : programming.python
summary    : Meson PEP 517 Python build backend
description: |
    meson-python is a Python build backend built on top of the Meson build system. It enables to use Meson for the configuration and build steps of Python packages. Meson is an open source build system meant to be both extremely fast, and, even more importantly, as user friendly as possible. meson-python is best suited for building Python packages containing extension modules implemented in languages such as C, C++, Cython, Fortran, Pythran, or Rust.
builddeps  :
    - patchelf
    - python-build
    - python-installer
    - python-pyproject-metadata
    - python-wheel
checkdeps  :
    - cython
    - git
    - meson
    - python-pytest
    - python-pytest-mock
rundeps    :
    - meson
    - python-pyproject-metadata
networking : true # check
environment: |
    # flip this for python3 rebuilds
    export BOOTSTRAP=0
build      : |
    if [[ ${BOOTSTRAP} == "1" ]]; then
        python3 -m pip wheel --no-deps .
    else
        %python3_setup
    fi
install    : |
    if [[ ${BOOTSTRAP} == "1" ]]; then
        python3 -m pip install --root=%installroot% --no-deps --ignore-installed .
    else
        %python3_install
    fi
check      : |
    # test_use_ansi_escapes[True-env1-True] failed on build server
    # test_invalid_build_dir: pytest-mock 3.12 uses deprecated asyncio.iscoroutinefunction on 3.14
    %python3_test pytest -v -k 'not test_use_ansi_escapes[True-env1-True] and not test_invalid_build_dir'
