# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : pychess
version    : 1.2.0
release    : 21
source     :
    - https://github.com/pychess/pychess/archive/refs/tags/1.2.0.tar.gz : da989acb45ebe77fa013ab68a5e6d4202c8d831af68e3533c8b96a9b5e387548
homepage   : https://pychess.github.io/
license    : GPL-3.0-or-later
component  : games.strategy
summary    : PyChess - a free, pleasant, chess game for the Linux desktop that does everything you require from an advanced chess client
description: |
    PyChess is a chess client for playing and analyzing chess games. It is intended to be usable both for those totally new to chess as well as advanced users who want to use a computer to further enhance their play. PyChess has a builtin python chess engine and auto-detects most popular chess engines (Stockfish, Rybka, Houdini, Shredder, GNU Chess, Crafty, Fruit, and many more). These engines are available as opponents, and are used to provide hints and analysis. PyChess also shows analysis from opening books and Gaviota end-game tablebases. When you get sick of playing computer players you can login to FICS (the Free Internet Chess Server) and play against people all over the world. PyChess has a built-in Timeseal client, so you won't lose clock time during a game due to lag. PyChess also has pre-move support, which means you can make (or start making) a move before your opponent has made their move.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - gstreamer-plugins-base
    - librsvg
    - ptyprocess
    - python-build
    - python-installer
    - python-pexpect
    - python-psutil
    - python-setuptools
    - python-sqlalchemy
    - python-wheel
rundeps    :
    - gnome-icon-theme
    - gstreamer-plugins-base
    - libgtksourceview4
    - librsvg
    - ptyprocess
    - python-cairo
    - python-gobject
    - python-pexpect
    - python-psutil
    - python-sqlalchemy
    - python-websockets
setup      : |
    %patch -p1 -i ${pkgfiles}/0001-Don-t-auto-detect-shredder.patch
build      : |
    # Pre-generate the ECO SQLite database
    PYTHONPATH=lib python3 pgn2ecodb.py
    
    # Pre-generate the preview images
    PYTHONPATH=lib python3 create_theme_preview.py
    
    %pyproject_build
install    : |
    %pyproject_install