# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : sqlitebrowser
version    : 3.13.1
release    : 12
source     :
    - https://github.com/sqlitebrowser/sqlitebrowser/archive/v3.13.1.tar.gz : 1044ba67d649cabc459eb887c016f70d6a404ad651390ab33bf7859dc7f1b67b
homepage   : https://sqlitebrowser.org/
license    :
    - GPL-3.0-or-later
    - MPL-2.0
component  : programming.tools
summary    : DB Browser for SQLite
description: |
    DB Browser for SQLite (DB4S) is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
setup      : |
    %cmake_ninja \
        -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
        -DENABLE_TESTING=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE*
check      : |
    %ninja_check
