# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tcpdump
version    : 4.99.6
release    : 19
source     :
    - https://github.com/the-tcpdump-group/tcpdump/archive/refs/tags/tcpdump-4.99.6.tar.gz : dc48c7976db0284ed7d662007fd7cbf1625391dc8707ba210d2f0656ba6f0601
homepage   : https://www.tcpdump.org/
license    : BSD-2-Clause
component  : network.util
summary    : Dump traffic on a network
description: |
    Tcpdump prints out a description of the contents of packets on a network interfacethat matches a given expression, allowing targeted analysis. It can save data to files for analysis later as well.
builddeps  :
    - pkgconfig(libpcap)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
