# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kontactinterface
version    : 26.04.3
release    : 104
source     :
    - https://download.kde.org/stable/release-service/26.04.3/src/kontactinterface-26.04.3.tar.xz : ec67aad623d3d80bfad1157a7be863d8f7a0eed3e8c620c59c5cd7ff276bb76a
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-only
    - MIT
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(x11)
    - kf6-kparts-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        - kf6-kparts-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
