# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kontactinterface
version    : 26.08.2
release    : 107
source     :
    - https://download.kde.org/stable/release-service/26.08.2/src/kontactinterface-26.08.2.tar.xz : c318a9eaef9df8f3e3bce515f4379c5284255f7b2cb424950ae7cc5fff99eca3
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-only
    - MIT
component  : desktop.library
summary    : Kontact Plugin Interface Library
description: |
    Kontact Plugin Interface Library.
builddeps  :
    - pkgconfig(x11)
    - kf6-kparts-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        - kf6-kparts-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
