# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : rocm-openmp
version    : 7.2.0
release    : 2
source     :
    - https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-7.2.0.tar.gz : e86138d2a63fbcbdf64668d55573b26ae944d0f0ae5a3f5bb59bf7bdb3124d3f
homepage   : https://github.com/ROCm/llvm-project
license    : Apache-2.0-with-LLVM-exception
summary    : ROCm's patched LLVM
component  : programming.devel
libsplit   : false
description: |
    The LLVM package contains a collection of modular and reusable compiler and toolchain technologies. The Low Level Virtual Machine (LLVM) Core libraries provide a modern source and target-independent optimizer, along with code generation support for many popular CPUs (as well as some less common ones!). These libraries are built around a well specified code representation known as the LLVM intermediate representation ("LLVM IR").
builddeps  :
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(libzstd)
    - pkgconfig(numa)
    - binutils-devel
    - rocm-device-libs-devel
    - rocm-llvm
environment: |
    export CXXFLAGS="${CXXFLAGS/-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32/-fcf-protection=none}"

    export ROCM_PATH=/usr
    export HIP_CLANG_PATH=/usr/lib64/llvm-rocm/bin
    export HIP_DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode

    if [ -e /usr/bin/sccache ]; then
        export CMAKE_C_COMPILER_LAUNCHER=/usr/bin/sccache
        export CMAKE_CXX_COMPILER_LAUNCHER=/usr/bin/sccache
    fi
setup      : |
    %cmake_ninja -S openmp \
      -DCMAKE_INSTALL_PREFIX=%libdir%/llvm-rocm \
      -DOPENMP_LIBDIR_SUFFIX=%LIBSUFFIX% \
      -DCMAKE_C_COMPILER=$HIP_CLANG_PATH/clang \
      -DCMAKE_CXX_COMPILER=$HIP_CLANG_PATH/clang++ \
build      : |
    %ninja_build
install    : |
    %ninja_install
