# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-license-expression
version    : 30.4.4
release    : 2
source     :
    - https://github.com/aboutcode-org/license-expression/releases/download/v30.4.4/license_expression-30.4.4.tar.gz : 73448f0aacd8d0808895bdc4b2c8e01a8d67646e4188f887375398c761f340fd
homepage   : https://github.com/aboutcode-org/license-expression
license    : Apache-2.0
component  : programming.python
summary    : Utility library to parse, normalize and compare License expressions for Python using a boolean logic engine
description: |
    license-expression is a comprehensive utility library to parse, compare, simplify and normalize license expressions (such as SPDX license expressions) using boolean logic.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools-scm
    - python-wheel
checkdeps  :
    - python-boolean.py
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
