# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-business-isbn
version    : '3.014'
release    : 11
source     :
    - https://cpan.metacpan.org/authors/id/B/BR/BRIANDFOY/Business-ISBN-3.014.tar.gz : 91135da48dd97fdbb40ea33306a008a2eae35ac5e3fae15fd420beab106b1e7a
homepage   : https://metacpan.org/pod/Business::ISBN
license    : Artistic-2.0
component  : programming.perl
summary    : Business::ISBN - work with International Standard Book Numbers
description: |
    This modules handles International Standard Book Numbers, including ISBN-10 and ISBN-13. The data come from Business::ISBN::Data, which means you can update the data separately from the code. Also, you can use Business::ISBN::Data with whatever RangeMessage.xml you like if you have updated data. See that module for details.
builddeps  :
    - perl
rundeps    :
    - perl-business-isbn-data
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
patterns   : /*
