# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : rocm-runtime
version    : '7.14'
release    : 11
source     :
    - https://github.com/ROCm/rocm-systems/archive/refs/tags/therock-7.14.tar.gz : 8cadf0d5c0f53f334b7b940a78619d1746c913b26ae719e2a09e20a6f7128330
homepage   : https://github.com/RadeonOpenCompute/ROCR-Runtime
license    : NCSA
component  : programming.devel
summary    : ROCm Runtime Library
description: |
    The ROCm Runtime Library is a thin, user-mode API that exposes the necessary interfaces to access and interact with graphics hardware driven by the AMDGPU driver set and the AMDKFD kernel driver. Together they enable programmers to directly harness the power of AMD discrete graphics devices by allowing host applications to launch compute kernels directly to the graphics hardware.
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libelf)
    - pkgconfig(numa)
    - rocm-device-libs-devel
    - rocprofiler-register-devel
    - rocm-llvm
    - vim # they need the xxd executable during build
environment: |
    export ROCM_PATH=/usr
    export CMAKE_PREFIX_PATH=/usr/lib64/llvm-rocm
    export HIP_DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
setup      : |
    %apply_patches

    %cmake_ninja -S projects/rocr-runtime -L \
      -DBUILD_SHARED_LIBS=ON \
build      : |
    %ninja_build
install    : |
    %ninja_install
