# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dankmaterialshell
version    : 1.5.3
release    : 5
source     :
    - https://github.com/AvengeMedia/DankMaterialShell/archive/refs/tags/v1.5.3.tar.gz : 2d665870f7019700fb38d59d043202e298e1aad1d3f1cb96360a75acbd3be9ca
homepage   : https://danklinux.com/
license    : MIT
component  : desktop
summary    : Desktop shell for Wayland compositors built with Quickshell and Go
description: |
    DankMaterialShell is a complete desktop shell for niri, Hyprland, MangoWC, Sway, labwc, Scroll, Miracle WM, and other Wayland compositors. It replaces waybar, swaylock, swayidle, mako, fuzzel, polkit, and everything else you'd normally stitch together to make a desktop.
networking : true
builddeps  :
    - golang
rundeps    :
    - cava
    - dgop
    - dsearch
    - matugen
    - qt6-multimedia
    - quickshell
    - wl-clipboard
build      : |
    %make PREFIX=/usr
install    : |
    %make_install \
        DESTDIR=${installdir} \
        PREFIX=/usr \
        SYSTEMD_USER_DIR=${installdir}/usr/lib/systemd/user
    %install_license LICENSE
