# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libldac
version    : 2.0.2.6
release    : 3
source     :
    - https://github.com/EHfive/ldacBT/releases/download/v2.0.2.6/ldacBT-2.0.2.6.tar.gz : fee05740e86ee66f4540486d92683ee8e8071119907b57ca762c7e5d943ecef0
    - git|https://android.googlesource.com/platform/external/libldac : platform-tools-34.0.4
homepage   : https://android.googlesource.com/platform/external/libldac
license    : Apache-2.0
component  : multimedia.codecs
summary    : LDAC Bluetooth encoder library
description: |
    LDAC is an audio coding technology developed by Sony that enables the transmission of High Resolution (Hi-Res) Audio content even over a Bluetooth connection. 
setup      : |
    rm -rf libldac
    cp -r $sources/libldac.git libldac
    sed -i "s|@SOURCE_VER@|${version/2.0.2./}|" CMakeLists.txt
    %cmake_ninja -DINSTALL_LIBDIR=lib%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %install_license LICENSE
    %ninja_install
