# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : bmon
version    : '5.0'
release    : 15
source     :
    - https://github.com/tgraf/bmon/archive/v5.0.tar.gz : cd7f5fb366a8c32c0e33c79a5daae78edd273993d0edf1036638f269400cf012
homepage   : https://github.com/tgraf/bmon/
license    :
    - BSD-2-Clause
    - MIT
summary    : A command line based bandwidth monitor.
builddeps  :
    - pkgconfig(libconfuse)
    - pkgconfig(libnl-3.0)
component  : network.util
description: |
    A command line based bandwidth monitor.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    %install_license LICENSE.BSD LICENSE.MIT
