# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-audioop-lts
version    : 0.2.2
release    : 1
source     :
    - https://github.com/AbstractUmbra/audioop/archive/refs/tags/0.2.2.tar.gz : 1673d5b5ff7663b64c974160b275469206dd123f483212ba26b50899b774485f
homepage   : https://github.com/AbstractUmbra/audioop
license    : PSF-2.0
component  : programming.python
summary    : An LTS port of Python's audioop module
description: |
    An LTS port of the Python builtin module audioop which was deprecated since version 3.11 and removed in 3.13.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
