# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-app-list
version    : '2026.08'
release    : 3
source     :
    - https://download.gnome.org/sources/gnome-app-list/2026/gnome-app-list-2026.08.tar.xz : 4142563951a5897cdc42db080d50edea2e7decf2d85da1d1e7fba2b02ec9f455
homepage   : https://gitlab.gnome.org/GNOME/gnome-app-list
license    : LGPL-2.1-or-later
component  : desktop.gnome
summary    : This project provides app recommendation data for the GNOME project
description: |
    This project provides app recommendation data for the GNOME project, in the form of AppStream data which is installed in the standard system location. This is mainly used by the Software app.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
