# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : r
version    : 4.6.1
release    : 58
source     :
    - https://cran.r-project.org/src/base/R-4/R-4.6.1.tar.gz : 4da6e61d2c0aac5f14a2e7e432cb5fcc269efe83da4293050ba7f03dff4e2cf4
homepage   : https://www.r-project.org/
license    : GPL-2.0-or-later
component  : programming
summary    : R is a system for statistical computation and graphics.
description: |
    R is a system for statistical computation and graphics.
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(icu-io)
    - pkgconfig(lapack)
    - pkgconfig(libcurl)
    - pkgconfig(liblzma)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(pangocairo)
    - pkgconfig(tk)
    - pkgconfig(xmu)
    - pkgconfig(xscrnsaver)
    - gfortran
    - libiconv-devel
    - openblas-devel
    - xdg-utils
extract    : false
environment: |
    unset LD_AS_NEEDED
setup      : |
    # manually extract to work around https://github.com/getsolus/solbuild/issues/126
    tar --strip-components=1 -xf $sources/R-%version%.tar.gz

    %configure \
        --enable-R-shlib \
        --with-blas="-lopenblas" \
        --with-lapack \
        --with-tcltk \
        rdocdir=/usr/share/doc/R \
        rincludedir=/usr/include/R \
        rsharedir=/usr/share/R
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
patterns   :
    - /usr/include/R
    - /usr/lib64/pkgconfig
