# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libei
version    : 1.6.0
release    : 7
source     :
    - https://gitlab.freedesktop.org/libinput/libei/-/archive/1.6.0/libei-1.6.0.tar.gz : 81b4b967f0e5938492434a04f7ea2e6c6d96d3e6c44700bc691821f82281e602
homepage   : https://libinput.pages.freedesktop.org/libei/
license    : MIT
component  : desktop.library
summary    : libei is a library for Emulated Input, primarily aimed at the Wayland stack.
description: |
    libei is a library for Emulated Input, primarily aimed at the Wayland stack.
builddeps  :
    - pkgconfig(libevdev)
    - pkgconfig(xkbcommon)
    - python-attrs
    - python-jinja
setup      : |
    %meson_configure -Dtests=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
