# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mdbook
version    : 0.5.3
release    : 51
source     :
    - https://github.com/rust-lang/mdBook/archive/refs/tags/v0.5.3.tar.gz : 7c3e2907c0482fc9721a46ac42d7954600d795ce2152bed418553999ec1ee8f1
homepage   : https://github.com/rust-lang/mdBook
license    : MPL-2.0
component  : programming.tools
summary    : Create books from markdown files
description: |
    mdBook is a command line tool to create book from markdown files. Like Gitbook but implemented in Rust.
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
    %install_license LICENSE
