# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : evolution-ews
version    : 3.60.1
release    : 71
source     :
    - https://download.gnome.org/sources/evolution-ews/3.60/evolution-ews-3.60.1.tar.xz : 0a22f865ebeb70e2679520fd2d94aa9973c403cbe4e03aa88cf8f23f358e8b6d
homepage   : https://gitlab.gnome.org/GNOME/evolution/-/wikis/home
license    : LGPL-2.1-or-later
component  : network.mail
summary    : MS Exchange integration through Exchange Web Services
description: |
    MS Exchange integration through Exchange Web Services
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(evolution-shell-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmspack)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-1.0)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DLIB_INSTALL_DIR=%libdir% -DSYSCONF_INSTALL_DIR=/etc .
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
