# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kontact
version    : 26.04.1
release    : 98
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/kontact-26.04.1.tar.xz : f137ddc84dfb2759621f7d6d63ca60879f40f6c2ffae3d206e2e80f2e9bd4743
homepage   : https://kde.org/applications/office/org.kde.kontact
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Container application to unify several major PIM applications within one application
description: |
    Kontact is the integrated solution to your personal information management (PIM) needs. It combines well-known KDE applications like KMail, KOrganizer and KAddressBook into a single interface to provide easy access to mail, scheduling, address book and other PIM functionality.
builddeps  :
    - pkgconfig(KF6GuiAddons)
    - pkgconfig(Qt6WebEngineCore)
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kontactinterface-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - akregator
    - kaddressbook
    - kmail
    - korganizer
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rfv $installdir/usr/share/doc
