# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-pytokens
version    : 0.4.1
release    : 1
source     :
    - https://github.com/tusharsadhwani/pytokens/archive/refs/tags/0.4.1.tar.gz : 68f03dc59116ac6b0ff36d418d54a7aa901fb63295c99d9ee11b5a4dd42f1efe
homepage   : https://pypi.org/p/pytokens
license    : MIT
component  : programming.python
summary    : A fast, spec compliant Python 3.14+ tokenizer
description: |
    A fast, spec compliant Python 3.14+ tokenizer.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-mypy
    - python-setuptools
    - python-wheel
checkdeps  :
    - python-pytest
    - python-pytest-cov
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
