name       : libxfce4ui
version    : 4.19.6
release    : 9
source     :
    - https://archive.xfce.org/xfce/4.20pre1/src/libxfce4ui-4.19.6.tar.bz2 : effe2c29408161beff4ae879f4591e7209c2bf5517c46545a1701337950afc7c
homepage   : https://docs.xfce.org/xfce/libxfce4ui/start
license    : GPL-2.0-only
component  : desktop.xfce
summary    : Widgets library for the Xfce desktop environment.
description: |
    Widgets library for the Xfce desktop environment.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libxfce4util-1.0)
    - pkgconfig(libxfconf-0)
    - pkgconfig(sm)
setup      : |
    %patch -p1 -i $pkgfiles/0001-libxfce4kbd-private-Add-shortcut-for-Whiskermenu.patch
    %configure \
        --with-vendor-info='Solus' \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
