name       : libshumate
version    : 1.2.0
release    : 8
source     :
    - https://download.gnome.org/sources/libshumate/1.2/libshumate-1.2.0.tar.xz : 4f8413a707cd00f84cee39ca49f58c48fc436f008ea80d6532ac37dafd0ba96b
homepage   : https://wiki.gnome.org/Projects/libshumate
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Shumate is a GTK toolkit providing widgets for embedded maps.
description: |
    Shumate is a GTK toolkit providing widgets for embedded maps.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(sysprof-capture-4)
    - gperf
    - vala
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
