# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : freeciv
version    : 3.2.3
release    : 48
source     :
    - https://files.freeciv.org/stable/freeciv-3.2.3.tar.xz : 989d6d58bd4cd97a4899e7e25afdee6c35fd03f87a379428a6e196d600d8d307
license    : GPL-2.0-or-later
homepage   : https://www.freeciv.org/
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : false
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(Qt6Core)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(gtk4)
    - pkgconfig(libcurl)
    - pkgconfig(lua-5.4)
    - pkgconfig(sqlite3)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
