# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libgravatar
version    : 26.04.3
release    : 98
source     :
    - https://download.kde.org/stable/release-service/26.04.3/src/libgravatar-26.04.3.tar.xz : 4e46acbd21c2a817247fea5ff66a89ebab2b824466e8939e7dc565f299dd9a81
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
    - MIT
component  : desktop.library
summary    : KDE PIM library providing Gravatar support
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - kf6-kio-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
