# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-jupyter-server-terminals
version    : 0.5.4
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyter_server_terminals/jupyter_server_terminals-0.5.4.tar.gz : bbda128ed41d0be9020349f9f1f2a4ab9952a73ed5f5ac9f1419794761fb87f5
homepage   : https://github.com/jupyter-server/jupyter_server_terminals
license    : BSD-3-Clause
component  : programming.python
summary    : A Jupyter Server Extension Providing Terminals
description: |
    Jupyter Server Terminals is a Jupyter Server Extension providing support for terminals.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-terminado
build      : |
    %python3_setup
install    : |
    %python3_install
