# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : freefilesync
version    : '14.10'
release    : 10
source     :
    - https://freefilesync.org/download/FreeFileSync_14.10_Source.zip : b63c89e3eb1ce276713fb3509c194848e0eca831ca48a7e9c3c3fc462c598fcd
homepage   : https://freefilesync.org/
license    : GPL-3.0-or-later
component  : network.util
summary    : Free backup software to synchronize files and folders
description: |
    FreeFileSync is a folder comparison and synchronization software that creates and manages backup copies of all your important files.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libssh2)
    - pkgconfig(sm)
    - pkgconfig(xxf86vm)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    pushd ..
    %apply_patches
    # FreeFileSync forum build guidance for newer GLib where g_free may be a macro
    sed -i 's/ZEN_ON_SCOPE_EXIT(::g_free/ZEN_ON_SCOPE_EXIT(g_free/g' \
        FreeFileSync/Source/afs/ftp.cpp \
        FreeFileSync/Source/base/icon_loader.cpp \
        zen/zstring.cpp
    popd
build      : |
    %make -C Source exeName=FreeFileSync
    %make -C Source/RealTimeSync exeName=RealTimeSync
install    : |
    %install_license ../License.txt
    install -Dm00755 ${workdir}/Build/Bin/FreeFileSync ${installdir}/usr/bin/FreeFileSync
    install -Dm00755 ${workdir}/Build/Bin/RealTimeSync ${installdir}/usr/bin/RealTimeSync
    install -Dm00644 ${pkgfiles}/FreeFileSync.desktop ${installdir}/usr/share/applications/FreeFileSync.desktop
    install -Dm00644 ${pkgfiles}/RealTimeSync.desktop ${installdir}/usr/share/applications/RealTimeSync.desktop

    mkdir ${installdir}/usr/share/freefilesync
    install -Dm00644 ${workdir}/Build/Resources/* ${installdir}/usr/share/freefilesync
    install -Dm00644 ${pkgfiles}/FreeFileSync.png ${installdir}/usr/share/icons/hicolor/128x128/apps/FreeFileSync.png
    install -Dm00644 ${pkgfiles}/RealTimeSync.png ${installdir}/usr/share/icons/hicolor/128x128/apps/RealTimeSync.png
    install -Dm00644 ${pkgfiles}/org.freefilesync.FreeFileSync.metainfo.xml -t ${installdir}/usr/share/metainfo/
