# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : rpcbind
version    : 1.2.9
release    : 10
source     :
    - https://sourceforge.net/projects/rpcbind/files/rpcbind/1.2.9/rpcbind-1.2.9.tar.bz2 : ce5f1a87c566ef0b2897a28f50a75c1dc23fec413a46a7f4183423b6b6aa991b
homepage   : https://sourceforge.net/projects/rpcbind/
license    : BSD-3-Clause
component  : system.utils
summary    : rpcbind is a server that converts RPC program numbers into universal addresses.
description: |
    rpcbind is a server that converts RPC program numbers into universal addresses.
clang      : true
builddeps  :
    - pkgconfig(libtirpc)
    - pkgconfig(systemd)
    - rpcsvc-proto-devel
setup      : |
    %configure \
        --enable-warmstarts \
        --with-statedir=/run/rpcbind
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
