# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libx11
version    : 1.8.13
release    : 50
source     :
    - https://www.x.org/releases/individual/lib/libX11-1.8.13.tar.gz : acf0e7cd7541110e6330ecb539441a2d53061f386ec7be6906dfde0de2598470
license    : MIT
component  : xorg.library
homepage   : https://www.x.org/
summary    : Core X11 protocol client library
description: |
    Core X11 protocol client library
emul32     : true
mancompress: true
clang      : true
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xcb)
    - pkgconfig32(xdmcp)
    - pkgconfig32(xtrans)
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static \
               --disable-xf86bigfont
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
