# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : cxx-rust-cssparser
version    : 1.1.0
release    : 2
source     :
    - https://download.kde.org/stable/cxx-rust-cssparser/cxx-rust-cssparser-1.1.0.tar.xz : c88f883f67d132240f7ef5c8b8fe4f743a79c448b98ac88f2be3b68264840358
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-2-Clause
    - CC0-1.0
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.kde.core
summary    : Library for parsing CSS using the Rust cssparser crate
description: |
    Library for parsing CSS using the Rust cssparser crate
builddeps  :
    - pkgconfig(Qt6Core)
    - corrosion
    - extra-cmake-modules
clang      : true
networking : true
setup      : |
    pushd rust
    %cargo_fetch
    popd
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
