# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-disks
version    : 6.6.5
release    : 82
source     :
    - https://download.kde.org/stable/plasma/6.6.5/plasma-disks-6.6.5.tar.xz : 660609a1f489c197d35419aeacbc08ec724c5e13538a736eb3d81ac331b9f639
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - FSFAP
    - GPL-2.0-only
    - GPL-3.0-only
    - LGPL-3.0-only
component  : system.utils
summary    : Monitors S.M.A.R.T. capable devices for imminent failure
description: |
    Monitors S.M.A.R.T. capable devices for imminent failure
builddeps  :
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - smartmontools-devel
rundeps    :
    - smartmontools
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
