# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : slop
version    : '7.7'
release    : 27
source     :
    - https://github.com/naelstrof/slop/archive/refs/tags/v7.7.tar.gz : a69a6e5c41d7fff1c6aa35b367a5c5a6dc98e621fa9a1908808d6308c2b40f4e
homepage   : https://github.com/naelstrof/slop
license    : GPL-3.0-or-later
component  : desktop
summary    : slop (Select Operation) is an application that queries for a selection from the user and prints the region to stdout
description: |
    slop (Select Operation) is an application that queries for a selection from the user and prints the region to stdout.
# libsplit   : false
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(glm)
    - pkgconfig(icu-uc)
    - pkgconfig(xext)
    - pkgconfig(xrender)
setup      : |
    sed -e 's|CXX_STANDARD 11|CXX_STANDARD 17|g' -i CMakeLists.txt # Fix build with ICU 74
    %cmake_ninja -DCMAKE_POLICY_VERSION_MINIMUM=3.5
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
