# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : rocprim
version    : 7.2.0
release    : 7
source     :
    - https://github.com/ROCm/rocm-libraries/archive/refs/tags/rocm-7.2.0.tar.gz : 8ad5f4a11f1ed8a7b927f2e65f24083ca6ce902a42021a66a815190a91ccb654
homepage   : https://github.com/ROCmSoftwarePlatform/rocPRIM
license    : MIT
component  : programming.library
summary    : ROCm Parallel Primitives
description: |
    rocPRIM is a header-only library providing HIP parallel primitives for developing performant GPU-accelerated code on AMD ROCm platform.
patterns   : /*
builddeps  :
    - rocm-cmake
    # We don't build anything, but CMake still checks for HIP
    - rocm-hip
    - rocm-llvm
environment: |
    export ROCM_PATH=/usr
    export HIP_DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
    export HIP_CLANG_PATH=/usr/lib64/llvm-rocm/bin
setup      : |
    %cmake_ninja -S projects/rocprim -L \
      -DCMAKE_C_COMPILER=$HIP_CLANG_PATH/clang \
      -DCMAKE_CXX_COMPILER=$HIP_CLANG_PATH/clang++ \
      -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
      -DROCM_SYMLINK_LIBS=OFF \
      -DONLY_INSTALL=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
