# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : jasper
version    : 4.2.9
release    : 19
source     :
    - https://github.com/jasper-software/jasper/releases/download/version-4.2.9/jasper-4.2.9.tar.gz : f71cf643937a5fcaedcfeb30a22ba406912948ad4413148214df280afc425454
homepage   : https://ece.engr.uvic.ca/~frodo/jasper/
license    : JasPer-2.0
component  : multimedia.library
summary    : JasPer Image Processing/Coding Tool Kit
description: |
    JasPer Project is an open-source initiative to provide a free software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(glut)
    - pkgconfig(libturbojpeg)
    - pkgconfig(xi)
    - pkgconfig(xmu)
setup      : |
    %cmake_ninja \
        -DJAS_ENABLE_AUTOMATIC_DEPENDENCIES=FALSE \
        -DALLOW_IN_SOURCE_BUILD=TRUE
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE.txt
    rm -rf $installdir/usr/share/doc
check      : |
    %ninja_check
