# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : resources
version    : 1.10.2
release    : 1
source     :
    - https://github.com/nokyan/resources/archive/refs/tags/v1.10.2.tar.gz : 120aa520cf6b9cf957958c12a84b562db742114d41aeea59ad6b6caa63f34654
homepage   : https://github.com/nokyan/resources
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Resources is a system information tool
description: |
    Resources is a system information tool written in Rust that displays information about your operating system, software and hardware.
networking : true
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - appstream
    - desktop-file-utils
    - gettext-devel
    - git
    - rust
setup      : |
    %meson_configure \
         -Dprofile=default
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
