# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : resources
version    : '51.0'
release    : 2
source     :
    - https://download.gnome.org/sources/resources/51/resources-51.0.tar.xz : ce1a01c1b772ceeb86e7a59cdb414f82f2196d50da63bae2072c7af8e3b4c735
homepage   : https://github.com/nokyan/resources
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Resources is a system information tool
description: |
    Resources is a system information tool written in Rust that displays information about your operating system, software and hardware.
networking : true
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsoup-3.0)
    - appstream
    - desktop-file-utils
    - gettext-devel
    - git
    - rust
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
    %install_license LICENSE
