# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-tie-cycle
version    : '1.233'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/B/BR/BRIANDFOY/Tie-Cycle-1.233.tar.gz : 043d0bef0afba404eaff236a400a17265cbb609aa2112743212e1f9ee29039f1
homepage   : https://github.com/briandfoy/tie-cycle
license    : Artistic-2.0
component  : programming.perl
summary    : Tie::Cycle - Cycle through a list of values via a scalar
description: |
    You use Tie::Cycle to go through a list over and over again. Once you get to the end of the list, you go back to the beginning. You don't have to worry about any of this since the magic of tie does that for you.
checkdeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
check      : |
    %perl_build test
patterns   : /*
