# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-filetype
version    : 1.2.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/f/filetype/filetype-1.2.0.tar.gz : 66b56cd6474bf41d8c54660347d37afcc3f7d1970648de365c102ef77548aadb
homepage   : https://github.com/h2non/filetype.py
license    : MIT
component  : programming.python
summary    : Infer file type and MIME type of any file/buffer
description: |
    Small and dependency-free Python package to infer file type and MIME type checking of files/buffers.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
