# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : linux-headers
version    : 7.2.3
release    : 118
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.2.3.tar.xz : 8ba259e8e7b13ec6ef0941c8a39ad90b24bd4a4d6c0010ba6bafb794550ecd03
license    : GPL-2.0-only
component  : system.devel
homepage   : https://www.kernel.org/
summary    : Kernel's libc headers
description: |
    Headers for the kernel's libc implementation
builddeps  :
    - rsync
setup      : |
    %make allnoconfig
install    : |
    %make headers_install INSTALL_HDR_PATH=$installdir/usr
    find $installdir -name ..install.cmd -or -name .install | xargs rm -vf
patterns   :
    - /*
replaces   :
    - kernel-libc-devel
