# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : pip
version    : 26.1.2
release    : 18
source     :
    - https://github.com/pypa/pip/archive/refs/tags/26.1.2.tar.gz : 193a7030ac78282beba6a95a3512241a71c2025fe5a05308d0e827a679f99847
homepage   : https://pip.pypa.io/en/stable/
license    : MIT
component  : programming.tools
summary    : The PyPA recommended tool for installing Python packages
description: |
    pip is the package installer for Python. You can use it to install packages from the Python Package Index and other indexes.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-wheel
checkdeps  :
    - python-pytest
rundeps    :
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
  #    %python3_test pytest
