# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-idna
version    : '3.18'
release    : 17
source     :
    - https://pypi.io/packages/source/i/idna/idna-3.18.tar.gz : ffb385a7e039654cef1ab9ef32c6fafe283c0c0467bba1d9029738ce4a14a848
homepage   : https://github.com/kjd/idna
license    : BSD-3-Clause
component  : programming.python
summary    : A python library to support the Internationalised Domain Names in Applications
description: |
    A python library to support the Internationalised Domain Names in Applications.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
checkdeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
