# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xev
version    : 1.2.7
release    : 8
source     :
    - https://xorg.freedesktop.org/archive/individual/app/xev-1.2.7.tar.xz : 95167895924de58e34b1013b2b0c8476e90d0888c6c39e7ae9bc35e3a19dba04
license    :
    - MIT
component  : xorg.apps
homepage   : https://www.x.org/
summary    : Print contents of X events
description: |
    Xev creates a window and then asks the X server to send it events whenever anything happens to the window (such as it being moved, resized, typed in, clicked in, etc.). You can also attach it to an existing window. It is useful for seeing what causes events to occur and to display the information that they contain; it is essentially a debugging and development tool, and should not be needed in normal usage.
builddeps  :
    - pkgconfig(xrandr)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING