# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kactivitymanagerd
version    : 6.6.5
release    : 136
source     :
    - https://download.kde.org/stable/plasma/6.6.5/kactivitymanagerd-6.6.5.tar.xz : 859bb8e7a6efb4210a82512abec4d7b6ea9ac6f883a2b1db4d3de5ca11452224
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - CC0-1.0
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : false
builddeps  :
    - kf6-kcrash-devel
    - kf6-kglobalaccel-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - libboost-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
