name       : kactivitymanagerd
version    : 6.2.1
release    : 107
source     :
    - https://download.kde.org/stable/plasma/6.2.1/kactivitymanagerd-6.2.1.tar.xz : bdd82059622a9baa01e18e0e4bb251a14c841b9da61a38e5568886c3093c8cce
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : no
builddeps  :
    - kf6-kcrash-devel
    - kf6-kglobalaccel-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - libboost-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
