# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-babel
version    : 2.18.0
release    : 28
source     :
    - https://github.com/python-babel/babel/archive/refs/tags/v2.18.0.tar.gz : e3afb21416ea7694744c1a18ad47db64257fb717ebca2d96b920d1ec5767e925
    - https://unicode.org/Public/cldr/47/cldr-common-47.zip : d5ee2abac64158c04884a722f8ef4830ea22b6c74aac20185be2838db8eda788
    - https://unicode.org/Public/cldr/47/core.zip#cldr-core-47.zip : d5ee2abac64158c04884a722f8ef4830ea22b6c74aac20185be2838db8eda788
homepage   : https://babel.pocoo.org
license    : BSD-3-Clause
component  : programming.python
summary    : A collection of tools for internationalizing Python applications
description: |
    Babel is an integrated collection of utilities that assist in internationalizing and localizing Python applications, with an emphasis on web-based applications.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-freezegun
    - python-pytest
    - python-pytz
rundeps    :
    - python-pytz
setup      : |
    cp $sources/cldr-common-47.zip $workdir/cldr/cldr-common-47.0.zip
    cp $sources/cldr-core-47.zip $workdir/cldr/cldr-core-47.zip

    # These files confuse our Python macros, but we need
    # them later for the test suite. Let's rename them for now.
    mv pyproject.toml pyproject.toml.bak
    mv setup.cfg setup.cfg.bak
build      : |
    %python3_setup import_cldr
install    : |
    %python3_install
# TODO 3.14
#check      : |
#    # Rename these back to the test suite works.
#    mv pyproject.toml.bak pyproject.toml
#    mv setup.cfg.bak setup.cfg
#
#    # The tests fail if running in the wrong timezone:
#    # https://github.com/python-babel/babel/issues/757
#    %python3_test pytest -vk 'not test_setuptools_commands'
