# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-types-pyyaml
version    : 6.0.12.20260510
release    : 7
source     :
    - https://pypi.python.org/packages/source/t/types-PyYAML/types_pyyaml-6.0.12.20260510.tar.gz : 09c1f1cb65a6eebea1e2e51ccf4918b8288e152909609a35cdb0d805efd125ad
homepage   : https://github.com/python/typeshed
license    : Apache-2.0
component  : programming.python
summary    : Typing stubs for PyYAML
description: |
    This is a PEP 561 type stub package for the PyYAML package. It can be used by type-checking tools like mypy, pyright, pytype, PyCharm, etc. to check code that uses PyYAML.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
