# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ruby-rb-inotify
version    : 0.11.1
release    : 9
source     :
    - https://rubygems.org/downloads/rb-inotify-0.11.1.gem : a0a700441239b0ff18eb65e3866236cd78613d6b9f78fea1f9ac47a85e47be6e
homepage   : https://rubygems.org/gems/rb-inotify
license    : MIT
component  : programming.ruby
summary    : RubyGem - rb-inotify
description: |
    A Ruby wrapper for Linux inotify, using FFI.
builddeps  :
    - pkgconfig(ruby-4.0)
rundeps    :
    - ruby-ffi
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions,plugins}
