# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : oath-toolkit
version    : 2.6.14
release    : 6
source     :
    - https://download.savannah.nongnu.org/releases/oath-toolkit/oath-toolkit-2.6.14.tar.gz : 8b1da365759f1249be57a82aec6e107f7b57dc77d813f96dc0aaf81624f28971
license    :
    - LGPL-2.1-or-later
    - GPL-3.0-or-later
component  : security.library
homepage   : https://oath-toolkit.codeberg.page/
summary    : One-time password components
description: |
    The OATH Toolkit provide components for building one-time password authentication systems. It contains shared libraries, command line tools and a PAM module. Supported technologies include the event-based HOTP algorithm (RFC4226) and the time-based TOTP algorithm (RFC6238). OATH stands for Open AuTHentication, which is the organization that specify the algorithms. For managing secret key files, the Portable Symmetric Key Container (PSKC) format described in RFC6030 is supported.
builddeps  :
    - pkgconfig(xmlsec1)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
