# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : sudo
version    : 1.9.17_p2
release    : 59
source     :
    - https://www.sudo.ws/dist/sudo-1.9.17p2.tar.gz : 4a38a1ab3adb1199257edc2a7c4a2bd714665eb605b04368843b06dada2cfcfb
homepage   : https://www.sudo.ws/
license    : ISC
summary    : Run commands as a privileged user
component  : system.base
description: |
    The Sudo package allows a system administrator to give certain users (or groups of users) the ability to run some (or all) commands as root or another user while logging the commands and arguments.
setup      : |
    %patch -p1 -i ${pkgfiles}/visudo-stateless.patch

    %configure \
        --with-all-insults \
        --with-env-editor \
        --enable-adminconf=/etc/ \
        --sysconfdir=/usr/share/defaults/etc/sudo/ \
        --with-editor=/usr/bin/nano \
        --with-tty-tickets \
        --with-passprompt="[sudo] password for %p: " \
        --without-sendmail
build      : |
    %make
install    : |
    %make_install
    %install_license LICENSE.md

    rm -rvf ${installdir}/{etc,var,run}
    rm -v ${installdir}/usr/share/defaults/etc/sudo/sudoers.dist

    # sysusers
    %install_file ${pkgfiles}/sudo.sysusers ${installdir}/%libdir%/sysusers.d/sudo.conf

    # tmpfiles
    rm -rfv ${installdir}/usr/lib
    %install_file ${pkgfiles}/sudo.tmpfiles ${installdir}/%libdir%/tmpfiles.d/sudo.conf

    # sudoers file
    rm -fv ${installdir}/usr/share/defaults/etc/sudo/sudoers
    %install_file -t ${installdir}/usr/share/defaults/etc/sudo ${pkgfiles}/sudoers

    # PAM config
    %install_file -t ${installdir}/usr/share/defaults/etc/pam.d ${pkgfiles}/pam.d/sudo
patterns   :
    - docs :
        - /usr/share/doc
