# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-rpds-py
version    : 2026.6.3
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/r/rpds_py/rpds_py-2026.6.3.tar.gz : 1cebd1337c242e4ec2293e541f712b2da849b29f48f0c293684b71c0632625d4
homepage   : https://github.com/crate-py/rpds
license    : MIT
component  : programming.python
summary    : Python bindings to Rust's persistent data structures (rpds)
description: |
    Python bindings to the Rust rpds crate for persistent data structures.
networking : true
builddeps  :
    - python-build
    - python-installer
    - python-maturin
checkdeps  :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
