name       : appstream-data
version    : 20250513
release    : 71
source     :
    - https://appstream.getsol.us/data/unstable/main/Components-x86_64.xml.gz : d949c45e3b0b712170cefb33408550a78828fdf29960360100f482f57d344848
    - https://appstream.getsol.us/data/unstable/main/icons-128x128.tar.gz : 860503185b7a5a1929d9ac51e21ec0a47de50f0b708161539ffac58a335b0ed9
    - https://appstream.getsol.us/data/unstable/main/icons-128x128@2.tar.gz : c1f5930ec5597350f6b10c407adfd3cd0ed9f4079bea70cbc8aed1405933a8d2
    - https://appstream.getsol.us/data/unstable/main/icons-48x48.tar.gz : a33176278a7c10dabe4afd96867808926cca3ab9936890676aa273f1beac2225
    - https://appstream.getsol.us/data/unstable/main/icons-48x48@2.tar.gz : d17b8c2dac07df6383863ec01bd77efe85d8b7cc2f618bd9443bc6e837046daa
    - https://appstream.getsol.us/data/unstable/main/icons-64x64.tar.gz : 4aef7ccc868209a337a9516f3bb3662974a146c2d5bed943f752b7d4c60f503d
    - https://appstream.getsol.us/data/unstable/main/icons-64x64@2.tar.gz : 9bcd2115785a6c771aff0e7df9f398bee9f506db676853c53e3c13fed507e505
homepage   : https://www.freedesktop.org/wiki/Distributions/AppStream/
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3
component  : desktop.core
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
extract    : no
install    : |
    install -Dm00644 $sources/Components-x86_64.xml.gz $installdir/usr/share/swcatalog/xml/solus-unstable-main.xml.gz

    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    tar xf $sources/icons-48x48.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    tar xf $sources/icons-48x48@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    tar xf $sources/icons-64x64.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    tar xf $sources/icons-64x64@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    tar xf $sources/icons-128x128.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    tar xf $sources/icons-128x128@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2
