# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : adwaita-fonts
version    : '51.0'
release    : 4
source     :
    - https://download.gnome.org/sources/adwaita-fonts/51/adwaita-fonts-51.0.tar.xz : fa104ae2c1b96580d322f563ffe8b2dfca5296b0eca4971efd2d8011405123d2
homepage   : https://gitlab.gnome.org/GNOME/adwaita-fonts
license    : GPL-3.0-or-later
component  : desktop.font
summary    : The typefaces for GNOME
description: |
    Adwaita Fonts consists of Adwaita Sans, a variation of Inter, and Adwaita Mono, Iosevka customized to match Inter.
setup      : |
    %meson_configure
        # It doesn't support fontsdir option yet
        #Dfontsdir=/usr/share/fonts/truetype/adwaita
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/adwaita-fonts.metainfo.xml -t $installdir/usr/share/metainfo
