# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tpm2-tss
version    : 4.2.0
release    : 8
source     :
    - https://github.com/tpm2-software/tpm2-tss/releases/download/4.2.0/tpm2-tss-4.2.0.tar.gz : b53f0c5c8c4ce17f05701a410ca9688f725ca380c9bc4640eacd0eadb1fea124
homepage   : https://tpm2-software.github.io/
license    : BSD-2-Clause
component  : system.base
summary    : OSS implementation of the TCG TPM2 Software Stack (TSS2)
description: |
    OSS implementation of the Trusted Computing Group's (TCG) TPM2 Software Stack (TSS).
builddeps  :
    - pkgconfig(json-c)
    - pkgconfig(libcurl)
    - pkgconfig(libtpms)
    - pkgconfig(uthash)
    - autoconf-archive
    - cmocka-devel
    - doxygen
    - swtpm
    - valgrind
setup      : |
    %configure --disable-static \
               --sysconfdir=/usr/share/defaults/etc \
               --with-runstatedir=/run \
               --with-tmpfilesdir=%libdir%/tmpfiles.d \
               --with-sysusersdir=%libdir%/sysusers.d \
               --with-udevrulesprefix=60- \
               --enable-unit \
               --enable-integration \
               --enable-valgrind \
               --enable-self-generated-certificate
build      : |
    %make
install    : |
    %make_install
    %install_license LICENSE

    # Created by tmpfiles
    rmdir $installdir/var/lib/tpm2-tss/system/keystore
    rmdir $installdir/var/lib/tpm2-tss/system/
    rmdir $installdir/var/lib/tpm2-tss/
    rmdir $installdir/var/lib/
    rmdir $installdir/var
    rmdir $installdir/run/tpm2-tss/eventlog
    rmdir $installdir/run/tpm2-tss/
    rmdir $installdir/run/
check      : |
    unset LD_PRELOAD
    make prepare-check
    make check
