# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-dotenv
version    : 1.2.4
release    : 1
source     :
    - https://github.com/theskumar/python-dotenv/archive/refs/tags/v1.2.4.tar.gz : 5ce3633ec9607b8a949aa457f0c7e8438af50d01d4bcc0784f679bc5171711c4
homepage   : https://github.com/theskumar/python-dotenv
license    : BSD-3-Clause
component  : programming.python
summary    : Reads key-value pairs from a .env file and can set them as environment variables
description: |
    python-dotenv reads key-value pairs from a .env file and can set them as environment variables. It helps in the development of applications following the 12-factor principles.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
