# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tiled
version    : 1.12.1
release    : 27
source     :
    - https://github.com/mapeditor/tiled/archive/refs/tags/v1.12.1.tar.gz : 5d2b634f9d29433485d4f901dd2b695be278bd30216e7587b0d63fad35f19aed
    - https://github.com/qbs/qbs/archive/refs/tags/v3.2.0.tar.gz#qbs.tar.gz : 267dd2859fe46b0004f351c385d171fb8449a9cff8cc95faece2e530121842fd
homepage   : https://www.mapeditor.org
license    :
    - Apache-2.0
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : Tiled is a general purpose tile map editor.
description: |
    Tiled is a general purpose tile map editor.
libsplit   : false
environment: |
    export QBS=$workdir/qbs-tool/bin/qbs
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Help)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Svg)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - qt6-base-private-devel
setup      : |
    mkdir qbs-tool
    tar xf $sources/qbs.tar.gz -C qbs-tool --strip-components=1
    pushd qbs-tool
        %cmake -DQt6_DIR=/usr/lib64/cmake/Qt6 -DWITH_TESTS=OFF .
        %make
    popd
    %patch -p1 -i $pkgfiles/0001-Update-default-style-for-better-integration.patch
    $QBS setup-toolchains --detect
build      : |
    $QBS qbs.installPrefix:%PREFIX% moduleProviders.Qt.qmakeFilePaths:/usr/bin/qmake6
install    : |
    $QBS install --install-root $installdir qbs.installPrefix:%PREFIX% moduleProviders.Qt.qmakeFilePaths:/usr/bin/qmake6
    %install_license LICENSE.*
