# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-yarl
version    : 1.24.2
release    : 14
source     :
    - https://github.com/aio-libs/yarl/releases/download/v1.24.2/yarl-1.24.2.tar.gz : 
        9ac374123c6fd7abf64d1fec93962b0bd4ee2c19751755a762a72dd96c0378f8
homepage   : https://yarl.aio-libs.org/
license    : Apache-2.0
component  : programming.python
summary    : The module provides handy URL class for URL parsing and changing
description: |
    The module provides handy URL class for URL parsing and changing
builddeps  :
    - cython
    - python-build
    - python-expandvars
    - python-installer
    - python-setuptools
    - python-wheel
rundeps    :
    - python-multidict
build      : |
    %python3_setup
install    : |
    %python3_install
