# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : beets
version    : 2.14.1
release    : 22
source     :
    - https://github.com/beetbox/beets/archive/refs/tags/v2.14.1.tar.gz : 9e34a46e10b020eade410e62dbe9af70ee16b6d41a4b09d5f682d34303c096e6
homepage   : https://beets.io/
license    : MIT
component  : multimedia.audio
summary    : Beets is the media library management system for obsessive-compulsive music geeks
description: |
    Beets is the media library management system for obsessive music geeks. The purpose of beets is to get your music collection right once and for all. It catalogs your collection, automatically improving its metadata as it goes using the MusicBrainz database. Then it provides a bouquet of tools for manipulating and accessing your music. Because beets is designed as a library, it can do almost anything you can imagine for your music collection.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
    - python-wheel
rundeps    :
    - numpy
    - python-confuse
    - python-jellyfish
    - python-lap
    - python-mediafile
    - python-packaging
    - python-platformdirs
    - python-requests
    - python-requests-ratelimiter
    - python-typing-extensions
    - python-unidecode
    - pyyaml
build      : |
    %pyproject_build
install    : |
    %pyproject_install
    ln -s /usr/bin/beet ${installdir}/usr/bin/beets
