# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-2048
version    : '50.2'
release    : 21
source     :
    - https://download.gnome.org/sources/gnome-2048/50/gnome-2048-50.2.tar.xz : 6d15df68a6128cf0c99e598908af8c667b733dc4003ef4d21d4b4c4a42bd2da9
homepage   : https://gitlab.gnome.org/GNOME/gnome-2048
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : GNOME 2048 Puzzle Game
description: |
    A 2048 clone for GNOME.
networking : true
builddeps  :
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - itstool
    - rust-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
