# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-syrupy
version    : 5.5.3
release    : 1
source     :
    - https://github.com/syrupy-project/syrupy/archive/refs/tags/v5.5.3.tar.gz : 275a6d7ad03725944f0d6f81cd5ce4f64b55fce59eb2c477255bc37a82e6d1be
homepage   : https://syrupy-project.github.io/syrupy/
license    : MIT
component  : programming.python
summary    : The sweeter pytest snapshot plugin
description: |
    Syrupy is a zero-dependency pytest snapshot plugin. It enables developers to write tests which assert immutability of computed results.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
    - python-wheel
checkdeps  :
    - python-attrs
    - python-hypothesis
    - python-pydantic
    - python-pytest
    - python-pytest-xdist
rundeps    :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
