# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : akonadi-contacts
version    : 26.08.1
release    : 106
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/akonadi-contacts-26.08.1.tar.xz : 96894e82adff3e0ff84db4e6ed757a62971d4835c785efb353663a76550050e4
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - MIT
component  : desktop.library
summary    : Libraries and daemons to implement Contact Management in Akonadi
description: |
    Libraries and daemons to implement Contact Management in Akonadi.
builddeps  :
    - akonadi-devel
    - grantleetheme-devel
    - kf6-kcontacts-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kmime-devel
    - kf6-ktextwidgets-devel
    - kf6-kxmlgui-devel
    - kf6-prison-devel
    - kf6-syntax-highlighting-devel
    - ktextaddons-devel
rundeps    :
    - devel :
        - akonadi-devel
        - grantleetheme-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
