# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : akonadi-contacts
version    : 25.12.3
release    : 101
source     :
    - https://download.kde.org/stable/release-service/25.12.3/src/akonadi-contacts-25.12.3.tar.xz : 575bb419a6bfde2bb3eaceda9636878492f8601fe87c767721f9cea5c250898f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement Contact Management in Akonadi
description: |
    Libraries and daemons to implement Contact Management in Akonadi.
builddeps  :
    - akonadi-devel
    - grantleetheme-devel
    - kf6-kcontacts-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-ktextwidgets-devel
    - kf6-kxmlgui-devel
    - kf6-prison-devel
    - kmime-devel
    - ktextaddons-devel
rundeps    :
    - devel :
        - akonadi-devel
        - grantleetheme-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
