# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-pytest-dependency
version    : 0.6.1
release    : 1
source     :
    - https://github.com/RKrahl/pytest-dependency/releases/download/0.6.1/pytest-dependency-0.6.1.tar.gz : 246c24d2a5fc743a942cec4408853640e56a05ba58d46e5b213a1d4b738a2464
homepage   : https://pypi.org/project/pytest-dependency
license    : Apache-2.0
component  : programming.python
summary    : Manage dependencies of tests
description: |
    This module is a plugin for the popular Python testing framework pytest. It manages dependencies of tests: you may mark some tests as dependent from other tests. These tests will then be skipped if any of the dependencies did fail or has been skipped.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - python-pytest
rundeps    :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
