# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lagrange
version    : 1.20.5
release    : 32
source     :
    - https://github.com/skyjake/lagrange/releases/download/v1.20.5/lagrange-1.20.5.tar.gz : 79f2d451203f534bbd05a8b8f07fe40fa72f4794ffc238f43ad941b7d2450ace
homepage   : https://gmi.skyjake.fi/lagrange/
license    : BSD-2-Clause
component  : network.clients
summary    : A Beautiful Gemini and Gopher client
description: |
    Lagrange is a desktop GUI client for browsing Geminispace and Gopherspace. It offers modern conveniences familiar from web browsers, such as smooth scrolling, inline image viewing, multiple tabs, visual themes, Unicode fonts, bookmarks, history, gempub support, split view and page outlines.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(libwebp)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - libunistring-devel
rundeps    :
    - mpg123
setup      : |
    %cmake_ninja -DTFDN_ENABLE_SSE41=No
build      : |
    %ninja_build
install    : |
    %ninja_install
