# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lagrange
version    : 1.21.1
release    : 37
source     :
    - https://github.com/skyjake/lagrange/releases/download/v1.21.1/lagrange-1.21.1.tar.gz : 49389240e34fb9e79cebb9566af24723ae15f9ba2ca8e8933ffdd5c3e034953c
homepage   : https://gmi.skyjake.fi/lagrange/
license    : BSD-2-Clause
component  : network.clients
summary    : A Beautiful Gemini and Gopher client
description: |
    Lagrange is a desktop GUI client for browsing Geminispace and Gopherspace. It offers modern conveniences familiar from web browsers, such as smooth scrolling, inline image viewing, multiple tabs, visual themes, Unicode fonts, bookmarks, history, gempub support, split view and page outlines.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(libwebp)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - libunistring-devel
rundeps    :
    - mpg123
setup      : |
    %cmake_ninja -DTFDN_ENABLE_SSE41=No
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE.md
