# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-mistune
version    : 3.3.4
release    : 21
source     :
    - https://files.pythonhosted.org/packages/source/m/mistune/mistune-3.3.4.tar.gz : 58b5c96d6fcb61190dfe5fae498d2b2065f99cf61e9649418fd54cf1ada86dfe
homepage   : https://github.com/lepture/mistune
license    : BSD-3-Clause
component  : programming.python
summary    : A sane Markdown parser with useful plugins and renderers
description: |
    A fast yet powerful Python Markdown parser with renderers and plugins.
builddeps  :
    - cython
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
