name       : python-path
version    : 17.1.1
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/path/path-17.1.1.tar.gz : 2dfcbfec8b4d960f3469c52acf133113c2a8bf12ac7b98d629fa91af87248d42
homepage   : https://github.com/jaraco/path
license    : MIT
component  : programming.python
summary    : Object-oriented file system path manipulation
description: |
    Object-oriented file system path manipulation

    Implements path objects as first-class entities, allowing common operations on files to be invoked on those path objects directly.
builddeps  :
    - python-build
    - python-coherent-licensed
    - python-installer
    - python-setuptools
    - python-setuptools-scm
checkdeps  :
    - python-more-itertools
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
