# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : usb-modeswitch
version    : 2.6.2
release    : 6
source     :
    - https://www.draisberghof.de/usb_modeswitch/usb-modeswitch-2.6.2.tar.bz2 : f7abd337784a9d1bd39cb8a587518aff6f2a43d916145eafd80b1b8b7146db66
    - https://www.draisberghof.de/usb_modeswitch/usb-modeswitch-data-20251207.tar.bz2 : 0bb12d64aee5e467c31af61a53fb828ff7aa59c54a82ca85eeede4c5690bfa66
homepage   : https://www.draisberghof.de/usb_modeswitch/
license    : GPL-2.0-or-later
component  : network.util
summary    : Switch between USB modes
description: |
    USB ModeSwitch is a mode switching tool for controlling USB devices with multiple "modes".
builddeps  :
    - pkgconfig(libusb-1.0)
rundeps    :
    - tcl
setup      : |
    tar xf ${sources}/usb-modeswitch-data-*.tar.bz2

    %patch -p1 -i ${pkgfiles}/usb-modeswitch-2.6.2-stateless.patch
build      : |
    %make
install    : |
    %install_license COPYING

    install -dm00755 ${installdir}/%libdir%/systemd/system

    %make_install \
        UDEVDIR=${installdir}/%libdir%/udev \
        SYSDIR=${installdir}/%libdir%/systemd/system
    %make_install -C usb-modeswitch-data-* \
        RULESDIR=${installdir}/%libdir%/udev/rules.d

    install -Dm00644 ${pkgfiles}/usb_modeswitch.tmpfiles ${installdir}/%libdir%/tmpfiles.d/usb_modeswitch.conf

    # Stateless
    rmdir \
        ${installdir}/etc/usb_modeswitch.d \
        ${installdir}/etc

    # Not needed
    rmdir \
        ${installdir}/var/lib/usb_modeswitch \
        ${installdir}/var/lib \
        ${installdir}/var \
