# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-acme
version    : 5.7.0
release    : 30
source     :
    - https://pypi.python.org/packages/source/a/acme/acme-5.7.0.tar.gz : 4be4fe6cf3809c3988d75fa1213ce8e784d9d5d8380cac63c2dca555e105653d
homepage   : https://github.com/certbot/certbot
license    : Apache-2.0
component  : programming.python
summary    : ACME protocol implementation in Python
description: |
    ACME protocol implementation in Python
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-josepy
    - python-pyrfc3339
    - python-pytest
    - python-requests
rundeps    :
    - python-josepy
    - python-pyrfc3339
    - python-requests
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
