# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-fastjsonschema
version    : 2.22.2
release    : 14
source     :
    - https://github.com/horejsek/python-fastjsonschema/archive/refs/tags/v2.22.2.tar.gz : 330cf64bdbf1b4c62eb10ee4a2cc85746f051c7f34065f126771c355b0981176
homepage   : https://github.com/horejsek/python-fastjsonschema
license    : BSD-3-Clause
component  : programming.python
summary    : Fast JSON schema validator for Python
description: |
    fastjsonschema implements validation of JSON documents by JSON schema. The library implements JSON schema drafts 04, 06 and 07. The main purpose is to have a really fast implementation.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-pytest
    - python-pytest-benchmark
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v

