# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-inline-snapshot
version    : 0.35.3
release    : 1
source     :
    - https://github.com/15r10nk/inline-snapshot/archive/refs/tags/0.35.3.tar.gz : 435caa16dd81a4b56a0a1b6d9afd6bfa028c455f29b218a724545428c7a45b32
homepage   : https://15r10nk.github.io/inline-snapshot/
license    : MIT
component  : programming.python
summary    : Boosts efficiency when writing tests
description: |
    Boosts efficiency when writing tests by generating code with the expected values and simplifies snapshot tests with pytest.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
    - python-wheel
checkdeps  :
    - python-asttokens
    - python-black
    - python-dirty-equals
    - python-executing
    - python-hypothesis
    - python-isort
    # - python-pydantic
    - python-pytest
    - python-pytokens
    - python-rich
    - python-typing-extensions
rundeps    :
    - python-asttokens
    - python-executing
    - python-pytest
    - python-rich
    - python-typing-extensions
build      : |
    %pyproject_build
install    : |
    %pyproject_install
# TODO(Evan): Revisit after updating pydantic
# check      : |
#     _pytest_args=(
#         --deselect tests/test_formating.py::test_format_command_fail \
#         --deselect tests/test_typing.py
#     )

#     %pytest -v "${_pytest_args[@]}"
