# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : puddletag
version    : 2.5.0
release    : 9
source     :
    - https://github.com/puddletag/puddletag/archive/refs/tags/2.5.0.tar.gz : aa04bd796a78ca726c91c28ade0b64a9d693cac307713728359dfc551d250815
homepage   : https://docs.puddletag.net/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Powerful, simple, audio tag editor for GNU/Linux
description: |
    puddletag is an audio tag editor (primarily created) for GNU/Linux similar to the Windows program, Mp3tag. Unlike most taggers for GNU/Linux, it uses a spreadsheet-like layout so that all the tags you want to edit by hand are visible and easily editable.
builddeps  :
    - python-build
    - python-installer
    - python-scikit-build
    - python-setuptools
rundeps    :
    - mutagen
    - pyparsing
    - python-configobj
    - python-levenshtein
    - python-lxml
    - python-pyacoustid
    - python-qt6
    - python-unidecode
setup      : |
    %patch -p1 -i $pkgfiles/puddletag-2.5.0-req.patch # patch from Fedora
build      : |
    %python3_setup
install    : |
    %python3_install
    %install_license LICENSE
    # Install AppStream metainfo
    install -Dm00644 $pkgfiles/net.puddletag.puddletag.appdata.xml -t $installdir/usr/share/metainfo
