# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : numix-icon-theme-square
version    : 26.02.21
release    : 50
source     :
    - https://github.com/numixproject/numix-icon-theme-square/archive/refs/tags/26.02.21.tar.gz : 8b661671a188246308eba6664bb976d3146d9f44c8e3b0dcfd5b61d1675b302d
homepage   : https://numixproject.github.io/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix Square Icon Theme
description: |
    Numix Square is an icon theme from the Numix project
rundeps    :
    - numix-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {Numix-Square,Numix-Square-Light} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
    %install_license LICENSE
