# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : palapeli
version    : 25.12.3
release    : 82
source     :
    - https://download.kde.org/stable/release-service/25.12.3/src/palapeli-25.12.3.tar.xz : 5a8f5cd6ae8fa8f29dada3808417a51c355e4e3077b1063152324d9406cd25e5
homepage   : https://kde.org/applications/games/org.kde.palapeli
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt6Svg)
    - kf6-karchive-devel
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kxmlgui-devel
    - libkdegames-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rfv $installdir/usr/share/doc
