# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : palapeli
version    : 26.04.1
release    : 83
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/palapeli-26.04.1.tar.xz : 1854dcbfc038db8f95ec9736a769557e12b3542729067e0793297f1cf82d0c74
homepage   : https://kde.org/applications/games/org.kde.palapeli
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt6Svg)
    - kf6-karchive-devel
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kxmlgui-devel
    - libkdegames-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rfv $installdir/usr/share/doc
