# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : palapeli
version    : 26.04.3
release    : 85
source     :
    - https://download.kde.org/stable/release-service/26.04.3/src/palapeli-26.04.3.tar.xz : 4e6d678cf8dd3866c829ae006d01bd07f2e045c03f5677227d2e20fd7b86ad05
homepage   : https://kde.org/applications/games/org.kde.palapeli
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : games.puzzle
summary    : A single-player jigsaw puzzle game
description: |
    A single-player jigsaw puzzle game
builddeps  :
    - pkgconfig(Qt6Svg)
    - kf6-karchive-devel
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kxmlgui-devel
    - libkdegames-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*

    # remove doc
    rm -rfv $installdir/usr/share/doc
