# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : weston
version    : 16.0.0
release    : 37
source     :
    - https://gitlab.freedesktop.org/wayland/weston/-/releases/16.0.0/downloads/weston-16.0.0.tar.xz : dfb32e2bccabda957b94a8d0ec6075acd18c71c87ebc543ee3e618d294ca0f7f
homepage   : https://gitlab.freedesktop.org/wayland/weston
license    : MIT
component  :
    - desktop
    - demos : desktop
    - libs : programming.library
    - session : desktop
    - tools : system.utils
summary    :
    - A lightweight and functional Wayland compositor
    - demos : Weston demo program files
    - libs : Weston compositor libraries
    - session : Weston desktop session
    - tools : Tools for Weston
description: |
    Weston is the reference implementation of a Wayland compositor, as well as a useful environment in and of itself. Out of the box, Weston provides a very basic desktop, or a full-featured environment for non-desktop uses such as automotive, embedded, in-flight, industrial, kiosks, set-top boxes and TVs. It also provides a library allowing other projects to build their own full-featured environments on top of Weston's core.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(egl)
    - pkgconfig(fontconfig)
    - pkgconfig(freerdp3)
    - pkgconfig(gbm)
    - pkgconfig(glesv2)
    - pkgconfig(glib-2.0)
    - pkgconfig(lcms2)
    - pkgconfig(libdisplay-info)
    - pkgconfig(libdrm)
    - pkgconfig(libevdev)
    - pkgconfig(libinput)
    - pkgconfig(libjpeg)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpng)
    - pkgconfig(libseat)
    - pkgconfig(libspa-0.2)
    - pkgconfig(libsystemd)
    - pkgconfig(libudev)
    - pkgconfig(libwebp)
    - pkgconfig(lua)
    - pkgconfig(pango)
    - pkgconfig(pangocairo)
    - pkgconfig(pixman-1)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-cursor)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(winpr3)
    - pkgconfig(xcb)
    - pkgconfig(xcb-composite)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-shape)
    - pkgconfig(xcb-xfixes)
    - pkgconfig(xcursor)
    - pkgconfig(xkbcommon)
    - pkgconfig(xwayland)
rundeps    :
    - libs :
        - xorg-xwayland
    - session :
        - weston
    - tools :
        - weston
setup      : |
    %meson_configure \
        -Dbackend-vnc=false
build      : |
    %meson_build
install    : |
    %meson_install
    %install_license COPYING
patterns   :
    - demos :
        - /usr/bin/weston-*
    - devel :
        - /usr/share/libweston-*/protocols
    - libs :
        - /usr/lib64/libweston-*/*.so
        - /usr/lib64/libweston-*.so.*
    - session :
        - /usr/share/wayland-sessions/weston.desktop
    - tools :
        - /usr/bin/weston-calibrator
        - /usr/bin/weston-debug
        - /usr/bin/weston-screenshooter
        - /usr/bin/weston-tablet
        - /usr/bin/weston-terminal
        - /usr/bin/weston-touch-calibrator
