# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : pygments
version    : 2.21.0
release    : 24
source     :
    - https://files.pythonhosted.org/packages/source/p/pygments/pygments-2.21.0.tar.gz : 610ca751c9bc2492b38eb9a38a7fbc93edbbb2d7182edaf34e66ae493dee5c8c
homepage   : https://pygments.org/
license    : BSD-2-Clause
component  : programming
summary    : Pygments is a syntax highlighting package written in Python
description: |
    Pygments is a generic syntax highlighter written in Python that supports over 500 languages and text formats, for use in code hosting, forums, wikis or other applications that need to prettify source code.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
checkdeps  :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest --ignore=tests/contrast/test_contrasts.py
