name       : ksshaskpass
version    : 6.2.1
release    : 106
source     :
    - https://download.kde.org/stable/plasma/6.2.1/ksshaskpass-6.2.1.tar.xz : b9c076fabc9ffbcef172eec284c1a8bde93bbbb60d7de7ea4aac8bc52e1acb72
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-kwallet-devel
    - kf6-kwidgetsaddons-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
