# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : filen-desktop
version    : 3.0.53
release    : 1
source     :
    - https://github.com/FilenCloudDienste/filen-desktop/archive/refs/tags/v3.0.53.tar.gz : b22056e1d8d87e41aefba34ae91c5a1a42249440af586b0c9f63eb648f02ec14
homepage   : https://filen.io/
license    : AGPL-3.0-only
component  : network.download
summary    : Zero knowledge end-to-end encrypted cloud storage
description: |
    Filen Desktop Client for Windows, macOS and Linux. Zero knowledge end-to-end encrypted cloud storage.
networking : true
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atspi-2)
    - pkgconfig(cairo)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(nss)
    - pkgconfig(pango)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - cups-devel
    - git
    - make
    - nodejs
rundeps    :
    - rclone
setup      : |
    # Bypass the build-time check for static rclone binaries
    %patch -p1 -i $pkgfiles/0001-bypass-rclone-bundled-check.patch
    npm install
build      : |
    NODE_ENV=production npm run build
    NODE_ENV=production npx electron-builder --linux dir
install    : |
    # Install the main application files
    %install_dir $installdir/usr/share/filen-desktop
    cp -av --no-preserve=ownership prod/linux-unpacked/* $installdir/usr/share/filen-desktop/

    # Create the directory where Filen expects its bundled rclone to live
    %install_dir $installdir/usr/share/filen-desktop/resources/app.asar.unpacked/bin/rclone
    ln -s /usr/bin/rclone $installdir/usr/share/filen-desktop/resources/app.asar.unpacked/bin/rclone/rclone-linux-amd64

    # Create the executable symlink
    %install_dir $installdir/usr/bin
    ln -srv $installdir/usr/share/filen-desktop/Filen $installdir/usr/bin/filen-desktop

    %install_file $pkgfiles/io.filen.file-desktop.desktop $installdir/usr/share/applications/io.filen.file-desktop.desktop
    %install_file $pkgfiles/io.filen.file-desktop.metainfo.xml $installdir/usr/share/metainfo/io.filen.file-desktop.metainfo.xml
    

    # Install the application icons
    for i in 16 24 32 48 64 128 256 512 1024; do
        if [ -f "build/icons/png/${i}x${i}.png" ]; then
            %install_file build/icons/png/${i}x${i}.png $installdir/usr/share/icons/hicolor/${i}x${i}/apps/filen-desktop.png
        fi
    done

    %install_license LICENSE
    
