# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libabigail
version    : '2.10'
release    : 7
source     :
    - http://mirrors.kernel.org/sourceware/libabigail/libabigail-2.10.tar.xz : 0cc10e6471398330e001b9fe37f1e8c5108a9ab632b08ca9634d6c64bc380b78
homepage   : https://sourceware.org/libabigail/
license    : Apache-2.0 WITH LLVM-exception
component  : programming.tools
summary    : The project aims at providing a library to manipulate ABI corpora, compare them, provide detailed information about their differences and help build tools to infer interesting conclusions about these differences.
description: |
    This project aims at providing a C++ library for constructing, manipulating, serializing and de-serializing ABI-relevant artifacts. The set of artifacts that we are interested in is made of constructions like types, variables, functions and declarations of a given library or program. For a given program or library, this set of constructions is called an ABI corpus.
builddeps  :
    - pkgconfig(libdw)
    - pkgconfig(libxxhash)
    - python-sphinx # docs
setup      : |
    %reconfigure \
        --disable-static \
        --enable-bash-completion
build      : |
    %make
    make -C doc/manuals man
install    : |
    %install_license LICENSE.txt
    %make_install

    pushd bash-completion
        install -Dm00644 -t $installdir/usr/share/bash-completion/completions {abicompat,abidiff,abidw,abilint,abipkgdiff}
    popd

    pushd doc/manuals/man
        install -Dm00644 -t $installdir/usr/share/man/man1/ {abicompat.1,abidiff.1,abidw.1,abilint.1,abipkgdiff.1}
        install -Dm00644 -t $installdir/usr/share/man/man7/ libabigail.7
    popd
check      : |
    %make check
