# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tpm2-tools
version    : '5.8'
release    : 6
source     :
    - https://github.com/tpm2-software/tpm2-tools/releases/download/5.8/tpm2-tools-5.8.tar.gz : 
        1cb73185cae814b4e15c7c2d0b22642d640faf48775f4156a1fd92edf84bef73
homepage   : https://tpm2-software.github.io/
license    : BSD-2-Clause
component  : security
summary    : Trusted Platform Module (TPM2.0) tools
description: |
    Trusted Platform Module (TPM2.0) tools based on tpm2-tss
builddeps  :
    - pkgconfig(efivar)
    - pkgconfig(tss2-esys)
    - pandoc
setup      : |
    %configure --with-efivar
build      : |
    %make
install    : |
    %make_install
    %install_license docs/LICENSE
# Requires tpm2-abrmd
# check      : |
#    %make check
