# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-pytest-run-parallel
version    : 0.9.1
release    : 1
source     :
    - https://github.com/Quansight-Labs/pytest-run-parallel/archive/refs/tags/v0.9.1.tar.gz : 2bfa0976f1859777a13a76b2365fdb024932453ab9874538efbe3dfa7f1d1853
homepage   : https://github.com/Quansight-Labs/pytest-run-parallel
license    : MIT
component  : programming.python
summary    : A simple pytest plugin to run tests concurrently
description: |
    This pytest plugin takes a set of tests that would be normally be run serially and execute them in parallel.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-hypothesis
    - python-pytest
    - python-pytest-order
    - python-pytest-xdist
rundeps    :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
