# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ngtcp2
version    : 1.21.0
release    : 1
source     :
    - https://github.com/ngtcp2/ngtcp2/releases/download/v1.21.0/ngtcp2-1.21.0.tar.bz2 : 11c12fada0bcb380a6fdbaf71646eccc85f97580d930c2761ef473fb0eef3838
homepage   : https://nghttp2.org/ngtcp2/
license    : MIT
component  : system.base
summary    : An effort to implement RFC9000 QUIC protocol
description: |
    The ngtcp2 project is an effort to implement IETF QUIC protocol.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libbrotlidec)
    - pkgconfig(libbrotlienc)
    - pkgconfig(libnghttp3)
    - pkgconfig(openssl)
    - libev-devel
setup      : |
    %cmake_ninja \
        -DENABLE_GNUTLS:FEAT=ON \
        -DENABLE_OPENSSL:FEAT=ON \
        -DENABLE_STATIC_LIB:FEAT=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
