# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kgeography
version    : 26.08.1
release    : 103
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/kgeography-26.08.1.tar.xz : f55ee70f440e2420c2306e43e1ba63d51557cf3f693c0ac07fb19e197ddb6c00
homepage   : https://kde.org/applications/education/org.kde.kgeography
license    :
    - GPL-2.0-or-later
component  : games.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kxmlgui-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING

    #remove docs
    rm -rfv $installdir/usr/share/doc
