# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kgeography
version    : 26.04.1
release    : 100
source     :
    - https://download.kde.org/stable/release-service/26.04.1/src/kgeography-26.04.1.tar.xz : c6880eaae67cd007d6026c106ce49692c1afbb89c4333e63747cea9a19b8caf9
homepage   : https://kde.org/applications/education/org.kde.kgeography
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kxmlgui-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rfv $installdir/usr/share/doc
