# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kgeography
version    : 25.12.3
release    : 99
source     :
    - https://download.kde.org/stable/release-service/25.12.3/src/kgeography-25.12.3.tar.xz : a9ad85ed43881cf034f24e140b1fedeb32b3a6f5f08e5d6c081ffb3aa15ee02c
homepage   : https://kde.org/applications/education/org.kde.kgeography
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kxmlgui-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rfv $installdir/usr/share/doc
