# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ansible
version    : 2.20.3
release    : 68
source     :
    - https://github.com/ansible/ansible/archive/refs/tags/v2.20.3.tar.gz : b6256ce8707f9a071a07e00298a3ea4d32fa51d6ed2249f68973c3ca2a4749fd
license    : GPL-3.0-or-later
homepage   : https://www.ansible.com/
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python3)
    - asciidoc
    - python-build
    - python-docutils
    - python-installer
    - python-jinja
    - python-setuptools
    - python-wheel
rundeps    :
    - python-jinja
    - python-jmespath
    - python-paramiko
    - python-resolvelib
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
