# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : faugus-launcher
version    : 1.19.5
release    : 2
source     :
    - https://github.com/Faugus/faugus-launcher/archive/refs/tags/1.19.5.tar.gz : bffac0cd9a4253efe3067f93566d0425148cb1671566c54966ec206dc7224582
homepage   : https://github.com/Faugus/faugus-launcher
license    : MIT
component  : games
summary    : A simple and lightweight app for running Windows games using UMU-Launcher
description: |
    A simple and lightweight app for running Windows games using UMU-Launcher
builddeps  :
    - pkgconfig(gtk4)
rundeps    :
    - imagemagick
    - libayatana-appindicator
    - libcanberra
    - libgtk-3
    - python-gobject
    - python-icoextract
    - python-pillow
    - python-psutil
    - python-requests
    - python-vdf
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
