# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : faugus-launcher
version    : 2.1.0
release    : 15
source     :
    - https://github.com/Faugus/faugus-launcher/archive/refs/tags/2.1.0.tar.gz : a6956e5bbd831bcb5b43ce9ccc41341bf108e0c372d12724b994e737c8c668ed
homepage   : https://github.com/Faugus/faugus-launcher
license    : MIT
component  : games
summary    : A simple and lightweight app for running Windows games using UMU-Launcher
description: |
    A simple and lightweight app for running Windows games using UMU-Launcher
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(manette-0.2)
rundeps    :
    - libadwaita
    - libgtk-4
    - libmanette
    - python-gobject
    - python-icoextract
    - python-pillow
    - python-psutil
    - python-requests
    - python-vdf
    - python3-dbus
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
