# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : faugus-launcher
version    : 2.0.1
release    : 11
source     :
    - https://github.com/Faugus/faugus-launcher/archive/refs/tags/2.0.1.tar.gz : 882f3f3c800c40ea25c463f69b511d18d536c4787557a72ccf428484238109b2
homepage   : https://github.com/Faugus/faugus-launcher
license    : MIT
component  : games
summary    : A simple and lightweight app for running Windows games using UMU-Launcher
description: |
    A simple and lightweight app for running Windows games using UMU-Launcher
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(manette-0.2)
rundeps    :
    - libadwaita
    - libgtk-4
    - libmanette
    - python-gobject
    - python-icoextract
    - python-pillow
    - python-psutil
    - python-requests
    - python-vdf
    - python3-dbus
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
