# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ksystemstats
version    : 6.7.1
release    : 73
source     :
    - https://download.kde.org/stable/plasma/6.7.1/ksystemstats-6.7.1.tar.xz : 23b16a93beae6bedb1925e0c22d05f2ad5f9ffbdd97c0fa75335fe2be2ebb31f
homepage   : https://invent.kde.org/plasma/ksystemstats
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-only
    - GPL-3.0-only
component  : programming.library
summary    : A plugin based system monitoring daemon
description: |
    A plugin based system monitoring daemon
builddeps  :
    - pkgconfig(libnl-3.0)
    - kf6-kcrash-devel
    - kf6-kio-devel
    - kf6-networkmanager-qt-devel
    - libksysguard-devel
    - lm_sensors-devel
rundeps    :
    - libksysguard
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
