name       : ksystemstats
version    : 6.2.1
release    : 43
source     :
    - https://download.kde.org/stable/plasma/6.2.1/ksystemstats-6.2.1.tar.xz : c3198a96216b48e8754e5dfc70a8f675af7b35def3fe063f727044839d45a073
homepage   : https://invent.kde.org/plasma/ksystemstats
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.1-only
component  : programming.library
summary    : A plugin based system monitoring daemon
description: |
    A plugin based system monitoring daemon
builddeps  :
    - pkgconfig(libnl-3.0)
    - kf6-kcrash-devel
    - kf6-kio-devel
    - kf6-networkmanager-qt-devel
    - libksysguard-devel
    - lm_sensors-devel
rundeps    :
    - libksysguard
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
