# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : pimcommon
version    : 26.08.1
release    : 106
source     :
    - https://download.kde.org/stable/release-service/26.08.1/src/pimcommon-26.08.1.tar.xz : 67ea0976c8a3d37c224e0f2a5db08dcb88342f0c77378f28b7aef6f502fccb7e
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - MIT
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-search-devel
    - kf6-karchive-devel
    - kf6-kcmutils-devel
    - kf6-kcontacts-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - kf6-ktextwidgets-devel
    - kf6-purpose-devel
    - kf6-syntax-highlighting-devel
    - kimap-devel
    - kldap-devel
    - ktextaddons-devel
    - libkdepim-devel
    - plasma-activities-devel
rundeps    :
    - devel :
        - akonadi-devel
        - akonadi-contacts-devel
        - kf6-kconfig-devel
        - kf6-kcontacts-devel
        - kf6-kio-devel
        - kimap-devel
        - ktextaddons-devel
        - libkdepim-devel
        - plasma-activities-devel
        - qt6-base-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
