# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : snapshot
version    : '51.0'
release    : 13
source     :
    - https://download.gnome.org/sources/snapshot/51/snapshot-51.0.tar.xz : 3e64fa4cd1a742ae34b6f6d8e6d9614a2d3eab88a1b0071c11ab53617eb214c2
homepage   : https://apps.gnome.org/Snapshot/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Take pictures and videos
description: |
    Take pictures and videos on your computer, tablet, or phone.
builddeps  :
    - pkgconfig(glycin-gtk4-2)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libseccomp)
    - desktop-file-utils
    - rust
rundeps    :
    - gstreamer-plugin-gtk4
    - gstreamer-plugin-pipewire
    - gstreamer-plugins-good
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
