# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mailimporter
version    : 26.08.2
release    : 100
source     :
    - https://download.kde.org/stable/release-service/26.08.2/src/mailimporter-26.08.2.tar.xz : 7badf1e23f8a3660f20d9e36397bc6015dc70c0ba51825fd6f47ed405a55853c
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-or-later
    - MIT
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-mime-devel
    - kf6-karchive-devel
    - kf6-kcontacts-devel
    - kf6-kio-devel
    - kf6-kmime-devel
    - kf6-sonnet-devel
    - kf6-syntax-highlighting-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - kf6-karchive-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
