# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mailimporter
version    : 25.12.3
release    : 94
source     :
    - https://download.kde.org/stable/release-service/25.12.3/src/mailimporter-25.12.3.tar.xz : eb99de68d8f5febe3d9eef8e6a793f9bdf62f54ad016fabe78f564d90e7a2db4
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-mime-devel
    - kf6-karchive-devel
    - kf6-kcontacts-devel
    - kf6-kio-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - kf6-karchive-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
