# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libksieve
version    : 26.04.3
release    : 99
source     :
    - https://download.kde.org/stable/release-service/26.04.3/src/libksieve-26.04.3.tar.xz : b49b46fbb43c8a4b7c4e9a383389ad93719194140e7d910d25f2165f66b91ad9
homepage   : https://kde.org/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-only
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : Sieve Script Library
description: |
    Sieve Script Library.
builddeps  :
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(libsasl2)
    - kf6-karchive-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - kf6-sonnet-devel
    - kf6-syntax-highlighting-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kmailtransport-devel
    - kmime-devel
    - ktextaddons-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - kf6-syntax-highlighting-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*

    # remove doc
    rm -rfv $installdir/usr/share/doc
