# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dpkg
version    : 1.23.7
release    : 20
source     :
    - https://ftp.debian.org/debian/pool/main/d/dpkg/dpkg_1.23.7.tar.xz : 60fe2be72e5f0a4bb0ac7baff3b1697ebc5cfaac1885f66649521571a97440ad
homepage   : https://wiki.debian.org/dpkg/
license    : GPL-2.0-or-later
component  : programming.devel
summary    : DO NOT USE THIS.
description: |
    Debian Package Manager - for Cross Distro Purposes. Do NOT use to attempt installation of packages on Solus, it's not compatible!
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(liblzma)
    - pkgconfig(libmd)
    - pkgconfig(libzstd)
rundeps    :
    - perl
setup      : |
    %configure \
        --disable-start-stop-daemon \
        --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING

    # use standard names for man pages
    for file in $installdir/usr/share/man/man3/*; do
        newname=$(echo "$file" | sed -Ee 's/3perl/3/')
        mv "$file" "$newname"
    done

    # nuke docs
    rm -rf $installdir/usr/share/doc

    # why is this even here
    rm -f $installdir/etc/alternatives/README

    # delete empty dirs
    find $installdir -type d -empty -delete

    # static bad
    rm $installdir/usr/lib64/libdpkg.a
