# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tomcat-connectors
version    : 1.2.50
release    : 8
source     :
    - https://github.com/apache/tomcat-connectors/archive/refs/tags/JK_1_2_50.tar.gz : 7f1e75451ac663e82c811f3fd36aa3d44fc563bb01a0d2cce00cf7ec78bd126e
homepage   : https://tomcat.apache.org/
license    : Apache-2.0
component  : programming
summary    : Provides mod_jk for connecting httpd to a Tomcat container
description: |
    mod_jk is an Apache module used to connect the Tomcat servlet container with web servers such as Apache, iPlanet, Sun ONE (formerly Netscape) and even IIS using the Apache JServ Protocol.
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(valgrind)
    - httpd-devel
rundeps    :
    - httpd
setup      : |
    cd native
    %reconfigure --with-apxs
build      : |
    cd native
    %make
install    : |
    cd native
    # Install routine is totally broken
    %install_exe apache-2.0/mod_jk.so $installdir/%libdir%/httpd/mod_jk.so
    %install_license README.txt
