# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : appstream-catalog
version    : '20260925'
release    : 80
source     :
    - https://appstream.getsol.us/data/unstable/main/Components-x86_64.xml.gz: 
        4ba08d23122b38cb07c58f4b2c3d825ef9d2fd82226b127f5242a0996a7f5ee7
    - https://appstream.getsol.us/data/unstable/main/icons-128x128.tar.gz: 
        dfa98fb7db0e58eb9d32d1b6ee5f4b15f5c2f5eddfc2b93e7b658250c3458298
    - https://appstream.getsol.us/data/unstable/main/icons-128x128@2.tar.gz: 
        fad3173bfa3621eb1d5a7b090dd6a615b6adfbb2dab8dac73df6ed0b01c4740e
    - https://appstream.getsol.us/data/unstable/main/icons-48x48.tar.gz: 
        43f918dccb0f1f8f9e37ee150fe8143e1bcaf4d022c66ad76d638936c59c5f99
    - https://appstream.getsol.us/data/unstable/main/icons-48x48@2.tar.gz: 
        a93823700f0ce6391688e11b58e619952da59d210fcadee03abf7c4f36de9741
    - https://appstream.getsol.us/data/unstable/main/icons-64x64.tar.gz: 
        02c32be81957d8b6efa9ccd4368f344a88b76dd81f0073395be4294bb58e4456
    - https://appstream.getsol.us/data/unstable/main/icons-64x64@2.tar.gz: 
        8f4a99d06b5cccba41b5bede2e753501a871807b4ac70da5554aee771ffb0940
homepage   : https://www.freedesktop.org/wiki/Distributions/AppStream/
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3-or-later
component  : desktop.core
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
extract    : false
install    : |
    %install_file ${sources}/Components-x86_64.xml.gz ${installdir}/usr/share/swcatalog/xml/solus-unstable-main.xml.gz

    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/48x48
    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/64x64
    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/128x128
    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    tar xf ${sources}/icons-48x48.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/48x48
    tar xf ${sources}/icons-48x48@2.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    tar xf ${sources}/icons-64x64.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/64x64
    tar xf ${sources}/icons-64x64@2.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    tar xf ${sources}/icons-128x128.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/128x128
    tar xf ${sources}/icons-128x128@2.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    %install_license ${pkgfiles}/*
replaces   : appstream-data
