# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : appstream-catalog
version    : '20260523'
release    : 58
source     :
    - https://appstream.getsol.us/data/unstable/main/Components-x86_64.xml.gz: 
        49d191c0447c7ab5c5559a02a13a6669b1811eb9fbea60b81e7974fe5d00d71b
    - https://appstream.getsol.us/data/unstable/main/icons-128x128.tar.gz: 
        fcbcf89df409c4fb339e239f337ca536b41ba9c6e62ce421293acfdf1a6a9e12
    - https://appstream.getsol.us/data/unstable/main/icons-128x128@2.tar.gz: 
        496d203154fe8fe5a845adb475e5dbe23e30d73d3c823386f903f674c28b44b7
    - https://appstream.getsol.us/data/unstable/main/icons-48x48.tar.gz: 
        2efd183c26ec2da2a0c827be1af56b0d71d35a7d742389011d9c8c638d73c9f2
    - https://appstream.getsol.us/data/unstable/main/icons-48x48@2.tar.gz: 
        aba4ee511939f3939bb0422de4a28c2e072a5c5ab96509ca2b34e9f2ead98720
    - https://appstream.getsol.us/data/unstable/main/icons-64x64.tar.gz: 
        e4e97251910476a0ace2187a9d5e22fe6b193952a1958de174c1de2bc1e6cc39
    - https://appstream.getsol.us/data/unstable/main/icons-64x64@2.tar.gz: 
        a28bd119ba46a60cf4dbcc33cf0a4b4ee6aea5f6ef7dda6591690911f83770df
homepage   : https://www.freedesktop.org/wiki/Distributions/AppStream/
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3-or-later
component  : desktop.core
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
extract    : false
install    : |
    install -Dm00644 $sources/Components-x86_64.xml.gz $installdir/usr/share/swcatalog/xml/solus-unstable-main.xml.gz

    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    tar xf $sources/icons-48x48.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    tar xf $sources/icons-48x48@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    tar xf $sources/icons-64x64.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    tar xf $sources/icons-64x64@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    tar xf $sources/icons-128x128.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    tar xf $sources/icons-128x128@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    %install_license ${pkgfiles}/*
replaces   : appstream-data
