# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : appstream-catalog
version    : '20261002'
release    : 81
source     :
    - https://appstream.getsol.us/data/unstable/main/Components-x86_64.xml.gz: 
        4e1fe905af35b597348c007245c4a07df97469f2933f2242b665df408e6e60eb
    - https://appstream.getsol.us/data/unstable/main/icons-128x128.tar.gz: 
        80c6e3b125b82aeff3ecbd9f9395e75f4cec66292f341bc968d409864a7e5d6a
    - https://appstream.getsol.us/data/unstable/main/icons-128x128@2.tar.gz: 
        fd08ed315e2e1c3363c5ccd8ed4065dce55d584a4a0541d0003a60714de32fa9
    - https://appstream.getsol.us/data/unstable/main/icons-48x48.tar.gz: 
        10578de7e2638d34b58d3a1496c2bd0942c33dc5aa617c4f376eadba22701e15
    - https://appstream.getsol.us/data/unstable/main/icons-48x48@2.tar.gz: 
        2a5edf805439e21164b2d303c1d5f68db9c827e01d07a47e2293495eac23f10f
    - https://appstream.getsol.us/data/unstable/main/icons-64x64.tar.gz: 
        39ee043b171a678b784ca2323e9393622d224189c8472b2a9f5b2bf655321a84
    - https://appstream.getsol.us/data/unstable/main/icons-64x64@2.tar.gz: 
        6c35b879e471b233597bf39f79bb2bee4369ddf87fa9010999d59377b682cfa4
homepage   : https://www.freedesktop.org/wiki/Distributions/AppStream/
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3-or-later
component  : desktop.core
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
extract    : false
install    : |
    %install_file ${sources}/Components-x86_64.xml.gz ${installdir}/usr/share/swcatalog/xml/solus-unstable-main.xml.gz

    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/48x48
    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/64x64
    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/128x128
    %install_dir ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    tar xf ${sources}/icons-48x48.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/48x48
    tar xf ${sources}/icons-48x48@2.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    tar xf ${sources}/icons-64x64.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/64x64
    tar xf ${sources}/icons-64x64@2.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    tar xf ${sources}/icons-128x128.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/128x128
    tar xf ${sources}/icons-128x128@2.tar.gz -C ${installdir}/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    %install_license ${pkgfiles}/*
replaces   : appstream-data
