# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kuserfeedback
version    : 6.29.0
release    : 43
source     :
    - https://download.kde.org/stable/frameworks/6.29/kuserfeedback-6.29.0.tar.xz : 36fd747bd0c8a22e3e542a4d0f05e4a85101953e19d80839a3c9cd67b5d1ac9f
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - CC0-1.0
    - MIT
component  : desktop.library
summary    : Framework for collecting user feedback for applications via telemetry and surveys
description: |
    Framework for collecting user feedback for applications via telemetry and surveys
builddeps  :
    - pkgconfig(Qt6Charts)
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Svg)
    - extra-cmake-modules
    - php-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        - qt6-base-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF \
               -DENABLE_CONSOLE=ON \
               -DENABLE_CLI=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
