# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kirigami
version    : 6.28.0
release    : 43
source     :
    - https://download.kde.org/stable/frameworks/6.28/kirigami-6.28.0.tar.xz : 30fc6bd928a7124ace334944c8b45748603d37e45464db874903d7eb91f41d36
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - FSFAP
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - LGPL-3.0-only
    - MIT
component  : desktop.kde
summary    : QtQuick components for mobile and desktop UI development.
description: |
    Kirigami is a set of QtQuick components for the creation of applications that look and feel great on mobile as well as desktop devices and follow the Kirigami Human Interface Guidelines.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(Qt6Svg)
    - extra-cmake-modules
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-base-devel
        - qt6-declarative-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
patterns   :
    - devel :
        - /usr/share/kdevappwizard
