# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xorg-driver-input-wacom
version    : 1.2.4
release    : 35
source     :
    - https://github.com/linuxwacom/xf86-input-wacom/releases/download/xf86-input-wacom-1.2.4/xf86-input-wacom-1.2.4.tar.bz2 : cbc5fccda8994b9314e60da6933d8e5f901e4c3f208dd9fc09a611fe25b71a0d
license    : GPL-2.0-or-later
component  : xorg.driver
homepage   : https://github.com/linuxwacom/xf86-input-wacom
summary    : Input driver for Wacom/Wacom-like tablets
description: |
    The Xorg Wacom Driver package contains the X.Org X11 driver for Wacom and Wacom-like tablets. It is not required to use a Wacom tablet, the xf86-input-evdev driver can handle these devices without problems.
optimize   :
    - no-bind-now
    - no-symbolic
builddeps  :
    - pkgconfig(pciaccess)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
    - pkgconfig(xrandr)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license GPL
check      : |
    %make check
