# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-puremagic
version    : 2.2.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/p/puremagic/puremagic-2.2.0.tar.gz : eb4bddf07c177c4b434554b92165b67449f5a51e152b976202d6254498810eef
homepage   : https://github.com/cdgriffith/puremagic
license    : MIT
component  : programming.python
summary    : Pure python implementation of identifying files based off their magic numbers
description: |
    puremagic is a pure python module that will identify a file based off it's magic numbers. It is designed to be minimalistic and inherently cross platform compatible. It is also designed to be a stand in for python-magic, it incorporates the functions from_file(filename[, mime]) and from_string(string[, mime]) however the magic_file() and magic_string() are more powerful and will also display confidence and duplicate matches.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools-scm
checkdeps  :
    - python-pytest
build      : |
    %pyproject_build
install    : |
    %pyproject_install
check      : |
    %pytest -v
