name       : garcon
version    : 4.19.2
release    : 5
source     :
    - https://archive.xfce.org/xfce/4.20pre1/src/garcon-4.19.2.tar.bz2 : b2c8de6c3c258574f357ee23bf183dd8c73773724c7d1bed1187a9d789ededed
homepage   : https://docs.xfce.org/xfce/garcon/start
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - GFDL-1.1-only #For documentation
component  : desktop.xfce
summary    : Freedesktop.org compliant menu library.
description: |
    Freedesktop.org compliant menu library.
builddeps  :
    - pkgconfig(libxfce4ui-2)
setup      : |
    %configure --disable-debug
build      : |
    %make
install    : |
    %make_install

    # Stateless
    install -dm0755 $installdir/usr/share/xdg/menus/
    mv $installdir/etc/xdg/menus/xfce-applications.menu $installdir/usr/share/xdg/menus/
    rmdir -v $installdir/etc/xdg/menus \
             $installdir/etc/xdg \
             $installdir/etc/
