# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ccid
version    : 1.8.4
release    : 16
source     :
    - https://ccid.apdu.fr/files/ccid-1.8.4.tar.xz : 4ff98151a7feb828a711e2f9d68c6b6065a97c597a81c2cbbd11d7f7edcfe743
homepage   : https://ccid.apdu.fr/
license    : LGPL-2.1-or-later
component  : programming
summary    : Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver
description: |
    Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(libusb-1.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 src/92_pcscd_ccid.rules $installdir/%libdir%/udev/rules.d/92_pcscd_ccid.rules
