# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kimageformats
version    : 6.28.0
release    : 43
source     :
    - https://download.kde.org/stable/frameworks/6.28/kimageformats-6.28.0.tar.xz : 91808c6de080ab5b506721c1f78ad5772bcb1f70bba7262c275ccd98de8b6b38
homepage   : https://community.kde.org/Frameworks
license    :
    - Apache-2.0
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - LGPL-3.0-only
component  : desktop.library
summary    : A fast and easy to use image viewer
description: |
    A fast and easy to use image viewer
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - pkgconfig(libjxl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libraw)
    - pkgconfig(libsharpyuv)
    - kf6-karchive-devel
rundeps    :
    - qt6-imageformats
clang      : true
optimize   : thin-lto
setup      : |
    %patch -p1 -i ${pkgfiles}/upstream-01.patch
    %cmake_kf6 \
        -DKIMAGEFORMATS_HEIF:BOOL=ON \
        -DKIMAGEFORMATS_JXR:BOOL=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
