# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mpv-mpris
version    : '1.2'
release    : 1
source     :
    - https://github.com/hoyon/mpv-mpris/archive/refs/tags/1.2.tar.gz : ecdc66f0182a38164b8bdc79502c575df3d2c4453bae5bff225c4e5ce9dbef6c
homepage   : https://github.com/hoyon/mpv-mpris
license    : MIT
component  : multimedia.video
summary    : MPRIS plugin for mpv
description: |
    A C plugin for mpv which allows control of the player using standard media keys. It integrates mpv with desktop environments and media controllers by implementing the standard MPRIS D-Bus interface.
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(mpv)
rundeps    :
    - mpv
build      : |
    %make
install    : |
    %make_install install-system \
        PREFIX=/usr \
        PLUGINDIR=/usr/lib64/mpv-mpris \
        SYS_SCRIPTS_DIR=/usr/share/mpv/scripts
        %install_license LICENSE

