# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : dsearch
version    : 1.6.0
release    : 3
source     :
    - https://github.com/AvengeMedia/danksearch/releases/download/v1.6.0/dsearch-1.6.0.tar.gz : 4e63abb6f352fd9a0d7846aeab8fa115b12eb90ed47d54c765070f6831f9707b
homepage   : https://github.com/AvengeMedia/danksearch
license    : MIT
component  : desktop
summary    : Indexed filesystem search in Go
description: |
    A configurable filesystem search service powered by bleve for Unix-based operating systems.
networking : true
builddeps  :
    - golang
setup      : |
    # Fix systemd service
    sed -i 's|/usr/local|/usr|' assets/dsearch.service

    go mod vendor
build      : |
    go build \
        -o bin/dsearch \
        -ldflags="-s -w -X main.Version=${version}" \
        cmd/dsearch/*.go
install    : |
    %install_bin bin/dsearch
    %install_license LICENSE

    %install_file assets/dsearch.service -t ${installdir}/%libdir%/systemd/user/
