# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mindforger
version    : 2.1.0
release    : 8
source     :
    - https://github.com/dvorka/mindforger/releases/download/2.1.0/mindforger_2.1.0_tarball.tgz : 
        65fb588a59c2e7cfa5a538e9780d6f013710443966257ae822f1c0ac2234d0ac
homepage   : https://www.mindforger.com/
license    : GPL-2.0-or-later
component  : office.notes
summary    : Thinking notebook and Markdown IDE
description: |
    MindForger is a thinking notebook and markdown IDE for creating, editing and managing all type of notes.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(hunspell)
    - pkgconfig(libcurl)
clang      : true
environment: |
    export CFLAGS="${CFLAGS} -Wno-implicit-function-declaration -Wno-int-conversion"
setup      : |
    # build cmark-gfm
    mkdir -p deps/cmark-gfm
    pushd deps/cmark-gfm
    BUILDDIR="build"
    %cmake_ninja \
        -B "${BUILDDIR}" \
        -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
        -DCMAKE_TESTS=OFF \
        -DCMARK_SHARED=OFF
    %cmake_build
    popd
build      : |
    %qmake -r mindforger.pro
    %make
install    : |
    %make_install INSTALL_ROOT=${installdir}/usr
    %install_license LICENSE
