# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lrzip
version    : 0.7.1
release    : 10
source     :
    - https://github.com/ckolivas/lrzip/archive/refs/tags/v0.7.1.tar.gz : 782d16ecf78766aea422f3e288009c4c3f83e7b0898d90f7a46b68d2c693dcff
homepage   : https://github.com/ckolivas/lrzip
license    : GPL-2.0-or-later
component  : system.utils
summary    : lrzip - Long Range ZIP or LZMA RZIP
description: |
    A compression utility that excels at compressing large files (usually > 10-50 MB). Larger files and/or more free RAM means that the utility will be able to more effectively compress your files (ie: faster / smaller size), especially if the filesize(s) exceed 100 MB. You can either choose to optimise for speed (fast compression / decompression) or size, but not both.
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(liblz4)
    - pkgconfig(lzo2)
setup      : |
    %reconfigure \
        --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
