# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : amule
version    : 3.0.0
release    : 32
source     :
    - https://github.com/amule-org/amule/archive/refs/tags/3.0.0.tar.gz : 
        850a09d1a5ec7d1b8962e4051d51b29355ac3df84a7b0b1209f2d0dd5c62eab4
homepage   : https://amule-org.github.io/
license    : GPL-2.0-or-later
component  : network.util
summary    : aMule is a multi-platform ed2k client, fork of the eMule client
description: |
    aMule is a multi-platform ed2k client, fork of the eMule client
builddeps  :
    - pkgconfig(gdlib)
    - pkgconfig(libpng)
    - pkgconfig(libupnp)
    - cryptopp-devel
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $installdir/usr/share/LICENSE.md $installdir/usr/share/licenses/amule/LICENSE.md
    rm $installdir/usr/share/LICENSE.md
