# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lenovo-legion-linux
version    : 0.0.20
release    : 52
source     :
    - https://github.com/johnfanv2/LenovoLegionLinux/archive/refs/tags/v0.0.20.tar.gz : c9974cfde03d8fd73de0a09628189f8fd9341037f10e28649b2fe5d1ec68bb2e
extract    : false
homepage   : https://github.com/johnfanv2/LenovoLegionLinux
license    : GPL-2.0-or-later
component  :
    - kernel.drivers
    - current : kernel.drivers
summary    :
    - Driver and tools for controlling Lenovo Legion laptops
    - current : lenovo-legion-linux kernel modules for the linux-current kernel
    - lts : lenovo-legion-linux kernel modules for the linux-lts kernel
description: |
    Lenovo Legion Linux (LLL) brings additional drivers and tools for Lenovo Legion series laptops to Linux. It allows you to control features like the fan curve, power mode, power limits, rapid charging, and more.
builddeps  :
    - pkgconfig(inih)
    - linux-current
    - linux-current-headers
    - linux-lts
    - linux-lts-headers
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
rundeps    :
    - current :
        - lenovo-legion-linux
    - lts :
        - lenovo-legion-linux
    - python-qt6
    - pyyaml
environment: |
    kernels=(
        %kernel_version_current%
        %kernel_version_lts%
    )
setup      : |
    # Prep build dirs for each kernel version
    for _kernel in "${kernels[@]}"; do
        mkdir "${_kernel}"
        tar --strip-components=1 -xf ${sources}/v*.tar.gz -C "${_kernel}"
    done

    sed -i 's|version = _VERSION|version = %version%|' */python/legion_linux/setup.cfg
build      : |
    for _kernel in "${kernels[@]}"; do
        %make -C "${_kernel}/kernel_module" \
            KERNELVERSION="${_kernel}" \
            KSRC="%libdir%/modules/${_kernel}/build"

        if [[ "${_kernel}" == *".current" ]]; then
            pushd "${_kernel}/python/legion_linux"
            %pyproject_build
            popd
        fi
    done
install    : |
    for _kernel in "${kernels[@]}"; do
        %install_file "${_kernel}/kernel_module/legion-laptop.ko" -t "${installdir}/%libdir%/modules/${_kernel}/extra/drivers/platform/x86"

        if [[ "${_kernel}" == *".current" ]]; then
            pushd "${_kernel}/python/legion_linux"
            %pyproject_install
            popd
        fi

        %install_license "${_kernel}/LICENSE"
    done

    find "${installdir}" -name '*.ko' -exec strip --strip-debug {} \; -exec zstd {} \; -exec rm -v {} \;
patterns   :
    - current :
        - /usr/lib64/modules/*.current/**
    - lts :
        - /usr/lib64/modules/*.lts/**
permanent  :
    - /lib64/modules
    - /usr/lib64/modules
