# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lenovo-legion-linux
version    : 0.0.20
release    : 35
source     :
    # Waiting for upstream to tag a new release
    - git|https://github.com/johnfanv2/LenovoLegionLinux.git : 7c19579d13ce686cf1e237699b9a78e80d03c977
homepage   : https://github.com/johnfanv2/LenovoLegionLinux
license    : GPL-2.0-or-later
component  :
    - kernel.drivers
    - current : kernel.drivers
summary    :
    - Driver and tools for controlling Lenovo Legion laptops
    - current : lenovo-legion-linux kernel modules for the linux-current kernel
    - lts : lenovo-legion-linux kernel modules for the linux-lts kernel
description: |
    Lenovo Legion Linux (LLL) brings additional drivers and tools for Lenovo Legion series laptops to Linux. It allows you to control features like the fan curve, power mode, power limits, rapid charging, and more.
builddeps  :
    - pkgconfig(inih)
    - linux-current
    - linux-current-headers
    - linux-lts
    - linux-lts-headers
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
patterns   :
    - current :
        - /lib64/modules/*.current/**
        - /usr/lib64/modules/*.current/**
    - lts :
        - /lib64/modules/*.lts/**
        - /usr/lib64/modules/*.lts/**
permanent  :
    - /lib64/modules
    - /usr/lib64/modules
rundeps    :
    - current :
        - lenovo-legion-linux
    - lts :
        - lenovo-legion-linux
    - python-qt6
    - pyyaml
setup      : |
    # Prep build dirs for each kernel version
    cp -r $PKG_BUILD_DIR/LenovoLegionLinux.git $PKG_BUILD_DIR/current
    cp -r $PKG_BUILD_DIR/LenovoLegionLinux.git $PKG_BUILD_DIR/lts

    sed -i 's|version = _VERSION|version = %version%|' $PKG_BUILD_DIR/*/python/legion_linux/setup.cfg
build      : |
    %make -C $PKG_BUILD_DIR/current/kernel_module KERNELVERSION=%kernel_version_current% KSRC=%libdir%/modules/%kernel_version_current%/build
    %make -C $PKG_BUILD_DIR/lts/kernel_module KERNELVERSION=%kernel_version_lts% KSRC=%libdir%/modules/%kernel_version_lts%/build

    pushd python/legion_linux
        python3 -m build --wheel --no-isolation
    popd
install    : |
    install -Dm00644 $PKG_BUILD_DIR/current/kernel_module/legion-laptop.ko -t $installdir/%libdir%/modules/%kernel_version_current%/extra/drivers/platform/x86/
    install -Dm00644 $PKG_BUILD_DIR/lts/kernel_module/legion-laptop.ko -t $installdir/%libdir%/modules/%kernel_version_lts%/extra/drivers/platform/x86/

    find "$installdir" -name '*.ko' -exec strip --strip-debug {} \; -exec zstd {} \; -exec rm -v {} \;

    pushd python/legion_linux
        python3 -m installer --destdir=%installroot% dist/*.whl
    popd
