# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ksmtp
version    : 25.12.3
release    : 91
source     :
    - https://download.kde.org/stable/release-service/25.12.3/src/ksmtp-25.12.3.tar.xz : a4a76de3a2471d8828c086ea04633a3de2d9ba135b80c5c0ede7eb285ac45a9e
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Job-based library to send email through an SMTP server
description: |
    Job-based library to send email through an SMTP server.
builddeps  :
    - pkgconfig(libsasl2)
    - kf6-kio-devel
rundeps    :
    - devel :
        - kf6-kcoreaddons-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
